### ISSUE TITLE
Processing "Import vector into PostGIS database" error when using a connection with autentication

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26817]
Author Name: **Luca Lanteri** (Luca Lanteri)
Original Redmine Issue: [18986](https://issues.qgis.org/issues/18986)
Affected QGIS version: 3.1(master)
Redmine category:processing/gdal

---
- Set a connection to postgres using Autentication metod.
- Try to import a vector using processing alg "Import vector into PostGIS database" 

QGIS 2.18.18 return this error:
- global name 'os' is not defined See log for more details

QGIS 3.01 return this error:
2018-05-18T14:18:11     WARNING    Traceback (most recent call last):
              File "C:/OSGEO4~2/apps/qgis-dev/./python/plugins\processing\gui\wrappers_postgis.py", line 102, in connectionChanged
              self.setConnection(connection)
              File "C:/OSGEO4~2/apps/qgis-dev/./python/plugins\processing\gui\wrappers_postgis.py", line 108, in setConnection
              self._database = GeoDB.from_name(connection)
              File "C:/OSGEO4~2/apps/qgis-dev/./python/plugins\processing\tools\postgis.py", line 170, in from_name
              return cls(uri=uri)
              File "C:/OSGEO4~2/apps/qgis-dev/./python/plugins\processing\tools\postgis.py", line 232, in __init__
              os.remove(sslCAFile)
             PermissionError: [WinError 5] Accesso negato: 'C:/Users/lucalant/AppData/Local/Temp/tmp_basic_{4c101150-2bc7-499b-895b-c6efae392a37}.pem'

**Comment by alexbruy** [comment]
Already fixed
