### ISSUE TITLE
"Couldn't load SIP module." with Madeira

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28948]
Author Name: **Boris D.** (Boris D.)
Original Redmine Issue: [21130](https://issues.qgis.org/issues/21130)
Affected QGIS version: 3.4.4
Redmine category:windows_package
Assignee: Jürgen Fischer

---
I got this problem with both 64 and 32 bits version.
Tried to reinstall SIP.
Tried to install several python packages.
I also use Anaconda.
I searched online and found several similar error, didn't managed to fixed it.

I installed QGIS 3.0.1 and it started without any error. Since I spent already something like 4H trying to get QGIS work, I'll just keep working with version 3.0.1 but I wanted to repport the error?

First Error window : 
```
Couldn't load SIP module.
Python support will be disabled.


Traceback (most recent call last):
File "", line 1, in 
File "C:/PROGRA~2/QGIS3~1.4/apps/qgis/./python\qgis\__init__.py", line 80, in 
import qgis.gui
File "C:/PROGRA~2/QGIS3~1.4/apps/qgis/./python\qgis\gui\__init__.py", line 27, in 
from qgis._gui import *
RuntimeError: the sip module implements API v12.0 to v12.4 but the qgis._gui module requires API v12.5


Python version:
3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)]

QGIS version:
3.4.4-Madeira 'Madeira', f6ddc62fdb

Python path:
['C:/PROGRA~2/QGIS3~1.4/apps/qgis/./python', 'C:/Users/Boris/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python', 'C:/Users/Boris/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python/plugins', 'C:/PROGRA~2/QGIS3~1.4/apps/qgis/./python/plugins', 'C:\\Program Files (x86)\\QGIS 3.4\\bin\\python37.zip', 'C:\\PROGRA~2\\QGIS3~1.4\\apps\\Python37\\DLLs', 'C:\\PROGRA~2\\QGIS3~1.4\\apps\\Python37\\lib', 'C:\\Program Files (x86)\\QGIS 3.4\\bin', 'C:\\Users\\Boris\\AppData\\Roaming\\Python\\Python37\\site-packages', 'C:\\PROGRA~2\\QGIS3~1.4\\apps\\Python37', 'C:\\PROGRA~2\\QGIS3~1.4\\apps\\Python37\\lib\\site-packages', 'C:\\PROGRA~2\\QGIS3~1.4\\apps\\Python37\\lib\\site-packages\\win32', 'C:\\PROGRA~2\\QGIS3~1.4\\apps\\Python37\\lib\\site-packages\\win32\\lib', 'C:\\PROGRA~2\\QGIS3~1.4\\apps\\Python37\\lib\\site-packages\\Pythonwin']

```

Second error window : 
```
An error occurred during execution of following code:
qgis.utils.uninstallErrorHook()


Traceback (most recent call last):
File "", line 1, in 
NameError: name 'qgis' is not defined


Python version:
3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]

QGIS version:
3.4.4-Madeira 'Madeira', 73c31df831

Python path:
['C:/OSGEO4~1/apps/qgis/./python', 'C:/Users/Boris/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python', 'C:/Users/Boris/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python/plugins', 'C:/OSGEO4~1/apps/qgis/./python/plugins', 'C:\\OSGeo4W64\\bin\\python37.zip', 'C:\\OSGEO4~1\\apps\\Python37\\DLLs', 'C:\\OSGEO4~1\\apps\\Python37\\lib', 'C:\\OSGeo4W64\\bin', 'C:\\Users\\Boris\\AppData\\Roaming\\Python\\Python37\\site-packages', 'C:\\OSGEO4~1\\apps\\Python37', 'C:\\OSGEO4~1\\apps\\Python37\\lib\\site-packages', 'C:\\OSGEO4~1\\apps\\Python37\\lib\\site-packages\\win32', 'C:\\OSGEO4~1\\apps\\Python37\\lib\\site-packages\\win32\\lib', 'C:\\OSGEO4~1\\apps\\Python37\\lib\\site-packages\\Pythonwin']

```

**Comment by alexbruy** [comment]
Try to install QGIS on a clean machine without anaconda.

**Comment by alexbruy** [comment]
Closing for the lack of feedback
