### ISSUE TITLE
macOS: Error when attempting to connect spatialite DB in DB manager

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29272]
Author Name: **ann rae** (@andreaparr)
Original Redmine Issue: [21455](https://issues.qgis.org/issues/21455)
Affected QGIS version: 3.6.0
Redmine category:mac_os_specific

---
Error when attempting to connect spatialite DB in DB manager:
Traceback (most recent call last):
  File "/Applications/QGIS3.6.app/Contents/MacOS/../Resources/python/plugins/db_manager/db_model.py", line 444, in rowCount
    self._refreshIndex(parent, True)
  File "/Applications/QGIS3.6.app/Contents/MacOS/../Resources/python/plugins/db_manager/db_model.py", line 493, in _refreshIndex
    if item.populate():
  File "/Applications/QGIS3.6.app/Contents/MacOS/../Resources/python/plugins/db_manager/db_model.py", line 170, in populate
    if not connection.connect():
  File "/Applications/QGIS3.6.app/Contents/MacOS/../Resources/python/plugins/db_manager/db_plugins/spatialite/plugin.py", line 78, in connect
    return self.connectToUri(uri)
  File "/Applications/QGIS3.6.app/Contents/MacOS/../Resources/python/plugins/db_manager/db_plugins/plugin.py", line 109, in connectToUri
    self.db = self.databasesFactory(self, uri)
  File "/Applications/QGIS3.6.app/Contents/MacOS/../Resources/python/plugins/db_manager/db_plugins/spatialite/plugin.py", line 64, in databasesFactory
    return SLDatabase(connection, uri)
  File "/Applications/QGIS3.6.app/Contents/MacOS/../Resources/python/plugins/db_manager/db_plugins/spatialite/plugin.py", line 107, in __init__
    Database.__init__(self, connection, uri)
  File "/Applications/QGIS3.6.app/Contents/MacOS/../Resources/python/plugins/db_manager/db_plugins/plugin.py", line 218, in __init__
    self.connector = self.connectorsFactory(uri)
  File "/Applications/QGIS3.6.app/Contents/MacOS/../Resources/python/plugins/db_manager/db_plugins/spatialite/plugin.py", line 110, in connectorsFactory
    return SpatiaLiteDBConnector(uri)
  File "/Applications/QGIS3.6.app/Contents/MacOS/../Resources/python/plugins/db_manager/db_plugins/spatialite/connector.py", line 51, in __init__
    self.connection = spatialite_connect(self._connectionInfo())
  File "/Applications/QGIS3.6.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 615, in spatialite_connect
    raise RuntimeError("Cannot find any suitable spatialite module")
RuntimeError: Cannot find any suitable spatialite module
 Python version: 3.6.8 (v3.6.8:3c6b436a57, Dec 24 2018, 02:04:31) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]  QGIS version: 3.6.0-Noosa Noosa, exported  
Python Path:
* /Applications/QGIS3.6.app/Contents/MacOS/../Resources/python
* /Users/andreaparr/Library/Application Support/QGIS/QGIS3/profiles/default/python
* /Users/andreaparr/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
* /Applications/QGIS3.6.app/Contents/MacOS/../Resources/python/plugins
* /Library/Frameworks/SQLite3.framework/Versions/E/Python/3.6
* /Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
* /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6
* /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
* /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
* /Users/andreaparr/Library/Application Support/QGIS/QGIS3/profiles/default/python

**Comment by alexbruy** [comment]
Still true with 3.10/master?

**Comment by nyalldawson** [comment]
Closing due to lack of feedback
