### ISSUE TITLE
Error while importing h5py in python console

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29439]
Author Name: **shiva reddy koti** (@shivareddyiirs)
Original Redmine Issue: [21623](https://issues.qgis.org/issues/21623)
Affected QGIS version: 3.6.0
Redmine category:windows_package

---

Below is error message:
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3~1.6\apps\Python37\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:/PROGRA~1/QGIS3~1.6/apps/qgis/./python\qgis\utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\shiva\AppData\Roaming\Python\Python37\site-packages\h5py\__init__.py", line 36, in <module>
    from ._conv import register_converters as _register_converters
  File "C:/PROGRA~1/QGIS3~1.6/apps/qgis/./python\qgis\utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "h5py\h5r.pxd", line 21, in init h5py._conv
  File "C:/PROGRA~1/QGIS3~1.6/apps/qgis/./python\qgis\utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "h5py\_objects.pxd", line 12, in init h5py.h5r
  File "C:/PROGRA~1/QGIS3~1.6/apps/qgis/./python\qgis\utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "h5py\_objects.pyx", line 1, in init h5py._objects
  File "C:/PROGRA~1/QGIS3~1.6/apps/qgis/./python\qgis\utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: DLL load failed: The specified procedure could not be found.

**Comment by alexbruy** [comment]
Still true with 3.10/master?

**Comment by alexbruy** [comment]
Closing for the lack of feedback. Please reopen if necessary.

**Comment by mr-bryn** [comment]
Still getting this error message using QGIS 3.14.16-Pi and h5py 2.10.0-1 installed from OSGeo4W

**Comment by Jibede** [comment]
I have the same issue on versions 3.10, 3.16, 3.28 and 3.32.
