### ISSUE TITLE
Processing: python error on startup

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29535]
Author Name: **John Drewett** (John Drewett)
Original Redmine Issue: [21720](https://issues.qgis.org/issues/21720)
Affected QGIS version: 3.6.1
Redmine category:processing/saga

---
The following error occurs on start up.  Any advice would be appreciated.

```
2019-04-01T13:25:00     WARNING    Traceback (most recent call last):
              File "C:/PROGRA~1/QGIS3~1.6/apps/qgis/./python/plugins\processing\algs\saga\SagaAlgorithmProvider.py", line 90, in loadAlgorithms
              version = SagaUtils.getInstalledVersion(True)
              File "C:/PROGRA~1/QGIS3~1.6/apps/qgis/./python/plugins\processing\algs\saga\SagaUtils.py", line 145, in getInstalledVersion
              universal_newlines=True,
              File "C:\PROGRA~1\QGIS3~1.6\apps\Python37\lib\subprocess.py", line 709, in __init__
              errread, errwrite) = self._get_handles(stdin, stdout, stderr)
              File "C:\PROGRA~1\QGIS3~1.6\apps\Python37\lib\subprocess.py", line 1015, in _get_handles
              p2cread = msvcrt.get_osfhandle(self._get_devnull())
              File "C:\PROGRA~1\QGIS3~1.6\apps\Python37\lib\subprocess.py", line 848, in _get_devnull
              self._devnull = os.open(os.devnull, os.O_RDWR)
             FileNotFoundError: [Errno 2] No such file or directory: 'nul'

```

**Comment by alexbruy** [comment]
Please test with master. I can not reproduce with 3.8 and master.

**Comment by alexbruy** [comment]
Closed for the lack of feedback. Reopen if necessary
