### ISSUE TITLE
Ubuntu Disco Python Error

### ISSUE THREAD

**Issue by charliedavi** [qgis/QGIS#30007]
I am having the error while loading:

```
Couldn't load SIP module.
Python support will be disabled.


Traceback (most recent call last):
  File "", line 1, in
  File "/usr/lib/python3/dist-packages/qgis/__init__.py", line 72, in
    from qgis.PyQt import QtCore
  File "/usr/lib/python3/dist-packages/qgis/PyQt/QtCore.py", line 26, in
    from PyQt5.QtCore import *
ModuleNotFoundError: No module named 'PyQt5.QtCore'


Python version:
3.6.8 (default, Apr  9 2019, 04:59:38)
[GCC 8.3.0]

QGIS version:
3.6.3-Noosa 'Noosa', 0c5774c

Python path:
['/usr/share/qgis/python', '/home/charlie/.local/share/QGIS/QGIS3/profiles/default/python', '/home/charlie/.local/share/QGIS/QGIS3/profiles/default/python/plugins', '/usr/share/qgis/python/plugins', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/usr/lib/python3/dist-packages']
```

and
```
An error occurred during execution of following code:
qgis.utils.uninstallErrorHook()


Traceback (most recent call last):
  File "", line 1, in
NameError: name 'qgis' is not defined


Python version:
3.6.8 (default, Apr  9 2019, 04:59:38)
[GCC 8.3.0]

QGIS version:
3.6.3-Noosa 'Noosa', 0c5774c

Python path:
['/usr/share/qgis/python', '/home/charlie/.local/share/QGIS/QGIS3/profiles/default/python', '/home/charlie/.local/share/QGIS/QGIS3/profiles/default/python/plugins', '/usr/share/qgis/python/plugins', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/usr/lib/python3/dist-packages']
```

I have tried removing and re-installing. 

```
{19-05-29 12:19}[]CharlieThink:~ charlie% pip3 install PyQt5
Requirement already satisfied: PyQt5 in /usr/lib/python3/dist-packages (5.12.1)

{19-05-29 12:21}[]CharlieThink:~ charlie% sudo apt-get install python3-pip
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-pip is already the newest version (18.1-5).
0 to upgrade, 0 to newly install, 0 to remove and 21 not to upgrade.
{19-05-29 12:21}[]CharlieThink:~ charlie% 

Python == ```Python 3.7.3```
```

**Comment by charliedavi** [comment]
I have made it work by uninstalling everything (apt-get remove)
and changing the sources list to:
deb https://qgis.org/debian disco ltr 
deb-src https://qgis.org/debian disco ltr
