### ISSUE TITLE
db manager: python error when trying add a geometry less table

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#30260]
```
AttributeError: 'PGTable' object has no attribute 'srid' 
Traceback (most recent call last):
  File "/usr/share/qgis/python/plugins/db_manager/db_tree.py", line 163, in addLayer
    layer = table.toMapLayer()
  File "/usr/share/qgis/python/plugins/db_manager/db_plugins/plugin.py", line 733, in toMapLayer
    uri = self.uri().uri(False)
  File "/usr/share/qgis/python/plugins/db_manager/db_plugins/plugin.py", line 716, in uri
    uri.setSrid(str(self.srid))
AttributeError: 'PGTable' object has no attribute 'srid
```

QGIS master on Ubuntu 18.04

**Comment by m-kuhn** [comment]
@olivierdalang is that related to your recent fix?

**Comment by olivierdalang** [comment]
@m-kuhn Yes I think, I'll have a look and try to fix

**Comment by olivierdalang** [comment]
Ok I made the fix, sorry for that :-/
@m-kuhn What's the procedure to backport to 3.8 ? Should I open another PR, or can you apply the "backport 3.8" tag ? (unfortunately I can't set tags)

**Comment by kylefelipe** [comment]
Hi guys, i still have the same issue on QGIS 3.4
```An error has occurred while executing Python code: 

AttributeError: 'PGTable' object has no attribute 'srid' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python/plugins\db_manager\db_tree.py", line 163, in addLayer
    layer = table.toMapLayer()
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python/plugins\db_manager\db_plugins\plugin.py", line 728, in toMapLayer
    uri = self.uri().uri(False)
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python/plugins\db_manager\db_plugins\plugin.py", line 711, in uri
    uri.setSrid(str(self.srid))
AttributeError: 'PGTable' object has no attribute 'srid'


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.4.9-Madeira Madeira, 54585165bb```

**Comment by Gustry** [comment]
> QGIS version: 3.4.9-Madeira Madeira, 54585165bb```

@kylefelipe You must update your 3.4 version.
