### ISSUE TITLE
SemiAutomaticClassificationPlugin Error, Qgis 3.6 - OSX Mojave

### ISSUE THREAD

**Issue by AntonioDEM** [qgis/QGIS#30335]
I installed on a macbook pro with OS-10.14.5 (Mojave), the SemiAutomaticClassification plugin on Qgis3.6, python 3.6.8, including all the necessary libraries.
at the start of Qgis, have this error :

**AttributeError**: 'Legend' object has no attribute 'draggable' 
Traceback (most recent call last):
  File "/Users/harlock/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/semiautomaticclassificationplugin.py", line 1296, in newProjectLoaded
    cfg.spSigPlot.refreshPlot()
  File "/Users/harlock/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/spectralsignature/spectralsignatureplot.py", line 463, in refreshPlot
    self.signaturePlot()
  File "/Users/harlock/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/spectralsignature/spectralsignatureplot.py", line 711, in signaturePlot
    cfg.uisp.Sig_Widget.sigCanvas.ax.legend(pL, pLN, bbox_to_anchor=(0.1, 0.0, 1.1, 1.0), loc=1, borderaxespad=0.).draggable()
AttributeError: 'Legend' object has no attribute 'draggable'

**Versione Python**: 3.6.8 (v3.6.8:3c6b436a57, Dec 24 2018, 02:04:31) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] 
**Versione di QGIS:** 3.6.3-Noosa Noosa, exported 

Percorso Python:
/Applications/QGIS3.6.app/Contents/MacOS/../Resources/python
/Users/harlock/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/harlock/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS3.6.app/Contents/MacOS/../Resources/python/plugins
/Library/Frameworks/SQLite3.framework/Versions/E/Python/3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
/Users/harlock/Library/Application Support/QGIS/QGIS3/profiles/default/python

Have any solution? thanks

**Comment by gioman** [comment]
Must be reported to the plugin author/s, not here.
