### ISSUE TITLE
Gdal contour dialog not opening

### ISSUE THREAD

**Issue by ghtmtt** [qgis/QGIS#30669]
Gdal contour dialog window throws an error:

```
KeyError: 'OPTIONS' 
Traceback (most recent call last):
  File "/home/matteo/lavori/QGIS/build-qgis3-master3/output/python/plugins/processing/gui/ProcessingToolbox.py", line 259, in executeAlgorithm
    dlg = alg.createCustomParametersWidget(self)
  File "/home/matteo/lavori/QGIS/build-qgis3-master3/output/python/plugins/processing/algs/gdal/GdalAlgorithm.py", line 63, in createCustomParametersWidget
    return GdalAlgorithmDialog(self, parent=parent)
  File "/home/matteo/lavori/QGIS/build-qgis3-master3/output/python/plugins/processing/algs/gdal/GdalAlgorithmDialog.py", line 56, in __init__
    self.mainWidget().parametersHaveChanged()
  File "/home/matteo/lavori/QGIS/build-qgis3-master3/output/python/plugins/processing/algs/gdal/GdalAlgorithmDialog.py", line 131, in parametersHaveChanged
    or (not p.checkValueIsAcceptable(parameters[p.name()])):
KeyError: 'OPTIONS'
```

QGIS 3.9

**Comment by gioman** [comment]
Confirmed here too.

**Comment by ghtmtt** [comment]
Thanks @gioman for confirming. Shouldn't be the gdal algorithms covered by tests?

https://github.com/qgis/QGIS/blob/master/python/plugins/processing/tests/GdalAlgorithmsRasterTest.py#L403

**Comment by nyalldawson** [comment]
@ghtmtt this error is being thrown by the processing gdal GUI - so existing unit tests are all happy (which cover non-gdal processing GUI and core gdal processing functionality). There is a test gap here.
