### ISSUE TITLE
incorrect GRASS path in package

### ISSUE THREAD

**Issue by gubuntu** [qgis/QGIS#31390]
**Describe the bug**

QGIS references the brew grass path that was used for packaging rather than the local installation path, so grass processing modules will not work with the grass that is installed with QGIS

**How to Reproduce**

1. Set the Grass7 folder to '/Applications/QGIS3.4.app/Contents/Resources/grass7' in processing settings
1. Try to run a grass process
1. See error -->

```
2019-08-24T17:14:31     INFO    GRASS GIS 7 execution console output
             Cleaning up temporary files...
             
             Traceback (most recent call last):
             
              File "/Applications/QGIS3.4.app/Contents/Resources/grass7/bin/_grass76", line 2207, in 
             
              main()
             
              File "/Applications/QGIS3.4.app/Contents/Resources/grass7/bin/_grass76", line 2085, in main
             
              clean_temp()
             
              File "/Applications/QGIS3.4.app/Contents/Resources/grass7/bin/_grass76", line 1782, in clean_temp
             
              call([gpath("etc", "clean_temp")], stdout=nul)
             
              File "/Applications/QGIS3.4.app/Contents/Resources/grass7/bin/_grass76", line 247, in call
             
              return subprocess.call(cmd, **kwargs)
             
              File "/Applications/QGIS3.4.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/subprocess.py", line 323, in call
             
              with Popen(*popenargs, **kwargs) as p:
             
              File "/Applications/QGIS3.4.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/subprocess.py", line 775, in __init__
             
              restore_signals, start_new_session)
             
              File "/Applications/QGIS3.4.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/subprocess.py", line 1522, in _execute_child
             
              raise child_exception_type(errno_num, err_msg, err_filename)
             
             FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/Cellar/osgeo-grass/7.6.1_5/grass76/etc/clean_temp': '/usr/local/Cellar/osgeo-grass/7.6.1_5/grass76/etc/clean_temp'
             
             /Applications/QGIS3.4.app/Contents/Resources/grass7/grass76.sh: line 19: /private/var/folders/8b/12slfx955yj25xt6x1_zjz8m0000gn/T/processing_01bf769e38844b0e9d2cf07e5f659f24/grassdata/temp_location/PERMANENT: is a directory
             
             Cleaning up temporary files...
             Traceback (most recent call last):
             File "/Applications/QGIS3.4.app/Contents/Resources/grass7/bin/_grass76", line 2207, in 
             main()
             File "/Applications/QGIS3.4.app/Contents/Resources/grass7/bin/_grass76", line 2085, in main
             clean_temp()
             File "/Applications/QGIS3.4.app/Contents/Resources/grass7/bin/_grass76", line 1782, in clean_temp
             call([gpath("etc", "clean_temp")], stdout=nul)
             File "/Applications/QGIS3.4.app/Contents/Resources/grass7/bin/_grass76", line 247, in call
             return subprocess.call(cmd, **kwargs)
             File "/Applications/QGIS3.4.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/subprocess.py", line 323, in call
             with Popen(*popenargs, **kwargs) as p:
             File "/Applications/QGIS3.4.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/subprocess.py", line 775, in __init__
             restore_signals, start_new_session)
             File "/Applications/QGIS3.4.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/subprocess.py", line 1522, in _execute_child
             raise child_exception_type(errno_num, err_msg, err_filename)
             FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/Cellar/osgeo-grass/7.6.1_5/grass76/etc/clean_temp': '/usr/local/Cellar/osgeo-grass/7.6.1_5/grass76/etc/clean_temp'
             /Applications/QGIS3.4.app/Contents/Resources/grass7/grass76.sh: line 19: /private/var/folders/8b/12slfx955yj25xt6x1_zjz8m0000gn/T/processing_01bf769e38844b0e9d2cf07e5f659f24/grassdata/temp_location/PERMANENT: is a directory
```

**QGIS and OS versions**

QGIS version | 3.4.11-Madeira | QGIS code revision | 9a8a6d4687
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 520 | Running against PROJ | 5.2.0

**Comment by gubuntu** [comment]
same problem in 

QGIS version | 3.8.2-Zanzibar | QGIS code revision | 4470baa1a3
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS Mojave (10.14) |   |

**Comment by gubuntu** [comment]
Same problem if Processing GRASS provider is set to an external one like `/Applications/GRASS-7.6.app/Contents/MacOS`

**Comment by spatialthoughts** [comment]
Still persists in 3.10 package. And it references QGIS3.4.app

FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/Cellar/osgeo-grass/7.6.1_5/grass76/etc/lock': '/usr/local/Cellar/osgeo-grass/7.6.1_5/grass76/etc/lock'
/Applications/QGIS3.4.app/Contents/Resources/grass7/grass76.sh

**Comment by AndrewAnnex** [comment]
I think this issue is with the qgis mac packager repository, I've posted an issue there that should be investigated further https://github.com/qgis/QGIS-Mac-Packager/issues/25

**Comment by MelnykAndriy** [comment]
Happens to me.

**Comment by soilphysics** [comment]
Same here. Please fix.

**Comment by rmseifried** [comment]
Fresh install of 3.10 today, still getting this error.

**Comment by citizenfish** [comment]
Can confirm error still persists in 3.10 OSX

**Comment by gioman** [comment]
See:

https://github.com/qgis/QGIS/issues/33206
https://github.com/qgis/QGIS/issues/32511

**Comment by gioman** [comment]
merging with https://github.com/qgis/QGIS/issues/32511
