### ISSUE TITLE
PostgreSQL tests: host name "postgres" to address: Name or service not known

### ISSUE THREAD

**Issue by strk** [qgis/QGIS#32787]
Some test is assuming an host named "postgres" exists. This is probably the case under Travis, but not that easily on developers'  machines.

I think the involved tests are:

testSslRequireNoCaCheck
testValidAuthAccess
PyQgsAuthManagerOgrPostgresTest

I'm not sure because the output from make check is not very intuitive to me:

```
src/core/qgsmessagelog.cpp:29 : (logMessage) [0ms] 2019-11-11T12:44:07 PostGIS[1] Connection to database failed
could not translate host name "postgres" to address: Name or service not known

Fsrc/providers/postgres/qgspostgresprovider.cpp:318 : (~QgsPostgresProvider) [1ms] deconstructing.

======================================================================
FAIL: testSslRequireNoCaCheck (__main__.TestAuthManager)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/qgis/qgis-do-not-override-source-files/tests/src/python/test_authmanager_password_postgres.py", line 151, in testSslRequireNoCaCheck
    self.assertTrue(pg_layer.isValid())
AssertionError: False is not true

======================================================================
FAIL: testValidAuthAccess (__main__.TestAuthManager)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/qgis/qgis-do-not-override-source-files/tests/src/python/test_authmanager_password_postgres.py", line 134, in testValidAuthAccess
    self.assertTrue(pg_layer.isValid())
AssertionError: False is not true

----------------------------------------------------------------------
Ran 4 tests in 0.523s

FAILED (failures=2)Application state:
QGIS_PREFIX_PATH env var:               /usr/src/qgis/build/do-not-override-source-files/output
Prefix:
Plugin Path:            /usr/src/qgis/build/do-not-override-source-files/output/lib/qgis/plugins
Package Data Path:      /usr/src/qgis/build/do-not-override-source-files/output/data
Active Theme Name:
Active Theme Path:      /usr/src/qgis/build/do-not-override-source-files/output/data/resources/themes//icons/
Default Theme Path:     :/images/themes/default/
SVG Search Paths:       /usr/src/qgis/build/do-not-override-source-files/output/data/svg/
                /home/strk/.local/share/test_authmanager_password_postgres.py/profiles/default/svg/
User DB Path:   /usr/src/qgis/build/do-not-override-source-files/output/data/resources/qgis.db
Auth DB Path:   /home/strk/.local/share/test_authmanager_password_postgres.py/profiles/default/qgis-auth.db

PostGIS(1): Connection to database failed
could not translate host name "postgres" to address: Name or service not known

PostGIS(1): Connection to database failed
could not translate host name "postgres"
to address: Name or service not known

PostGIS(1): Connection to database failed
could not translate host name "postgres" to address: Name or service not known

PostGIS(1): Connection to database failed
could not translate host name "postgres" to address: Name or service not known

CMake Error at PyQgsAuthManagerPasswordPostgresTest.cmake:15 (MESSAGE):
  Test failed: 1



        Start 532: PyQgsAuthManagerOgrPostgresTest
531/583 Test #532: PyQgsAuthManagerOgrPostgresTest ...............***Failed    0.45 sec
```

**Comment by strk** [comment]
I'm trying to work on a fix but I'm puzzled by this:
`make check` reports:
FAIL: testSslRequireNoCaCheck (__main__.TestAuthManager)

But `ctest -V -R testSslRequireNoCaCheck` reports:
No tests were found!!!

**Comment by strk** [comment]
What I needed to do to figure out which name the test had:
```
$ git grep testSslRequireNoCaCheck
tests/src/python/test_authmanager_password_postgres.py:    def testSslRequireNoCaCheck(self):
$ git grep test_authmanager_password_postgres
tests/src/python/CMakeLists.txt:  ADD_PYTHON_TEST(PyQgsAuthManagerPasswordPostgresTest test_authmanager_password_postgres.py)
```

Following the above excercise I could finally do:
`ctest -V -R PyQgsAuthManagerPasswordPostgresTest`

Which shows the failure.

**Comment by strk** [comment]
So: the issue with that test (` ctest -V -R PyQgsAuthManagerPasswordPostgresTest`) is that it *expects* the presence of a running docker container with an expected setup (having auth certs from testsuite). The `test_authmanager_password_postgres.py` test contains a comment instructing the user to:
```
Use docker-compose -f .ci/travis/linux/docker-compose.travis.yml up postgres to start the server.
```

But there's no such file in the repository.
@elpaso the test seems to be yours, how can a developer start the requested docker to perform the actual testing ?
It would be nice if `make check` did this automatically

**Comment by strk** [comment]
In PR #47057 I've updated the outdated comments in the test. Please review !

**Comment by strk** [comment]
Next issue: in *addition* to require a running docker, the test requires the hostname `postgres` to resolve to the IP of the running container. I think this is needed for the used certificates to be accepted:
```
745: src/core/qgsmessagelog.cpp:29 : (logMessage) [9ms] 2022-01-28T19:34:17 PostGIS[1] Connection to database failed
745: server certificate for "postgres" does not match host name "172.19.0.2"
```

**Comment by strk** [comment]
Answering a TODO item in one of the authmanager tests, I'm documenting here how I could extract the IP from the running docker, started with docker-compose:

    docker inspect docker_postgres_1 | jq -r .[0].NetworkSettings.Networks.docker_default.IPAddress
