### ISSUE TITLE
QGIS Server WMTS: Capabilities document is not valid

### ISSUE THREAD

**Issue by jgrocha** [qgis/QGIS#33008]
**Describe the bug**

If we query QGIS Server about WMTS Capabilities, the returned document is not valid against the XSD.

The document depends on data provided by the user, but we should try to create a valid document, even if some elements are empty of have default values.

**How to Reproduce**

1. I've created a project with two layers.
2. On the Project properties → QGIS Server:
2.1 On WMS capabilities: Turn on CRS restrictions
2.2 On WMTS capabilities: Publish the two layers
2.3 Publish also the available grid (that appears when CRS restrictions are selected)
3. Save the project

![wmts settings](https://user-images.githubusercontent.com/163681/69387288-48536a80-0cbd-11ea-9e10-f1b4b94b2f2e.png)

4. Request Capabilities document from QGIS Server.
5. Validate the document against the XSD.

On the command line, using `xmlstarlet`:
```bash
xmlstarlet val --err --xsd http://schemas.opengis.net/wmts/1.0/wmtsGetCapabilities_response.xsd "http://qgis.sig.cm-agueda.pt/postgresql/publica/public/edificadinho/cgi-bin/qgis_mapserv.fcgi?SERVICE=WMTS&VERSION=1.1.1&REQUEST=GetCapabilities"
```
```text
GetCapabilities:8.24: Element '{http://www.opengis.net/ows/1.1}ServiceProvider': Missing child element(s). Expected is ( {http://www.opengis.net/ows/1.1}ProviderName ).
GetCapabilities:54.17: Element 'LowerCorner': This element is not expected. Expected is ( {http://www.opengis.net/ows/1.1}LowerCorner ).
GetCapabilities:58.17: Element 'LowerCorner': This element is not expected. Expected is ( {http://www.opengis.net/ows/1.1}LowerCorner ).
GetCapabilities:63.15: Element '{http://www.opengis.net/ows/1.1}Title': This element is not expected. Expected is ( LegendURL ).
GetCapabilities:77.18: Element 'MinTileCol': This element is not expected. Expected is ( MinTileRow ).
GetCapabilities:84.18: Element 'MinTileCol': This element is not expected. Expected is ( MinTileRow ).
GetCapabilities:91.18: Element 'MinTileCol': This element is not expected. Expected is ( MinTileRow ).
GetCapabilities:98.18: Element 'MinTileCol': This element is not expected. Expected is ( MinTileRow ).
GetCapabilities:105.18: Element 'MinTileCol': This element is not expected. Expected is ( MinTileRow ).
GetCapabilities:112.18: Element 'MinTileCol': This element is not expected. Expected is ( MinTileRow ).
GetCapabilities:119.18: Element 'MinTileCol': This element is not expected. Expected is ( MinTileRow ).
GetCapabilities:126.18: Element 'MinTileCol': This element is not expected. Expected is ( MinTileRow ).
GetCapabilities:133.18: Element 'MinTileCol': This element is not expected. Expected is ( MinTileRow ).
GetCapabilities:140.18: Element 'MinTileCol': This element is not expected. Expected is ( MinTileRow ).
GetCapabilities:147.18: Element 'MinTileCol': This element is not expected. Expected is ( MinTileRow ).
GetCapabilities:154.18: Element 'MinTileCol': This element is not expected. Expected is ( MinTileRow ).
GetCapabilities:161.18: Element 'MinTileCol': This element is not expected. Expected is ( MinTileRow ).
GetCapabilities:168.18: Element 'MinTileCol': This element is not expected. Expected is ( MinTileRow ).
GetCapabilities:175.18: Element 'MinTileCol': This element is not expected. Expected is ( MinTileRow ).
GetCapabilities:182.18: Element 'MinTileCol': This element is not expected. Expected is ( MinTileRow ).
GetCapabilities:189.18: Element 'MinTileCol': This element is not expected. Expected is ( MinTileRow ).
GetCapabilities:196.18: Element 'MinTileCol': This element is not expected. Expected is ( MinTileRow ).
GetCapabilities:203.18: Element 'MinTileCol': This element is not expected. Expected is ( MinTileRow ).
GetCapabilities:214.17: Element 'LowerCorner': This element is not expected. Expected is ( {http://www.opengis.net/ows/1.1}LowerCorner ).
GetCapabilities:218.17: Element 'LowerCorner': This element is not expected. Expected is ( {http://www.opengis.net/ows/1.1}LowerCorner ).
GetCapabilities:223.15: Element '{http://www.opengis.net/ows/1.1}Title': This element is not expected. Expected is ( LegendURL ).
GetCapabilities:237.18: Element 'MinTileCol': This element is not expected. Expected is ( MinTileRow ).
GetCapabilities:244.18: Element 'MinTileCol': This element is not expected. Expected is ( MinTileRow ).
GetCapabilities:251.18: Element 'MinTileCol': This element is not expected. Expected is ( MinTileRow ).
GetCapabilities:258.18: Element 'MinTileCol': This element is not expected. Expected is ( MinTileRow ).
GetCapabilities:265.18: Element 'MinTileCol': This element is not expected. Expected is ( MinTileRow ).
GetCapabilities:272.18: Element 'MinTileCol': This element is not expected. Expected is ( MinTileRow ).
GetCapabilities:279.18: Element 'MinTileCol': This element is not expected. Expected is ( MinTileRow ).
GetCapabilities:286.18: Element 'MinTileCol': This element is not expected. Expected is ( MinTileRow ).
GetCapabilities:293.18: Element 'MinTileCol': This element is not expected. Expected is ( MinTileRow ).
GetCapabilities:300.18: Element 'MinTileCol': This element is not expected. Expected is ( MinTileRow ).
GetCapabilities:307.18: Element 'MinTileCol': This element is not expected. Expected is ( MinTileRow ).
GetCapabilities:314.18: Element 'MinTileCol': This element is not expected. Expected is ( MinTileRow ).
GetCapabilities:321.18: Element 'MinTileCol': This element is not expected. Expected is ( MinTileRow ).
GetCapabilities:328.18: Element 'MinTileCol': This element is not expected. Expected is ( MinTileRow ).
GetCapabilities:335.18: Element 'MinTileCol': This element is not expected. Expected is ( MinTileRow ).
GetCapabilities:342.18: Element 'MinTileCol': This element is not expected. Expected is ( MinTileRow ).
GetCapabilities:349.18: Element 'MinTileCol': This element is not expected. Expected is ( MinTileRow ).
GetCapabilities:356.18: Element 'MinTileCol': This element is not expected. Expected is ( MinTileRow ).
GetCapabilities:363.18: Element 'MinTileCol': This element is not expected. Expected is ( MinTileRow ).
GetCapabilities - invalid
```

**QGIS and OS versions**

Master 3.11.0 build on 20191122.

**Additional context**

I noticed that the document wasn't valid, when using OWSLib:

```python
from owslib.wmts import WebMapTileService
wmts = WebMapTileService("http://qgis.sig.cm-agueda.pt/postgresql/publica/public/edificadinho/cgi-bin/qgis_mapserv.fcgi?SERVICE=WMTS&VERSION=1.1.1&REQUEST=GetCapabilities")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/owslib/wmts.py", line 187, in __init__
    self._buildMetadata(parse_remote_metadata)
  File "/usr/lib/python3/dist-packages/owslib/wmts.py", line 236, in _buildMetadata
    gather_layers(caps, None)
  File "/usr/lib/python3/dist-packages/owslib/wmts.py", line 229, in gather_layers
    parse_remote_metadata=parse_remote_metadata)
  File "/usr/lib/python3/dist-packages/owslib/wmts.py", line 705, in __init__
    ll = [float(s) for s in lc.text.split()]
AttributeError: 'NoneType' object has no attribute 'text'
```

It does seem difficult to fix. Some elements are just not using the right prefix, like `LowerCorner`.

**Comment by jgrocha** [comment]
Just by replacing:

tag used | tag with correct prefix
--- | ---
LowerCorner | ows:LowerCorner
UpperCorner | ows:UpperCorner

I was able to get it parsed by OWSLib.

**Comment by jgrocha** [comment]
I've done a quick fix in the code (was really easy), but I also need to change the [test file](https://github.com/qgis/QGIS/blob/baf38199e09651f7d85914b80fc1cc3cc64d2d3a/tests/testdata/qgis_server/wmts_getcapabilities.txt) used.

@rldhont Can you confirm that the above test file is valid?

My `xmlstarlet` says no.

```bash
xmlstarlet val --err --xsd http://schemas.opengis.net/wmts/1.0/wmtsGetCapabilities_response.xsd wmts_getcapabilities.txt
wmts_getcapabilities.txt - invalid
```

**Comment by jgrocha** [comment]
I've tested the `GetCapabilities` request against [Geoserver](http://web.sig.cm-agueda.pt:8080/geoserver/gwc/service/wmts?REQUEST=GetCapabilities). Geoserver properly used the `ows` prefix on `<ows:LowerCorner>` and `<ows:UpperCorner>`.

I'll proceed with a PR.
