### ISSUE TITLE
Problems with georeferance

### ISSUE THREAD

**Issue by shaninandrew** [qgis/QGIS#33083]
2019-11-26T16:01:29     WARNING    Traceback (most recent call last):
              File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 335, in startPlugin
              plugins[packageName] = package.classFactory(iface)
              File "C:/Users/Андрей/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\rastertool\__init__.py", line 35, in classFactory
              from .RasterTool import RasterTool
              File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 685, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:/Users/Андрей/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\rastertool\RasterTool.py", line 51, in 
              from pandas import read_csv
              File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 685, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
             ModuleNotFoundError: No module named 'pandas'

**Comment by gioman** [comment]
@shaninandrew the error comes from a 3rd party plugin (rastertool), please report it to the author.
