### ISSUE TITLE
All grass commands executing as batch processing in the qgis does not work

### ISSUE THREAD

**Issue by Abdur-Rahim-Safi** [qgis/QGIS#33105]
I want to use one layer as a mask and apply to another layer (both are tif files) by using r.mask.rast in QGIS GRASS. To execute as a single process it works, but when I execute as a batch processing it gives the following error. The same for i.vi or any other command.  

Traceback (most recent call last): File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\algs\grass7\Grass7Algorithm.py", line 428, in processAlgorithm Grass7Utils.executeGrass(self.commands, feedback, self.outputCommands) File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\algs\grass7\Grass7Utils.py", line 400, in executeGrass feedback.reportError(line.strip()) TypeError: reportError() missing 1 required positional argument: 'fatalError' . 

I am using QGIS 3.10 with GRASS 7.8.0, I also checked QGIS 3.4.10 and it gives the same error. I think there is a problem due to scripts in the files (Grass7Alogrithm.py and Grass7Utils.py). 

![r mask rast_error](https://user-images.githubusercontent.com/57115630/69737577-e66b8880-1134-11ea-990d-a798eb80094e.JPG)

**Comment by Abdur-Rahim-Safi** [comment]
Thank you Nyalldawson. It helped me a lot.
