### ISSUE TITLE
DBManager's PostgreSQL schema rename fails

### ISSUE THREAD

**Issue by strk** [qgis/QGIS#33316]
Cannot rename a PostgreSQL schema using DBManager. Console logs:
```
src/core/qgsmessagelog.cpp:29 : (logMessage) [4432ms] 2019-12-10T14:30:55 Python error[1] Traceback (most recent call last):
  File "/usr/src/qgis/build/do-not-override-source-files/output/python/plugins/db_manager/db_model.py", line 478, in setData
    obj.rename(new_value)
  File "/usr/src/qgis/build/do-not-override-source-files/output/python/plugins/db_manager/db_plugins/plugin.py", line 652, in rename
    ret = self.database().connector.renameSchema(self.name, new_name)
AttributeError: 'PostGisDBConnector' object has no attribute 'renameSchema'
```

**Comment by rjhale1971** [comment]
I got this error off QGIS 10.1 running on ubuntu 19.04 from the python.error tab under logs when trying to rename a schema: 
2019-12-16T21:45:02     WARNING    Traceback (most recent call last):
              File "/usr/share/qgis/python/plugins/db_manager/db_model.py", line 478, in setData
              obj.rename(new_value)
              File "/usr/share/qgis/python/plugins/db_manager/db_plugins/plugin.py", line 644, in rename
              ret = self.database().connector.renameSchema(self.name, new_name)
             AttributeError: 'PostGisDBConnector' object has no attribute 'renameSchema'

**Comment by strk** [comment]
I think I fixed this in https://github.com/qgis/QGIS/pull/33225 (but I could be wrong) would you be up for testing it ?

**Comment by rjhale1971** [comment]
I will give it a shot shortly and will let you know. Thanks!

**Comment by rjhale1971** [comment]
and this might relate or could be a separate issue. If you add data to QGIS (3.10.1) and then double click on it under Virtual Layers it will toss an error on that layer being invalid.  As an example for postgis 
![Screenshot from 2019-12-17 10-14-15](https://user-images.githubusercontent.com/389868/71008281-588d1880-20b6-11ea-8cdb-754fe82a4cb9.png)

The python error log is: 
2019-12-17T10:07:21     WARNING    dbname='safegroundai' host=safegrounddbserver.postgres.database.azure.com port=5432 user='rjhale@safegrounddbserver' key='ogc_fid' type=Point checkPrimaryKeyUnicity='1' table="dev"."addresspoints_toronto" (wkb_geometry) sql= is an invalid layer - not loaded

Same thing with shapefiles. If I need to I will open a separate issue.

**Comment by gioman** [comment]
> and this might relate or could be a separate issue

@rjhale1971 I think is a separate issue, can you please file a separate ticket?

**Comment by gioman** [comment]
Closing as renaming schemas works ok now (tested on master).
