### ISSUE TITLE
TIN interpolation in Model Builder not editable - AttributeError: 'InterpolationDataWidget' object has no attribute 'addLayerData'  and can't assign input layers

### ISSUE THREAD

**Issue by mikedufty** [qgis/QGIS#33406]
When adding Interpolate Triangulation Algorithm in Model Builder, Model inputs are not selectable in the vector layer input dropdown for the algorithm. 

If the algorithm is set up with project layers instead, the dialogue can be closed, and the model will run successfully.
If one clicks on the ... button of the algorithm in model builder to edit it, a python error occurs and it cannot be opened for editing.
![image](https://user-images.githubusercontent.com/34697905/70863285-62612f80-1f81-11ea-85b7-d011197bbb21.png)

While the error on editing is the clearer bug, the inability to select model inputs for the interpolation is the bigger problem.  

The stack trace generated is copied below.

AttributeError: 'InterpolationDataWidget' object has no attribute 'addLayerData' 

An error has occurred while executing Python code: 

AttributeError: 'InterpolationDataWidget' object has no attribute 'addLayerData' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis/./python/plugins\processing\modeler\ModelerGraphicItem.py", line 523, in mousePressEvent
    self.action()
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis/./python/plugins\processing\modeler\ModelerGraphicItem.py", line 280, in editElement
    dlg = ModelerParametersDialog(elemAlg, self.model, self.element.childId(), self.element.configuration())
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis/./python/plugins\processing\modeler\ModelerParametersDialog.py", line 94, in __init__
    self.setupUi()
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis/./python/plugins\processing\modeler\ModelerParametersDialog.py", line 219, in setupUi
    self.setPreviousValues()
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis/./python/plugins\processing\modeler\ModelerParametersDialog.py", line 327, in setPreviousValues
    wrapper.setValue(value)
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis/./python/plugins\processing\algs\qgis\ui\InterpolationWidgets.py", line 215, in setValue
    self.widget.setValue(value)
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis/./python/plugins\processing\algs\qgis\ui\InterpolationWidgets.py", line 162, in setValue
    self.addLayerData(v[0], v[1])
AttributeError: 'InterpolationDataWidget' object has no attribute 'addLayerData'

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.10.1-A Coruña A Coruña, ef24c526da 

Python Path:
C:/PROGRA~1/QGIS3~1.10/apps/qgis/./python
C:/Users/Michael/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Michael/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.10/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.10\bin\python37.zip
C:\PROGRA~1\QGIS3~1.10\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib
C:\Program Files\QGIS 3.10\bin
C:\PROGRA~1\QGIS3~1.10\apps\Python37
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\Pythonwin
C:/Users/Michael/AppData/Roaming/QGIS/QGIS3\profiles\default/python
D:/SharedFiles/maps/QGIS plugins

**Comment by alexbruy** [comment]
Duplicates #30029.
