### ISSUE TITLE
importing networkx causes error

### ISSUE THREAD

**Issue by matheusfillipe** [qgis/QGIS#33542]
I am trying to use networkx inside qgis but either importing it from the qgis shell or using it from a plugin causes this error: "AttributeError: 'WindowsPath' object has no attribute 'rstrip"

`
AttributeError: 'WindowsPath' object has no attribute 'rstrip' 
Traceback (most recent call last):
  File "C:/Users/mathe/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoRoad\trimesh\path\traversal.py", line 11, in 
    import networkx as nx
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\networkx\__init__.py", line 128, in 
    import networkx.drawing
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\networkx\drawing\__init__.py", line 6, in 
    from . import nx_pydot
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\networkx\drawing\nx_pydot.py", line 27, in 
    from pkg_resources import parse_version
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\pkg_resources\__init__.py", line 3112, in 
    @_call_aside
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\pkg_resources\__init__.py", line 3096, in _call_aside
    f(*args, **kwargs)
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\pkg_resources\__init__.py", line 3140, in _initialize_master_working_set
    for dist in working_set
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\pkg_resources\__init__.py", line 3140, in 
    for dist in working_set
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\pkg_resources\__init__.py", line 2647, in activate
    declare_namespace(pkg)
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\pkg_resources\__init__.py", line 2184, in declare_namespace
    _handle_ns(packageName, path_item)
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\pkg_resources\__init__.py", line 2101, in _handle_ns
    loader = importer.find_module(packageName)
  File "", line 431, in _find_module_shim
  File "", line 1346, in find_loader
  File "", line 1391, in find_spec
  File "", line 59, in _path_join
  File "", line 59, in 
AttributeError: 'WindowsPath' object has no attribute 'rstrip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/mathe/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoRoad\app\controller\estacas.py", line 160, in 
    diag.btnPreview.clicked.connect(lambda: self.corteExport(True))
  File "C:/Users/mathe/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoRoad\app\controller\estacas.py", line 181, in corteExport
    self.combined.show()
  File "C:/Users/mathe/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoRoad\trimesh\path\path.py", line 1018, in show
    if self.is_closed:
  File "C:/Users/mathe/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoRoad\trimesh\path\path.py", line 414, in is_closed
    dict(self.vertex_graph.degree()).values())
  File "C:/Users/mathe/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoRoad\trimesh\caching.py", line 104, in get_cached
    value = function(*args, **kwargs)
  File "C:/Users/mathe/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoRoad\trimesh\path\path.py", line 438, in vertex_graph
    graph, closed = traversal.vertex_graph(self.entities)
  File "C:/Users/mathe/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoRoad\trimesh\path\traversal.py", line 39, in vertex_graph
    graph = nx.Graph()
  File "C:/Users/mathe/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoRoad\trimesh\exceptions.py", line 23, in __getattribute__
    raise super(ExceptionModule, self).__getattribute__('exc')
  File "C:/Users/mathe/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoRoad\trimesh\path\traversal.py", line 14, in 
    from .. import networkx
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/mathe/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoRoad\trimesh\networkx\__init__.py", line 105, in 
    from . import convert_matrix
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/mathe/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoRoad\trimesh\networkx\convert_matrix.py", line 31, in 
    import networkx as nx
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\networkx\__init__.py", line 128, in 
    import networkx.drawing
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\networkx\drawing\__init__.py", line 6, in 
    from . import nx_pydot
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\networkx\drawing\nx_pydot.py", line 27, in 
    from pkg_resources import parse_version
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\pkg_resources\__init__.py", line 3112, in 
    @_call_aside
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\pkg_resources\__init__.py", line 3096, in _call_aside
    f(*args, **kwargs)
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\pkg_resources\__init__.py", line 3140, in _initialize_master_working_set
    for dist in working_set
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\pkg_resources\__init__.py", line 3140, in 
    for dist in working_set
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\pkg_resources\__init__.py", line 2647, in activate
    declare_namespace(pkg)
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\pkg_resources\__init__.py", line 2184, in declare_namespace
    _handle_ns(packageName, path_item)
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\pkg_resources\__init__.py", line 2101, in _handle_ns
    loader = importer.find_module(packageName)
  File "", line 431, in _find_module_shim
  File "", line 1346, in find_loader
  File "", line 1391, in find_spec
  File "", line 59, in _path_join
  File "", line 59, in 
AttributeError: 'WindowsPath' object has no attribute 'rstrip'

`

**Comment by alexbruy** [comment]
Still true with latest 3.10/master?

**Comment by alexbruy** [comment]
Closing for the lack of feedback. Please reopen if necessary.
