### ISSUE TITLE
PyQt/QtWebKitWidgets.py uses deprecated QtWebKitWidgets

### ISSUE THREAD

**Issue by neteler** [qgis/QGIS#33924]
**Describe the bug**

In PyQt5 "QtWebKitWidgets" is no longer available. Instead it is replaced with "QtWebEngineWidgets". QtWebKit got deprecated upstream in Qt 5.5 and removed in 5.6, see https://wiki.qt.io/New_Features_in_Qt_5.6#Removed_Modules

This has become an issue in Fedora 31+ (and likely other distros offering Qt5.6+), probably requiring a QGIS update in:

https://github.com/qgis/QGIS/blob/8a3c7b14c367771d096b4a6d006aa3c4b1017dd5/python/PyQt/PyQt5/QtWebKitWidgets.py#L24

Probably into (just guessing):

```
from PyQt5.QtWebEngineWidgets import *
```

References:
 * https://wiki.qt.io/New_Features_in_Qt_5.6#Removed_Modules
 * https://stackoverflow.com/questions/37876987/cannot-import-qtwebkitwidgets-in-pyqt5/52228428#52228428
 * https://doc.qt.io/qt-5/qtwebenginewidgets-qtwebkitportingguide.html

**Comment by nyalldawson** [comment]
It was later undeprecated by qt. The web engine widgets aren't a full replacement, and qgis requires functionality that isn't available in the web engine versions. This is a won't fix.

**Comment by neteler** [comment]
> It was later undeprecated by qt.

@nyalldawson: I see - in which version? I don't find any reference... 

> The web engine widgets aren't a full replacement, and qgis requires functionality that isn't available in the web engine versions. This is a won't fix.

Sure, np. I would, knowing the right Qt version, open a Fedora packaging bugticket.

**Comment by nyalldawson** [comment]
@neteler 

See 

https://lists.qt-project.org/pipermail/development/2016-June/026156.html

https://lists.qt-project.org/pipermail/development/2016-June/026282.html

and  (more importantly), all the activity flowing into https://code.qt.io/cgit/qt/qtwebkit.git

**Comment by ArchangeGabriel** [comment]
It was already abandoned again at the time this issue was opened. They were no new commits since October 2019, and there has not been any ever since. It’s also being removed from distro like Arch Linux.

**Comment by togo65** [comment]
No updates yet? Still a problem on QGIS 3.42

```An error has occurred while executing Python code: 

ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets' 
Traceback (most recent call last):
  File "/home/roger/.local/share/QGIS/QGIS3/profiles/default/python/plugins/postgis_toolbox/CustomQueryBuilder/UI/PostGISHelpDialog.py", line 31, in add_web_view_widget
    from qgis.PyQt import QtWebEngineWidgets
  File "/usr/lib/python3.13/site-packages/qgis/utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3.13/site-packages/qgis/PyQt/QtWebEngineWidgets.py", line 20, in 
    from PyQt5.QtWebEngineWidgets import *
  File "/usr/lib/python3.13/site-packages/qgis/utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/roger/.local/share/QGIS/QGIS3/profiles/default/python/plugins/postgis_toolbox/postgis_toolbox.py", line 187, in run_query_editor
    self._display_query_builder()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/roger/.local/share/QGIS/QGIS3/profiles/default/python/plugins/postgis_toolbox/postgis_toolbox.py", line 220, in _display_query_builder
    self.query_dlg = CustomQueryBuilder(
                     ~~~~~~~~~~~~~~~~~~^
        self, parent.db, parent, parent.queryBuilderFirst)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roger/.local/share/QGIS/QGIS3/profiles/default/python/plugins/postgis_toolbox/CustomQueryBuilder/CustomQueryBuilder.py", line 46, in __init__
    self.ui.setupUi(self)
    ~~~~~~~~~~~~~~~^^^^^^
  File "/home/roger/.local/share/QGIS/QGIS3/profiles/default/python/plugins/postgis_toolbox/CustomQueryBuilder/UI/CustomQueryBuilderDialog.py", line 18, in setupUi
    self.create_widgets(dialog_instance)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/roger/.local/share/QGIS/QGIS3/profiles/default/python/plugins/postgis_toolbox/CustomQueryBuilder/UI/CustomQueryBuilderDialog.py", line 257, in create_widgets
    self.postgis_info_dialog = PostGISHelpDialog(self)
                               ~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/roger/.local/share/QGIS/QGIS3/profiles/default/python/plugins/postgis_toolbox/CustomQueryBuilder/UI/PostGISHelpDialog.py", line 24, in __init__
    self.add_web_view_widget()
    ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/roger/.local/share/QGIS/QGIS3/profiles/default/python/plugins/postgis_toolbox/CustomQueryBuilder/UI/PostGISHelpDialog.py", line 34, in add_web_view_widget
    from qgis.PyQt import QtWebKitWidgets
  File "/usr/lib/python3.13/site-packages/qgis/utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3.13/site-packages/qgis/PyQt/QtWebKitWidgets.py", line 24, in 
    from PyQt5.QtWebKitWidgets import *
  File "/usr/lib/python3.13/site-packages/qgis/utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'


Python version: 3.13.5 (main, Jun 21 2025, 09:35:00) [GCC 15.1.1 20250425] 
QGIS version: 3.42.3-Münster Münster, exported 

Python Path:
/home/roger/.local/share/QGIS/QGIS3/profiles/default/python/plugins/postgis_toolbox
/usr/share/qgis/python
/home/roger/.local/share/QGIS/QGIS3/profiles/default/python
/home/roger/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python313.zip
/usr/lib/python3.13
/usr/lib/python3.13/lib-dynload
/usr/lib/python3.13/site-packages
/home/roger/.local/share/QGIS/QGIS3/profiles/default/python```
