### ISSUE TITLE
Python Error Message

### ISSUE THREAD

**Issue by FlyingEagle** [qgis/QGIS#34116]
QGIS 3.10.2

I got this message/error, which plugin is it?
How can I fix it?

2020-01-29T15:35:31     WARNING    Traceback (most recent call last):
              File "C:/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ale\advanced_line_editor.py", line 299, in currentLayerChanged
              self.currentlayer.editingStarted.disconnect(self.curLayerIsEditable)
             RuntimeError: wrapped C/C++ object of type QgsVectorLayer has been deleted
             
2020-01-29T15:35:32     WARNING    Traceback (most recent call last):
              File "C:/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ale\advanced_line_editor.py", line 299, in currentLayerChanged
              self.currentlayer.editingStarted.disconnect(self.curLayerIsEditable)
             RuntimeError: wrapped C/C++ object of type QgsVectorLayer has been deleted
             
2020-01-29T15:43:01     WARNING    Traceback (most recent call last):
              File "C:/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ale\advanced_line_editor.py", line 299, in currentLayerChanged
              self.currentlayer.editingStarted.disconnect(self.curLayerIsEditable)
             RuntimeError: wrapped C/C++ object of type QgsVectorLayer has been deleted

**Comment by elpaso** [comment]
The plugin name seems to be something like "advanced line editor" but this is not the place to ask for help about plugins sorry.
