### ISSUE TITLE
AssertionError: '' not found in ('EPSG:4326', 'EPSG:4030')

### ISSUE THREAD

**Issue by strk** [qgis/QGIS#34209]
Running:
> ctest --output-on-failure -R 'PyQgsVectorLayer$'

From a build of  [current master](db40d88e8d84ec6c54e9aa3ac3f229739f987bea) branch with GDAL `3.0.4, released 2020/01/28` and sqlite `3.22.0 2018-01-22 18:45:57 0c55d179733b46d8d0ba4d88e01a25e10677046ee3da1d5b1581e86726f2alt2
` on my system results in this error:

```
======================================================================
FAIL: testSetDataSource (__main__.TestQgsVectorLayer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/qgis/qgis-master/tests/src/python/test_qgsvectorlayer.py", line 354, in testSetDataSource
    self.assertIn(layer.crs().authid(), ('EPSG:4326', 'EPSG:4030'))
AssertionError: '' not found in ('EPSG:4326', 'EPSG:4030')

----------------------------------------------------------------------

```

Any idea what could be the cause of that ?
@jef-n @nyalldawson @m-kuhn

**Comment by strk** [comment]
More output (`ctest -V`):
```
509: ....Application state:
509: QGIS_PREFIX_PATH env var:          /usr/src/qgis/build/master/output
509: Prefix:            
509: Plugin Path:               /usr/src/qgis/build/master/output/lib/qgis/plugins
509: Package Data Path: /usr/src/qgis/build/master/output/data
509: Active Theme Name: 
509: Active Theme Path: /usr/src/qgis/build/master/output/data/resources/themes//icons/
509: Default Theme Path:        :/images/themes/default/
509: SVG Search Paths:  /usr/src/qgis/build/master/output/data/svg/
509:            /home/strk/.local/share/test_qgsvectorlayer.py/profiles/default/svg/
509: User DB Path:      /usr/src/qgis/build/master/output/data/resources/qgis.db
509: Auth DB Path:      /home/strk/.local/share/test_qgsvectorlayer.py/profiles/default/qgis-auth.db
509: 
509: OGR(1): Cannot open this is an outrage!!!.()
509: OGR(1): Cannot open i'm the moon.()
509: OGR(1): Cannot open nothing.()
509: OGR(1): Cannot open nothing.()
509: OGR(1): Cannot open nothing.()
509: (1): 1 unavailable layers found:
509: (1):  * nothing
509: (1): cannot add feature, wrong field count: layer: 2 feature: 0:
509: (1): cannot add feature, wrong field count: layer: 2 feature: 0:
509: General(2): St
509: ======================================================================
509: FAIL: testSetDataSource (__main__.TestQgsVectorLayer)
509: ----------------------------------------------------------------------
509: Traceback (most recent call last):
509:   File "/usr/src/qgis/qgis-master/tests/src/python/test_qgsvectorlayer.py", line 354, in testSetDataSource
509:     self.assertIn(layer.crs().authid(), ('EPSG:4326', 'EPSG:4030'))
509: AssertionError: '' not found in ('EPSG:4326', 'EPSG:4030')
509: 
509: ----------------------------------------------------------------------
```

@rouault does the above ring any bell for you ?

**Comment by strk** [comment]
Proj version is `Rel. 6.3.0, January 1st, 2020`

**Comment by strk** [comment]
It looks like the above was due to a dirty build of GDAL. A _clean_ rebuild of it fixed it.

**Comment by strk** [comment]
Sorry, I was wrong, the reported problem is NOT fixed by a clean GDAL build

**Comment by jgrocha** [comment]
Same error here, with GDAL and PROJ buils from source.
```
GDAL 3.1.0dev-406debacac-dirty, released 2020/01/25
PROJ Rel. 7.0.0, March 1st, 2020
```
In my local builds, I always get a large number of `INSERT INTO tbl_srs` errors.

**Comment by jgrocha** [comment]
The errors related with the build/crssync are:
```
Could not execute: INSERT INTO tbl_srs(srs_id, description,projection_acronym,ellipsoid_acronym,parameters,srid,auth_name,auth_id,is_geo,deprecated) VALUES (60158, 'RESEAU GEODESIQUE DE WALLIS ET FUTUNA 1996 CARTESIENNES GEOCENTRIQUES','geocent','GRS80','+proj=geocent +ellps=GRS80 +units=m +no_defs',520000158,'IGNF','RGWF96',0,0) [UNIQUE constraint failed: tbl_srs.srs_id/UNIQUE constraint failed: tbl_srs.srs_id]

Could not execute: INSERT INTO tbl_srs(srs_id, description,projection_acronym,ellipsoid_acronym,parameters,srid,auth_name,auth_id,is_geo,deprecated) VALUES (60159, 'RESEAU GEODESIQUE DE WALLIS ET FUTUNA 1996 GEOGRAPHIQUES (DD)','longlat','GRS80','+proj=longlat +ellps=GRS80 +no_defs',520000159,'IGNF','RGWF96GDD',1,0) [UNIQUE constraint failed: tbl_srs.srs_id/UNIQUE constraint failed: tbl_srs.srs_id]

Could not execute: INSERT INTO tbl_srs(srs_id, description,projection_acronym,ellipsoid_acronym,parameters,srid,auth_name,auth_id,is_geo,deprecated) VALUES (60160, 'RESEAU GEODESIQUE DE WALLIS ET FUTUNA 1996 GEOGRAPHIQUES (DD)','longlat','GRS80','+proj=longlat +ellps=GRS80 +no_defs',520000160,'IGNF','RGWF96GEODD',1,0) [UNIQUE constraint failed: tbl_srs.srs_id/UNIQUE constraint failed: tbl_srs.srs_id]

161 CRSs could not be updated.
```

I don't think they are related with this issue.

**Comment by strk** [comment]
I can't reproduce this anymore, closing
