### ISSUE TITLE
QGIS fails to get CRS of inserted shapefile under gdal3/proj6

### ISSUE THREAD

**Issue by nirvn** [qgis/QGIS#34211]
**Describe the bug**

That didn't take long. 

Using a  gdal3/proj6 QGIS build, inserting a shapefile layer fails to assign the proper CRS (wrongly flagged as Unknown CRS).

An error/warning message is printed in the console:

`src/core/qgscoordinatetransform_p.cpp:289 : (proj_logger) [40ms] proj_crs_get_coordinate_system: Object is not a SingleCRS`

**How to Reproduce**

1. Launch a gdal3/proj6 QGIS build, and create a new project
2. Add the attached dataset onto the project:
[ELCs2012.zip](https://github.com/qgis/QGIS/files/4147133/ELCs2012.zip)

3. The CRS of the shapefile is EPSG:3148, yet QGIS registers the shapefile as having an Unknown CRS

**QGIS and OS versions**

QGIS master, Ubuntu 20.04, gdal 3.0.4, proj 6.3.0.

**Comment by nirvn** [comment]
This is what comes prior to the logger warning/error message:

```
(gdb) where
#0  proj_logger(void*, int, char const*) (level=1, message=0x5555571e9350 "proj_crs_get_coordinate_system: Object is not a SingleCRS")
    at /home/webmaster/dev/cpp/QGIS/src/core/qgscoordinatetransform_p.cpp:289
#1  0x00007fffed82c00a in  () at /usr/lib/x86_64-linux-gnu/libproj.so.15
#2  0x00007fffed836da6 in proj_crs_get_coordinate_system () at /usr/lib/x86_64-linux-gnu/libproj.so.15
#3  0x00007ffff4f4812a in QgsCoordinateReferenceSystem::setMapUnits() (this=0x7fffffffbaa0) at /home/webmaster/dev/cpp/QGIS/src/core/qgscoordinatereferencesystem.cpp:1686
#4  0x00007ffff4f47eab in QgsCoordinateReferenceSystem::setWktString(QString const&, bool) (this=0x7fffffffbaa0, wkt=..., allowProjFallback=true)
    at /home/webmaster/dev/cpp/QGIS/src/core/qgscoordinatereferencesystem.cpp:1608
#5  0x00007ffff4f44f41 in QgsCoordinateReferenceSystem::createFromWkt(QString const&) (this=0x7fffffffbaa0, wkt=...)
    at /home/webmaster/dev/cpp/QGIS/src/core/qgscoordinatereferencesystem.cpp:864
#6  0x00007ffff4f40b09 in QgsCoordinateReferenceSystem::fromWkt(QString const&) (wkt=...) at /home/webmaster/dev/cpp/QGIS/src/core/qgscoordinatereferencesystem.cpp:235
#7  0x00007ffff4e7188d in QgsOgrProvider::crs() const (this=0x55555b49a410) at /home/webmaster/dev/cpp/QGIS/src/core/providers/ogr/qgsogrprovider.cpp:3703
#8  0x00007ffff52f64c9 in QgsVectorLayer::setCoordinateSystem() (this=0x55555b98c330) at /home/webmaster/dev/cpp/QGIS/src/core/qgsvectorlayer.cpp:3434
#9  0x00007ffff52dcafe in QgsVectorLayer::setDataSource(QString const&, QString const&, QString const&, QgsDataProvider::ProviderOptions const&, bool)
    (this=0x55555b98c330, dataSource=..., baseName=..., provider=..., options=..., loadDefaultStyleFlag=false) at /home/webmaster/dev/cpp/QGIS/src/core/qgsvectorlayer.cpp:1607
#10 0x00007ffff52d2613 in QgsVectorLayer::QgsVectorLayer(QString const&, QString const&, QString const&, QgsVectorLayer::LayerOptions const&)
    (this=0x55555b98c330, vectorLayerPath=..., baseName=..., providerKey=..., options=...) at /home/webmaster/dev/cpp/QGIS/src/core/qgsvectorlayer.cpp:178
#11 0x00007ffff74bf665 in QgisApp::addVectorLayerPrivate(QString const&, QString const&, QString const&, bool) (this=
    0x55555685dd80, vectorLayerPath=..., name=..., providerKey=..., guiWarning=true) at /home/webmaster/dev/cpp/QGIS/src/app/qgisapp.cpp:11763
#12 0x00007ffff74bf17c in QgisApp::addVectorLayer(QString const&, QString const&, QString const&) (this=0x55555685dd80, vectorLayerPath=..., name=..., providerKey=...)
    at /home/webmaster/dev/cpp/QGIS/src/app/qgisapp.cpp:11728
```

**Comment by nirvn** [comment]
Note: if I delete the .qpj file, which doesn't match the content of the .prj file, the shapefile opens and the right CRS is attributed to the layer.

**Comment by nirvn** [comment]
projinfo --identify using the .qpj WKT string:

```
Identification match count: 1
BoundCRS of EPSG:3148: 70 %
```

projinfo --identify using the .prj WKT string:

```
Identification match count: 1
EPSG:3148: 90 %
```

**Comment by nirvn** [comment]
@jef-n , 10 years ago, you pushed this commit (https://github.com/qgis/QGIS/commit/1712e428fb1945e46673725f921519982c32c75a) adding the .qpj workaround for two projection issues. I'm wondering whether we should get rid of it under GDAL3/PROJ6. The GDAL2/PROJ5 strings created and added to .qpj when saving a shapefile are causing issues under GDAL3/PROJ6.

I propose to keep this hack for GDAL2/PROJ5 but clear the deck and avoid it under GDAL3/PROJ6. All good?

**Comment by gioman** [comment]
@nirvn could this be somehow related to https://github.com/qgis/QGIS/issues/34196#issuecomment-581190754 ?
