### ISSUE TITLE
DB Manager throws Python error on table metadata preview

### ISSUE THREAD

**Issue by tjukanovt** [qgis/QGIS#34681]
Using the latest QGIS 3.12.0 on Windows and I have a PostGIS connected. When I go to DB Manager and click on a table on the left sidebar list, I should usually see table metadata (number of rows, extent, etc.), but with the latest QGIS I get a Python error with the following message:

`2020-02-26T07:36:25     WARNING    Traceback (most recent call last):
              File "C:/PROGRA~1/QGIS3~1.12/apps/qgis/./python/plugins\db_manager\db_manager.py", line 100, in itemChanged
              self.refreshTabs()
              File "C:/PROGRA~1/QGIS3~1.12/apps/qgis/./python/plugins\db_manager\db_manager.py", line 143, in refreshTabs
              self.info.showInfo(item)
              File "C:/PROGRA~1/QGIS3~1.12/apps/qgis/./python/plugins\db_manager\info_viewer.py", line 74, in showInfo
              self._showTableInfo(item)
              File "C:/PROGRA~1/QGIS3~1.12/apps/qgis/./python/plugins\db_manager\info_viewer.py", line 133, in _showTableInfo
              html += table.info().toHtml()
              File "C:/PROGRA~1/QGIS3~1.12/apps/qgis/./python/plugins\db_manager\db_plugins\info_model.py", line 361, in toHtml
              ret = self.getTableInfo()
              File "C:/PROGRA~1/QGIS3~1.12/apps/qgis/./python/plugins\db_manager\db_plugins\postgis\info_model.py", line 231, in getTableInfo
              ret = TableInfo.getTableInfo(self)
              File "C:/PROGRA~1/QGIS3~1.12/apps/qgis/./python/plugins\db_manager\db_plugins\info_model.py", line 303, in getTableInfo
              spatial_info = self.spatialInfo()
              File "C:/PROGRA~1/QGIS3~1.12/apps/qgis/./python/plugins\db_manager\db_plugins\postgis\info_model.py", line 250, in spatialInfo
              return VectorTableInfo.spatialInfo(self)
              File "C:/PROGRA~1/QGIS3~1.12/apps/qgis/./python/plugins\db_manager\db_plugins\info_model.py", line 400, in spatialInfo
              estimated_extent_str = '%.5f, %.5f - %.5f, %.5f' % self.table.estimatedExtent
             TypeError: must be real number, not list`

**Comment by elpaso** [comment]
Duplicates https://github.com/qgis/QGIS/issues/34467 ?

**Comment by tjukanovt** [comment]
@elpaso Yes it does! Sorry. Didn't see that in the similar issues. I'll close this.
