### ISSUE TITLE
PostGisDBConnector AttributeError: 'PostGisDBConnector' object has no attribute 'connection'

### ISSUE THREAD

**Issue by HenrikSpa** [qgis/QGIS#35654]
I get a python error when trying to create a PostGisDBConnector object. Creating this object has worked in QGIS 3 up until at least version 3.10.

To reproduce, open Plugins > Python console and run the command: 
(the uri is an empty string in this example just to show the error. The command fail with a correct uri as well.)

```
>>> from db_manager.db_plugins.postgis.connector import PostGisDBConnector
>>> PostGisDBConnector('')
```

Which returns

```
Exception ignored in: <function DBConnector.__del__ at 0x0000021C52755488>
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python/plugins\db_manager\db_plugins\connector.py", line 41, in __del__
    if self.connection is not None:
AttributeError: 'PostGisDBConnector' object has no attribute 'connection'
Traceback (most recent call last):
  File "C:\OSGEO4~1\apps\Python37\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
TypeError: __init__() missing 1 required positional argument: 'connection'
```

I get this error both using Windows 10 + OSgeo4win64 and Linux Mint.

Windows 10:

```
QGIS version
3.12.1-București
QGIS code revision
121cc00ff0
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.1
Running against PROJ
Rel. 6.3.1, February 10th, 2020
OS Version
Windows 10 (10.0)
Active python plugins
db_manager; 
MetaSearch; 
processing
```

Linu Mint

```
QGIS version
3.12.1-București
QGIS code revision
121cc00ff0
Compiled against Qt
5.9.5
Running against Qt
5.9.5
Compiled against GDAL/OGR
2.2.3
Running against GDAL/OGR
2.2.3
Compiled against GEOS
3.6.2-CAPI-1.10.2
Running against GEOS
3.6.2-CAPI-1.10.2 4d2925d6
Compiled against SQLite
3.22.0
Running against SQLite
3.22.0
PostgreSQL Client Version
10.12 (Ubuntu 10.12-0ubuntu0.18.04.1)
SpatiaLite Version
4.3.0a
QWT Version
6.1.3
QScintilla2 Version
2.10.2
PROJ.4 Version
493
OS Version
Linux Mint 19.1
Active python plugins
db_manager; 
processing; 
MetaSearch
```

**Comment by nyalldawson** [comment]
That's not part of the stable API, and was moved to a C++ class in 3.10
