### ISSUE TITLE
DB Manager/PostgreSQL doesn't show tables with CONSTRAINT TRIGGER

### ISSUE THREAD

**Issue by espinafre** [qgis/QGIS#35967]
On DB Manager, when trying to open a PostgreSQL that has a CONSTRAINT TRIGGER, the table is not shown, giving instead a Python error: 

![image](https://user-images.githubusercontent.com/25933044/80145457-94654c80-8586-11ea-8c7d-dae774940d6f.png)
The contents of the window that opens when I click on the Stack trace button is as follows:
```
An error has occurred while executing Python code: 

AttributeError: 'NoneType' object has no attribute 'split' 
Traceback (most recent call last):
  File "/home/jose/sw/qgis/QGIS/build-master/output/python/plugins/db_manager/db_manager.py", line 100, in itemChanged
    self.refreshTabs()
  File "/home/jose/sw/qgis/QGIS/build-master/output/python/plugins/db_manager/db_manager.py", line 143, in refreshTabs
    self.info.showInfo(item)
  File "/home/jose/sw/qgis/QGIS/build-master/output/python/plugins/db_manager/info_viewer.py", line 74, in showInfo
    self._showTableInfo(item)
  File "/home/jose/sw/qgis/QGIS/build-master/output/python/plugins/db_manager/info_viewer.py", line 133, in _showTableInfo
    html += table.info().toHtml()
  File "/home/jose/sw/qgis/QGIS/build-master/output/python/plugins/db_manager/db_plugins/info_model.py", line 361, in toHtml
    ret = self.getTableInfo()
  File "/home/jose/sw/qgis/QGIS/build-master/output/python/plugins/db_manager/db_plugins/postgis/info_model.py", line 231, in getTableInfo
    ret = TableInfo.getTableInfo(self)
  File "/home/jose/sw/qgis/QGIS/build-master/output/python/plugins/db_manager/db_plugins/info_model.py", line 296, in getTableInfo
    general_info = self.generalInfo()
  File "/home/jose/sw/qgis/QGIS/build-master/output/python/plugins/db_manager/db_plugins/postgis/info_model.py", line 121, in generalInfo
    if len([fld for fld in self.table.fields() if fld.primaryKey])   File "/home/jose/sw/qgis/QGIS/build-master/output/python/plugins/db_manager/db_plugins/plugin.py", line 813, in fields
    self._fields = [self.tableFieldsFactory(x, self) for x in fields]
  File "/home/jose/sw/qgis/QGIS/build-master/output/python/plugins/db_manager/db_plugins/plugin.py", line 813, in 
    self._fields = [self.tableFieldsFactory(x, self) for x in fields]
  File "/home/jose/sw/qgis/QGIS/build-master/output/python/plugins/db_manager/db_plugins/postgis/plugin.py", line 256, in tableFieldsFactory
    return PGTableField(row, table)
  File "/home/jose/sw/qgis/QGIS/build-master/output/python/plugins/db_manager/db_plugins/postgis/plugin.py", line 405, in __init__
    for con in self.table().constraints():
  File "/home/jose/sw/qgis/QGIS/build-master/output/python/plugins/db_manager/db_plugins/plugin.py", line 859, in constraints
    self._constraints = [self.tableConstraintsFactory(x, self) for x in constraints]
  File "/home/jose/sw/qgis/QGIS/build-master/output/python/plugins/db_manager/db_plugins/plugin.py", line 859, in 
    self._constraints = [self.tableConstraintsFactory(x, self) for x in constraints]
  File "/home/jose/sw/qgis/QGIS/build-master/output/python/plugins/db_manager/db_plugins/postgis/plugin.py", line 259, in tableConstraintsFactory
    return PGTableConstraint(row, table)
  File "/home/jose/sw/qgis/QGIS/build-master/output/python/plugins/db_manager/db_plugins/postgis/plugin.py", line 434, in __init__
    self.columns = list(map(int, columns.split(' ')))
AttributeError: 'NoneType' object has no attribute 'split'


Python version: 3.8.2 (default, Apr 22 2020, 12:01:16) [GCC 9.3.0] 
QGIS version: 3.13.0-Master Master, 5d45b71421 

Python Path:
/home/jose/sw/qgis/QGIS/build-master/output/python
/home/jose/.local/share/QGIS/QGIS3/profiles/default/python
/home/jose/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/home/jose/sw/qgis/QGIS/build-master/output/python/plugins
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/usr/lib/python3.8/site-packages
/home/jose/.local/share/QGIS/QGIS3/profiles/default/python

```

To reproduce, the following SQL creates a table with a dummy trigger:

```sql
CREATE FUNCTION hi_trigger() RETURNS TRIGGER AS $$ BEGIN RAISE NOTICE 'Hello world'; RETURN NEW; END; $$ LANGUAGE plpgsql;
CREATE TABLE test_trigger(id SERIAL NOT NULL PRIMARY KEY, value varchar(32));
CREATE CONSTRAINT TRIGGER tg_test AFTER INSERT ON test_trigger DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE PROCEDURE hi_trigger();
```

I found that the following change fixes the problem:

```diff
--- connector.py        2020-03-18 14:40:33.057574531 -0300
+++ ../../../../../build-master/output/python/plugins/db_manager/db_plugins/postgis/connector.py        2020-04-23 17:32:27.159156063 -0300
@@ -657,7 +657,7 @@
                   LEFT JOIN pg_class t ON c.conrelid = t.oid
                         LEFT JOIN pg_class t2 ON c.confrelid = t2.oid
                         JOIN pg_namespace nsp ON t.relnamespace = nsp.oid
-                        WHERE t.relname = %s %s """ % (con_col_name, self.quoteString(tablename), schema_where)
+                        WHERE c.contype <> 't' AND t.relname = %s %s """ % (con_col_name, self.quoteString(tablename), schema_where)
 
         c = self._execute(None, sql)
         res = self._fetchall(c)
```
Despite appearing as constraints on the catalog pg_constraint, they are not *really* constraints, but rather a special kind of trigger, as seen here: https://www.postgresql.org/docs/12/catalog-pg-constraint.html and here: https://www.postgresql.org/docs/12/sql-createtrigger.html

Must I open a PR? Thank you all.

**Comment by gioman** [comment]
> Must I open a PR? Thank you all.

@espinafre yes plesae!
