### ISSUE TITLE
Processing modeler error when trying to comment an algorithm

### ISSUE THREAD

**Issue by m-kuhn** [qgis/QGIS#36036]
I am trying to add a comment to an algorithm in the modeler (latest master). A right click on an algorithm offers the menu item "Add comment", but an exception is raised when clicking on it:

```
AttributeError: 'ModelerParametersDialog' object has no attribute 'widget' 
Traceback (most recent call last):
  File "/home/mkuhn/dev/qgis/build-QGIS-Desktop-Debug/output/python/plugins/processing/modeler/ModelerGraphicItem.py", line 164, in editComment
    self.edit(edit_comment=True)
  File "/home/mkuhn/dev/qgis/build-QGIS-Desktop-Debug/output/python/plugins/processing/modeler/ModelerGraphicItem.py", line 135, in edit
    self.component().configuration())
  File "/home/mkuhn/dev/qgis/build-QGIS-Desktop-Debug/output/python/plugins/processing/modeler/ModelerParametersDialog.py", line 79, in __init__
    self.widget = ModelerParametersWidget(alg, model, algName, configuration, context=self.context, dialog=self)
  File "/home/mkuhn/dev/qgis/build-QGIS-Desktop-Debug/output/python/plugins/processing/modeler/ModelerParametersDialog.py", line 500, in __init__
    self.widget = ModelerParametersPanelWidget(alg, model, algName, configuration, dialog, context)
  File "/home/mkuhn/dev/qgis/build-QGIS-Desktop-Debug/output/python/plugins/processing/modeler/ModelerParametersDialog.py", line 160, in __init__
    self.setupUi()
  File "/home/mkuhn/dev/qgis/build-QGIS-Desktop-Debug/output/python/plugins/processing/modeler/ModelerParametersDialog.py", line 225, in setupUi
    wrapper = WidgetWrapperFactory.create_wrapper(param, self.dialog)
  File "/home/mkuhn/dev/qgis/build-QGIS-Desktop-Debug/output/python/plugins/processing/gui/wrappers.py", line 1847, in create_wrapper
    return WidgetWrapperFactory.create_wrapper_from_metadata(param, dialog, row, col)
  File "/home/mkuhn/dev/qgis/build-QGIS-Desktop-Debug/output/python/plugins/processing/gui/wrappers.py", line 1882, in create_wrapper_from_metadata
    wrapper = wrapper(param, dialog, row, col, **params)
  File "/home/mkuhn/dev/qgis/build-QGIS-Desktop-Debug/output/python/plugins/processing/gui/wrappers.py", line 155, in __init__
    self.widget = self.createWidget(**kwargs)
  File "/home/mkuhn/dev/qgis/build-QGIS-Desktop-Debug/output/python/plugins/processing/algs/gdal/ui/RasterOptionsWidget.py", line 38, in createWidget
    strings = self.dialog.getAvailableValuesOfType(QgsProcessingParameterString, QgsProcessingOutputString)
  File "/home/mkuhn/dev/qgis/build-QGIS-Desktop-Debug/output/python/plugins/processing/modeler/ModelerParametersDialog.py", line 111, in getAvailableValuesOfType
    return self.widget.getAvailableValuesOfType(paramType, outTypes, dataTypes)
AttributeError: 'ModelerParametersDialog' object has no attribute 'widget'
```

The model in question can be downloaded from https://raw.githubusercontent.com/jvdkwast/PyQGIS_Hydro/master/models/accessible_wells.model3

**Comment by m-kuhn** [comment]
That was quick, thanks !
