### ISSUE TITLE
Python error opening vector layers

### ISSUE THREAD

**Issue by thaysl** [qgis/QGIS#36104]
2020-04-29T22:03:30     WARNING    Traceback (most recent call last):
              File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins\processing\ProcessingPlugin.py", line 293, in sync_in_place_button_state
              self.toolbox.set_in_place_edit_mode(new_enabled_state and self.editInPlaceAction.isChecked())
              File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins\processing\gui\ProcessingToolbox.py", line 133, in set_in_place_edit_mode
              self.algorithmTree.setFilters(filters)
             RuntimeError: wrapped C/C++ object of type QgsProcessingToolboxTreeView has been deleted

**Comment by m-kuhn** [comment]
@thaysl can you describe exactly each step you have been doing (ideally in English) and try again on a new profile?

**Comment by gioman** [comment]
> (ideally in English)

English is not optional :)

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
