### ISSUE TITLE
Python Plugin Error with QGIS Desktop 3.10.5-A Coruña

### ISSUE THREAD

**Issue by RNodagala** [qgis/QGIS#36473]
QGIS Desktop fails with "Python error: Couldn't load plugin 'processing' due to an error when calling its classFactory() method See message log (Python Error) for more details."

PythonError Log:
Traceback (most recent call last):
              File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 334, in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins\processing\__init__.py", line 41, in classFactory
              from processing.ProcessingPlugin import ProcessingPlugin
              File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 744, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins\processing\ProcessingPlugin.py", line 47, in 
              from processing.gui.HistoryDialog import HistoryDialog
              File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 744, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins\processing\gui\HistoryDialog.py", line 33, in 
              from processing.gui import TestTools
              File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 744, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins\processing\gui\TestTools.py", line 34, in 
              from numpy import nan_to_num
              File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 744, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\Users\Ram\AppData\Roaming\Python\Python37\site-packages\numpy\__init__.py", line 140, in 
              from . import _distributor_init
              File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 744, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\Users\Ram\AppData\Roaming\Python\Python37\site-packages\numpy\_distributor_init.py", line 26, in 
              WinDLL(os.path.abspath(filename))
              File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\ctypes\__init__.py", line 356, in __init__
              self._handle = _dlopen(self._name, mode)
             OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by gioman** [comment]
@RNodagala try with a new QGIS profile.

**Comment by gioman** [comment]
Closing for lack of further feedback.
