### ISSUE TITLE
user-defined functions

### ISSUE THREAD

**Issue by genfild** [qgis/QGIS#36489]
Why does an error occur when loading user-defined functions?
v3.12.2
             
2020-05-16T21:01:46     WARNING    Пользовательское выражение getLayoutByName не действительно
             Traceback (most recent call last):
              File "C:/PROGRA~1/QGIS3~1.12/apps/qgis/./python\qgis\user.py", line 46, in load_user_expressions
              __import__("expressions.{0}".format(name), locals(), globals())
              File "C:/PROGRA~1/QGIS3~1.12/apps/qgis/./python\qgis\utils.py", line 744, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:/Users/genf/AppData/Roaming/QGIS/QGIS3\profiles\default/python\expressions\getLayoutByName.py", line 1, in 
              @qgsfunction(args='auto', group='Custom')
             NameError: name 'qgsfunction' is not defined
             
2020-05-16T21:01:46     WARNING    Пользовательское выражение getTop не действительно
             Traceback (most recent call last):
              File "C:/PROGRA~1/QGIS3~1.12/apps/qgis/./python\qgis\user.py", line 46, in load_user_expressions
              __import__("expressions.{0}".format(name), locals(), globals())
              File "C:/PROGRA~1/QGIS3~1.12/apps/qgis/./python\qgis\utils.py", line 744, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:/Users/genf/AppData/Roaming/QGIS/QGIS3\profiles\default/python\expressions\getTop.py", line 1, in 
              @qgsfunction(args='auto', group='Custom')
             NameError: name 'qgsfunction' is not defined

**Comment by alexbruy** [comment]
Please ask questions in the support channels like gis.stackexchange, mailing lists, IRC. Bugtracker used to report bug and ask for features.
