### ISSUE TITLE
Vector menu doesn't open on Windows with `Not setting mouse grab for invisible window`

### ISSUE THREAD

**Issue by olivierdalang** [qgis/QGIS#37227]
**Describe the bug**

The Vector menu doesn't open, with the following error (message bar and console) :

```
Qt : QWindowsWindow::setMouseGrabEnabled: Not setting mouse grab for invisible window QWidgetWindow/'mVectorMenuWindow'
```

The other menus still work.

**How to Reproduce**

Open QGIS, click on the vector menu.

**QGIS and OS versions**

```

QGIS version
3.13.0-Master
QGIS code revision
e9a0c01b21
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.2.0dev
Running against GDAL/OGR
3.2.0dev
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
7.1.0
Running against PROJ
Rel. 7.1.0, August 1st, 2020
OS Version
Windows 10 (10.0)
This copy of QGIS writes debugging output.
Active python plugins
curved_split_merge; 
pluginbuilder3; 
plugin_reloader; 
swiss_locator; 
db_manager
```

**Additional context**

**Comment by gioman** [comment]
Does not happen here, but my master could be not the latest one (I install from repos).

**Comment by gioman** [comment]
sorry, I overlooked "on Windows".

**Comment by nyalldawson** [comment]
I can't reproduce (on Windows). Have you tried a clean profile?

**Comment by olivierdalang** [comment]
Yes, but I noticed I have the issue with the nightly installed from OSGeo4W, not my local build, so it's probably some packaging issue ?

I also have the below error that happens only on nightly (on QGIS startup and when trying to open the python console) :

```
Traceback (most recent call last):
  File "C:\OSGEO4~1\apps\gdal-dev\pymod3\lib\site-packages\osgeo\ogr.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\OSGEO4~1\apps\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "", line 1006, in _gcd_import
  File "", line 983, in _find_and_load
  File "", line 967, in _find_and_load_unlocked
  File "", line 670, in _load_unlocked
  File "", line 583, in module_from_spec
  File "", line 1043, in create_module
  File "", line 219, in _call_with_frames_removed
ImportError: DLL load failed: The specified procedure could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\OSGEO4~1\apps\Python37\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "", line 1, in 
  File "C:/OSGEO4~1/apps/qgis-dev/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/OSGEO4~1/apps/qgis-dev/./python/plugins\processing\__init__.py", line 35, in 
    from processing.tools.raster import *  # NOQA
  File "C:/OSGEO4~1/apps/qgis-dev/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/OSGEO4~1/apps/qgis-dev/./python/plugins\processing\tools\raster.py", line 26, in 
    from osgeo import gdal
  File "C:/OSGEO4~1/apps/qgis-dev/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGEO4~1\apps\gdal-dev\pymod3\lib\site-packages\osgeo\gdal.py", line 1904, in 
    import osgeo.ogr
  File "C:/OSGEO4~1/apps/qgis-dev/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGEO4~1\apps\gdal-dev\pymod3\lib\site-packages\osgeo\ogr.py", line 17, in 
    _ogr = swig_import_helper()
  File "C:\OSGEO4~1\apps\gdal-dev\pymod3\lib\site-packages\osgeo\ogr.py", line 16, in swig_import_helper
    return importlib.import_module('_ogr')
  File "C:\OSGEO4~1\apps\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_ogr'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "", line 2, in 
  File "C:/OSGEO4~1/apps/qgis-dev/./python\console\console.py", line 47, in show_console
    _console = PythonConsole(parent)
  File "C:/OSGEO4~1/apps/qgis-dev/./python\console\console.py", line 83, in __init__
    self.console = PythonConsoleWidget(self)
  File "C:/OSGEO4~1/apps/qgis-dev/./python\console\console.py", line 113, in __init__
    self.shell = ShellScintilla(self)
  File "C:/OSGEO4~1/apps/qgis-dev/./python\console\console_sci.py", line 104, in __init__
    self.runsource(line)
  File "C:/OSGEO4~1/apps/qgis-dev/./python\console\console_sci.py", line 676, in runsource
    return super(ShellScintilla, self).runsource(source, filename, symbol)
  File "C:\OSGEO4~1\apps\Python37\lib\code.py", line 74, in runsource
    self.runcode(code)
  File "C:\OSGEO4~1\apps\Python37\lib\code.py", line 94, in runcode
    self.showtraceback()
  File "C:\OSGEO4~1\apps\Python37\lib\code.py", line 148, in showtraceback
    sys.excepthook(ei[0], ei[1], last_tb)
  File "C:/OSGEO4~1/apps/qgis-dev/./python\console\console_sci.py", line 672, in excepthook
    self.write("".join(traceback.format_exception(etype, value, tb)))
  File "C:/OSGEO4~1/apps/qgis-dev/./python\console\console_sci.py", line 657, in write
    sys.stderr.write(txt)
AttributeError: 'NoneType' object has no attribute 'write'


Python version:
3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]

QGIS version:
3.13.0-Master 'Master', e9a0c01b21

Python path:
['C:/OSGEO4~1/apps/qgis-dev/./python', 'C:/Users/Olivier/AppData/Roaming/QGIS/QGIS3\\profiles\\reallyempty/python', 'C:/Users/Olivier/AppData/Roaming/QGIS/QGIS3\\profiles\\reallyempty/python/plugins', 'C:/OSGEO4~1/apps/qgis-dev/./python/plugins', 'C:\\OSGEO4~1\\apps\\gdal-dev\\pymod3\\lib\\site-packages', 'C:\\OSGEO4~1\\apps\\Python37', 'C:\\OSGEO4~1\\apps\\Python37\\Scripts', 'C:\\OSGeo4W64\\bin\\python37.zip', 'C:\\OSGEO4~1\\apps\\Python37\\DLLs', 'C:\\OSGEO4~1\\apps\\Python37\\lib', 'C:\\OSGeo4W64\\bin', 'C:\\Users\\Olivier\\AppData\\Roaming\\Python\\Python37\\site-packages', 'C:\\OSGEO4~1\\apps\\Python37\\lib\\site-packages', 'C:\\OSGEO4~1\\apps\\Python37\\lib\\site-packages\\win32', 'C:\\OSGEO4~1\\apps\\Python37\\lib\\site-packages\\win32\\lib', 'C:\\OSGEO4~1\\apps\\Python37\\lib\\site-packages\\Pythonwin', 'C:/Users/Olivier/AppData/Roaming/QGIS/QGIS3\\profiles\\reallyempty/python']
```
