### ISSUE TITLE
Crash on QGIS start

### ISSUE THREAD

**Issue by Nimn** [qgis/QGIS#37867]
**QGIS and OS versions**
* QGIS 3.10.7-A Coruña 'A Coruña' (7b4ca4c8d0)
* Debian buster. QGIS debian-ltr repository.

**Description**
QGIS crash on start. I have tried with a clean profile but no change.
I have not used QGIS since a couple of month so I cannot say if this is due to a new QGIS package or one of the library update.
The same crash has been observed on another computer with the same OS/repository.

**Backtrace**
```
QGIS died on signal 11[New LWP 17890]
[New LWP 17891]
[New LWP 17892]
[New LWP 17893]
[New LWP 17897]
[New LWP 17898]
[New LWP 17904]
[New LWP 17905]
[New LWP 17906]
[New LWP 17907]
[New LWP 17908]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007fbe921ff5f0 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
[Current thread is 1 (Thread 0x7fbe85ebde40 (LWP 17886))]
#0  0x00007fbe921ff5f0 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#1  0x00007fbe921d0db5 in QDockWidget::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#2  0x00007fbe920bc4c1 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#3  0x00007fbe920c3970 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#4  0x00007fbe95b544fb in QgsApplication::notify(QObject*, QEvent*) () at /usr/lib/libqgis_core.so.3.10.7
#5  0x00007fbe8ef7f489 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007fbe920f6336 in QWidget::ensurePolished() const () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007fbe920f9f66 in QWidget::setVisible(bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#8  0x00007fbe921cffca in QDockWidgetLayout::setWidgetForRole(QDockWidgetLayout::Role, QWidget*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#9  0x00007fbe98442c4f in  () at /usr/lib/libqgis_gui.so.3.10.7
#10 0x00007fbe9843e001 in QgsBrowserDockWidget::QgsBrowserDockWidget(QString const&, QgsBrowserGuiModel*, QWidget*) () at /usr/lib/libqgis_gui.so.3.10.7
#11 0x00007fbe98cbf375 in QgisApp::QgisApp(QSplashScreen*, bool, bool, QString const&, QString const&, QWidget*, QFlags<Qt::WindowType>) () at /usr/lib/libqgis_app.so.3.10.7
#12 0x0000557fa38015c4 in  ()
#13 0x00007fbe8e85709b in __libc_start_main (main=0x557fa37ff600, argc=1, argv=0x7ffe9072eca8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffe9072ec98) at ../csu/libc-start.c:308
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, -8305952179056160301, 94006692301104, 140731321871520, 0, 0, -2758116553678794285, -2794186199208570413}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x7ffe9072ecb8, 0x7fbe995e9190}, data = {prev = 0x0, cleanup = 0x0, canceltype = -1871516488}}}
        not_first_call = <optimized out>
#14 0x0000557fa380495a in _start ()
[Inferior 1 (process 17886) detached]
gdb returned 0
```

**Comment by enzedrailmaps** [comment]
I currently have a startup crash on 3.10.8 on buster reported as issue 37892. Since my output is different from yours, it looks like a different but possibly related issue. The output I posted was obtained from starting Qgis in a terminal window.

Both my computers that crash 3.10.8 are running Debian 10 with KDE. A third computer running Debian 10 with LXQt is working successfully. This computer is the most recent reinstallation of my systems. However a virtual machine running Debian 10 with LXQt is crashing.

Most of my computers do not output in the terminal window when Qgis is started at the command line and again I am unsure how to get output for comparison, for example similar to yours, or from the system that starts successfully.

**Comment by alexmodesto73** [comment]
Debian Buster / QGIS 3.14.1-Pi 'Pi' (de08d6b71d)

Same problem 


```
$ qgis
QGIS died on signal 11[New LWP 24149]
[New LWP 24150]
[New LWP 24151]
[New LWP 24153]
[New LWP 24154]
[New LWP 24159]
[New LWP 24160]
[New LWP 24161]
[New LWP 24162]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007f000a11d3c0 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
[Current thread is 1 (Thread 0x7f000132ae80 (LWP 24146))]
#0  0x00007f000a11d3c0 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#1  0x00007efffc0ad937 in ?? () from /usr/lib/x86_64-linux-gnu/qt5/plugins/iconengines/libqsvgicon.so
No symbol table info available.
#2  0x00007efffc0ab899 in ?? () from /usr/lib/x86_64-linux-gnu/qt5/plugins/iconengines/libqsvgicon.so
No symbol table info available.
#3  0x00007f000ab6b638 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
No symbol table info available.
#4  0x00007f000ab70469 in QIcon::addFile(QString const&, QSize const&, QIcon::Mode, QIcon::State) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
No symbol table info available.
#5  0x00007f000ab70613 in QIcon::QIcon(QString const&) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
No symbol table info available.
#6  0x00007f001141686b in QgsApplication::getThemeIcon(QString const&) () from /usr/lib/libqgis_core.so.3.14.1
No symbol table info available.
#7  0x00007f00144e0419 in QgsLayoutGuiUtils::registerGuiForKnownItemTypes(QgsMapCanvas*) () from /usr/lib/libqgis_gui.so.3.14.1
No symbol table info available.
#8  0x00007f001506272f in QgisApp::initLayouts() () from /usr/lib/libqgis_app.so.3.14.1
No symbol table info available.
#9  0x00007f0015047297 in QgisApp::functionProfile(void (QgisApp::*)(), QgisApp*, QString const&) () from /usr/lib/libqgis_app.so.3.14.1
No symbol table info available.
#10 0x00007f001509f1ce in QgisApp::QgisApp(QSplashScreen*, bool, bool, QString const&, QString const&, QWidget*, QFlags<Qt::WindowType>) () from /usr/lib/libqgis_app.so.3.14.1
No symbol table info available.
#11 0x0000556d73dbd4e8 in ?? ()
No symbol table info available.
#12 0x00007f0009aa909b in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#13 0x0000556d73dc07da in _start ()
No symbol table info available.
[Inferior 1 (process 24146) detached]
gdb returned 0
Abandon

```

**Comment by Nimn** [comment]
Same problem on new version: QGIS 3.10.8-A Coruña 'A Coruña' (d09a4f2388)

**Comment by Nimn** [comment]
Ok with the last version.

**Comment by enzedrailmaps** [comment]
There has been an update to the current Buster packages for qgis.org/debian and qgis.org/debian-ltr posted on the Qgis website since August 8. When I tested these versions on my computers, everything now works.
