### ISSUE TITLE
Plugin doesn't load when opening QGIS

### ISSUE THREAD

**Issue by Ninie14** [qgis/QGIS#37950]
Hi,

I get the following error message when opening QGIS. While this doesn't prevent QGIS to open, I need to use the plugin "rastertool", which doesn't work. Can you please help me. I don't know anything about Python.

Couldn't load plugin 'rastertool' due to an error when calling its classFactory() method 

AttributeError: 'tuple' object has no attribute 'read' 
Traceback (most recent call last):
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/virginiebrunetaud/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/rastertool/__init__.py", line 35, in classFactory
    from .RasterTool import RasterTool
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/virginiebrunetaud/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/rastertool/RasterTool.py", line 45, in 
    import processing, os, subprocess, time
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/plugins/processing/__init__.py", line 24, in 
    from processing.tools.dataobjects import *          # NOQA
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/plugins/processing/tools/dataobjects.py", line 42, in 
    from processing.core.ProcessingConfig import ProcessingConfig
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/plugins/processing/core/ProcessingConfig.py", line 34, in 
    from processing.tools.system import defaultOutputFolder
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/plugins/processing/tools/system.py", line 27, in 
    import uuid
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/uuid.py", line 57, in 
    _AIX     = platform.system() == 'AIX'
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/platform.py", line 891, in system
    return uname().system
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/platform.py", line 857, in uname
    processor = _syscmd_uname('-p', '')
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/platform.py", line 613, in _syscmd_uname
    output = subprocess.check_output(('uname', option),
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/run/__init__.py", line 145, in __new__
    process = cls.create_process(command, stdin, cwd=cwd, env=env, shell=shell)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/run/__init__.py", line 121, in create_process
    shlex.split(command),
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shlex.py", line 311, in split
    return list(lex)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shlex.py", line 300, in __next__
    token = self.get_token()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shlex.py", line 109, in get_token
    raw = self.read_token()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shlex.py", line 140, in read_token
    nextchar = self.instream.read(1)
AttributeError: 'tuple' object has no attribute 'read'

Python version: 3.8.2 (v3.8.2:7b3ab5921f, Feb 24 2020, 17:52:18) [Clang 6.0 (clang-600.0.57)] 
QGIS version: 3.10.6-A Coruña A Coruña, exported 
Using macOS Catalina version 10.15.5

**Comment by gioman** [comment]
@Ninie14 it is a 3rd party plugin, you must report the issue to the plugin author.
