### ISSUE TITLE
Crash when you remove the search/filter string in the WMS dialog using the 'clean' button in the input, after switching WMS service

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#38071]
I get a crash (both in current 3.14 and master) when I switch between 2 WMS services, and used the 'filter' input (new since 3.14).

To reproduce:

- Create 2 WMS services, for example the public dutch ones:
KNMI: http://geoservices.knmi.nl/cgi-bin/RADNL_OPER_R___25PCPRR_L3.cgi
INSPIRE: https://geodata.nationaalgeoregister.nl/inspire/cp/ows

- Now connect to KNMI (Our Meteo institute), and search for 'prec' (precipitation. See that the filter is working fine).
- Do NOT load a layer, but just switch to the INSPIRE service, and connect to it (so it show it's layer list)
- And NOW use the little 'clean/delete' button in the filter input to remove the still there 'prec' string (see screenie).
- immediate crash (see below for stracktrace)

![Screenshot-20200731171510-1111x366](https://user-images.githubusercontent.com/731673/89049424-86775280-d351-11ea-8fbc-ca2411c22a85.png)

My guess is that the input is still pointing to the old 'model' of the earlier service?

QGIS version | 3.15.0-Master | QGIS code revision | e19f27d289
-- | -- | -- | --
Compiled against Qt | 5.14.2 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 3.1.2 | Running against GDAL/OGR | 3.1.2
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.32.3 | Running against SQLite | 3.32.3
PostgreSQL Client Version | 12.3 (Debian 12.3-1+b1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 7.1.0 | Running against PROJ | Rel. 7.1.0, August 1st, 2020
OS Version | Debian GNU/Linux bullseye/sid | This copy of QGIS writes debugging output.

```
<pre>QGIS died on signal 11[New LWP 178657]
[New LWP 178662]
[New LWP 178663]
[New LWP 178665]
[New LWP 178683]
[New LWP 178684]
[New LWP 178685]
[New LWP 178686]
[New LWP 178687]
[New LWP 178688]
[New LWP 178695]
[New LWP 178808]
[New LWP 180888]
[Thread debugging using libthread_db enabled]
Using host libthread_db library &quot;/lib/x86_64-linux-gnu/libthread_db.so.1&quot;.
0x00007fe7137541c7 in __GI___wait4 (pid=180908, stat_loc=0x7ffc20cbef54, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
27	../sysdeps/unix/sysv/linux/wait4.c: No such file or directory.
[Current thread is 1 (Thread 0x7fe701429f80 (LWP 178644))]
#0  0x00007fe7137541c7 in __GI___wait4 (pid=180908, stat_loc=0x7ffc20cbef54, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
#1  0x000055c503f7a266 in qgisCrash(int) (signal=11) at ../src/app/main.cpp:349
        status = 21957
        pidstr = &quot;--pid=178644\000\177\000\000\000\000\000\000\000\000\000\000\377\377\377\377\377\377\377\377&quot;
        gdbpid = 180908
        exename = &quot;/home/richard/bin/qgis_/3.14/debug/bin/qgis\000\347\177&quot;, &apos;\000&apos; &lt;repeats 70 times&gt;, &quot;\374\177\000\000\000\000\000\000\000\000\000\000P\300\003\006\305U\000\000\000\330U\365\212̳\250\b&quot;, &apos;\000&apos; &lt;repeats 15 times&gt;, &quot;p\237Y\a\305U\000\000\300\356\313 \374\177\000\000\320\311)\016\305U\000\000\000\330U\365\212̳\250\060\356\313 \374\177\000\000*\000\000\000\000\000\000\000&quot;...
        len = 43
#2  0x00007fe7136c4d30 in &lt;signal handler called&gt; () at /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007fe716b10406 in QAbstractItemView::model() const () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#4  0x00007fe716b918d1 in QTreeWidgetItem::treeModel(QTreeWidget*) const () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#5  0x00007fe716b91f4b in QTreeWidgetItem::setExpanded(bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x00007fe6cee648b0 in QgsWMSSourceSelect::filterLayers(QString const&amp;) (this=0x55c50e2bc1e0, searchText=...) at ../src/providers/wms/qgswmssourceselect.cpp:1144
        item = 0x55c50f468c80
        __for_range = @0x7ffc20cbf6e0: {&lt;QListSpecialMethods&lt;QTreeWidgetItem*&gt;&gt; = {&lt;No data fields&gt;}, {p = {static shared_null = {ref = {atomic = {_q_value = {&lt;std::__atomic_base&lt;int&gt;&gt; = {static _S_alignment = 4, _M_i = -1}, &lt;No data fields&gt;}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x55c50ead18c0}, d = 0x55c50ead18c0}}
        __for_begin = {i = 0x55c50ead18d0}
        __for_end = {i = 0x55c50ead18e8}
        setChildrenVisible = {&lt;std::_Maybe_unary_or_binary_function&lt;void, QTreeWidgetItem*, bool&gt;&gt; = {&lt;std::binary_function&lt;QTreeWidgetItem*, bool, void&gt;&gt; = {&lt;No data fields&gt;}, &lt;No data fields&gt;}, &lt;std::_Function_base&gt; = {static _M_max_size = 16, static _M_max_align = 8, _M_functor = {_M_unused = {_M_object = 0x7ffc20cbf6f0, _M_const_object = 0x7ffc20cbf6f0, _M_function_pointer = 0x7ffc20cbf6f0, _M_member_pointer = (void (std::_Undefined_class::*)(class std::_Undefined_class * const)) 0x7ffc20cbf6f0, this adjustment 140630527254678}, _M_pod_data = &quot;\360\366\313 \374\177\000\000\226 \237\030\347\177\000&quot;}, _M_manager = 0x7fe6cee659a5 &lt;std::_Function_base::_Base_manager&lt;QgsWMSSourceSelect::filterLayers(const QString&amp;)::&lt;lambda(QTreeWidgetItem*, bool)&gt; &gt;::_M_manager(std::_Any_data &amp;, const std::_Any_data &amp;, std::_Manager_operation)&gt;}, _M_invoker = 0x7fe6cee65947 &lt;std::_Function_handler&lt;void(QTreeWidgetItem*, bool), QgsWMSSourceSelect::filterLayers(const QString&amp;)::&lt;lambda(QTreeWidgetItem*, bool)&gt; &gt;::_M_invoke(const std::_Any_data &amp;, QTreeWidgetItem *&amp;&amp;, bool &amp;&amp;)&gt;}
#7  0x00007fe6cee71627 in QtPrivate::FunctorCall&lt;QtPrivate::IndexesList&lt;0&gt;, QtPrivate::List&lt;QString const&amp;&gt;, void, void (QgsWMSSourceSelect::*)(QString const&amp;)&gt;::call(void (QgsWMSSourceSelect::*)(QString const&amp;), QgsWMSSourceSelect*, void**) (f=(void (QgsWMSSourceSelect::*)(class QgsWMSSourceSelect * const, const class QString &amp;)) 0x7fe6cee6474a &lt;QgsWMSSourceSelect::filterLayers(QString const&amp;)&gt;, o=0x55c50e2bc1e0, arg=0x7ffc20cbf930) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:152
#8  0x00007fe6cee70b69 in QtPrivate::FunctionPointer&lt;void (QgsWMSSourceSelect::*)(QString const&amp;)&gt;::call&lt;QtPrivate::List&lt;QString const&amp;&gt;, void&gt;(void (QgsWMSSourceSelect::*)(QString const&amp;), QgsWMSSourceSelect*, void**) (f=(void (QgsWMSSourceSelect::*)(class QgsWMSSourceSelect * const, const class QString &amp;)) 0x7fe6cee6474a &lt;QgsWMSSourceSelect::filterLayers(QString const&amp;)&gt;, o=0x55c50e2bc1e0, arg=0x7ffc20cbf930) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:185
#9  0x00007fe6cee6f834 in QtPrivate::QSlotObject&lt;void (QgsWMSSourceSelect::*)(QString const&amp;), QtPrivate::List&lt;QString const&amp;&gt;, void&gt;::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0x55c50e6b1280, r=0x55c50e2bc1e0, a=0x7ffc20cbf930, ret=0x0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:418
#10 0x00007fe715e4a6fe in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007fe7169f1072 in QLineEdit::textChanged(QString const&amp;) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007fe7169f780b in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007fe715e4a730 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007fe7169f8365 in QWidgetLineControl::textChanged(QString const&amp;) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007fe7169fbbbd in QWidgetLineControl::finishChange(int, bool, bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007fe7169fbeeb in QWidgetLineControl::internalSetText(QString const&amp;, int, bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007fe7169eee57 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007fe717c4eadd in QgsFilterLineEdit::clearValue() (this=0x55c50e2eafd0) at ../src/gui/qgsfilterlineedit.cpp:112
#19 0x00007fe717c4f9dc in QtPrivate::FunctorCall&lt;QtPrivate::IndexesList&lt;&gt;, QtPrivate::List&lt;&gt;, void, void (QgsFilterLineEdit::*)()&gt;::call(void (QgsFilterLineEdit::*)(), QgsFilterLineEdit*, void**) (f=&amp;virtual table offset 416, o=0x55c50e2eafd0, arg=0x7ffc20cbfdc0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:152
#20 0x00007fe717c4f8db in QtPrivate::FunctionPointer&lt;void (QgsFilterLineEdit::*)()&gt;::call&lt;QtPrivate::List&lt;&gt;, void&gt;(void (QgsFilterLineEdit::*)(), QgsFilterLineEdit*, void**) (f=&amp;virtual table offset 416, o=0x55c50e2eafd0, arg=0x7ffc20cbfdc0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:185
#21 0x00007fe717c4f800 in QtPrivate::QSlotObject&lt;void (QgsFilterLineEdit::*)(), QtPrivate::List&lt;&gt;, void&gt;::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0x7fe6e8010080, r=0x55c50e2eafd0, a=0x7ffc20cbfdc0, ret=0x0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:418
#22 0x00007fe715e4a6fe in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x00007fe7168a4ad2 in QAction::triggered(bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007fe7168a70f8 in QAction::activate(QAction::ActionEvent) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#25 0x00007fe7169a1b8c in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#26 0x00007fe7169a1db5 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#27 0x00007fe716a9375a in QToolButton::mouseReleaseEvent(QMouseEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#28 0x00007fe7168ed5ce in QWidget::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#29 0x00007fe716a93804 in QToolButton::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#30 0x00007fe7168aaccf in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#31 0x00007fe7168b4063 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#32 0x00007fe71453eb35 in QgsApplication::notify(QObject*, QEvent*) (this=0x7ffc20cc29e0, receiver=0x55c50eecd330, event=0x7ffc20cc0430) at ../src/core/qgsapplication.cpp:439
        done = true
        __FUNCTION__ = &quot;notify&quot;
#33 0x00007fe715e15d02 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#34 0x00007fe7168b3143 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer&lt;QWidget&gt;&amp;, bool, bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#35 0x00007fe716908609 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#36 0x00007fe71690b4d4 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#37 0x00007fe7168aaccf in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#38 0x00007fe7168b3e10 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#39 0x00007fe71453eb35 in QgsApplication::notify(QObject*, QEvent*) (this=0x7ffc20cc29e0, receiver=0x55c50ed51310, event=0x7ffc20cc0980) at ../src/core/qgsapplication.cpp:439
        done = true
        __FUNCTION__ = &quot;notify&quot;
#40 0x00007fe715e15d02 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#41 0x00007fe7161dd213 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#42 0x00007fe7161de8a5 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#43 0x00007fe7161b760b in QWindowSystemInterface::sendWindowSystemEvents(QFlags&lt;QEventLoop::ProcessEventsFlag&gt;) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#44 0x00007fe6ef7f2d7a in  () at /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#45 0x00007fe70bf5c5fd in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#46 0x00007fe70bf5c880 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#47 0x00007fe70bf5c90f in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#48 0x00007fe715e6c8ee in QEventDispatcherGlib::processEvents(QFlags&lt;QEventLoop::ProcessEventsFlag&gt;) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#49 0x00007fe715e1489b in QEventLoop::exec(QFlags&lt;QEventLoop::ProcessEventsFlag&gt;) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#50 0x00007fe716aadecd in QDialog::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#51 0x00007fe718872cd6 in QgisApp::dataSourceManager(QString const&amp;) (this=0x55c506ca2ff0, pageName=...) at ../src/app/qgisapp.cpp:2370
#52 0x00007fe718875566 in QgisApp::&lt;lambda()&gt;::operator()(void) const (__closure=0x55c5073bf230) at ../src/app/qgisapp.cpp:2683
        this = 0x55c506ca2ff0
        menuAllEdits = 0x7fe718875566 &lt;QgisApp::&lt;lambda()&gt;::operator()(void) const+54&gt;
        copyShortcut = 0x7ffc20cc1030
        cutShortcut = 0x55c506c927a0
        pasteShortcut = 0x55c5073bf220
        selectAllShortcut = 0x55c506c8a090
#53 0x00007fe71890593f in QtPrivate::FunctorCall&lt;QtPrivate::IndexesList&lt;&gt;, QtPrivate::List&lt;&gt;, void, QgisApp::createActions()::&lt;lambda()&gt; &gt;::call(QgisApp::&lt;lambda()&gt; &amp;, void **) (f=..., arg=0x7ffc20cc11e0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:146
#54 0x00007fe71890391f in QtPrivate::Functor&lt;QgisApp::createActions()::&lt;lambda()&gt;, 0&gt;::call&lt;QtPrivate::List&lt;&gt;, void&gt;(QgisApp::&lt;lambda()&gt; &amp;, void *, void **) (f=..., arg=0x7ffc20cc11e0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:256
#55 0x00007fe718900231 in QtPrivate::QFunctorSlotObject&lt;QgisApp::createActions()::&lt;lambda()&gt;, 0, QtPrivate::List&lt;&gt;, void&gt;::impl(int, QtPrivate::QSlotObjectBase *, QObject *, void **, bool *) (which=1, this_=0x55c5073bf220, r=0x55c506ca2ff0, a=0x7ffc20cc11e0, ret=0x0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:443
#56 0x00007fe715e4a6fe in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#57 0x00007fe7168a4ad2 in QAction::triggered(bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#58 0x00007fe7168a70f8 in QAction::activate(QAction::ActionEvent) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#59 0x00007fe7169a1b8c in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#60 0x00007fe7169a1db5 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#61 0x00007fe716a9375a in QToolButton::mouseReleaseEvent(QMouseEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#62 0x00007fe7168ed5ce in QWidget::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#63 0x00007fe716a93804 in QToolButton::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#64 0x00007fe7168aaccf in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#65 0x00007fe7168b4063 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#66 0x00007fe71453eb35 in QgsApplication::notify(QObject*, QEvent*) (this=0x7ffc20cc29e0, receiver=0x55c507411e00, event=0x7ffc20cc1850) at ../src/core/qgsapplication.cpp:439
        done = true
        __FUNCTION__ = &quot;notify&quot;
#67 0x00007fe715e15d02 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#68 0x00007fe7168b3143 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer&lt;QWidget&gt;&amp;, bool, bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#69 0x00007fe716908609 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#70 0x00007fe71690b4d4 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#71 0x00007fe7168aaccf in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#72 0x00007fe7168b3e10 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#73 0x00007fe71453eb35 in QgsApplication::notify(QObject*, QEvent*) (this=0x7ffc20cc29e0, receiver=0x55c50695b580, event=0x7ffc20cc1da0) at ../src/core/qgsapplication.cpp:439
        done = true
        __FUNCTION__ = &quot;notify&quot;
#74 0x00007fe715e15d02 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#75 0x00007fe7161dd213 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#76 0x00007fe7161de8a5 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#77 0x00007fe7161b760b in QWindowSystemInterface::sendWindowSystemEvents(QFlags&lt;QEventLoop::ProcessEventsFlag&gt;) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#78 0x00007fe6ef7f2d7a in  () at /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#79 0x00007fe70bf5c5fd in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#80 0x00007fe70bf5c880 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#81 0x00007fe70bf5c90f in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#82 0x00007fe715e6c8ee in QEventDispatcherGlib::processEvents(QFlags&lt;QEventLoop::ProcessEventsFlag&gt;) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#83 0x00007fe715e1489b in QEventLoop::exec(QFlags&lt;QEventLoop::ProcessEventsFlag&gt;) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#84 0x00007fe715e1c672 in QCoreApplication::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#85 0x000055c503f81a4f in main(int, char**) (argc=3, argv=0x7ffc20cc3cf8) at ../src/app/main.cpp:1618
        preApplicationLogMessages = {&lt;QList&lt;QString&gt;&gt; = {&lt;QListSpecialMethods&lt;QString&gt;&gt; = {&lt;No data fields&gt;}, {p = {static shared_null = {ref = {atomic = {_q_value = {&lt;std::__atomic_base&lt;int&gt;&gt; = {static _S_alignment = 4, _M_i = -1}, &lt;No data fields&gt;}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x55c505ddb090}, d = 0x55c505ddb090}}, &lt;No data fields&gt;}
        __FUNCTION__ = &quot;main&quot;
        mySnapshotFileName = {static null = {&lt;No data fields&gt;}, d = 0x7fe715efa860 &lt;QArrayData::shared_null&gt;}
        configLocalStorageLocation = {static null = {&lt;No data fields&gt;}, d = 0x55c505fa73f0}
        profileName = {static null = {&lt;No data fields&gt;}, d = 0x55c505fa81e0}
        mySnapshotWidth = 800
        mySnapshotHeight = 600
        myHideSplash = false
        settingsMigrationForce = false
        mySkipVersionCheck = false
        hideBrowser = false
        myRestoreDefaultWindowState = false
        myRestorePlugins = true
        myCustomization = true
        dxfOutputFile = {static null = {&lt;No data fields&gt;}, d = 0x7fe715efa860 &lt;QArrayData::shared_null&gt;}
        dxfSymbologyMode = QgsDxfExport::SymbolLayerSymbology
        dxfScale = 50000
        dxfEncoding = {static null = {&lt;No data fields&gt;}, d = 0x55c503f8cb00 &lt;main::{lambda()#2}::operator()() const::qstring_literal&gt;}
        dxfMapTheme = {static null = {&lt;No data fields&gt;}, d = 0x7fe715efa860 &lt;QArrayData::shared_null&gt;}
        dxfExtent = {mXmin = 0, mYmin = 0, mXmax = 0, mYmax = 0}
        takeScreenShots = false
        screenShotsPath = {static null = {&lt;No data fields&gt;}, d = 0x7fe715efa860 &lt;QArrayData::shared_null&gt;}
        screenShotsCategories = 0
        myInitialExtent = {static null = {&lt;No data fields&gt;}, d = 0x7fe715efa860 &lt;QArrayData::shared_null&gt;}
        translationCode = {static null = {&lt;No data fields&gt;}, d = 0x55c505faf810}
        authdbdirectory = {static null = {&lt;No data fields&gt;}, d = 0x7fe715efa860 &lt;QArrayData::shared_null&gt;}
        pythonfile = {static null = {&lt;No data fields&gt;}, d = 0x7fe715efa860 &lt;QArrayData::shared_null&gt;}
        customizationfile = {static null = {&lt;No data fields&gt;}, d = 0x55c506694630}
        globalsettingsfile = {static null = {&lt;No data fields&gt;}, d = 0x55c505f9d890}
        openClProgramFolder = {static null = {&lt;No data fields&gt;}, d = 0x7fe715efa860 &lt;QArrayData::shared_null&gt;}
        args = {&lt;QList&lt;QString&gt;&gt; = {&lt;QListSpecialMethods&lt;QString&gt;&gt; = {&lt;No data fields&gt;}, {p = {static shared_null = {ref = {atomic = {_q_value = {&lt;std::__atomic_base&lt;int&gt;&gt; = {static _S_alignment = 4, _M_i = -1}, &lt;No data fields&gt;}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x55c505f9d9a0}, d = 0x55c505f9d9a0}}, &lt;No data fields&gt;}
        myUseGuiFlag = true
        rootProfileFolder = {static null = {&lt;No data fields&gt;}, d = 0x55c505f9df10}
        manager = {&lt;QObject&gt; = {&lt;No data fields&gt;}, static staticMetaObject = {d = {superdata = {direct = 0x7fe716095c40 &lt;QObject::staticMetaObject&gt;}, stringdata = 0x7fe714e811a0 &lt;qt_meta_stringdata_QgsUserProfileManager&gt;, data = 0x7fe714e81220 &lt;qt_meta_data_QgsUserProfileManager&gt;, static_metacall = 0x7fe71400e39c &lt;QgsUserProfileManager::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)&gt;, relatedMetaObjects = 0x0, extradata = 0x0}}, mWatchProfiles = false, mWatcher = std::unique_ptr&lt;class QFileSystemWatcher&gt; = {get() = 0x0}, mRootProfilePath = {static null = {&lt;No data fields&gt;}, d = 0x55c505f9df10}, mUserProfile = std::unique_ptr&lt;class QgsUserProfile&gt; = {get() = 0x0}, mSettings = std::unique_ptr&lt;class QSettings&gt; = {get() = 0x55c505fa53b0}}
        profile = 0x55c505fa6310
        profileFolder = {static null = {&lt;No data fields&gt;}, d = 0x55c505dbb2c0}
        myApp = {&lt;QApplication&gt; = {&lt;No data fields&gt;}, static staticMetaObject = {d = {superdata = {direct = 0x7fe716dab5c0 &lt;QApplication::staticMetaObject&gt;}, stringdata = 0x7fe714e6e7c0 &lt;qt_meta_stringdata_QgsApplication&gt;, data = 0x7fe714e6e9c0 &lt;qt_meta_data_QgsApplication&gt;, static_metacall = 0x7fe713ff51da &lt;QgsApplication::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)&gt;, relatedMetaObjects = 0x0, extradata = 0x0}}, static QGIS_ORGANIZATION_NAME = 0x7fe714fa9972 &quot;QGIS&quot;, static QGIS_ORGANIZATION_DOMAIN = 0x7fe714fa9977 &quot;qgis.org&quot;, static QGIS_APPLICATION_NAME = 0x7fe714fa9980 &quot;QGIS3&quot;, static mFileOpenEventReceiver31400 = 0x55c506ca2ff0, static mInitialized31400 = true, static mRunningFromBuildDir31400 = false, static sMaxThreads31400 = -1, mIconCache = {d = 0x55c5062ae8f0}, mCursorCache = {d = 0x55c50729e2b0}, mQgisTranslator = 0x55c50617cc80, mQtTranslator = 0x55c5061a9aa0, mDataItemProviderRegistry = 0x55c5068f21f0, mAuthManager = 0x55c50690e770, mApplicationMembers = 0x55c506305940, static sApplicationMembers = 0x0, static sAuthManager = 0x0}
        settings = {&lt;QObject&gt; = {&lt;No data fields&gt;}, static staticMetaObject = {d = {superdata = {direct = 0x7fe716095c40 &lt;QObject::staticMetaObject&gt;}, stringdata = 0x7fe714e7cfe0 &lt;qt_meta_stringdata_QgsSettings&gt;, data = 0x7fe714e7d020 &lt;qt_meta_data_QgsSettings&gt;, static_metacall = 0x7fe71400a4d0 &lt;QgsSettings::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)&gt;, relatedMetaObjects = 0x0, extradata = 0x0}}, mUserSettings = 0x55c506199fa0, mGlobalSettings = 0x55c5061c7530, mUsingGlobalArray = false}
        libPaths = {&lt;QList&lt;QString&gt;&gt; = {&lt;QListSpecialMethods&lt;QString&gt;&gt; = {&lt;No data fields&gt;}, {p = {static shared_null = {ref = {atomic = {_q_value = {&lt;std::__atomic_base&lt;int&gt;&gt; = {static _S_alignment = 4, _M_i = -1}, &lt;No data fields&gt;}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x55c5062950b0}, d = 0x55c5062950b0}}, &lt;No data fields&gt;}
        relLibPath = {static null = {&lt;No data fields&gt;}, d = 0x55c5061ca920}
        customizationsettings = 0x55c5063e1c30
        systemEnvVars = {d = 0x55c5061728b0}
        useCustomVars = false
        desiredStyle = {static null = {&lt;No data fields&gt;}, d = 0x55c5061cd090}
        theme = {static null = {&lt;No data fields&gt;}, d = 0x55c50665f620}
        activeStyleName = {static null = {&lt;No data fields&gt;}, d = 0x55c506bf1820}
        mySplashPath = {static null = {&lt;No data fields&gt;}, d = 0x7fe714faaae0 &lt;QgsApplication::splashPath()::{lambda()#1}::operator()() const::qstring_literal&gt;}
        myPixmap = &lt;incomplete type&gt;
        w = 600
        h = 300
        mypSplash = 0x55c5061a44b0
        qgis = 0x55c506ca2ff0
        sigwatch = {&lt;QObject&gt; = {&lt;No data fields&gt;}, static staticMetaObject = {d = {superdata = {direct = 0x7fe716095c40 &lt;QObject::staticMetaObject&gt;}, stringdata = 0x55c503fce3c0 &lt;qt_meta_stringdata_UnixSignalWatcher&gt;, data = 0x55c503fce480 &lt;qt_meta_data_UnixSignalWatcher&gt;, static_metacall = 0x55c503f8891a &lt;UnixSignalWatcher::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)&gt;, relatedMetaObjects = 0x0, extradata = 0x0}}, d_ptr = 0x7fe6e8005830}
        retval = 66904320
[Inferior 1 (process 178644) detached]
gdb returned 0
</pre>
```

**Comment by gioman** [comment]
Confirmed here too.
