### ISSUE TITLE
Processing: python error on opening tool

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#38613]
QGIS 3.10 on Ubuntu 20.04

Add a delimited text layer (a CSV) in my case

With this layer selected in  the layers panel open the gdal/ogr based tool to import layers in PostgreSQL/PostGIS

```
Traceback (most recent call last):
  File "/usr/share/qgis/python/plugins/processing/gui/ProcessingToolbox.py", line 259, in executeAlgorithm
    dlg = alg.createCustomParametersWidget(self)
  File "/usr/share/qgis/python/plugins/processing/algs/gdal/GdalAlgorithm.py", line 64, in createCustomParametersWidget
    return GdalAlgorithmDialog(self, parent=parent)
  File "/usr/share/qgis/python/plugins/processing/algs/gdal/GdalAlgorithmDialog.py", line 56, in __init__
    self.mainWidget().parametersHaveChanged()
  File "/usr/share/qgis/python/plugins/processing/algs/gdal/GdalAlgorithmDialog.py", line 139, in parametersHaveChanged
    commands = self.alg.getConsoleCommands(parameters, context, feedback, executing=False)
  File "/usr/share/qgis/python/plugins/processing/algs/gdal/ogr2ogrtopostgislist.py", line 281, in getConsoleCommands
    table = layername.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

After dismissing the error a similar one 
```

Traceback (most recent call last):
  File "/usr/share/qgis/python/plugins/processing/algs/gdal/GdalAlgorithmDialog.py", line 139, in parametersHaveChanged
    commands = self.alg.getConsoleCommands(parameters, context, feedback, executing=False)
  File "/usr/share/qgis/python/plugins/processing/algs/gdal/ogr2ogrtopostgislist.py", line 281, in getConsoleCommands
    table = layername.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

will pop up when opening other Processing tools, even native ones (like the one to import data in PostGIS).

**Comment by pblottiere** [comment]
Hi @gioman,

> open the gdal/ogr based tool to import layers in PostgreSQL/PostGIS

Are you talking about this one v?

![qs](https://user-images.githubusercontent.com/9266424/94450910-20bb1180-01ae-11eb-85d9-2c560c238756.png)

**Comment by gioman** [comment]
> Are you talking about this one v?

@pblottiere yes, but I can't replicate anymoe on the latest 3.10.
