### ISSUE TITLE
Processing Plugin Causing Crash on Startup

### ISSUE THREAD

**Issue by jgr007** [qgis/QGIS#38772]
When I start QGIS, I'm getting a crash error that seems to be associated with the Processing Plugin (it looks like) related to GRASS.  I'm using 3.14.16 installed via OSGeo4W.  I've tried on two different systems and I get the same issue.  I've completely removed the entire OSGeo4W directory and deleted everything in AppData\local and AppData\roaming and then re-installed using Express Desktop install.  My apologies if this is not the right place to post.  The following errors are from the QGIS logs:

Plugins Log

2020-09-15T10:54:17     WARNING    Failed to load C:/OSGEO4~2/apps/qgis/plugins/grassplugin7.dll (Reason: Cannot load library C:\OSGEO4~2\apps\qgis\plugins\grassplugin7.dll: The specified module could not be found.)
2020-09-15T10:54:17     WARNING    Failed to load C:/OSGEO4~2/apps/qgis/plugins/grassprovider7.dll (Reason: Cannot load library C:\OSGEO4~2\apps\qgis\plugins\grassprovider7.dll: The specified module could not be found.)
2020-09-15T10:54:17     WARNING    Failed to load C:/OSGEO4~2/apps/qgis/plugins/grassrasterprovider7.dll (Reason: Cannot load library C:\OSGEO4~2\apps\qgis\plugins\grassrasterprovider7.dll: The specified module could not be found.)
2020-09-15T10:54:17     INFO    Loaded DB Manager (package: db_manager)
2020-09-15T10:54:17     INFO    Loaded MetaSearch Catalog Client (package: MetaSearch)
2020-09-15T10:54:20     INFO    Loaded Processing (package: processing)

Python error Log

2020-09-15T10:54:17     WARNING    Traceback (most recent call last):
              File "C:/OSGEO4~2/apps/qgis/./python\qgis\utils.py", line 777, in _import
              new_path = os.environ['PATH']
              File "C:\OSGEO4~2\apps\Python37\lib\os.py", line 675, in __getitem__
              value = self._data[self.encodekey(key)]
              File "C:\OSGEO4~2\apps\Python37\lib\os.py", line 744, in encodekey
              return encode(key).upper()
             RecursionError: maximum recursion depth exceeded
             
			 
			 
When activating
An error has occurred while executing Python code: 

RecursionError: maximum recursion depth exceeded while calling a Python object 
Traceback (most recent call last):
  File "C:/OSGEO4~2/apps/qgis/./python\qgis\utils.py", line 777, in _import
    new_path = os.environ['PATH']
  File "C:\OSGEO4~2\apps\Python37\lib\os.py", line 675, in __getitem__
    value = self._data[self.encodekey(key)]
  File "C:\OSGEO4~2\apps\Python37\lib\os.py", line 744, in encodekey
    return encode(key).upper()
  File "C:\OSGEO4~2\apps\Python37\lib\os.py", line 738, in check_str
    if not isinstance(value, str):
RecursionError: maximum recursion depth exceeded while calling a Python object

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.14.16-Pi Pi, a235a149f0

**Comment by gioman** [comment]
Already fixed.
