### ISSUE TITLE
scipy.stats ImportError

### ISSUE THREAD

**Issue by AndreasRabe** [qgis/QGIS#38799]
**Describe the bug**

Can't import the scipy.stats module inside QGIS (e.g. via the QGIS Python Console). Inside the OSGeo4W console, the import works fine.

**How to Reproduce**

In the QGIS Python Console enter:

`>>>import scipy.stats`

Error traceback:

**Traceback (most recent call last):
  File "C:\QGIS\apps\Python37\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:/QGIS/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\janzandr\AppData\Roaming\Python\Python37\site-packages\scipy\stats\__init__.py", line 384, in <module>
    from .stats import *
  File "C:/QGIS/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\janzandr\AppData\Roaming\Python\Python37\site-packages\scipy\stats\stats.py", line 179, in <module>
    from scipy.spatial.distance import cdist
  File "C:/QGIS/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\janzandr\AppData\Roaming\Python\Python37\site-packages\scipy\spatial\__init__.py", line 102, in <module>
    from ._procrustes import procrustes
  File "C:/QGIS/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\janzandr\AppData\Roaming\Python\Python37\site-packages\scipy\spatial\_procrustes.py", line 11, in <module>
    from scipy.linalg import orthogonal_procrustes
  File "C:/QGIS/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\janzandr\AppData\Roaming\Python\Python37\site-packages\scipy\linalg\__init__.py", line 195, in <module>
    from .misc import *
  File "C:/QGIS/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\janzandr\AppData\Roaming\Python\Python37\site-packages\scipy\linalg\misc.py", line 5, in <module>
    from .blas import get_blas_funcs
  File "C:/QGIS/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\janzandr\AppData\Roaming\Python\Python37\site-packages\scipy\linalg\blas.py", line 215, in <module>
    from scipy.linalg import _fblas
  File "C:/QGIS/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.**

**QGIS and OS versions**

QGIS version
3.14.15-Pi
QGIS code revision
d5114d2cfa
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)

**Comment by Gustry** [comment]
There are already many tickets, which are all closed : https://github.com/qgis/QGIS/issues?q=is%3Aissue+scipy+is%3Aclosed
I might be already fixed, no?

**Comment by AndreasRabe** [comment]
Oh, sorry, may very well be the case!

I installed the latest QGIS today via the standalone installer: https://qgis.org/downloads/QGIS-OSGeo4W-3.14.15-1-Setup-x86_64.exe

Which QGIS version should I use for testing if the bug still exists?

**Comment by rduivenvoorde** [comment]
@AndreasRabe if I understand correctly, it had something to do with needed dll's which where not in the right (python?)PATH available. The fix for that created other issues, which were also fixed, but the upcoming Windows builds should be fine

See https://github.com/qgis/QGIS/pull/38420
and commits in https://github.com/qgis/QGIS/issues/38720

**Comment by AndreasRabe** [comment]
> the upcoming Windows builds should be fine

Good to know, thanks! Which QGIS version would that be? 3.14.17 or 3.16?

**Comment by mattfack** [comment]
> 
> 
> > the upcoming Windows builds should be fine
> 
> Good to know, thanks! Which QGIS version would that be? 3.14.17 or 3.16?

It should be 3.16.2

**Comment by Gustry** [comment]
Or a nightly build.

Let's close this issue, because it should be resolved.
