### ISSUE TITLE
I got this error when I'd try to install and load cityJSON plugin in QGIS 3.10 LTR

### ISSUE THREAD

**Issue by Navid61** [qgis/QGIS#38811]
Couldn't load plugin 'CityJSON-loader' due to an error when calling its classFactory() method 

ValueError: could not convert string to float: '6378137.0.' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/sigma/.local/share/QGIS/QGIS3/profiles/default/python/plugins/CityJSON-loader/__init__.py", line 35, in classFactory
    from .cityjson_loader import CityJsonLoader
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/sigma/.local/share/QGIS/QGIS3/profiles/default/python/plugins/CityJSON-loader/cityjson_loader.py", line 33, in 
    from .cjio import cityjson
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/sigma/.local/share/QGIS/QGIS3/profiles/default/python/plugins/CityJSON-loader/cjio/cityjson.py", line 15, in 
    import pyproj
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/local/lib/python3.7/dist-packages/pyproj/__init__.py", line 81, in 
    from pyproj.crs import CRS  # noqa: F401
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/local/lib/python3.7/dist-packages/pyproj/crs.py", line 57, in 
    from pyproj.geod import Geod
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/local/lib/python3.7/dist-packages/pyproj/geod.py", line 42, in 
    pj_ellps = get_ellps_map()
  File "pyproj/_list.pyx", line 39, in pyproj._list.get_ellps_map
ValueError: could not convert string to float: '6378137.0.'

Python version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0] 
QGIS version: 3.10.9-A Coruña A Coruña, bf47e9d3e1

**Comment by gioman** [comment]
@Navid61 you must report it to the plugin author/s.
