### ISSUE TITLE
Uncaught FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\macie\\AppData\\Roaming\\QGIS\\QGIS3\\profiles\\default\\processing\\scripts\\DlgFieldsCalculator.ui'


### ISSUE THREAD

**Issue by olszewskimac** [qgis/QGIS#39143]
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python/plugins\processing\script\ScriptAlgorithmProvider.py", line 121, in loadAlgorithms
    alg = ScriptUtils.loadAlgorithm(moduleName, filePath)
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python/plugins\processing\script\ScriptUtils.py", line 66, in loadAlgorithm
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\macie\AppData\Roaming\QGIS\QGIS3\profiles\default\processing\scripts\FieldsCalculatorDialog1.py", line 55, in <module>
    os.path.join(pluginPath, 'DlgFieldsCalculator.ui'))
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\PyQt\uic\__init__.py", line 36, in __loadUiType
    return __PyQtLoadUiType(*args, **kwargs)
  File "C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib\site-packages\PyQt5\uic\__init__.py", line 198, in loadUiType
    winfo = compiler.UICompiler().compileUi(uifile, code_string, from_imports, resource_suffix, import_from)
  File "C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib\site-packages\PyQt5\uic\Compiler\compiler.py", line 110, in compileUi
    w = self.parse(input_stream, resource_suffix)
  File "C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib\site-packages\PyQt5\uic\uiparser.py", line 1013, in parse
    document = parse(filename)
  File "C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib\xml\etree\ElementTree.py", line 1197, in parse
    tree.parse(source, parser)
  File "C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib\xml\etree\ElementTree.py", line 587, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\macie\\AppData\\Roaming\\QGIS\\QGIS3\\profiles\\default\\processing\\scripts\\DlgFieldsCalculator.ui'

```
processing 2.12.99, QGIS 3.14.15-Pi on Windows 10

**Comment by nyalldawson** [comment]
This is a local issue -- you have a script "FieldsCalculatorDialog1.py" which is importing a ui file which no longer exists. You'll need to remove that script or find a copy of the missing file from an older qgis version and distribute it alongside your script.
