### ISSUE TITLE
Problems with loading Plugins (processing and other plugins)

### ISSUE THREAD

**Issue by troyaqgis** [qgis/QGIS#39539]
I have the following python errors when starting the QGIS 3.14.16, Windows 10 Pro:
```
2020-10-21T09:21:57     CRITICAL    Traceback (most recent call last):
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\osgeo\osr.py", line 14, in swig_import_helper
              return importlib.import_module(mname)
              File "C:\OSGEO4~1\apps\Python37\lib\importlib\__init__.py", line 127, in import_module
              return _bootstrap._gcd_import(name[level:], package, level)
              File "", line 1006, in _gcd_import
              File "", line 983, in _find_and_load
              File "", line 967, in _find_and_load_unlocked
              File "", line 670, in _load_unlocked
              File "", line 583, in module_from_spec
              File "", line 1043, in create_module
              File "", line 219, in _call_with_frames_removed
             ImportError: DLL load failed: Nie można odnaleźć określonej procedury.
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              File "C:/Users/jadwi/AppData/Roaming/QGIS/QGIS3\profiles\JTRO/python/plugins\go2streetview\__init__.py", line 34, in classFactory
              from .go2streetview import go2streetview
              File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 792, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:/Users/jadwi/AppData/Roaming/QGIS/QGIS3\profiles\JTRO/python/plugins\go2streetview\go2streetview.py", line 27, in 
              from .snapshot import snapShot
              File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 792, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:/Users/jadwi/AppData/Roaming/QGIS/QGIS3\profiles\JTRO/python/plugins\go2streetview\snapshot.py", line 25, in 
              from osgeo import ogr
              File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 792, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\osgeo\ogr.py", line 260, in 
              import osgeo.osr
              File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 792, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\osgeo\osr.py", line 17, in 
              _osr = swig_import_helper()
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\osgeo\osr.py", line 16, in swig_import_helper
              return importlib.import_module('_osr')
              File "C:\OSGEO4~1\apps\Python37\lib\importlib\__init__.py", line 127, in import_module
              return _bootstrap._gcd_import(name[level:], package, level)
             ModuleNotFoundError: No module named '_osr'
             
         
2020-10-21T09:22:06     CRITICAL    Traceback (most recent call last):
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\osgeo\osr.py", line 14, in swig_import_helper
              return importlib.import_module(mname)
              File "C:\OSGEO4~1\apps\Python37\lib\importlib\__init__.py", line 127, in import_module
              return _bootstrap._gcd_import(name[level:], package, level)
              File "", line 1006, in _gcd_import
              File "", line 983, in _find_and_load
              File "", line 967, in _find_and_load_unlocked
              File "", line 670, in _load_unlocked
              File "", line 583, in module_from_spec
              File "", line 1043, in create_module
              File "", line 219, in _call_with_frames_removed
             ImportError: DLL load failed: Nie można odnaleźć określonej procedury.
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 312, in loadPlugin
              __import__(packageName)
              File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 792, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\__init__.py", line 35, in 
              from processing.tools.raster import * # NOQA
              File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 792, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\tools\raster.py", line 26, in 
              from osgeo import gdal
              File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 792, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\osgeo\gdal.py", line 1756, in 
              import osgeo.ogr
              File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 792, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\osgeo\ogr.py", line 260, in 
              import osgeo.osr
              File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 792, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\osgeo\osr.py", line 17, in 
              _osr = swig_import_helper()
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\osgeo\osr.py", line 16, in swig_import_helper
              return importlib.import_module('_osr')
              File "C:\OSGEO4~1\apps\Python37\lib\importlib\__init__.py", line 127, in import_module
              return _bootstrap._gcd_import(name[level:], package, level)
             ModuleNotFoundError: No module named '_osr'
                 

```
and messages:
```
2020-10-21T09:21:48     WARNING    Plugin BDOT10k_GML_SHP_Loader : This plugin is disabled because it previously crashed QGIS.
2020-10-21T09:21:57     WARNING    Python error : Couldn't load plugin 'go2streetview' due to an error when calling its classFactory() method See message log (Python Error) for more details.
2020-10-21T09:21:59     WARNING    Python error : Couldn't load plugin 'pobieracz_danych_gugik' due to an error when calling its classFactory() method See message log (Python Error) for more details.
2020-10-21T09:21:59     WARNING    Python error : Couldn't load plugin 'qgis2web' due to an error when calling its classFactory() method See message log (Python Error) for more details.
2020-10-21T09:22:06     WARNING    Python error : Couldn't load plugin 'processing' See message log (Python Error) for more details.
```

and sample Python warnings:
```
WARNING warning:C:\OSGEO4~1\apps\Python37\lib\site-packages\PyQt5\uic\objcreator.py:152:DeprecationWarning: 'U' mode is deprecated 

WARNING warning:C:/Users/jadwi/AppData/Roaming/QGIS/QGIS3\profiles\JTRO/python/plugins\gissupport_plugin\modules\uldk\modules\map_point_search\main.py:11: DeprecationWarning: QgsCoordinateReferenceSystem.createFromSrid() is deprecated

WARNING    warning:C:/Users/jadwi/AppData/Roaming/QGIS/QGIS3\profiles\JTRO/python/plugins\gissupport_plugin\modules\uldk\modules\point_layer_import\worker.py:20: DeprecationWarning: QgsCoordinateReferenceSystem.createFromSrid() is deprecated
````

I tried uninstalling all versions of QGIS and reinstalling it but that didn't solve the problem. I always use OSGEO4W Installer to install and update QGIS. On the [gis.stackexchange.com](https://gis.stackexchange.com/questions/377122/problems-with-loading-plugins-processing-and-other-plugins/377177#377177), two people confirmed the same problem.

**Comment by gioman** [comment]
> I tried uninstalling all versions of QGIS and reinstalling it but that didn't solve the problem

@troyaqgis re-installing QGIS do not solves any issue, if there is one. Anyway the above errors come from 3rd party plugins, not QGIS. Contact the plugins author/s. In the meantime create a nee QGIS profile to start a "fresh" copy of QGIS.
