### ISSUE TITLE
Failing to load plugins

### ISSUE THREAD

**Issue by grantboxer** [qgis/QGIS#39703]
I have installed the latest version using the OGeo4GW installer and now when I try to open QGIS I get the following message, along with a few other similar messages.

An error occurred during execution of following code:
import console

can't import io

Python version:

QGIS version:
3.16.0-Hannover 'Hannover', 43b64b13f3

Python path:

**Comment by roya0045** [comment]
Your python is broken.

**Comment by abodsalas** [comment]
Hi. I've just installed QGIS 3.16 stand alone 64 bit and received the same error message,
However QGIS 3.12.0 doesn't show any error when its launched. It says:

An error occurred during execution of following code:
pyplugin_installer.initPluginInstaller()

can't import io

**Comment by orkutmuratyilmaz** [comment]
I use Pop!_OS (Ubuntu 20.04 Derivative) and QGIS 3.16.0 Hannover. Full error message is below:

```
An error occurred during execution of following code:
import console


Traceback (most recent call last):
  File "", line 1, in 
  File "/app/share/qgis/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/app/share/qgis/python/console/__init__.py", line 24, in 
    from .console import show_console  # NOQA
  File "/app/share/qgis/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/app/share/qgis/python/console/console.py", line 31, in 
    from .console_sci import ShellScintilla
  File "/app/share/qgis/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/app/share/qgis/python/console/console_sci.py", line 26, in 
    from qgis.gui import QgsCodeEditorPython, QgsCodeEditorColorScheme
ImportError: cannot import name 'QgsCodeEditorPython' from 'qgis.gui' (/app/share/qgis/python/qgis/gui/__init__.py)


Python version:
3.8.6 (default, Nov 10 2011, 15:00:00) 
[GCC 10.2.0]

QGIS version:
3.16.0-Hannover 'Hannover', 43b64b13

Python path:
['/app/share/qgis/python', '/home/username/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python', '/home/username/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins', '/app/share/qgis/python/plugins', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/usr/lib/python3.8/site-packages', '/app/lib/python3.8/site-packages', '/app/lib/python3.8/site-packages/numpy-1.19.2-py3.8-linux-x86_64.egg', '/app/lib/python3.8/site-packages/MarkupSafe-1.1.1-py3.8-linux-x86_64.egg', '/home/username/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python', '/home/username/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/mmqgis/forms']
```

**Comment by gioman** [comment]
Closing for lack of feedback.

**Comment by abodsalas** [comment]
Installing QGIS 3.16.1 (64 bit) fixed this issue for me in windows 7.
