### ISSUE TITLE
MySQLdb

### ISSUE THREAD

**Issue by andreyderkach** [qgis/QGIS#39727]
Не вдається завантажити плагін 'mysqlimport через помилку під час виклику методу classFactory () 

ModuleNotFoundError: No module named 'MySQLdb' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/aderkac1/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\mysqlimport\__init__.py", line 34, in classFactory
    from .mysql_import import mysqlimport
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/aderkac1/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\mysqlimport\mysql_import.py", line 31, in 
    import os.path, subprocess, MySQLdb
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'MySQLdb'

Версія Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Версія QGIS: 3.14.1-Pi Pi, de08d6b71d 

Шлях до Python:
C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python
C:/Users/aderkac1/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/aderkac1/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS3~1.14\apps\Python37
C:\PROGRA~1\QGIS3~1.14\apps\Python37\Scripts
C:\Program Files\QGIS 3.14\bin\python37.zip
C:\PROGRA~1\QGIS3~1.14\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib
C:\Program Files\QGIS 3.14\bin
C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib\site-packages\Pythonwin
C:/Users/aderkac1/AppData/Roaming/QGIS/QGIS3\profiles\default/python

**Comment by alexbruy** [comment]
This is plugin issue and should be reported in the plugin bugtracker.
