### ISSUE TITLE
QGIS is getting crashed while pre-processing using SCP plugin

### ISSUE THREAD

**Issue by rahulkgour** [qgis/QGIS#39794]
Getting below error while firing up QGIS in mac.

**Couldn't load plugin 'sentinel2_download' due to an error when calling its classFactory() method** 

**ModuleNotFoundError: No module named 'ee_plugin'** 
Traceback (most recent call last):
  File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/sentinel2_download/__init__.py", line 12, in classFactory
    from .Sentinel2_Download_Menu import s2_menu
  File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/sentinel2_download/Sentinel2_Download_Menu.py", line 4, in 
    from .Sentinel2_Download_Dialog import *
  File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/sentinel2_download/Sentinel2_Download_Dialog.py", line 6, in 
    from .Sentinel2_Download_Library import *
  File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/sentinel2_download/Sentinel2_Download_Library.py", line 7, in 
    from ee_plugin import Map
  File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'ee_plugin'

Python version: 3.7.3 (default, Mar 27 2019, 09:23:15) [Clang 10.0.1 (clang-1001.0.46.3)] 
QGIS version: 3.10.11-A Coruña A Coruña, d2171173e4 

Python Path:
/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python
/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/site-packages
/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python37.zip
/Applications/QGIS3.10.app/Contents/Resources/python
/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/site-packages/geos
/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7
/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/lib-dynload
/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgisgbifapi/vendor
/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgisgbifapi/vendor

**Comment by rahulkgour** [comment]
Same Issue while trying the things on QGIS version: 3.14

**Comment by Gustry** [comment]
The QGIS project can do nothing about third party plugin. You must report the issue in the plugin code repository.
