### ISSUE TITLE
[Processing][Modeler] Rename layer does nothing/error out

### ISSUE THREAD

**Issue by roya0045** [qgis/QGIS#39874]
I've been trying with some setup and can never get the algorithm to do anything on permanent or temporary layer outputs in my models.

The only thing that the tool provide is the following error

> An error has occurred while executing Python code: 
> 
> TypeError: 'NoneType' object is not subscriptable 
> Traceback (most recent call last):
>   File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\algs\gdal\GdalAlgorithm.py", line 55, in tags
>     return ['ogr', 'gdal', self.commandName()]
>   File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\algs\gdal\GdalAlgorithm.py", line 156, in commandName
>     name = self.getConsoleCommands(parameters, context, feedback, executing=False)[0]
> TypeError: 'NoneType' object is not subscriptable
> 

On a created layer it works fine. I suspect this is caused by the fact that layers are added only aftr a model is executed, thus if the layer doesn't exist it cannot be renamed.

If this is not a mistake on my part this severely reduce the usability of that tool.

**Comment by roya0045** [comment]
A way to address this would be to set the output name to be something else than the destination parameter name and have the name of the parameter as a fallback. This would allow setting up an alias or simply using the renamer by pushing the new name when the layer has not been made.

I'm slowly looking into this but I'm not sure if I can find an elegant way to have the info go into the destination parameter in a way that would work. I'm not sure where or how the layers are temporarily stored and how they are 'uploaded' in qgis upon termination of the model. I guess this would be easier if the limbo could be modifier but less extensible if we want an expression to modify the output name in the output parameter widget (which would nullify the need for rename also).

**Comment by pathmapper** [comment]
I came also across this trying to rename a temporary output layer created by an algorithim of a model.

> an expression to modify the output name in the output parameter widget (which would nullify the need for rename also).

👍 Would be great to be able to use expressions with variables for the output name. My use case is to make the name of a specific input layer a part of the name of the output layer.
