### ISSUE TITLE
QGIS Crashes when searching for settings

### ISSUE THREAD

**Issue by timlinux** [qgis/QGIS#40443]
Using QGIS master: 6d2be4001769c93ffbb4f035235f3e7252821d2d

Search in the settings dialog and QGIS hangs:

![qgis-crash](https://user-images.githubusercontent.com/178003/101149694-32d68780-3617-11eb-8911-7f9935d186f3.gif)

Here is the traceback:

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib64/libthread_db.so.1".
Missing separate debuginfo for /usr/lib64/libnvidia-opencl.so.1
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/19/4012d9ccbac19e564ff66e0b82fec576e0dde9.debug
Missing separate debuginfo for /usr/lib64/libcuda.so.1
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/50/ec2144919daed5c5d576ee316d1a8157eb8a03.debug
0x00007fc1c8e7bf0f in wait4 () from /usr/lib64/libc.so.6
[Current thread is 1 (Thread 0x7fc1bbd71dc0 (LWP 68969))]
#0  0x00007fc1c8e7bf0f in wait4 () at /usr/lib64/libc.so.6
#1  0x000000000040d257 in qgisCrash(int) (signal=11) at /home/timlinux/dev/cpp/QGIS/src/app/main.cpp:349
        status = 0
        pidstr = "--pid=68969\000X&\224@\240\341\026\006\000\000\000\000\000\200h(X&\224@"
        gdbpid = 69028
        exename = "/home/timlinux/dev/cpp/QGIS-Debug-Build/output/bin/qgis\000\264\376\066\324\301\177\000\000\260\364\061\003\000\000\000\000\260\364\061\003\000\000\000\000\260\364\061\003\000\000\000\000\220+4\324\301\177\000\000\300\265\272\323\301\177\000\000\200\316i\001\000\000\000\000\360\276H(\376\177\000\000`\314\332\005\000\000\000\000\002\000\000\000\000\000\000\000L\330#\327\301\177\000\000\060\275H(\376\177\000\000\354.$\327\301\177\000\000p\314\332\005\000\000\000\000ӂ\343\323\301\177\000\000\000\000\000\000\000\000\000\000\020\031\262\001\000\000\000\000 X\255\001", '\000' <repeats 13 times>...
        len = 55
#2  0x00007fc1c8deaa70 in <signal handler called> () at /usr/lib64/libc.so.6
#3  0x00007fc1d37df652 in QString::operator=(QString const&) () at /usr/lib64/libQt5Core.so.5
#4  0x00007fc1d5aa706d in QgsOptionsDialogHighlightWidget::searchHighlight(QString const&) (this=0x8044340, text=...) at /home/timlinux/dev/cpp/QGIS/src/gui/qgsoptionsdialoghighlightwidget.cpp:80
        found = false
#5  0x00007fc1d5aa4208 in QgsOptionsDialogBase::searchText(QString const&) (this=0x62cdf70, text=...) at /home/timlinux/dev/cpp/QGIS/src/gui/qgsoptionsdialogbase.cpp:323
        rsw = @0x5980db0: {first = 0x8044340, second = 4}
        __for_range = @0x62cdfa0: {<QListSpecialMethods<QPair<QgsOptionsDialogHighlightWidget*, int> >> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, <No data fields>}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x70e4610}, d = 0x70e4610}}
        __for_begin = {i = 0x70e4950}
        __for_end = {i = 0x70e55e8}
        minimumTextLength = 3
#6  0x00007fc1d5aa6d84 in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<QString const&>, void, void (QgsOptionsDialogBase::*)(QString const&)>::call(void (QgsOptionsDialogBase::*)(QString const&), QgsOptionsDialogBase*, void**) (f=(void (QgsOptionsDialogBase::*)(QgsOptionsDialogBase * const, const QString &)) 0x7fc1d5aa4048 <QgsOptionsDialogBase::searchText(QString const&)>, o=0x62cdf70, arg=0x7ffe2848c6b0) at /usr/include/qt5/QtCore/qobjectdefs_impl.h:152
#7  0x00007fc1d5aa6ae9 in QtPrivate::FunctionPointer<void (QgsOptionsDialogBase::*)(QString const&)>::call<QtPrivate::List<QString const&>, void>(void (QgsOptionsDialogBase::*)(QString const&), QgsOptionsDialogBase*, void**) (f=(void (QgsOptionsDialogBase::*)(QgsOptionsDialogBase * const, const QString &)) 0x7fc1d5aa4048 <QgsOptionsDialogBase::searchText(QString const&)>, o=0x62cdf70, arg=0x7ffe2848c6b0) at /usr/include/qt5/QtCore/qobjectdefs_impl.h:185
#8  0x00007fc1d5aa6700 in QtPrivate::QSlotObject<void (QgsOptionsDialogBase::*)(QString const&), QtPrivate::List<QString const&>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0x58eccd0, r=0x62cdf70, a=0x7ffe2848c6b0, ret=0x0) at /usr/include/qt5/QtCore/qobjectdefs_impl.h:418
#9  0x00007fc1d391ff76 in void doActivate<false>(QObject*, int, void**) () at /usr/lib64/libQt5Core.so.5
#10 0x00007fc1d43cc856 in QLineEdit::textChanged(QString const&) () at /usr/lib64/libQt5Widgets.so.5
#11 0x00007fc1d391ffb0 in void doActivate<false>(QObject*, int, void**) () at /usr/lib64/libQt5Core.so.5
#12 0x00007fc1d43d34c9 in QWidgetLineControl::textChanged(QString const&) () at /usr/lib64/libQt5Widgets.so.5
#13 0x00007fc1d43d6a63 in QWidgetLineControl::finishChange(int, bool, bool) () at /usr/lib64/libQt5Widgets.so.5
#14 0x00007fc1d43d9363 in QWidgetLineControl::processKeyEvent(QKeyEvent*) () at /usr/lib64/libQt5Widgets.so.5
#15 0x00007fc1d43cc9af in QLineEdit::keyPressEvent(QKeyEvent*) () at /usr/lib64/libQt5Widgets.so.5
#16 0x00007fc1d42ce1cf in QWidget::event(QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#17 0x00007fc1d595daa5 in QgsFilterLineEdit::event(QEvent*) (this=0x621b4e0, event=0x7ffe2848cf20) at /home/timlinux/dev/cpp/QGIS/src/gui/qgsfilterlineedit.cpp:214
#18 0x00007fc1d428c063 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#19 0x00007fc1d42919d7 in QApplication::notify(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#20 0x00007fc1d04c78cd in QgsApplication::notify(QObject*, QEvent*) (this=0x7ffe2848f2e0, receiver=0x621b4e0, event=0x7ffe2848cf20) at /home/timlinux/dev/cpp/QGIS/src/core/qgsapplication.cpp:462
        done = true
        __PRETTY_FUNCTION__ = "virtual bool QgsApplication::notify(QObject*, QEvent*)"
#21 0x00007fc1d38f0fc0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib64/libQt5Core.so.5
#22 0x00007fc1d42e8e38 in QWidgetWindow::event(QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#23 0x00007fc1d428c063 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#24 0x00007fc1d04c78cd in QgsApplication::notify(QObject*, QEvent*) (this=0x7ffe2848f2e0, receiver=0x70ff990, event=0x7ffe2848cf20) at /home/timlinux/dev/cpp/QGIS/src/core/qgsapplication.cpp:462
        done = true
        __PRETTY_FUNCTION__ = "virtual bool QgsApplication::notify(QObject*, QEvent*)"
#25 0x00007fc1d38f0fc0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib64/libQt5Core.so.5
#26 0x00007fc1d3cd19aa in QGuiApplicationPrivate::processKeyEvent(QWindowSystemInterfacePrivate::KeyEvent*) () at /usr/lib64/libQt5Gui.so.5
#27 0x00007fc17c20959c in QIBusPlatformInputContext::filterEventFinished(QDBusPendingCallWatcher*) () at /usr/lib64/qt5/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so
#28 0x00007fc1d391ff76 in void doActivate<false>(QObject*, int, void**) () at /usr/lib64/libQt5Core.so.5
#29 0x00007fc1d498ad03 in QDBusPendingCallWatcher::finished(QDBusPendingCallWatcher*) () at /usr/lib64/libQt5DBus.so.5
#30 0x00007fc1d3918b5e in QObject::event(QEvent*) () at /usr/lib64/libQt5Core.so.5
#31 0x00007fc1d428c063 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#32 0x00007fc1d04c78cd in QgsApplication::notify(QObject*, QEvent*) (this=0x7ffe2848f2e0, receiver=0x8125fc0, event=0x59a4df0) at /home/timlinux/dev/cpp/QGIS/src/core/qgsapplication.cpp:462
        done = true
        __PRETTY_FUNCTION__ = "virtual bool QgsApplication::notify(QObject*, QEvent*)"
#33 0x00007fc1d38f0fc0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib64/libQt5Core.so.5
#34 0x00007fc1d38f3c47 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib64/libQt5Core.so.5
#35 0x00007fc1d393d0a7 in postEventSourceDispatch(_GSource*, int (*)(void*), void*) () at /usr/lib64/libQt5Core.so.5
#36 0x00007fc1c84cc78f in g_main_context_dispatch () at /usr/lib64/libglib-2.0.so.0
#37 0x00007fc1c84ccb18 in g_main_context_iterate.constprop () at /usr/lib64/libglib-2.0.so.0
#38 0x00007fc1c84ccbe3 in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#39 0x00007fc1d393cb73 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#40 0x00007fc1d38ef91b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#41 0x00007fc1d448a4ef in QDialog::exec() () at /usr/lib64/libQt5Widgets.so.5
#42 0x00007fc1d66b1b27 in QgisApp::showOptionsDialog(QWidget*, QString const&, int) (this=0x297dcb0, parent=0x297dcb0, currentPage=..., pageNumber=-1) at /home/timlinux/dev/cpp/QGIS/src/app/qgisapp.cpp:12492
        optionsDialog = std::unique_ptr<QgsOptions> = {get() = 0x62cdf70}
        mySettings = {<QObject> = {<No data fields>}, static staticMetaObject = {d = {superdata = {direct = 0x7fc1d3ba02c0 <QObject::staticMetaObject>}, stringdata = 0x7fc1d0f0f280 <qt_meta_stringdata_QgsSettings>, data = 0x7fc1d0f0f2c0 <qt_meta_data_QgsSettings>, static_metacall = 0x7fc1cff31688 <QgsSettings::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, mUserSettings = 0x587f9d0, mGlobalSettings = 0x587f150, mUsingGlobalArray = false}
        oldScales = {static null = {<No data fields>}, d = 0x319d110}
#43 0x00007fc1d66afbfc in QgisApp::options() (this=0x297dcb0) at /home/timlinux/dev/cpp/QGIS/src/app/qgisapp.cpp:12342
#44 0x00007fc1d675a1e3 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (QgisApp::*)()>::call(void (QgisApp::*)(), QgisApp*, void**) (f=(void (QgisApp::*)(QgisApp * const)) 0x7fc1d66afbca <QgisApp::options()>, o=0x297dcb0, arg=0x7ffe2848db30) at /usr/include/qt5/QtCore/qobjectdefs_impl.h:152
#45 0x00007fc1d6752f15 in QtPrivate::FunctionPointer<void (QgisApp::*)()>::call<QtPrivate::List<>, void>(void (QgisApp::*)(), QgisApp*, void**) (f=(void (QgisApp::*)(QgisApp * const)) 0x7fc1d66afbca <QgisApp::options()>, o=0x297dcb0, arg=0x7ffe2848db30) at /usr/include/qt5/QtCore/qobjectdefs_impl.h:185
#46 0x00007fc1d6744dae in QtPrivate::QSlotObject<void (QgisApp::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0x314d720, r=0x297dcb0, a=0x7ffe2848db30, ret=0x0) at /usr/include/qt5/QtCore/qobjectdefs_impl.h:418
#47 0x00007fc1d391ff76 in void doActivate<false>(QObject*, int, void**) () at /usr/lib64/libQt5Core.so.5
#48 0x00007fc1d4285876 in QAction::triggered(bool) () at /usr/lib64/libQt5Widgets.so.5
#49 0x00007fc1d4288161 in QAction::activate(QAction::ActionEvent) () at /usr/lib64/libQt5Widgets.so.5
#50 0x00007fc1d4405d5a in QMenuPrivate::activateCausedStack(QVector<QPointer<QWidget> > const&, QAction*, QAction::ActionEvent, bool) () at /usr/lib64/libQt5Widgets.so.5
#51 0x00007fc1d440d3c2 in QMenuPrivate::activateAction(QAction*, QAction::ActionEvent, bool) () at /usr/lib64/libQt5Widgets.so.5
#52 0x00007fc1d42cd36e in QWidget::event(QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#53 0x00007fc1d428c063 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#54 0x00007fc1d4291891 in QApplication::notify(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#55 0x00007fc1d04c78cd in QgsApplication::notify(QObject*, QEvent*) (this=0x7ffe2848f2e0, receiver=0x27605b0, event=0x7ffe2848e2c0) at /home/timlinux/dev/cpp/QGIS/src/core/qgsapplication.cpp:462
        done = true
        __PRETTY_FUNCTION__ = "virtual bool QgsApplication::notify(QObject*, QEvent*)"
#56 0x00007fc1d38f0fc0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib64/libQt5Core.so.5
#57 0x00007fc1d429078a in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () at /usr/lib64/libQt5Widgets.so.5
#58 0x00007fc1d42e698f in QWidgetWindow::handleMouseEvent(QMouseEvent*) () at /usr/lib64/libQt5Widgets.so.5
#59 0x00007fc1d42e8dde in QWidgetWindow::event(QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#60 0x00007fc1d428c063 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#61 0x00007fc1d04c78cd in QgsApplication::notify(QObject*, QEvent*) (this=0x7ffe2848f2e0, receiver=0x3898050, event=0x7ffe2848e6a0) at /home/timlinux/dev/cpp/QGIS/src/core/qgsapplication.cpp:462
        done = true
        __PRETTY_FUNCTION__ = "virtual bool QgsApplication::notify(QObject*, QEvent*)"
#62 0x00007fc1d38f0fc0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib64/libQt5Core.so.5
#63 0x00007fc1d3cd516b in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /usr/lib64/libQt5Gui.so.5
#64 0x00007fc1d3cb715b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Gui.so.5
#65 0x00007fc17ebc7c9e in xcbSourceDispatch(_GSource*, int (*)(void*), void*) () at /usr/lib64/libQt5XcbQpa.so.5
#66 0x00007fc1c84cc78f in g_main_context_dispatch () at /usr/lib64/libglib-2.0.so.0
#67 0x00007fc1c84ccb18 in g_main_context_iterate.constprop () at /usr/lib64/libglib-2.0.so.0
#68 0x00007fc1c84ccbe3 in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#69 0x00007fc1d393cb73 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#70 0x00007fc1d38ef91b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#71 0x00007fc1d38f75a6 in QCoreApplication::exec() () at /usr/lib64/libQt5Core.so.5
#72 0x0000000000414ac2 in main(int, char**) (argc=1, argv=0x7ffe28490668) at /home/timlinux/dev/cpp/QGIS/src/app/main.cpp:1636
        preApplicationLogMessages = {<QList<QString>> = {<QListSpecialMethods<QString>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, <No data fields>}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x188cf90}, d = 0x188cf90}}, <No data fields>}
        __FUNCTION__ = "main"
        mySnapshotFileName = {static null = {<No data fields>}, d = 0x7fc1d39af180 <QArrayData::shared_null>}
        configLocalStorageLocation = {static null = {<No data fields>}, d = 0x1896fc0}
        profileName = {static null = {<No data fields>}, d = 0x1897960}
        mySnapshotWidth = 800
        mySnapshotHeight = 600
        myHideSplash = false
        settingsMigrationForce = false
        mySkipVersionCheck = false
        hideBrowser = false
        myRestoreDefaultWindowState = false
        myRestorePlugins = true
        myCustomization = true
        dxfOutputFile = {static null = {<No data fields>}, d = 0x7fc1d39af180 <QArrayData::shared_null>}
        dxfSymbologyMode = QgsDxfExport::SymbolLayerSymbology
        dxfScale = 50000
        dxfEncoding = {static null = {<No data fields>}, d = 0x41fae0 <main::{lambda()#2}::operator()() const::qstring_literal>}
        dxfMapTheme = {static null = {<No data fields>}, d = 0x7fc1d39af180 <QArrayData::shared_null>}
        dxfExtent = {mXmin = 0, mYmin = 0, mXmax = 0, mYmax = 0}
        takeScreenShots = false
        screenShotsPath = {static null = {<No data fields>}, d = 0x7fc1d39af180 <QArrayData::shared_null>}
        screenShotsCategories = 0
        myInitialExtent = {static null = {<No data fields>}, d = 0x41fb20 <main::{lambda()#3}::operator()() const::qstring_literal>}
        translationCode = {static null = {<No data fields>}, d = 0x18ef100}
        authdbdirectory = {static null = {<No data fields>}, d = 0x7fc1d39af180 <QArrayData::shared_null>}
        pythonfile = {static null = {<No data fields>}, d = 0x7fc1d39af180 <QArrayData::shared_null>}
        customizationfile = {static null = {<No data fields>}, d = 0x1b31af0}
        globalsettingsfile = {static null = {<No data fields>}, d = 0x188d8d0}
        openClProgramFolder = {static null = {<No data fields>}, d = 0x7fc1d39af180 <QArrayData::shared_null>}
        args = {<QList<QString>> = {<QListSpecialMethods<QString>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, <No data fields>}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x188cfc0}, d = 0x188cfc0}}, <No data fields>}
        myUseGuiFlag = true
        rootProfileFolder = {static null = {<No data fields>}, d = 0x1899020}
        manager = {<QObject> = {<No data fields>}, static staticMetaObject = {d = {superdata = {direct = 0x7fc1d3ba02c0 <QObject::staticMetaObject>}, stringdata = 0x7fc1d0f136e0 <qt_meta_stringdata_QgsUserProfileManager>, data = 0x7fc1d0f13760 <qt_meta_data_QgsUserProfileManager>, static_metacall = 0x7fc1cff359ae <QgsUserProfileManager::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, mWatchProfiles = false, mWatcher = std::unique_ptr<QFileSystemWatcher> = {get() = 0x0}, mRootProfilePath = {static null = {<No data fields>}, d = 0x1899020}, mUserProfile = std::unique_ptr<QgsUserProfile> = {get() = 0x0}, mSettings = std::unique_ptr<QSettings> = {get() = 0x188cc80}}
        profile = 0x1898d60
        profileFolder = {static null = {<No data fields>}, d = 0x188de80}
        myApp = {<QApplication> = {<No data fields>}, static staticMetaObject = {d = {superdata = {direct = 0x7fc1d478fee0 <QApplication::staticMetaObject>}, stringdata = 0x7fc1d0effa40 <qt_meta_stringdata_QgsApplication>, data = 0x7fc1d0effc40 <qt_meta_data_QgsApplication>, static_metacall = 0x7fc1cff1b276 <QgsApplication::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, static QGIS_ORGANIZATION_NAME = 0x7fc1d104a0da "QGIS", static QGIS_ORGANIZATION_DOMAIN = 0x7fc1d104a0df "qgis.org", static QGIS_APPLICATION_NAME = 0x7fc1d104a0e8 "QGIS3", static mFileOpenEventReceiver31700 = 0x297dcb0, static mInitialized31700 = true, static mRunningFromBuildDir31700 = true, static sMaxThreads31700 = 22, mIconCache = {d = 0x188ce00}, mCursorCache = {d = 0x2e90290}, mQgisTranslator = 0x1b2bd80, mQtTranslator = 0x1b2bf40, mDataItemProviderRegistry = 0x2631a50, mAuthManager = 0x2541800, mApplicationMembers = 0x1a02600, static sApplicationMembers = 0x0, static sAuthManager = 0x0}
        settings = {<QObject> = {<No data fields>}, static staticMetaObject = {d = {superdata = {direct = 0x7fc1d3ba02c0 <QObject::staticMetaObject>}, stringdata = 0x7fc1d0f0f280 <qt_meta_stringdata_QgsSettings>, data = 0x7fc1d0f0f2c0 <qt_meta_data_QgsSettings>, static_metacall = 0x7fc1cff31688 <QgsSettings::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, mUserSettings = 0x1af3870, mGlobalSettings = 0x1e4d6e0, mUsingGlobalArray = false}
        libPaths = {<QList<QString>> = {<QListSpecialMethods<QString>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, <No data fields>}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x24e8be0}, d = 0x24e8be0}}, <No data fields>}
        relLibPath = {static null = {<No data fields>}, d = 0x20d6b90}
        customizationsettings = 0x2304400
        systemEnvVars = {d = 0x1acd360}
        useCustomVars = false
        desiredStyle = {static null = {<No data fields>}, d = 0x1f78010}
        theme = {static null = {<No data fields>}, d = 0x1f9a660}
        activeStyleName = {static null = {<No data fields>}, d = 0x25af890}
        mySplashPath = {static null = {<No data fields>}, d = 0x7fc1d104b1e0 <QgsApplication::splashPath()::{lambda()#1}::operator()() const::qstring_literal>}
        myPixmap = <incomplete type>
        w = 493
        h = 246
        mypSplash = 0x1b27ec0
        qgis = 0x297dcb0
        sigwatch = {<QObject> = {<No data fields>}, static staticMetaObject = {d = {superdata = {direct = 0x7fc1d3ba02c0 <QObject::staticMetaObject>}, stringdata = 0x461420 <qt_meta_stringdata_UnixSignalWatcher>, data = 0x4614e0 <qt_meta_data_UnixSignalWatcher>, static_metacall = 0x41be8e <UnixSignalWatcher::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, d_ptr = 0x19f7580}
        retval = 4591904
[Inferior 1 (process 68969) detached]
gdb returned 0
ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=68969 comm="qgis" exe="/home/timlinux/dev/cpp/QGIS-Debug-Build/output/bin/qgis" sig=6 res=1
09:53:25: The program has unexpectedly finished.
09:53:25: The process was ended forcefully.
09:53:25: /home/timlinux/dev/cpp/QGIS-Debug-Build/output/bin/qgis crashed.
```

**Comment by gioman** [comment]
@timlinux duplicate of https://github.com/qgis/QGIS/issues/40111 ?

**Comment by timlinux** [comment]
Oh yeah sorry, I'll close here.
