### ISSUE TITLE
Getting Python error while clipping rasters

### ISSUE THREAD

**Issue by rahulkgour** [qgis/QGIS#40455]
**Even though I have installed latest Python version 3.9

I am getting below error:**

2020-12-04T21:50:04     WARNING    Traceback (most recent call last):
              File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/SemiAutomaticClassificationPlugin/maininterface/clipmultiplerasters.py", line 82, in clipRastersAction
              self.clipRasters()
              File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/SemiAutomaticClassificationPlugin/maininterface/clipmultiplerasters.py", line 223, in clipRasters
              cfg.utls.GDALCopyRaster(vrtCheck, f, 'GTiff', cfg.rasterCompression, 'LZW')
              File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/SemiAutomaticClassificationPlugin/core/utils.py", line 7340, in GDALCopyRaster
              manager = cfg.MultiManagerSCP()
              File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/multiprocessing/context.py", line 56, in Manager
              m.start()
              File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/multiprocessing/managers.py", line 547, in start
              self._address = reader.recv()
              File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/multiprocessing/connection.py", line 250, in recv
              buf = self._recv_bytes()
              File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
              buf = self._recv(4)
              File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/multiprocessing/connection.py", line 383, in _recv
              raise EOFError
             EOFError
             
2020-12-04T22:01:19     WARNING    Traceback (most recent call last):
              File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/SemiAutomaticClassificationPlugin/maininterface/clipmultiplerasters.py", line 82, in clipRastersAction
              self.clipRasters()
              File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/SemiAutomaticClassificationPlugin/maininterface/clipmultiplerasters.py", line 223, in clipRasters
              cfg.utls.GDALCopyRaster(vrtCheck, f, 'GTiff', cfg.rasterCompression, 'LZW')
              File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/SemiAutomaticClassificationPlugin/core/utils.py", line 7340, in GDALCopyRaster
              manager = cfg.MultiManagerSCP()
              File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/multiprocessing/context.py", line 56, in Manager
              m.start()
              File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/multiprocessing/managers.py", line 547, in start
              self._address = reader.recv()
              File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/multiprocessing/connection.py", line 250, in recv
              buf = self._recv_bytes()
              File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
              buf = self._recv(4)
              File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/multiprocessing/connection.py", line 383, in _recv
              raise EOFError
             EOFError

**Comment by gioman** [comment]
@rahulkgour this an error from the SCP plugin, not QGIS. Contact the plugin author.
