### ISSUE TITLE
DB Manager python error on master

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#40943]
try expand a PostGIS connection

```
Traceback (most recent call last):
  File "/usr/share/qgis/python/plugins/db_manager/db_model.py", line 456, in rowCount
    self._refreshIndex(parent, True)
  File "/usr/share/qgis/python/plugins/db_manager/db_model.py", line 505, in _refreshIndex
    if item.populate():
  File "/usr/share/qgis/python/plugins/db_manager/db_model.py", line 182, in populate
    if not connection.connect():
  File "/usr/share/qgis/python/plugins/db_manager/db_plugins/postgis/plugin.py", line 104, in connect
    return self.connectToUri(uri)
  File "/usr/share/qgis/python/plugins/db_manager/db_plugins/plugin.py", line 142, in connectToUri
    self.db = self.databasesFactory(self, uri)
  File "/usr/share/qgis/python/plugins/db_manager/db_plugins/postgis/plugin.py", line 68, in databasesFactory
    return PGDatabase(connection, uri)
  File "/usr/share/qgis/python/plugins/db_manager/db_plugins/postgis/plugin.py", line 112, in __init__
    Database.__init__(self, connection, uri)
  File "/usr/share/qgis/python/plugins/db_manager/db_plugins/plugin.py", line 267, in __init__
    self.connector = self.connectorsFactory(uri)
  File "/usr/share/qgis/python/plugins/db_manager/db_plugins/postgis/plugin.py", line 115, in connectorsFactory
    return PostGisDBConnector(uri, self.connection())
  File "/usr/share/qgis/python/plugins/db_manager/db_plugins/postgis/connector.py", line 258, in __init__
    self.user, self.dbname = self._fetchone(c)
ValueError: not enough values to unpack (expected 2, got 1)
```

QGIS master on Ubuntu 20.04.

**Comment by gioman** [comment]
I updated master and the error went away...

**Comment by gioman** [comment]
And.... it's back again.

**Comment by elpaso** [comment]
@gioman can you retry master after https://github.com/qgis/QGIS/pull/41112 ?

**Comment by gioman** [comment]
> @gioman can you retry master after #41112 ?

@elpaso will do asap.

**Comment by gioman** [comment]
> @gioman can you retry master after #41112 ?

@elpaso I updated and the error is gone.
