### ISSUE TITLE
Various Python scripts failing to load on QGIS open

### ISSUE THREAD

**Issue by zvalentine22** [qgis/QGIS#41219]
Installed from the ``` https://qgis.org/ubuntu ``` repo. 

```
uname -a
Linux feta 5.8.0-7630-generic #32~1609193707~20.10~781bb80-Ubuntu SMP Tue Jan 5 21:29:56 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```
```
dpkg -l | grep qgis
ii  libqgis-3d3.16.3                                            1:3.16.3+33groovy                                    amd64        QGIS - shared 3d library
ii  libqgis-analysis3.16.3                                      1:3.16.3+33groovy                                    amd64        QGIS - shared analysis library
ii  libqgis-app3.16.3                                           1:3.16.3+33groovy                                    amd64        QGIS - shared app library
ii  libqgis-core3.16.3                                          1:3.16.3+33groovy                                    amd64        QGIS - shared core library
ii  libqgis-customwidgets                                       1:3.16.3+33groovy                                    amd64        QGIS custom widgets for Qt Designer
ii  libqgis-gui3.16.3                                           1:3.16.3+33groovy                                    amd64        QGIS - shared gui library
ii  libqgis-native3.16.3                                        1:3.16.3+33groovy                                    amd64        QGIS - shared native gui library
ii  libqgis-server3.16.3                                        1:3.16.3+33groovy                                    amd64        QGIS - shared server library
ii  libqgisgrass7-3.16.3                                        1:3.16.3+33groovy                                    amd64        QGIS - shared grass library
ii  libqgispython3.16.3                                         1:3.16.3+33groovy                                    amd64        QGIS - shared Python library
ii  python3-qgis                                                1:3.16.3+33groovy                                    amd64        Python bindings to QGIS
ii  python3-qgis-common                                         1:3.16.3+33groovy                                    all          Python bindings to QGIS - architecture-independent files
ii  qgis                                                        1:3.16.3+33groovy                                    amd64        Geographic Information System (GIS)
ii  qgis-common                                                 1:3.16.3+33groovy                                    all          QGIS - architecture-independent data
ii  qgis-plugin-grass                                           1:3.16.3+33groovy                                    amd64        GRASS plugin for QGIS
ii  qgis-plugin-grass-common                                    1:3.16.3+33groovy                                    all          GRASS plugin for QGIS - architecture-independent data
ii  qgis-provider-grass                                         1:3.16.3+33groovy                                    amd64        GRASS provider for QGIS
ii  qgis-providers                                              1:3.16.3+33groovy                                    amd64        collection of data providers to QGIS
ii  qgis-providers-common                                       1:3.16.3+33groovy                                    all          collection of data providers to QGIS - architecture-independent files
```
The about window  is saying Qt 5.14.2 and I've got 5.15 but I'm assuming that's a >= dependency, no? :
```
QGIS version | 3.16.3-Hannover | QGIS code revision | 94ac9f21b8
-- | -- | -- | --
Compiled against Qt | 5.14.2 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 3.1.3 | Running against GDAL/OGR | 3.1.3
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.33.0 | Running against SQLite | 3.33.0
PostgreSQL Client Version | 12.5 (Ubuntu 12.5-0ubuntu0.20.10.1) | SpatiaLite Version | 5.0.0
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 7.1.0 | Running against PROJ | Rel. 7.1.0, August 1st, 2020


```
```
dpkg -l | grep pyqt5
ii  pyqt5-dev                                                   5.15.0+dfsg-1                                        all          Development files for PyQt5
ii  pyqt5-dev-tools                                             5.15.0+dfsg-1                                        amd64        Development tools for PyQt5
ii  python3-pyqt5                                               5.15.0+dfsg-1                                        amd64        Python 3 bindings for Qt5
ii  python3-pyqt5.qsci                                          2.11.2+dfsg-6                                        amd64        Python 3 bindings for QScintilla 2 with Qt 5
ii  python3-pyqt5.qtopengl                                      5.15.0+dfsg-1                                        amd64        Python 3 bindings for Qt5's OpenGL module
ii  python3-pyqt5.qtsql                                         5.15.0+dfsg-1                                        amd64        Python 3 bindings for Qt5's SQL module
ii  python3-pyqt5.qtsvg                                         5.15.0+dfsg-1                                        amd64        Python 3 bindings for Qt5's SVG module
ii  python3-pyqt5.qtwebkit                                      5.15.0+dfsg-1                                        amd64        Python 3 bindings for Qt5's WebKit module
ii  python3-pyqt5.qwt                                           1.02.00-2                                            amd64        Python version of the Qwt6 technical widget library (Python3)
ii  python3-pyqt5.sip                                           12.8.0-1                                             amd64        runtime module for Python extensions using SIP
```
Immediately greeted with the following error windows:

```
An error occurred during execution of following code:
qgis.utils.initInterface(94724482521840)


Traceback (most recent call last):
  File "", line 1, in 
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 217, in initInterface
    iface = wrapinstance(pointer, QgisInterface)
TypeError: wrapinstance() argument 2 must be sip.wrappertype, not sip.wrappertype


Python version:
3.8.6 (default, Sep 25 2020, 09:36:53) 
[GCC 10.2.0]

QGIS version:
3.16.3-Hannover 'Hannover', 94ac9f21b8

Python path:
['/usr/share/qgis/python', '/home/feta/.local/share/QGIS/QGIS3/profiles/default/python', '/home/feta/.local/share/QGIS/QGIS3/profiles/default/python/plugins', '/usr/share/qgis/python/plugins', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/usr/local/lib/python3.8/dist-packages', '/usr/lib/python3/dist-packages']
```
```
Couldn't load plugin 'db_manager' due to an error when calling its initGui() method 

AttributeError: 'NoneType' object has no attribute 'mainWindow' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 359, in startPlugin
    plugins[packageName].initGui()
  File "/usr/share/qgis/python/plugins/db_manager/db_manager_plugin.py", line 46, in initGui
    self.iface.mainWindow())
AttributeError: 'NoneType' object has no attribute 'mainWindow'


Python version: 3.8.6 (default, Sep 25 2020, 09:36:53) [GCC 10.2.0] 
QGIS version: 3.16.3-Hannover Hannover, 94ac9f21b8 

Python Path:
/usr/share/qgis/python
/home/feta/.local/share/QGIS/QGIS3/profiles/default/python
/home/feta/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/usr/local/lib/python3.8/dist-packages
/usr/lib/python3/dist-packages
/home/feta/.local/share/QGIS/QGIS3/profiles/default/python
```
```
Couldn't load plugin 'processing' due to an error when calling its initGui() method 

AttributeError: 'NoneType' object has no attribute 'registerOptionsWidgetFactory' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 359, in startPlugin
    plugins[packageName].initGui()
  File "/usr/share/qgis/python/plugins/processing/ProcessingPlugin.py", line 178, in initGui
    iface.registerOptionsWidgetFactory(self.options_factory)
AttributeError: 'NoneType' object has no attribute 'registerOptionsWidgetFactory'


Python version: 3.8.6 (default, Sep 25 2020, 09:36:53) [GCC 10.2.0] 
QGIS version: 3.16.3-Hannover Hannover, 94ac9f21b8 

Python Path:
/usr/share/qgis/python
/home/feta/.local/share/QGIS/QGIS3/profiles/default/python
/home/feta/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/usr/local/lib/python3.8/dist-packages
/usr/lib/python3/dist-packages
/home/feta/.local/share/QGIS/QGIS3/profiles/default/python
```
```
Couldn't load plugin 'MetaSearch' due to an error when calling its initGui() method 

AttributeError: 'NoneType' object has no attribute 'mainWindow' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 359, in startPlugin
    plugins[packageName].initGui()
  File "/usr/share/qgis/python/plugins/MetaSearch/plugin.py", line 60, in initGui
    self.iface.mainWindow())
AttributeError: 'NoneType' object has no attribute 'mainWindow'


Python version: 3.8.6 (default, Sep 25 2020, 09:36:53) [GCC 10.2.0] 
QGIS version: 3.16.3-Hannover Hannover, 94ac9f21b8 

Python Path:
/usr/share/qgis/python
/home/feta/.local/share/QGIS/QGIS3/profiles/default/python
/home/feta/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/usr/local/lib/python3.8/dist-packages
/usr/lib/python3/dist-packages
/home/feta/.local/share/QGIS/QGIS3/profiles/default/python
```
```
An error occurred during execution of following code:
console.init_options_widget()


Traceback (most recent call last):
  File "", line 1, in 
  File "/usr/share/qgis/python/console/console.py", line 89, in init_options_widget
    iface.registerOptionsWidgetFactory(_options_factory)
AttributeError: 'NoneType' object has no attribute 'registerOptionsWidgetFactory'


Python version:
3.8.6 (default, Sep 25 2020, 09:36:53) 
[GCC 10.2.0]

QGIS version:
3.16.3-Hannover 'Hannover', 94ac9f21b8

Python path:
['/usr/share/qgis/python', '/home/feta/.local/share/QGIS/QGIS3/profiles/default/python', '/home/feta/.local/share/QGIS/QGIS3/profiles/default/python/plugins', '/usr/share/qgis/python/plugins', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/usr/local/lib/python3.8/dist-packages', '/usr/lib/python3/dist-packages', '/home/feta/.local/share/QGIS/QGIS3/profiles/default/python']
```

**Comment by roya0045** [comment]
So your qgis doesn't match your python environment and that cause issue?

**Comment by zvalentine22** [comment]
Right.. and they are the versions that installed with qgis?

**Comment by zvalentine22** [comment]
Apparently the 8th reinstall did it, the python environment versions are all still identical to what I posted above. Who knows.
