### ISSUE TITLE
TypeError: 'QVariant' object is not subscriptable

### ISSUE THREAD

**Issue by harshmistry96** [qgis/QGIS#42257]
Hi,

I am getting an error while installing the quick map service plugin.

TypeError: 'QVariant' object is not subscriptable 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/harsh/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\quick_map_services\__init__.py", line 35, in classFactory
    return QuickMapServices(iface)
  File "C:/Users/harsh/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\quick_map_services\quick_map_services.py", line 72, in __init__
    self.locale = Locale.get_locale()
  File "C:/Users/harsh/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\quick_map_services\plugin_locale.py", line 30, in get_locale
    return QSettings().value('locale/userLocale')[0:2]
TypeError: 'QVariant' object is not subscriptable

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.16.4-Hannover Hannover, 654e76b3cb 

Python Path:
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python
C:/Users/harsh/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/harsh/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3~1.16\apps\Python37
C:\PROGRA~1\QGIS3~1.16\apps\Python37\Scripts
C:\Program Files\QGIS 3.16\bin\python37.zip
C:\PROGRA~1\QGIS3~1.16\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib
C:\Program Files\QGIS 3.16\bin
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\Pythonwin
C:/Users/harsh/AppData/Roaming/QGIS/QGIS3\profiles\default/python
D:/PhD 2020/Numerical Analysis/Seismic Hazard Analysis/India/Tamil Nadu

**Comment by nyalldawson** [comment]
This is a bug in a third party plugin -- you'll need to report it to the plugin authors.
