### ISSUE TITLE
TIN Interpolation algorithm can't be reconfigured in the graphical modeller

### ISSUE THREAD

**Issue by SrNetoChan** [qgis/QGIS#42484]
**Describe the bug**

Once added and configured, the "TIN Interpolation" algorithm can't be configured again returning the following error:

```
An error has occurred while executing Python code: 

AttributeError: 'InterpolationDataWidget' object has no attribute 'addLayerData' 
Traceback (most recent call last):
  File "/usr/share/qgis/python/plugins/processing/modeler/ModelerGraphicItem.py", line 161, in editComponent
    self.edit()
  File "/usr/share/qgis/python/plugins/processing/modeler/ModelerGraphicItem.py", line 135, in edit
    self.component().configuration())
  File "/usr/share/qgis/python/plugins/processing/modeler/ModelerParametersDialog.py", line 79, in __init__
    self.widget = ModelerParametersWidget(alg, model, algName, configuration, context=self.context, dialog=self)
  File "/usr/share/qgis/python/plugins/processing/modeler/ModelerParametersDialog.py", line 497, in __init__
    self.widget = ModelerParametersPanelWidget(alg, model, algName, configuration, dialog, context)
  File "/usr/share/qgis/python/plugins/processing/modeler/ModelerParametersDialog.py", line 193, in __init__
    self.setupUi()
  File "/usr/share/qgis/python/plugins/processing/modeler/ModelerParametersDialog.py", line 315, in setupUi
    self.setPreviousValues()
  File "/usr/share/qgis/python/plugins/processing/modeler/ModelerParametersDialog.py", line 378, in setPreviousValues
    wrapper.setValue(value)
  File "/usr/share/qgis/python/plugins/processing/algs/qgis/ui/InterpolationWidgets.py", line 214, in setValue
    self.widget.setValue(value)
  File "/usr/share/qgis/python/plugins/processing/algs/qgis/ui/InterpolationWidgets.py", line 161, in setValue
    self.addLayerData(v[0], v[1])
AttributeError: 'InterpolationDataWidget' object has no attribute 'addLayerData'


Python version: 3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0] 
QGIS version: 3.16.5-Hannover Hannover, 58ba7c1ed6 

Python Path:
/usr/share/qgis/python
/home/aneto/.local/share/QGIS/QGIS3/profiles/default/python
/home/aneto/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/home/aneto/.local/lib/python3.6/site-packages
/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages
/home/aneto/.local/share/QGIS/QGIS3/profiles/default/python
/home/aneto/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web
/home/aneto/.local/share/QGIS/QGIS3/profiles/default/python/plugins
.
/home/aneto/.local/share/QGIS/QGIS3/profiles/default/python/plugins/recartDGT/convert/processing
/home/aneto/Trabalho/Inforgeo/Marina
```

**How to Reproduce**

1. Open a new model
2. Add a TIN Interpolate algoritm
3. Change some settings and close the dialog
4. right or double-click to edit the algotithm

**QGIS and OS versions**

QGIS version | 3.16.5-Hannover | QGIS code revision | 58ba7c1ed6
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 10.16 (Ubuntu 10.16-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Ubuntu 18.04.5 LTS
Active python plugins | splitmultipart; qgis2web; coretests; qfieldsync; changeDataSource; qconsolidate; ForestMetrixTools; QuickWKT; socarto_recart_tools; recartDGT; SpreadsheetLayers; geolayer_recart_tools; qgistester; QuickOSM; firstaid; plugin_reloader; IPyConsole; Plugin; lizmap; db_manager; processing

**Additional context**

It also happens in QGIS 3.18.1

**Comment by nicogodet** [comment]
see https://github.com/qgis/QGIS/issues/30029

**Comment by SrNetoChan** [comment]
@nicogodet you are right. It seems to be the same problem.
