### ISSUE TITLE
New Script From Template Error

### ISSUE THREAD

**Issue by ItaloCunhaBueno** [qgis/QGIS#42576]
When clicking 'Create script from template' from processing tools window, the following error is presented:

```
An error has occurred while executing Python code: 

AttributeError: type object 'Editor' has no attribute 'MARKER_NUM' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins\processing\script\AddScriptFromTemplateAction.py", line 53, in execute
    dlg.show()
  File "C:/Users/Italo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\bettereditor\customclasses.py", line 633, in show
    self.customize()
  File "C:/Users/Italo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\bettereditor\customclasses.py", line 639, in customize
    self.editor.customize()
  File "C:/Users/Italo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\bettereditor\customclasses.py", line 609, in customize
    define_indicators(self)
  File "C:/Users/Italo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\bettereditor\indicatorsutils.py", line 61, in define_indicators
    Editor.MARKER_NUM,
AttributeError: type object 'Editor' has no attribute 'MARKER_NUM'


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.16.5-Hannover Hannover, 58ba7c1ed6 

Python Path:
C:/Users/Italo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LAStools
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python
C:/Users/Italo/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Italo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3~1.16\apps\Python37
C:\PROGRA~1\QGIS3~1.16\apps\Python37\Scripts
C:\Program Files\QGIS 3.16\bin\python37.zip
C:\PROGRA~1\QGIS3~1.16\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib
C:\Program Files\QGIS 3.16\bin
C:\Users\Italo\AppData\Roaming\Python\Python37\site-packages
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\Pythonwin
C:/Users/Italo/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Italo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web
C:\Users\Italo\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
```

**Comment by ItaloCunhaBueno** [comment]
Closed, I realized the problem was caused by faulty plugin.
