### ISSUE TITLE
Crash master/3.18 on Report/Add Item/Add Dynamic Text

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#42579]
To reproduce:
- start QGIS in a fresh profile (no plugins nothing)
- without loading a data or project
- choose Project/New Report, hit enter when asked fro unique report title
- without adding/doing anything, choose menu 'Add Item', in which with me only(!) 'Add Dynamic Text' is enabled, and then 'Add Dynamic Text'
- immediate crash

Anybody can reproduce?
With me both Master and 3.18 have the  'Add Dynamic Text'  and crash.
My 3.16 (a little older) doe NOT have this option (not even disabled)

QGIS version | 3.19.0-Master | QGIS code revision | 764c652807
-- | -- | -- | --
Compiled against Qt | 5.15.2 | Running against Qt | 5.15.2
Compiled against GDAL/OGR | 3.2.1 | Running against GDAL/OGR | 3.2.1
Compiled against GEOS | 3.9.0-CAPI-1.16.2 | Running against GEOS | 3.9.0-CAPI-1.16.2
Compiled against SQLite | 3.34.1 | Running against SQLite | 3.34.1
Compiled against PDAL | 2.2.0 | Running against PDAL | 2.2.0 (git-version: Release)
PostgreSQL Client Version | 13.2 (Debian 13.2-1) | SpatiaLite Version | 5.0.1
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.6
Compiled against PROJ | 7.2.1 | Running against PROJ | Rel. 7.2.1, January 1st, 2021
OS Version | Debian GNU/Linux bullseye/sid | This copy of QGIS writes debugging output.
Active python plugins | MetaSearch; processing; db_manager

```
QGIS died on signal 11[New LWP 10686]
[New LWP 10687]
[New LWP 10689]
[New LWP 10690]
[New LWP 10691]
[New LWP 10696]
[New LWP 10719]
[New LWP 10720]
[New LWP 10721]
[New LWP 10722]
[New LWP 10723]
[New LWP 10749]
[New LWP 10755]
[New LWP 10756]
[New LWP 10762]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007fd329345207 in __GI___wait4 (pid=11015, stat_loc=0x7fff83500354, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
27	../sysdeps/unix/sysv/linux/wait4.c: No such file or directory.
[Current thread is 1 (Thread 0x7fd316bda100 (LWP 10674))]
#0  0x00007fd329345207 in __GI___wait4 (pid=11015, stat_loc=0x7fff83500354, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
#1  0x000055818803c266 in qgisCrash(int) (signal=11) at ../src/app/main.cpp:350
        status = 32767
        pidstr = "--pid=10674\000\377\177\000\000 \002P\203\377\177\000\000\330\001P\203\377\177\000"
        gdbpid = 11015
        exename = "/home/richard/bin/qgis_/3.18/debug/bin/qgis\000\377\177\000\000\060\rP\203\377\177\000\000\000\000\000\000\000\000 @\000\000\000\000\000\000\360?\000\000\000\000\000\000\b@\000\000\000\000\000\000\020@\300\004P\203\377\177\000\000\000\000\000\000\000\000\340?\000\000\000\000\000\000 @\000\000\000\000\000\000\340?\000\000\000\000\000\000\340? Yڈ\201U\000\000`[\271\211\201U\000\000\200q\270\211\201U\000\000p&\271\211\201U\000\000\000\000\000\000\000\000\034@\000\000\000\000\000\000\024@(\033\201,\323\177\000\000\000\000\335i", '\000' <repeats 12 times>, "\220"...
        len = 43
#2  0x00007fd3292b5d60 in <signal handler called> () at /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007fd32cc9ab8e in QGraphicsScene::items(Qt::SortOrder) const () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#4  0x00007fd32ee8b7cd in QgsLayout::layoutItems<QgsLayoutItemMap>(QList<QgsLayoutItemMap*>&) const (this=0x0, itemList=...) at ../src/core/layout/qgslayout.h:124
        graphicsItemList = {<QListSpecialMethods<QGraphicsItem*>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, <No data fields>}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x7fff83500aa0}, d = 0x7fff83500aa0}}
        itemIt = {i = 0x269ddc900}
#5  0x00007fd32daa2840 in QgsLayoutLabelWidget::buildInsertDynamicTextMenu(QgsLayout*, QMenu*, std::function<void (QString const&)> const&) (layout=0x0, menu=0x5581891eee90, callback=...) at ../src/gui/layout/qgslayoutlabelwidget.cpp:121
        addExpression = {__callback = @0x7fff835012e0}
        dateMenu = 0x55818cdc2400
        mapsMenu = 0x55818bbec0e0
        maps = {<QListSpecialMethods<QgsLayoutItemMap*>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, <No data fields>}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x7fd32bfb0470 <QListData::shared_null>}, d = 0x7fd32bfb0470 <QListData::shared_null>}}
#6  0x00007fd32eff4c8b in operator()() const (__closure=0x5581891eff70) at ../src/app/layout/qgslayoutdesignerdialog.cpp:429
        this = 0x5581891e5050
        size = 32767
        index = 21889
        resizeToolButton = 0x5581891f0170
        defAtlasExportAction = 0x1
        atlasExportAction = 0x55818cdc2400
        docksTitle = {<QList<QString>> = {<QListSpecialMethods<QString>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, <No data fields>}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x7fff83500a20}, d = 0x7fff83500a20}}, <No data fields>}
        docksActive = {<QList<QString>> = {<QListSpecialMethods<QString>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, <No data fields>}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x7fd32eba1294 <QtPrivate::RefCount::deref()+24>}, d = 0x7fd32eba1294 <QtPrivate::RefCount::deref()+24>}}, <No data fields>}
        viewLayout = 0x5581891eff60
        showRulers = false
        alignToolButton = 0x7fd32f021c04 <std::_Function_base::_Base_manager<QgsLayoutDesignerDialog::QgsLayoutDesignerDialog(QWidget*, Qt::WindowFlags)::<lambda()>::<lambda(const QString&)> >::_M_init_functor(std::_Any_data &, struct {...} &&)+46>
        distributeToolButton = 0x7fff83501290
        ctrlEquals = 0x7fff83500c20
        zoomRx = {d = {d = 0x7fff83500a00}}
        docks = {<QListSpecialMethods<QDockWidget*>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, <No data fields>}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x7fd32bfb0470 <QListData::shared_null>}, d = 0x7fd32bfb0470 <QListData::shared_null>}}
        actions = {<QListSpecialMethods<QAction*>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, <No data fields>}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x7fff835009e0}, d = 0x7fff835009e0}}
        settings = {<QObject> = {<No data fields>}, static staticMetaObject = {d = {superdata = {direct = 0x7fd32c156100 <QObject::staticMetaObject>}, stringdata = 0x7fd32ad472a0 <qt_meta_stringdata_QgsSettings>, data = 0x7fd32ad472e0 <qt_meta_data_QgsSettings>, static_metacall = 0x7fd329ce03e2 <QgsSettings::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, mUserSettings = 0x0, mGlobalSettings = 0x0, mUsingGlobalArray = 192}
        rulerMenu = 0x5581891eee90
        orderingToolButton = 0x7fff835012a0
        previewGroup = 0x7fff83500b10
        itemMetadataIds = {<QListSpecialMethods<int>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, <No data fields>}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x7fd32bfb0470 <QListData::shared_null>}, d = 0x7fd32bfb0470 <QListData::shared_null>}}
        bt = 0x3
        backSpace = 0x7fff83500b20
        zoomValidator = 0x7fff83501270
        minDockWidth = 32767
#7  0x00007fd32f0263fe in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, QgsLayoutDesignerDialog::QgsLayoutDesignerDialog(QWidget*, Qt::WindowFlags)::<lambda()> >::call(struct {...} &, void **) (f=..., arg=0x7fff83501460) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:146
#8  0x00007fd32f0257ea in QtPrivate::Functor<QgsLayoutDesignerDialog::QgsLayoutDesignerDialog(QWidget*, Qt::WindowFlags)::<lambda()>, 0>::call<QtPrivate::List<>, void>(struct {...} &, void *, void **) (f=..., arg=0x7fff83501460) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:256
#9  0x00007fd32f02342b in QtPrivate::QFunctorSlotObject<QgsLayoutDesignerDialog::QgsLayoutDesignerDialog(QWidget*, Qt::WindowFlags)::<lambda()>, 0, QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase *, QObject *, void **, bool *) (which=1, this_=0x5581891eff60, r=0x5581891e5050, a=0x7fff83501460, ret=0x0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:443
#10 0x00007fd32bf00546 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007fd32cb04d89 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007fd32cb05b8d in QMenu::popup(QPoint const&, QAction*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007fd32cb06b17 in QMenu::internalDelayedPopup() () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007fd32bef5ecf in QObject::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007fd32c98b15f in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007fd32a2f0a4d in QgsApplication::notify(QObject*, QEvent*) (this=0x7fff83502400, receiver=0x558189292f90, event=0x7fff835018b0) at ../src/core/qgsapplication.cpp:475
        done = true
        __PRETTY_FUNCTION__ = "virtual bool QgsApplication::notify(QObject*, QEvent*)"
#17 0x00007fd32bec9f6a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x00007fd32bf20883 in QTimerInfoList::activateTimers() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#19 0x00007fd32bf21104 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#20 0x00007fd3218c5e6b in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#21 0x00007fd3218c6118 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#22 0x00007fd3218c61cf in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00007fd32bf214bf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#24 0x00007fd32bec892b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#25 0x00007fd32bed0ba0 in QCoreApplication::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#26 0x0000558188043b1a in main(int, char**) (argc=3, argv=0x7fff83503788) at ../src/app/main.cpp:1638
        preApplicationLogMessages = {<QList<QString>> = {<QListSpecialMethods<QString>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, <No data fields>}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x558188f78c60}, d = 0x558188f78c60}}, <No data fields>}
        __FUNCTION__ = "main"
        mySnapshotFileName = {static null = {<No data fields>}, d = 0x7fd32bfaf960 <QArrayData::shared_null>}
        configLocalStorageLocation = {static null = {<No data fields>}, d = 0x558188f787b0}
        profileName = {static null = {<No data fields>}, d = 0x558188f79a20}
        mySnapshotWidth = 800
        mySnapshotHeight = 600
        myHideSplash = false
        settingsMigrationForce = false
        mySkipVersionCheck = false
        hideBrowser = false
        myRestoreDefaultWindowState = false
        myRestorePlugins = true
        myCustomization = true
        dxfOutputFile = {static null = {<No data fields>}, d = 0x7fd32bfaf960 <QArrayData::shared_null>}
        dxfSymbologyMode = QgsDxfExport::SymbolLayerSymbology
        dxfScale = 50000
        dxfEncoding = {static null = {<No data fields>}, d = 0x55818804eb40 <main::{lambda()#2}::operator()() const::qstring_literal>}
        dxfMapTheme = {static null = {<No data fields>}, d = 0x7fd32bfaf960 <QArrayData::shared_null>}
        dxfExtent = {mXmin = 0, mYmin = 0, mXmax = 0, mYmax = 0}
        takeScreenShots = false
        screenShotsPath = {static null = {<No data fields>}, d = 0x7fd32bfaf960 <QArrayData::shared_null>}
        screenShotsCategories = 0
        myInitialExtent = {static null = {<No data fields>}, d = 0x7fd32bfaf960 <QArrayData::shared_null>}
        translationCode = {static null = {<No data fields>}, d = 0x558188f849a0}
        authdbdirectory = {static null = {<No data fields>}, d = 0x7fd32bfaf960 <QArrayData::shared_null>}
        pythonfile = {static null = {<No data fields>}, d = 0x7fd32bfaf960 <QArrayData::shared_null>}
        customizationfile = {static null = {<No data fields>}, d = 0x55818931c650}
        globalsettingsfile = {static null = {<No data fields>}, d = 0x558188f78400}
        openClProgramFolder = {static null = {<No data fields>}, d = 0x7fd32bfaf960 <QArrayData::shared_null>}
        args = {<QList<QString>> = {<QListSpecialMethods<QString>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, <No data fields>}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x558188f78c30}, d = 0x558188f78c30}}, <No data fields>}
        myUseGuiFlag = true
        rootProfileFolder = {static null = {<No data fields>}, d = 0x558188f78d10}
        manager = {<QObject> = {<No data fields>}, static staticMetaObject = {d = {superdata = {direct = 0x7fd32c156100 <QObject::staticMetaObject>}, stringdata = 0x7fd32ad4bc60 <qt_meta_stringdata_QgsUserProfileManager>, data = 0x7fd32ad4bce0 <qt_meta_data_QgsUserProfileManager>, static_metacall = 0x7fd329ce5032 <QgsUserProfileManager::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, mWatchProfiles = false, mWatcher = std::unique_ptr<class QFileSystemWatcher> = {get() = 0x0}, mRootProfilePath = {static null = {<No data fields>}, d = 0x558188f78d10}, mUserProfile = std::unique_ptr<class QgsUserProfile> = {get() = 0x0}, mSettings = std::unique_ptr<class QSettings> = {get() = 0x558188f78930}}
        profile = 0x558188f789a0
        profileFolder = {static null = {<No data fields>}, d = 0x558188f799c0}
        myApp = {<QApplication> = {<No data fields>}, static staticMetaObject = {d = {superdata = {direct = 0x7fd32ce82fa0 <QApplication::staticMetaObject>}, stringdata = 0x7fd32ad3b4e0 <qt_meta_stringdata_QgsApplication>, data = 0x7fd32ad3b6e0 <qt_meta_data_QgsApplication>, static_metacall = 0x7fd329ccfcbe <QgsApplication::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, static QGIS_ORGANIZATION_NAME = 0x7fd32aea02ca "QGIS", static QGIS_ORGANIZATION_DOMAIN = 0x7fd32aea02cf "qgis.org", static QGIS_APPLICATION_NAME = 0x7fd32aea02d8 "QGIS3", static mFileOpenEventReceiver31801 = 0x558189c06760, static mInitialized31801 = true, static mRunningFromBuildDir31801 = false, static sMaxThreads31801 = -1, mIconCache = {d = 0x558189126fd0}, mCursorCache = {d = 0x55818a295c40}, mQgisTranslator = 0x5581891212e0, mQtTranslator = 0x5581890ed810, mDataItemProviderRegistry = 0x558189789b70, mAuthManager = 0x5581897167e0, mApplicationMembers = 0x55818909fed0, static sApplicationMembers = 0x0, static sAuthManager = 0x0}
        settings = {<QObject> = {<No data fields>}, static staticMetaObject = {d = {superdata = {direct = 0x7fd32c156100 <QObject::staticMetaObject>}, stringdata = 0x7fd32ad472a0 <qt_meta_stringdata_QgsSettings>, data = 0x7fd32ad472e0 <qt_meta_data_QgsSettings>, static_metacall = 0x7fd329ce03e2 <QgsSettings::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, mUserSettings = 0x5581891ea1e0, mGlobalSettings = 0x55818911f760, mUsingGlobalArray = false}
        libPaths = {<QList<QString>> = {<QListSpecialMethods<QString>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, <No data fields>}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x558189336720}, d = 0x558189336720}}, <No data fields>}
        relLibPath = {static null = {<No data fields>}, d = 0x55818935a730}
        customizationsettings = 0x558189340e40
        systemEnvVars = {d = 0x55818929cdf0}
        useCustomVars = false
        desiredStyle = {static null = {<No data fields>}, d = 0x55818804f960 <main::{lambda()#42}::operator()() const::qstring_literal>}
        theme = {static null = {<No data fields>}, d = 0x7fd32bfaf960 <QArrayData::shared_null>}
        activeStyleName = {static null = {<No data fields>}, d = 0x5581896ed5a0}
        mySplashPath = {static null = {<No data fields>}, d = 0x7fd32aea13e0 <QgsApplication::splashPath()::{lambda()#1}::operator()() const::qstring_literal>}
        myPixmap = <incomplete type>
        w = 600
        h = 300
        mypSplash = 0x55818902c070
        qgis = 0x558189c06760
        sigwatch = {<QObject> = {<No data fields>}, static staticMetaObject = {d = {superdata = {direct = 0x7fd32c156100 <QObject::staticMetaObject>}, stringdata = 0x558188090400 <qt_meta_stringdata_UnixSignalWatcher>, data = 0x5581880904c0 <qt_meta_data_UnixSignalWatcher>, static_metacall = 0x55818804aefa <UnixSignalWatcher::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, d_ptr = 0x5581893cabe0}
        retval = -2012675776
[Inferior 1 (process 10674) detached]
gdb returned 0
```

**Comment by nicogodet** [comment]
Same on Win10 OsGeo4w Testing

<details>
  <summary>Report Details</summary>
  
```
Crash ID: e0e72d4bd0fdd328f7b7b584d8bab9ecd4f99ed4


Stack Trace


QGraphicsScene::items :
QgsLayoutLabelWidget::buildInsertDynamicTextMenu :
QgsMapToolRotateLabel::setRotationPreviewBox :
QObject::qt_static_metacall :
QMenu::popup :
QMenu::internalDelayedPopup :
QObject::event :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32Private::sendTimerEvent :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.18.1-Z�rich
QGIS code revision: 202f1bf7e5
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.2.2
Running against GDAL: 3.2.2



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042
```

  
</details>
