### ISSUE TITLE
processing extension error when starting qgis zurich on m1 mac os

### ISSUE THREAD

**Issue by fran2a** [qgis/QGIS#42707]
Here the error message when launching qgis 3.18.1 on a m1 mac  (all is fine with 3.16 version):

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 195: ordinal not in range(128) 
Traceback (most recent call last):
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 335, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing/__init__.py", line 51, in classFactory
    return ProcessingPlugin(iface)
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing/ProcessingPlugin.py", line 168, in __init__
    self.initProcessing()
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing/ProcessingPlugin.py", line 173, in initProcessing
    Processing.initialize()
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing/core/Processing.py", line 134, in initialize
    RenderingStyles.loadStyles()
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing/gui/RenderingStyles.py", line 45, in loadStyles
    line = lines.readline().strip('\n')
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 195: ordinal not in range(128)

**Comment by roya0045** [comment]
Do you have any custom styles that may contain special characters?

**Comment by fran2a** [comment]
The issue appears when launching qgis prior opening any qgis document or style.

**Comment by roya0045** [comment]
The crash occur when styles are being loaded by RenderingStyles.py. This would indicate that one of the style available has non-ascii characters that causes the crash.

**Comment by fran2a** [comment]
Ok but why Long term qgis version (3.16) doesn't crash?

**Comment by roya0045** [comment]
You could try to move the processing folder /Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing/ elsewhere to see if this is the issue. I'm not sure what may be the issue as RenderingStyle itself hasen't changed.

**Comment by fran2a** [comment]
Multiple errors when moving this folder.

**Comment by jctull** [comment]
Did you try deleting (or moving) ~/Library/Application Support/QGIS/QGIS3?

**Comment by fran2a** [comment]
thanks.
Error desappear if I delete "processing_qgis_styles.conf"
