### ISSUE TITLE
GDAL Raster Calculator in the Processing Toolbox producing some incorrect results

### ISSUE THREAD

**Issue by tombrennan06** [qgis/QGIS#42724]
**Describe the bug**
The GDAL Raster Calculator in the Processing Toolbox is producing incorrect results for certain calculations. 

For example, when a raster with data from 1 to 255 has the formula A>128 applied via the GDAL Raster Calculator, you would expect data points greater than 128 to get the value 1 and those less than or equal to 128 to be 0. Instead, the output is much the same as the input, but with values from 1 to 254.

**How to Reproduce**

The input dataset is a simple 100 x 100 gradient raster with values from 255 (left) to 1 (right)
[raster_calc_issue.zip](https://github.com/qgis/QGIS/files/6279092/raster_calc_issue.zip)

1. Open the attached project file
2. In the Processing Toolbox, open the GDAL Raster Calculator tool
3. Select Input Layer A: raster_calc_sample, Calculation: A>128, Output Raster Type: Byte, and then Run
![2021_04_08_22_43_41_Raster_Calculator](https://user-images.githubusercontent.com/2381307/114037083-fa480280-98c3-11eb-9f46-d1dbc104a162.png)

Expected output: a 0/1 raster with the right half 0 and the left half 1
Actual output: a 0-254 raster

**QGIS and OS versions**

QGIS version | 3.18.1-Zürich | QGIS code revision | 202f1bf7e5
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | processing_wbt; qgis_resource_sharing; QuickOSM; db_manager; MetaSearch; processing

**Additional context**

* This was not a problem in QGIS 3.12(.1) or 3.16(.5) - it appears to be new in 3.18(.1)
* I have run this on two separate machines both running QGIS 3.18.1 (and Windows 10), so the issue doesn't appear to be machine-specific
* If I copy the gdal command line that the Processing Toolbox displays, and run it independently of QGIS (in an OSGEO4W shell with Python enabled), the output is as expected (ie no problem) - this is very strange!
* The version of gdal_calc.py appears to be the same between 3.16.5 and 3.18.1
* Other calculations don't necessarily seem to be an issue - for example, A*2 appears to work as expected. However, < or > don't appear to work

**Comment by gioman** [comment]
> Expected output: a 0/1 raster with the right half 0 and the left half 1
> Actual output: a 0-254 raster

@tombrennan06 works fine here on QGIS master/linux

![Screenshot_20210408_160908](https://user-images.githubusercontent.com/1951107/114051173-c5688b00-9884-11eb-95c2-83770d3299b8.png)

**Comment by nicogodet** [comment]
I can confirm the bug on 3.18.1 with "A>128", output format does not matter.
Works fine with greater(A, 128).

Works fine on 3.16.5

Gdal 3.2.2 on OSGeo4W Testing Win10

**Comment by gioman** [comment]
> I can confirm the bug on 3.18.1

@nicogodet can you test master?

**Comment by roya0045** [comment]
@gioman I tried with the mingw artefact, can't get the gdal file to perform, but the native calculator works fine. Were your tests on the gdal variant?

**Comment by gioman** [comment]
@roya0045 yes sure, I used the GDAL raster calc.

**Comment by nicogodet** [comment]
@gioman bug on master too.

**Comment by gioman** [comment]
> @gioman bug on master too.

@nicogodet same correct result for me on 3.18.1 on Windows 10

![Screenshot_20210408_202048](https://user-images.githubusercontent.com/1951107/114084340-fa3a0980-98a7-11eb-8273-9215fa712a83.png)

**Comment by nicogodet** [comment]
I installed 3.18.1 with the new standalone installer (.msi) to compare.

On OSGeo4W : 

```
QGIS version: 3.19.0-Master
QGIS code revision: ca7c033a4
Qt version: 5.15.2
GDAL version: 3.2.2
GEOS version: 3.9.1-CAPI-1.14.2
PROJ version: Rel. 8.0.0, March 1st, 2021
PDAL version: 2.2.0 (git-version: 24dd45)
Processing algorithm…
Algorithm 'Raster calculator' starting…
Input parameters:
{ 'BAND_A' : 1, 'BAND_B' : None, 'BAND_C' : None, 'BAND_D' : None, 'BAND_E' : None, 'BAND_F' : None, 'EXTRA' : '', 'FORMULA' : 'A>128', 'INPUT_A' : 'C:/Users/GODET/AppData/Local/Temp/processing_bbedrI/372c8ab275394b2eae455f6bf51e85a2/OUTPUT.tif', 'INPUT_B' : None, 'INPUT_C' : None, 'INPUT_D' : None, 'INPUT_E' : None, 'INPUT_F' : None, 'NO_DATA' : None, 'OPTIONS' : '', 'OUTPUT' : 'TEMPORARY_OUTPUT', 'RTYPE' : 5 }

GDAL command:
gdal_calc.bat --overwrite --calc "A>128" --format GTiff --type Float32 -A C:/Users/GODET/AppData/Local/Temp/processing_bbedrI/372c8ab275394b2eae455f6bf51e85a2/OUTPUT.tif --A_band 1 --outfile C:/Users/GODET/AppData/Local/Temp/processing_bbedrI/0d0f61c73b8e43d8abc3e5c5c4872d7d/OUTPUT.tif
GDAL command output:
Process completed successfully
Execution completed in 0.68 seconds
Results:
{'OUTPUT': 'C:/Users/GODET/AppData/Local/Temp/processing_bbedrI/0d0f61c73b8e43d8abc3e5c5c4872d7d/OUTPUT.tif'}

Loading resulting layers
Algorithm 'Raster calculator' finished
```
See GDAL command output is empty !

On standalone install:
```
QGIS version: 3.18.1-Zürich
QGIS code revision: 202f1bf7e5
Qt version: 5.15.2
GDAL version: 3.2.2
GEOS version: 3.9.1-CAPI-1.14.2
PROJ version: Rel. 8.0.0, March 1st, 2021
PDAL version: 2.2.0 (git-version: 24dd45)
Processing algorithm…
Algorithm 'Raster calculator' starting…
Input parameters:
{ 'BAND_A' : 1, 'BAND_B' : None, 'BAND_C' : None, 'BAND_D' : None, 'BAND_E' : None, 'BAND_F' : None, 'EXTRA' : '', 'FORMULA' : 'A>128', 'INPUT_A' : 'D:/raster_calc_sample.tif', 'INPUT_B' : None, 'INPUT_C' : None, 'INPUT_D' : None, 'INPUT_E' : None, 'INPUT_F' : None, 'NO_DATA' : None, 'OPTIONS' : '', 'OUTPUT' : 'TEMPORARY_OUTPUT', 'RTYPE' : 5 }

GDAL command:
gdal_calc.bat --calc "A>128" --format GTiff --type Float32 -A D:/raster_calc_sample.tif --A_band 1 --outfile C:/Users/GODET/AppData/Local/Temp/processing_IOytHx/2d2464a2133c4634b852133238777765/OUTPUT.tif
GDAL command output:
Traceback (most recent call last):
File "C:/PROGRA~1/QGIS31~1.1/apps/qgis/./python/plugins\processing\algs\gdal\GdalUtils.py", line 130, in on_stderr
val = ba.data().decode('UTF-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8a in position 3: invalid start byte

The above exception was the direct cause of the following exception:

SystemError: <class 'PyQt5.QtCore.QByteArray'> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <class 'PyQt5.QtCore.QByteArray'> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "C:/PROGRA~1/QGIS31~1.1/apps/qgis/./python/plugins\processing\algs\gdal\GdalAlgorithm.py", line 135, in processAlgorithm
GdalUtils.runGdal(commands, feedback)
File "C:/PROGRA~1/QGIS31~1.1/apps/qgis/./python/plugins\processing\algs\gdal\GdalUtils.py", line 146, in runGdal
res = proc.run(feedback)
SystemError: <built-in method run of QgsBlockingProcess object at 0x0000022FC1E7E160> returned a result with an error set

Execution failed after 0.08 seconds

Loading resulting layers
Algorithm 'Raster calculator' finished
```

With greater(A, 128) on both install:
```
QGIS version: 3.19.0-Master
QGIS code revision: ca7c033a4
Qt version: 5.15.2
GDAL version: 3.2.2
GEOS version: 3.9.1-CAPI-1.14.2
PROJ version: Rel. 8.0.0, March 1st, 2021
PDAL version: 2.2.0 (git-version: 24dd45)
Processing algorithm…
Algorithm 'Raster calculator' starting…
Input parameters:
{ 'BAND_A' : 1, 'BAND_B' : None, 'BAND_C' : None, 'BAND_D' : None, 'BAND_E' : None, 'BAND_F' : None, 'EXTRA' : '', 'FORMULA' : 'greater(A,128)', 'INPUT_A' : 'C:/Users/GODET/AppData/Local/Temp/processing_bbedrI/372c8ab275394b2eae455f6bf51e85a2/OUTPUT.tif', 'INPUT_B' : None, 'INPUT_C' : None, 'INPUT_D' : None, 'INPUT_E' : None, 'INPUT_F' : None, 'NO_DATA' : None, 'OPTIONS' : '', 'OUTPUT' : 'TEMPORARY_OUTPUT', 'RTYPE' : 5 }

GDAL command:
gdal_calc.bat --overwrite --calc "greater(A,128)" --format GTiff --type Float32 -A C:/Users/GODET/AppData/Local/Temp/processing_bbedrI/372c8ab275394b2eae455f6bf51e85a2/OUTPUT.tif --A_band 1 --outfile C:/Users/GODET/AppData/Local/Temp/processing_bbedrI/504796b75b60402cbba14d68b3352bb7/OUTPUT.tif
GDAL command output:
0.. 20.. 40.. 60.. 80.. 100 - Done
Process completed successfully
Execution completed in 0.58 seconds
Results:
{'OUTPUT': 'C:/Users/GODET/AppData/Local/Temp/processing_bbedrI/504796b75b60402cbba14d68b3352bb7/OUTPUT.tif'}

Loading resulting layers
Algorithm 'Raster calculator' finished
```

If I print the value of `ba` and `ba.decode()`
```
b'Acc\x8as refus\x82.\r\n'
b'Acc\x8as refus\x82.\r\n'
```
Locale issue

ping @nyalldawson as you implemented this in https://github.com/qgis/QGIS/pull/40897

**Comment by nicogodet** [comment]
https://github.com/qgis/QGIS/blob/3ee49a60a382b7fc8e97e5cf7796620efb950ef6/python/plugins/processing/algs/gdal/GdalUtils.py#L141
It seems to break the command.
Output is:
`['gdal_calc.bat', '--overwrite', '--calc', 'A>128', '--format', 'GTiff', '--type', 'Float32', '-A', 'D:/raster_calc_sample.tif', '--A_band', '1', '--outfile', 'C:/Users/GODET/AppData/Local/Temp/processing_hZjELV/1c1ad78c8ada42848f48772fbb57310f/OUTPUT.tif']`

If I run `gdal_calc.bat --overwrite --calc A>128 --format GTiff --type Float32 -A D:/raster_calc_sample.tif --A_band 1 --outfile D:/raster_calc_sample_truc.tif` in a shell, 
It fails and it results in a file named `128`

```
C:\OSGeo4W64_new>.\apps\Python39\Scripts\gdal_calc.bat --overwrite --calc A>128 --format GTiff --type Float32 -A D:/raster_calc_sample.tif --A_band 1 --outfile D:/raster_calc_sample_truc.tif

C:\OSGeo4W64_new>dir
 Le volume dans le lecteur C s’appelle OS
 Le numéro de série du volume est CABC-B79C

 Répertoire de C:\OSGeo4W64_new

04/09/2021  09:03 AM    <DIR>          .
04/09/2021  09:03 AM    <DIR>          ..
04/09/2021  09:03 AM                36 128
04/08/2021  05:35 PM    <DIR>          apps
04/08/2021  05:43 PM    <DIR>          bin
03/12/2021  05:32 PM    <DIR>          doc
04/08/2021  05:33 PM    <DIR>          etc
03/12/2021  05:32 PM    <DIR>          lib
02/18/2021  02:33 PM               321 OSGeo4W.bat
10/09/2020  11:59 PM             5,430 OSGeo4W.ico
04/08/2021  05:33 PM    <DIR>          share
03/12/2021  05:37 PM    <DIR>          var
               3 fichier(s)            5,787 octets
               9 Rép(s)  80,020,582,400 octets libres

C:\OSGeo4W64_new>
```

**Comment by gioman** [comment]
> I installed 3.18.1 with the new standalone installer (.msi) to compare.

@nicogodet so if you use the official Windows installer (the ones linked on QGIS's we site) no issue?

**Comment by nicogodet** [comment]
@jef-n The unquoted `A>128` is the output of https://github.com/qgis/QGIS/blob/3ee49a60a382b7fc8e97e5cf7796620efb950ef6/python/plugins/processing/algs/gdal/GdalUtils.py#L141

@gioman Same issue on Official Windows installer
But the refused access is caused by the console trying to create 128 in a folder that require an admin right.

**Comment by gioman** [comment]
> @gioman Same issue on Official Windows installer

@nicogodet so it not clear to me why I can't replicate on my machine.

**Comment by jef-n** [comment]
> gdal_calc.bat --calc "A>128" --format GTiff --type Float32 -A D:\raster_calc_sample.tif --A_band 1 --outfile C:/Users/GODET/AppData/Local/Temp/processing_VZTszq/016ad59a3ab2455da63429d6ef3f23ac/OUTPUT.tif

That output has the quotes.   But I was referring to what you entered into the shell and that was missing the quotes.    Running that with quotes might show what in the output might causes the hickup.

**Comment by nicogodet** [comment]
@jef-n Look at the output of `QgsRunProcess.splitCommand(fused_command)` and you will see that quotes are missing in the list of arguments.
This list of arguments is then throw in
https://github.com/qgis/QGIS/blob/3ee49a60a382b7fc8e97e5cf7796620efb950ef6/python/plugins/processing/algs/gdal/GdalUtils.py#L142

**Comment by jef-n** [comment]
> @jef-n Look at the output of `QgsRunProcess.splitCommand(fused_command)` and you will see that quotes are missing in the list of arguments.

I'm not sure what your point is.   I commented on what you ran manually.  I'm interested in it's output, but with the quotes.  AFAICT the command is run fine, but the "old" standalone can't parse it's output, while the "new" one can.

**Comment by nicogodet** [comment]
The output with quotes is not the actual command executed.

Of course if I execute manually the command with quotes everything runs correctly.

But.
The command with quotes is sent to QgsRunProcess.splitCommand() then QgsBlockingProcess().
The problem is that splitCommand() removes quotes.
That's the purpose of my previous comments.

**Comment by jef-n** [comment]
> Of course if I execute manually the command with quotes everything runs correctly.

And it outputs?

**Comment by nicogodet** [comment]
Outputs are corrects.

**Comment by nicogodet** [comment]
If I run avec `A > 128` output is correct
```
QGIS version: 3.18.1-Zürich
QGIS code revision: 202f1bf7e5
Qt version: 5.15.2
GDAL version: 3.2.2
GEOS version: 3.9.1-CAPI-1.14.2
PROJ version: Rel. 8.0.0, March 1st, 2021
PDAL version: 2.2.0 (git-version: 24dd45)
Processing algorithm…
Algorithm 'Raster calculator' starting…
Input parameters:
{ 'BAND_A' : 1, 'BAND_B' : None, 'BAND_C' : None, 'BAND_D' : None, 'BAND_E' : None, 'BAND_F' : None, 'EXTRA' : '', 'FORMULA' : 'A > 128', 'INPUT_A' : 'D:/raster_calc_sample.tif', 'INPUT_B' : None, 'INPUT_C' : None, 'INPUT_D' : None, 'INPUT_E' : None, 'INPUT_F' : None, 'NO_DATA' : None, 'OPTIONS' : '', 'OUTPUT' : 'TEMPORARY_OUTPUT', 'RTYPE' : 5 }

GDAL command:
gdal_calc.bat --calc "A > 128" --format GTiff --type Float32 -A D:\raster_calc_sample.tif --A_band 1 --outfile C:/Users/GODET/AppData/Local/Temp/processing_EuzHpE/3f8ccc7a6c2d41708226f60791fd86fc/OUTPUT.tif
GDAL command output:
0.. 20.. 40.. 60.. 80.. 100 - Done
Process completed successfully
Execution completed in 1.21 seconds
Results:
{'OUTPUT': 'C:/Users/GODET/AppData/Local/Temp/processing_EuzHpE/3f8ccc7a6c2d41708226f60791fd86fc/OUTPUT.tif'}

Loading resulting layers
Algorithm 'Raster calculator' finished
```

`A>128` incorrect

**Comment by nicogodet** [comment]
@tombrennan06 could you test with `A > 128` (space around `>`) instead of `A>128` ?

**Comment by gioman** [comment]
> @tombrennan06 could you test with `A > 128` (space around `>`) instead of `A>128` ?

@nicogodet for what is worth... correct results on 3.18.1 on both Ubuntu and Windows (using the official installer).

**Comment by nicogodet** [comment]
@gioman Even without spaces around `>`

**Comment by gioman** [comment]
> @gioman Even without spaces around `>` ?

@nicogodet yes.

**Comment by gioman** [comment]
> `A>128` incorrect

@nicogodet why you say that the image is incorrect: if you change the project background to something different from white you'll se that the left part of the output is white (1) and the right part is black (0).

**Comment by nicogodet** [comment]
@gioman No. With `A>128` without spaces the command executed is `gdal_calc.bat --overwrite --calc A>128 --format GTiff --type Float32 -A D:/raster_calc_sample.tif --A_band 1 --outfile D:/raster_calc_sample_truc.tif` so in a shell, `gdal_calc.bat --overwrite --calc A` redirected to `128`.

![image](https://user-images.githubusercontent.com/39594821/114199015-375bd580-9954-11eb-9bf6-4d21b51b987b.png)



I can not give more info, it's out of my competences...
But I think all my previous messages show where is the error (https://github.com/qgis/QGIS/issues/42724#issuecomment-816524879) but I can not explain why the output is correct when you run `A>128`...

**Comment by tombrennan06** [comment]
@nicogodet - same result as you. 

With A>128 (no spaces), I get the same error as I originally described.

With A > 128 (spaces), I get the expected (correct) output (half white/half black).

FWIW, I am using the official installer for 3.18.1

**Comment by nicogodet** [comment]
@gioman I think feedback label could be removed.

**Comment by gioman** [comment]
> @gioman I think feedback label could be removed.

@nicogodet done. It does not affect QGIS on Linux.

**Comment by nicogodet** [comment]
@gioman Indeed, it could be a Windows issue linked to QProcess and its Windows specificities regarding command arguments.

> Windows: The arguments are quoted and joined into a command line that is compatible with the CommandLineToArgvW() Windows function. For programs that have different command line quoting requirements, you need to use setNativeArguments(). One notable program that does not follow the CommandLineToArgvW() rules is cmd.exe and, by consequence, all batch scripts.

https://doc.qt.io/qt-5/qprocess.html#start

**Comment by jfbourdon** [comment]
A couple years later, I don't know if this issue still fully exists as using either `A>1` or `greater(A,1)` yield the same valid result for me (Windows 11, QGIS 3.40.1 from OSGeo4W) but one minor linked issue remains. In this comment from @nicogodet (https://github.com/qgis/QGIS/issues/42724#issuecomment-816450609), he says that on a OSGeo4W install, the GDAL command output is empty in the processing log. Well... I found that it goes to a file in `%OSGEO4W_ROOT%\bin\`. If the equation is `A>1`, it will create a file named `1`at that location and containing `0...10...20...30...40...50...60...70...80...90...100 - done.`

**Comment by agiudiceandrea** [comment]
I can confirm the issue on Windows 10 using QGIS 3.40.3 (OSGeo4W). The issue occurs if there is no space in expressions in which the "greater than" char `>` is present, like `A>100`, while the issue doesn't occur if there is at least a space between the "greater than" char `>` and one of the operands, like `A >100` or `A> 100` or `A > 100`.

In both the "GDAL/OGR console call" and the processing log, the expression is displayed enclosed in double quotes, resulting in a command displayed like: `gdal_calc.bat --overwrite --calc "A>100" --format GTiff --type Byte -A C:/Users/Andrea/Downloads/DEM.tif --A_band 1 --outfile OUTPUT.tif`.

The same command executed in the OSGeo4W Shell gives the correct results.

**Comment by agiudiceandrea** [comment]
@nicogodet, I think I've found a possible fix https://github.com/agiudiceandrea/QGIS/pull/247, but I cannot actually test it 'cause the MinGW64 build doesn't ship the gdal_*.bat files and I'm not sure it will break other algorithms, since the change will affect all the GDAL algorithms and the PDAL ones on Windows (anyway the tests pass).

**Comment by nicogodet** [comment]
@agiudiceandrea what about make sure to enclose arguments containing `>` or `<` with `"` after `splitCommand` on win os ?

**Comment by agiudiceandrea** [comment]
> what about make sure to enclose arguments containing `>` or `<` with `"` after `splitCommand` on win os ?

While the following one works:
```Python
p.start("gdal_calc.bat", ['--overwrite', '--calc', '"A>100"', '--format', 'GTiff', '--type', 'Byte', '-A', 'C:/test/DEM.tif', '--A_band', '1', '--co', 'ZLEVEL=9', '--outfile', 'C:/test/OUTPUT.tif'])
```
neither one of the following works;
```Python
p.start("gdal_calc.bat", ['--overwrite', '--calc', '"A >100"', '--format', 'GTiff', '--type', 'Byte', '-A', 'C:/test/DEM.tif', '--A_band', '1', '--co', 'ZLEVEL=9', '--outfile', 'C:/test/OUTPUT.tif'])
p.start("gdal_calc.bat", ['--overwrite', '--calc', '"A> 100"', '--format', 'GTiff', '--type', 'Byte', '-A', 'C:/test/DEM.tif', '--A_band', '1', '--co', 'ZLEVEL=9', '--outfile', 'C:/test/OUTPUT.tif'])
```

Moreover, according to https://doc.qt.io/qt-5/qprocess.html#start:

> Windows: The arguments are quoted and joined into a command line that is compatible with the CommandLineToArgvW() Windows function. For programs that have different command line quoting requirements, you need to use setNativeArguments(). One notable program that does not follow the CommandLineToArgvW() rules is cmd.exe and, by consequence, all batch scripts.

and https://doc.qt.io/qt-6/qprocess.html#details:

> QProcess does not support directly executing Unix shell or Windows command interpreter built-in functions, such as cmd.exe's dir command or the Bourne shell's export. On Unix, even though many shell built-ins are also provided as separate executables, their behavior may differ from those implemented as built-ins. To run those commands, one should explicitly execute the interpreter with suitable options. For Unix systems, launch "/bin/sh" with two arguments: "-c" and a string with the command-line to be run. For Windows, due to the non-standard way cmd.exe parses its command-line, use [setNativeArguments](https://doc.qt.io/qt-6/qprocess.html#setNativeArguments)() (for example, "/c dir d:").

**Comment by tombrennan06** [comment]
I am guessing it's the same issue, or closely related. With > or < in brackets eg (A<B)*2, I get an error rather than an incorrect result:

```
gdal_calc.bat --overwrite --calc "(A<B)*2" --format GTiff --type Float32 -A E:/geodata/_data/nsw100k/55/8728_gunning/Crookwell201411-PHO3-AHD_6866180_55_0002_0002_5m.tif --A_band 1 -B C:/Users/brennant/AppData/Local/Temp/processing_ycYNBM/af997b114b344b8cb5c39a75258b6cf0/OUTPUT.tif --B_band 1 --outfile C:/Users/brennant/AppData/Local/Temp/processing_ycYNBM/c32cdc5cbbcb4a51b13e61efbda421de/OUTPUT.tif
GDAL command output:
The filename, directory name, or volume label syntax is incorrect.
Process returned error code 1
```

This is with 3.40.15 on Windows, standalone installer.
