### ISSUE TITLE
Phyton failure at start

### ISSUE THREAD

**Issue by Auguste71** [qgis/QGIS#43095]
I just updated my qGIS-Version. Still i recieve at start the following message:

2021-05-06T09:41:48     WARNING    Traceback (most recent call last):
              File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins\processing\script\ScriptAlgorithmProvider.py", line 121, in loadAlgorithms
              alg = ScriptUtils.loadAlgorithm(moduleName, filePath)
              File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins\processing\script\ScriptUtils.py", line 66, in loadAlgorithm
              spec.loader.exec_module(module)
              File "", line 728, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "C:\Users\augus\AppData\Roaming\QGIS\QGIS3\profiles\default\processing\scripts\QGISCacheWebServicesTool.py", line 33, in 
              ServiceXML = ServiceDescriptionXMLList[Service_Description_XML]
             NameError: name 'Service_Description_XML' is not defined

As I am a simple user, i do not understand what I have to do! Thanks for helping.

**Comment by Gustry** [comment]
> C:\Users\augus\AppData\Roaming\QGIS\QGIS3\profiles\default\processing\scripts\QGISCacheWebServicesTool.py

Your problem is coming from a third party script.
You should remove it or fix it.
There is nothing that QGIS can do.
