### ISSUE TITLE
Core Processing plugin Python Error similar to #29535

### ISSUE THREAD

**Issue by Growflavor** [qgis/QGIS#43292]
I am encountering an issue similar to #29535.

Operating environment is current Windows 10 pro 2020H2

I have tried deleting QGIS folders in Appdata Local & Roaming & completed repeated un-installs & re-installs of both 3.16 & 3.18 via both standalone installer as well as OSgeoW4 network installer.  In all cases I get the same trouble with loading the "Processing" plugin, here is a screenshot when using the standalone installer, python paths change as expected when using the OSgeoW4 installer:

[ProcessingPlugin](https://user-images.githubusercontent.com/1580559/118926680-043c3700-b941-11eb-9dbb-bddcee3b5137.PNG)

The errors do not show if I uncheck "Processing" plugin, close & reopen QGIS.  The error windows open immediately when I re-check the built-in "Processing" plugin:

<details>
  <summary>(error messages pasted in drop down) I get the following two error messages when loading built-in Processing plugin: FileNotFoundError: [Errno 2] No such file or directory: 'nul' </summary>
  
`An error has occurred while executing Python code: 

FileNotFoundError: [Errno 2] No such file or directory: 'nul' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins\processing\algs\saga\SagaAlgorithmProvider.py", line 96, in loadAlgorithms
    version = SagaUtils.getInstalledVersion(True)
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins\processing\algs\saga\SagaUtils.py", line 140, in getInstalledVersion
    universal_newlines=True,
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\subprocess.py", line 709, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\subprocess.py", line 1015, in _get_handles
    p2cread = msvcrt.get_osfhandle(self._get_devnull())
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\subprocess.py", line 848, in _get_devnull
    self._devnull = os.open(os.devnull, os.O_RDWR)
FileNotFoundError: [Errno 2] No such file or directory: 'nul'

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.16.7-Hannover Hannover, 0471743889 

Python Path:
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python
C:/Users/Sys/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Sys/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3~1.16\apps\Python37
C:\PROGRA~1\QGIS3~1.16\apps\Python37\Scripts
C:\Program Files\QGIS 3.16\bin\python37.zip
C:\PROGRA~1\QGIS3~1.16\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib
C:\Program Files\QGIS 3.16\bin
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\Pythonwin
C:/Users/Sys/AppData/Roaming/QGIS/QGIS3\profiles\default/python`

`An error has occurred while executing Python code: 

FileNotFoundError: [Errno 2] No such file or directory: 'nul' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins\processing\algs\grass7\Grass7AlgorithmProvider.py", line 124, in loadAlgorithms
    version = Grass7Utils.installedVersion(True)
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins\processing\algs\grass7\Grass7Utils.py", line 123, in installedVersion
    startupinfo=si if isWindows() else None
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\subprocess.py", line 709, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\subprocess.py", line 1015, in _get_handles
    p2cread = msvcrt.get_osfhandle(self._get_devnull())
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\subprocess.py", line 848, in _get_devnull
    self._devnull = os.open(os.devnull, os.O_RDWR)
FileNotFoundError: [Errno 2] No such file or directory: 'nul'

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.16.7-Hannover Hannover, 0471743889 

Python Path:
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python
C:/Users/Sys/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Sys/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3~1.16\apps\Python37
C:\PROGRA~1\QGIS3~1.16\apps\Python37\Scripts
C:\Program Files\QGIS 3.16\bin\python37.zip
C:\PROGRA~1\QGIS3~1.16\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib
C:\Program Files\QGIS 3.16\bin
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\Pythonwin
C:/Users/Sys/AppData/Roaming/QGIS/QGIS3\profiles\default/python`

</details>

![ProcPlug](https://user-images.githubusercontent.com/1580559/118927752-8a0cb200-b942-11eb-8f23-686e64d49bf8.PNG)

<details>
  <summary>**QGIS and OS versions** pasted in drop down</summary>
  
`
QGIS version
3.16.7-Hannover
QGIS code revision
0471743889
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
db_manager; 
MetaSearch; 
processing
` 
</details>

**Additional context**

possibly coincidental: issue may have appeared after removing a QGIS 3.8 version installed via OSgeoW4 that had been installed in the past, forgotten thus left in place despite using stand alone installers to install seperately QGIS 3.10 and higher the past several years...are there residual settings files outside of AppData or registry keys?

Recommendations on what to check or try next are very much welcome.  Thank you.

**Comment by Growflavor** [comment]
Appears to be resolved by running the following commands in an administrator Command Prompt & restarting the computer:
 
sc config Null start= system
sc start Null

reference: http://revertservice.com/10/null/
