### ISSUE TITLE
Unable to use pyproj and owslib within QGIS: KeyError: 'URN:OGC:DEF:DATUM:EPSG::6326' with PROJ7

### ISSUE THREAD

**Issue by Guts** [qgis/QGIS#43760]
**Describe the bug**

Importing pyproj is raising a big trace error and making it unusable.

**How to Reproduce**

1. Launch QGIS: `qgis --profile /tmp/ows-pyproj-exception --lang en`
1. Open Python console
2. enter `from owslib.wfs import WebFeatureService`or `import pyproj`

Trace:

Fist I've got this message:

```bash
pyproj.exceptions.CRSError: Invalid datum string: urn:ogc:def:datum:EPSG::6326: (Internal Proj Error: proj_create: SQLite error on SELECT name, ellipsoid_auth_name, ellipsoid_code, prime_meridian_auth_name, prime_meridian_code, area_of_use_auth_name, area_of_use_code, publication_date, deprecated FROM geodetic_datum WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name) 
```
Then, after a bit of investigation:

```python
>>> from owslib.wfs import WebFeatureService
Traceback (most recent call last):
  File "pyproj/_crs.pyx", line 1545, in pyproj._crs.Datum.from_name
KeyError: 'URN:OGC:DEF:DATUM:EPSG::6326'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pyproj/_crs.pyx", line 1451, in pyproj._crs.Datum.from_string
  File "pyproj/_crs.pyx", line 1547, in pyproj._crs.Datum.from_name
pyproj.exceptions.CRSError: Invalid datum name: urn:ogc:def:datum:EPSG::6326

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3/dist-packages/owslib/wfs.py", line 16, in <module>
    from .feature import wfs100, wfs110, wfs200
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3/dist-packages/owslib/feature/wfs100.py", line 33, in <module>
    import pyproj
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3/dist-packages/pyproj/__init__.py", line 81, in <module>
    from pyproj.crs import CRS  # noqa: F401
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3/dist-packages/pyproj/crs/__init__.py", line 19, in <module>
    from pyproj.crs.crs import (  # noqa: F401
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3/dist-packages/pyproj/crs/crs.py", line 1028, in <module>
    class ProjectedCRS(CRS):
  File "/usr/lib/python3/dist-packages/pyproj/crs/crs.py", line 1040, in ProjectedCRS
    geodetic_crs=GeographicCRS(),
  File "/usr/lib/python3/dist-packages/pyproj/crs/crs.py", line 979, in __init__
    "datum": Datum.from_user_input(datum).to_json_dict(),
  File "pyproj/_crs.pyx", line 553, in pyproj._crs._CRSParts.from_user_input
  File "pyproj/_crs.pyx", line 1453, in pyproj._crs.Datum.from_string
  File "pyproj/_crs.pyx", line 1448, in pyproj._crs.Datum.from_string
  File "pyproj/_crs.pyx", line 1417, in pyproj._crs.Datum._from_string
pyproj.exceptions.CRSError: Invalid datum string: urn:ogc:def:datum:EPSG::6326: (Internal Proj Error: proj_create: SQLite error on SELECT name, ellipsoid_auth_name, ellipsoid_code, prime_meridian_auth_name, prime_meridian_code, area_of_use_auth_name, area_of_use_code, publication_date, deprecated FROM geodetic_datum WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name)
```

Since the issue is reproductible using pyproj at the system level, it seems to be a packaging error:

```bash
$ python3
Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyproj
Traceback (most recent call last):
  File "pyproj/_crs.pyx", line 1545, in pyproj._crs.Datum.from_name
KeyError: 'URN:OGC:DEF:DATUM:EPSG::6326'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pyproj/_crs.pyx", line 1451, in pyproj._crs.Datum.from_string
  File "pyproj/_crs.pyx", line 1547, in pyproj._crs.Datum.from_name
pyproj.exceptions.CRSError: Invalid datum name: urn:ogc:def:datum:EPSG::6326

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/pyproj/__init__.py", line 81, in <module>
    from pyproj.crs import CRS  # noqa: F401
  File "/usr/lib/python3/dist-packages/pyproj/crs/__init__.py", line 19, in <module>
    from pyproj.crs.crs import (  # noqa: F401
  File "/usr/lib/python3/dist-packages/pyproj/crs/crs.py", line 1028, in <module>
    class ProjectedCRS(CRS):
  File "/usr/lib/python3/dist-packages/pyproj/crs/crs.py", line 1040, in ProjectedCRS
    geodetic_crs=GeographicCRS(),
  File "/usr/lib/python3/dist-packages/pyproj/crs/crs.py", line 979, in __init__
    "datum": Datum.from_user_input(datum).to_json_dict(),
  File "pyproj/_crs.pyx", line 553, in pyproj._crs._CRSParts.from_user_input
  File "pyproj/_crs.pyx", line 1453, in pyproj._crs.Datum.from_string
  File "pyproj/_crs.pyx", line 1448, in pyproj._crs.Datum.from_string
  File "pyproj/_crs.pyx", line 1417, in pyproj._crs.Datum._from_string
```

Just displaying the proj version also returns an error:

```bash
$ proj --version
Rel. 6.3.1, February 10th, 2020
<proj>: 
invalid option: --
program abnormally terminated
```

**QGIS and OS versions**

QGIS version | 3.16.7-Hannover | QGIS code revision | 0471743889
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.9.0-CAPI-1.16.2
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.6 (Ubuntu 12.6-0ubuntu0.20.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Ubuntu 20.04.2 LTS
Active python plugins | db_manager; MetaSearch; processing

**Comment by Guts** [comment]
Fixed upgrading @pyproj4 on system. Pyproj was in version 2.5.0...
Weird, I though it was installed with QGIS.

Sorry for the noise.

**Comment by Guts** [comment]
I reopen here because I still reproduce the problem on a fresh install of QGIS from LTR packages (https://qgis.org/ubuntu-ltr) so it seems to be a packaging issue.

**Comment by Guts** [comment]
And maybe it's related, maybe not but everytime I launch QGIS I've got this message:

```bash
proj_create_from_database: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name
proj_create_from_database: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name
```

**Comment by Guts** [comment]
> Fixed upgrading @pyproj4 on system. Pyproj was in version 2.5.0...

I though it was a good idea but after that, QGIS is crashing with a cryptic message: `std::bad_alloc`.
So I preferred to stay on my first error which allows me to still use QGIS.

**Comment by gioman** [comment]
> enter `from owslib.wfs import WebFeatureService`or `import pyproj`

@Guts no errors here, QGIS master on Ubuntu 20.04

**Comment by gioman** [comment]
> ```shell
> $ proj --version
> Rel. 6.3.1, February 10th, 2020
> <proj>: 
> invalid option: --
> program abnormally terminated
> ```

Maybe because that option simply do not exist? see "man proj"

**Comment by Guts** [comment]
> > ```shell
> > $ proj --version
> > Rel. 6.3.1, February 10th, 2020
> > <proj>: 
> > invalid option: --
> > program abnormally terminated
> > ```
> 
> Maybe because that option simply do not exist? see "man proj"

You're damn right. Just `proj` works.

**Comment by Guts** [comment]
> > enter `from owslib.wfs import WebFeatureService`or `import pyproj`
> 
> @Guts no errors here, QGIS master on Ubuntu 20.04

QGIS compiled or installed from packages?

**Comment by gioman** [comment]
> QGIS compiled or installed from packages?

@Guts from packages.

**Comment by Guts** [comment]
> @Guts from packages.

🤔 OK, so how can I digg deeper to find wh it's failing on my side?

**Comment by Guts** [comment]
@gioman any idea on how to continue the diagnosis?

**Comment by gioman** [comment]
> @gioman any idea on how to continue the diagnosis?

@Guts have you tried on a different machine?

**Comment by Guts** [comment]
> @Guts have you tried on a different machine?

No. But sometimes I've got this error message:

```log
Pas de transformation disponible entre EPSG:4326 - WGS 84et EPSG:3857 - WGS 84 / Pseudo-Mercator.
proj_create_operations: SQLite error on SELECT name, coordinate_system_auth_name, coordinate_system_code, geodetic_crs_auth_name, geodetic_crs_code, conversion_auth_name, conversion_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM projected_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name
```

![image](https://user-images.githubusercontent.com/1596222/127298889-8656ca43-47dd-4d80-8333-71e9e204febc.png)

**Comment by Guts** [comment]
Running `projinfo -s EPSG:3059 -t EPSG:4326` I reproduce the error:

```bash
:~$ projinfo -s EPSG:3059 -t EPSG:4326
source CRS: parsing of user string failed: SQLite error on SELECT name, coordinate_system_auth_name, coordinate_system_code, geodetic_crs_auth_name, geodetic_crs_code, conversion_auth_name, conversion_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM projected_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name
```

**Comment by gioman** [comment]
> Running `projinfo -s EPSG:3059 -t EPSG:4326` I reproduce the error:

@Guts so seems an upstream issue.

**Comment by Guts** [comment]
> > Running `projinfo -s EPSG:3059 -t EPSG:4326` I reproduce the error:
> 
> @Guts so seems an upstream issue.

Or for packagers because I'm using the official qgis/ubuntu--ltr ppa?

**Comment by Guts** [comment]
Fixed forcing install of proj<7:

```bash
$ sudo apt install "proj-data=6*"
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
Version choisie « 6.3.1-1 » (Ubuntu:20.04/focal [all]) pour « proj-data »
Les paquets suivants seront mis à une VERSION INFÉRIEURE :
  proj-data
0 mis à jour, 0 nouvellement installés, 1 remis à une version inférieure, 0 à enlever et 5 non mis à jour.
Il est nécessaire de prendre 7 647 ko dans les archives.
Après cette opération, 2 792 ko d'espace disque seront libérés.
Souhaitez-vous continuer ? [O/n] O
Réception de :1 http://fr.archive.ubuntu.com/ubuntu focal/universe amd64 proj-data all 6.3.1-1 [7 647 kB]
7 647 ko réceptionnés en 1s (13,4 Mo/s)
dpkg: avertissement: dégradation (« downgrade ») de proj-data depuis 7.2.1-1~focal0 vers 6.3.1-1
(Lecture de la base de données... 426211 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de .../proj-data_6.3.1-1_all.deb ...
Dépaquetage de proj-data (6.3.1-1) sur (7.2.1-1~focal0) ...
Paramétrage de proj-data (6.3.1-1) ...
$ projinfo -s EPSG:3059 -t EPSG:4326
Candidate operations found: 1
-------------------------------------
Operation No. 1:

unknown id, Inverse of Latvian Transverse Mercator + LKS92 to WGS 84 (1), 1 m, Latvia

PROJ string:
+proj=pipeline +step +proj=axisswap +order=2,1 +step +inv +proj=tmerc +lat_0=0 +lon_0=24 +k=0.9996 +x_0=500000 +y_0=-6000000 +ellps=GRS80 +step +proj=unitconvert +xy_in=rad +xy_out=deg +step +proj=axisswap +order=2,1

WKT2:2019 string:
CONCATENATEDOPERATION["Inverse of Latvian Transverse Mercator + LKS92 to WGS 84 (1)",
    SOURCECRS[
        PROJCRS["LKS92 / Latvia TM",
            BASEGEOGCRS["LKS92",
                DATUM["Latvia 1992",
                    ELLIPSOID["GRS 1980",6378137,298.257222101,
                        LENGTHUNIT["metre",1]]],
                PRIMEM["Greenwich",0,
                    ANGLEUNIT["degree",0.0174532925199433]],
                ID["EPSG",4661]],
            CONVERSION["Latvian Transverse Mercator",
                METHOD["Transverse Mercator",
                    ID["EPSG",9807]],
                PARAMETER["Latitude of natural origin",0,
                    ANGLEUNIT["degree",0.0174532925199433],
                    ID["EPSG",8801]],
                PARAMETER["Longitude of natural origin",24,
                    ANGLEUNIT["degree",0.0174532925199433],
                    ID["EPSG",8802]],
                PARAMETER["Scale factor at natural origin",0.9996,
                    SCALEUNIT["unity",1],
                    ID["EPSG",8805]],
                PARAMETER["False easting",500000,
                    LENGTHUNIT["metre",1],
                    ID["EPSG",8806]],
                PARAMETER["False northing",-6000000,
                    LENGTHUNIT["metre",1],
                    ID["EPSG",8807]]],
            CS[Cartesian,2],
                AXIS["northing (X)",north,
                    ORDER[1],
                    LENGTHUNIT["metre",1]],
                AXIS["easting (Y)",east,
                    ORDER[2],
                    LENGTHUNIT["metre",1]],
            ID["EPSG",3059]]],
    TARGETCRS[
        GEOGCRS["WGS 84",
            DATUM["World Geodetic System 1984",
                ELLIPSOID["WGS 84",6378137,298.257223563,
                    LENGTHUNIT["metre",1]]],
            PRIMEM["Greenwich",0,
                ANGLEUNIT["degree",0.0174532925199433]],
            CS[ellipsoidal,2],
                AXIS["geodetic latitude (Lat)",north,
                    ORDER[1],
                    ANGLEUNIT["degree",0.0174532925199433]],
                AXIS["geodetic longitude (Lon)",east,
                    ORDER[2],
                    ANGLEUNIT["degree",0.0174532925199433]],
            ID["EPSG",4326]]],
    STEP[
        CONVERSION["Inverse of Latvian Transverse Mercator",
            METHOD["Inverse of Transverse Mercator",
                ID["INVERSE(EPSG)",9807]],
            PARAMETER["Latitude of natural origin",0,
                ANGLEUNIT["degree",0.0174532925199433],
                ID["EPSG",8801]],
            PARAMETER["Longitude of natural origin",24,
                ANGLEUNIT["degree",0.0174532925199433],
                ID["EPSG",8802]],
            PARAMETER["Scale factor at natural origin",0.9996,
                SCALEUNIT["unity",1],
                ID["EPSG",8805]],
            PARAMETER["False easting",500000,
                LENGTHUNIT["metre",1],
                ID["EPSG",8806]],
            PARAMETER["False northing",-6000000,
                LENGTHUNIT["metre",1],
                ID["EPSG",8807]],
            ID["INVERSE(EPSG)",19990]]],
    STEP[
        COORDINATEOPERATION["LKS92 to WGS 84 (1)",
            VERSION["Vzd-Lva"],
            SOURCECRS[
                GEOGCRS["LKS92",
                    DATUM["Latvia 1992",
                        ELLIPSOID["GRS 1980",6378137,298.257222101,
                            LENGTHUNIT["metre",1]]],
                    PRIMEM["Greenwich",0,
                        ANGLEUNIT["degree",0.0174532925199433]],
                    CS[ellipsoidal,2],
                        AXIS["geodetic latitude (Lat)",north,
                            ORDER[1],
                            ANGLEUNIT["degree",0.0174532925199433]],
                        AXIS["geodetic longitude (Lon)",east,
                            ORDER[2],
                            ANGLEUNIT["degree",0.0174532925199433]],
                    ID["EPSG",4661]]],
            TARGETCRS[
                GEOGCRS["WGS 84",
                    DATUM["World Geodetic System 1984",
                        ELLIPSOID["WGS 84",6378137,298.257223563,
                            LENGTHUNIT["metre",1]]],
                    PRIMEM["Greenwich",0,
                        ANGLEUNIT["degree",0.0174532925199433]],
                    CS[ellipsoidal,2],
                        AXIS["geodetic latitude (Lat)",north,
                            ORDER[1],
                            ANGLEUNIT["degree",0.0174532925199433]],
                        AXIS["geodetic longitude (Lon)",east,
                            ORDER[2],
                            ANGLEUNIT["degree",0.0174532925199433]],
                    ID["EPSG",4326]]],
            METHOD["Geocentric translations (geog2D domain)",
                ID["EPSG",9603]],
            PARAMETER["X-axis translation",0,
                LENGTHUNIT["metre",1],
                ID["EPSG",8605]],
            PARAMETER["Y-axis translation",0,
                LENGTHUNIT["metre",1],
                ID["EPSG",8606]],
            PARAMETER["Z-axis translation",0,
                LENGTHUNIT["metre",1],
                ID["EPSG",8607]],
            OPERATIONACCURACY[1.0],
            ID["EPSG",1958]]],
    USAGE[
        SCOPE["unknown"],
        AREA["Latvia"],
        BBOX[55.67,19.06,58.09,28.24]]]
```
I still think that packagers of the official ppa qgis.org/ubuntu* should be aware of this possible conflict.

**Comment by alexbruy** [comment]
Is this still an issue? I can't reproduce with the latest master (5566e42635) and LTR

**Comment by Guts** [comment]
I can't test anymore. Let's close it and see what happens :).
