### ISSUE TITLE
Cannot connect to a remote geonode server

### ISSUE THREAD

**Issue by geogeek11** [qgis/QGIS#43807]
I have tried following the [user guide](https://kartoza.github.io/qgis_geonode/user-guide/), and I've tried another [geonode guide](https://docs.geonode.org/en/master/usage/other_apps/qgis/index.html#connect-to-private-layers-by-using-oauth2), but both of them encounter the same issue.

Please check below the settings that I have used to connect to a remote geonode server.

![Screenshot from 2021-06-17 10-01-53](https://user-images.githubusercontent.com/7670475/122368698-78c0c080-cf55-11eb-9087-3185481b7ddf.png)

After clicking on Test connection, I get the web page below, then I click on authorize
![Screenshot from 2021-06-17 10-02-46](https://user-images.githubusercontent.com/7670475/122368873-9d1c9d00-cf55-11eb-99db-953b7046dc78.png)

After that I get redirected to the web page below, this is where I got stuck in both guides :
![Screenshot from 2021-06-17 10-03-07](https://user-images.githubusercontent.com/7670475/122369217-e7058300-cf55-11eb-93c7-5b7f56c9d116.png)

**The QGIS_Geonode logs :**
```           
2021-06-17T09:59:16     INFO    previous_box: None
2021-06-17T10:04:07     INFO    About to start custom event loop...
2021-06-17T10:04:07     INFO    requested_url: http://10.16.1.192/api/v2/layers/?page=1&page_size=10
2021-06-17T10:04:07     INFO    http_status_code: 200
2021-06-17T10:04:07     INFO    qt_error: None
2021-06-17T10:04:07     INFO    Custom event loop ended, resuming...
2021-06-17T10:04:07     INFO    Inside finished. Result: True
```
**The Python Stacktrace :**
```
2021-06-17T10:04:07     WARNING    Traceback (most recent call last):
File "C:/Users/JAAFARI/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_geonode\apiclient\apiv2.py", line 186, in handle_layer_list
self.network_fetcher_task.reply_content
File "C:/Users/JAAFARI/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_geonode\apiclient\apiv2.py", line 155, in deserialize_response_contents
return json.loads(decoded_contents)
File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\json\__init__.py", line 348, in loads
return _default_decoder.decode(s)
File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\json\decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```    

```

Version de QGIS
3.16.4-Hannover
Révision du code
654e76b3cb
Compilé avec Qt
5.11.2
Utilisant Qt
5.11.2
Compilé avec GDAL/OGR
3.1.4
Utilisé avec GDAL/OGR
3.1.4
Compilé avec GEOS
3.8.1-CAPI-1.13.3
Utilisé avec GEOS
3.8.1-CAPI-1.13.3
Compilé avec SQLite
3.29.0
Fonctionne avec SQLite
3.29.0
Version du client PostgreSQL
11.5
Version de SpatiaLite
4.3.0
Version de QWT
6.1.3
Version de QScintilla2
2.10.8
Compilé avec PROJ
6.3.2
Fonctionne avec PROJ
Rel. 6.3.2, May 1st, 2020
Version de l'OS
Windows 7 SP 1 (6.1)
Extensions Python actives
qgis_geonode; 
SemiAutomaticClassificationPlugin; 
db_manager; 
MetaSearch; 
processing
```

**Comment by gioman** [comment]
@geogeek11 you must report this issue to the plugin author/s, here https://github.com/kartoza/qgis_geonode/issues
