### ISSUE TITLE
Current master crashes

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#43837]
After succesfull build/install of current master (dd 22 juli 13:00 c2a1d87563d5d2067fd2e36da6dd27f94defe23a):
both with my old profile and a fresh (profiles-path) QGIS crashes immidiatly with the following stacktrace

```
$ qgis
Info: Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QGIS died on signal 11[New LWP 154919]
[New LWP 154920]
[New LWP 154921]
[New LWP 154922]
[New LWP 154924]
[New LWP 154925]
[New LWP 154926]
[New LWP 154927]
[New LWP 154928]
[New LWP 154929]
[New LWP 154930]
[New LWP 154931]
[New LWP 154932]
[New LWP 154933]
[New LWP 154934]
[New LWP 154935]
[New LWP 154936]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007fd66fa9c207 in __GI___wait4 (pid=154938, stat_loc=0x7ffd02c07a94, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
27	../sysdeps/unix/sysv/linux/wait4.c: No such file or directory.
[Current thread is 1 (Thread 0x7fd65cb611c0 (LWP 154911))]
#0  0x00007fd66fa9c207 in __GI___wait4 (pid=154938, stat_loc=0x7ffd02c07a94, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
#1  0x0000560a481513f8 in qgisCrash(int) (signal=11) at ../src/app/main.cpp:350
        status = 22026
        pidstr = "--pid=154911\000\000\000\000\210\000\000\000\000\000\000\000\324\347\330g\326\177\000"
        gdbpid = 154938
        exename = "/home/richard/bin/qgis_/master/debug/bin/qgis", '\000' <repeats 11 times>, "\220\250'J\nV\000\000\000\000\000\000\000\000\000\000\324\347\330g\326\177\000\000\000\000\000\000\000\000\000\000\220\250'J\nV", '\000' <repeats 18 times>, "\001\000\000\000\000\000\000\000\220\250'J\nV\000\000\220\250'J\nV\000\000\002\000\000\000\000\000\000\000\004", '\000' <repeats 15 times>, "p\254(J\nV\000\000\360\037\331g\326\177\000\000\220\250'J\nV\000\000\004\000\000\000\000\000\000\000\004\000\000\000\000\000\000\000"...
        len = 45
#2  0x00007fd66fa0cd60 in <signal handler called> () at /lib/x86_64-linux-gnu/libc.so.6
#3  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:245
#4  0x00007fd672cf89d3 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007fd672cf8bae in QtPrivate::argToQString(QStringView, unsigned long, QtPrivate::ArgBase const**) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007fd675cbd883 in QtPrivate::argToQStringDispatch<QStringView, QtPrivate::QStringViewArg, QtPrivate::QStringViewArg>(QStringView, QtPrivate::QStringViewArg const&, QtPrivate::QStringViewArg const&) (pattern=...) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:2111
        argBases = {0x7ffd02c08600, 0x7ffd02c08620, 0x0}
#7  QStringView::arg<QString, QString>(QString&&, QString&&) const (this=<optimized out>) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:2125
#8  QString::arg<QString, QString>(QString&&, QString&&) const (this=0x7ffd02c086b0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:387
#9  0x00007fd670a03e9e in QgsProviderMetadata::listStyles(QString const&, QStringList&, QStringList&, QStringList&, QString&) (this=0x7ffd02c08750, errCause=...) at ../src/core/providers/qgsprovidermetadata.cpp:212
#10 0x00007fd670a0aa18 in QgsProviderRegistry::dataItemProviders(QString const&) const (this=0x560a49fbf0a0, providerKey=...) at ../src/core/providers/qgsproviderregistry.cpp:584
        meta = 0x560a49fd8740
#11 0x00007fd670e84698 in QgsDataItemProviderRegistry::QgsDataItemProviderRegistry() (this=0x560a49fda5a0) at ../src/core/browser/qgsdataitemproviderregistry.cpp:31
        providerList = {<QListSpecialMethods<QgsDataItemProvider*>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, static is_always_lock_free = true}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x7ffd02c08770}, d = 0x7ffd02c08770}}
        key = @0x560a4a285800: {static null = {<No data fields>}, d = 0x7fd60c355a00 <QgsDb2Provider::{lambda()#6}::operator()() const::qstring_literal>}
        __for_range = @0x7ffd02c08768: {<QList<QString>> = {<QListSpecialMethods<QString>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, static is_always_lock_free = true}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x560a4a2857f0}, d = 0x560a4a2857f0}}, <No data fields>}
        __for_begin = {i = 0x560a4a285800}
        __for_end = {i = 0x560a4a2858d0}
        providersList = {<QList<QString>> = {<QListSpecialMethods<QString>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, static is_always_lock_free = true}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x560a4a2857f0}, d = 0x560a4a2857f0}}, <No data fields>}
        constProvidersList = {<QList<QString>> = {<QListSpecialMethods<QString>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, static is_always_lock_free = true}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x560a4a2857f0}, d = 0x560a4a2857f0}}, <No data fields>}
#12 0x00007fd670b504d5 in QgsApplication::dataItemProviderRegistry() () at ../src/core/qgsapplication.cpp:2275
        lInstance = 0x7ffd02c0a950
#13 0x00007fd670b4c569 in QgsApplication::initQgis() () at ../src/core/qgsapplication.cpp:1354
#14 0x00007fd675cdd55b in QgisApp::QgisApp(QSplashScreen*, bool, bool, QString const&, QString const&, QWidget*, QFlags<Qt::WindowType>) (this=0x560a493f1eb0, splash=0x560a49221f30, restorePlugins=true, skipVersionCheck=false, rootProfileLocation=..., activeProfile=..., parent=0x0, fl=...) at ../src/app/qgisapp.cpp:890
        splashTextColor = {cspec = QColor::Rgb, ct = {argb = {alpha = 65535, red = 23901, green = 39321, blue = 13107, pad = 0}, ahsv = {alpha = 65535, hue = 23901, saturation = 39321, value = 13107, pad = 0}, acmyk = {alpha = 65535, cyan = 23901, magenta = 39321, yellow = 13107, black = 0}, ahsl = {alpha = 65535, hue = 23901, saturation = 39321, lightness = 13107, pad = 0}, argbExtended = {alphaF16 = 65535, redF16 = 23901, greenF16 = 39321, blueF16 = 13107, pad = 0}, array = {65535, 23901, 39321, 13107, 0}}}
        settings = {<QObject> = {<No data fields>}, static staticMetaObject = {d = {superdata = {direct = 0x7fd6730d5100 <QObject::staticMetaObject>}, stringdata = 0x7fd67164d780 <qt_meta_stringdata_QgsSettings>, data = 0x7fd67164d7c0 <qt_meta_data_QgsSettings>, static_metacall = 0x7fd6704bb89a <QgsSettings::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, mUserSettings = 0x7ffd02c09030, mGlobalSettings = 0xffffffff00000000, mUsingGlobalArray = 8}
        myRed = 32765
        showAdvancedDigitizingDock = 0x7700000061
        showBrowserDock = 0x7
        puzzleWidget = 0xd60
        showStatsDock = 0x0
        templateDirName = {static null = {<No data fields>}, d = 0x7ffd02c09240}
        profiler = 0x560a494d12c0
        centralLayout = 0xd4
        myGreen = 46178496
        showDevToolsDock = 0xe4
        mainSnappingWidgetMode = {static null = {<No data fields>}, d = 0x7ffd02c09240}
        gpsStack = 0xd4
        zoomInShortCut = 0x7fd66fa5a07a <_int_malloc+2858>
        registerShortcuts = {__this = 0x42a0e93066ecf000}
        refreshBlocker = {mReleased = false}
        zoomShortCut2 = 0x1
        myBlue = 0
        showBookmarksDock = 0x7c0000006e
        showGpsDock = 0x7fd66fb8fbe0 <main_arena+96>
        zoomOutShortCut = 0x7c
        actions = {<QListSpecialMethods<QAction*>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, static is_always_lock_free = true}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x1000000008}, d = 0x1000000008}}
        dbError = {static null = {<No data fields>}, d = 0x7fd672f2e960 <QArrayData::shared_null>}
        centralWidget = 0xd58
        showUndoDock = 0x6
        captureTools = {<QListSpecialMethods<QgsMapToolCapture*>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, static is_always_lock_free = true}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x7fd6625d4c81}, d = 0x7fd6625d4c81}}
        showStylingDock = 0xd80
        caption = {static null = {<No data fields>}, d = 0x16c}
        zoomInToolShortCut = 0xd6
        shortcutTracing = 0x7fd66fb8fb80 <main_arena>
        toggleRevert = {__this = 0x7fd6625ea3ff}
#15 0x0000560a48157ac0 in main(int, char**) (argc=1, argv=0x7ffd02c0bc48) at ../src/app/main.cpp:1377
        preApplicationLogMessages = {<QList<QString>> = {<QListSpecialMethods<QString>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, static is_always_lock_free = true}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x560a48faeb70}, d = 0x560a48faeb70}}, <No data fields>}
        __FUNCTION__ = "main"
        mySnapshotFileName = {static null = {<No data fields>}, d = 0x7fd672f2e960 <QArrayData::shared_null>}
        configLocalStorageLocation = {static null = {<No data fields>}, d = 0x560a48fb2c30}
        profileName = {static null = {<No data fields>}, d = 0x560a48fb5380}
        mySnapshotWidth = 800
        mySnapshotHeight = 600
        myHideSplash = false
        settingsMigrationForce = false
        mySkipVersionCheck = false
        hideBrowser = false
        myRestoreDefaultWindowState = false
        myRestorePlugins = true
        myCustomization = true
        dxfOutputFile = {static null = {<No data fields>}, d = 0x7fd672f2e960 <QArrayData::shared_null>}
        dxfSymbologyMode = QgsDxfExport::SymbolLayerSymbology
        dxfScale = 50000
        dxfEncoding = {static null = {<No data fields>}, d = 0x560a48164d20 <main::{lambda()#2}::operator()() const::qstring_literal>}
        dxfMapTheme = {static null = {<No data fields>}, d = 0x7fd672f2e960 <QArrayData::shared_null>}
        dxfExtent = {mXmin = 0, mYmin = 0, mXmax = 0, mYmax = 0}
        takeScreenShots = false
        screenShotsPath = {static null = {<No data fields>}, d = 0x7fd672f2e960 <QArrayData::shared_null>}
        screenShotsCategories = 0
        myInitialExtent = {static null = {<No data fields>}, d = 0x560a48164d60 <main::{lambda()#3}::operator()() const::qstring_literal>}
        translationCode = {static null = {<No data fields>}, d = 0x560a48fcf7d0}
        authdbdirectory = {static null = {<No data fields>}, d = 0x7fd672f2e960 <QArrayData::shared_null>}
        pythonfile = {static null = {<No data fields>}, d = 0x7fd672f2e960 <QArrayData::shared_null>}
        customizationfile = {static null = {<No data fields>}, d = 0x560a4968c050}
        globalsettingsfile = {static null = {<No data fields>}, d = 0x560a48fb1540}
        openClProgramFolder = {static null = {<No data fields>}, d = 0x7fd672f2e960 <QArrayData::shared_null>}
        args = {<QList<QString>> = {<QListSpecialMethods<QString>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, static is_always_lock_free = true}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x560a48fb1480}, d = 0x560a48fb1480}}, <No data fields>}
        myUseGuiFlag = true
        rootProfileFolder = {static null = {<No data fields>}, d = 0x560a48fb2b50}
        manager = {<QObject> = {<No data fields>}, static staticMetaObject = {d = {superdata = {direct = 0x7fd6730d5100 <QObject::staticMetaObject>}, stringdata = 0x7fd67164c720 <qt_meta_stringdata_QgsUserProfileManager>, data = 0x7fd67164c7a0 <qt_meta_data_QgsUserProfileManager>, static_metacall = 0x7fd6704b9fa0 <QgsUserProfileManager::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, mWatchProfiles = false, mWatcher = std::unique_ptr<class QFileSystemWatcher> = {get() = 0x0}, mRootProfilePath = {static null = {<No data fields>}, d = 0x560a48fb2b50}, mUserProfile = std::unique_ptr<class QgsUserProfile> = {get() = 0x0}, mSettings = std::unique_ptr<class QSettings> = {get() = 0x560a48fb13a0}}
        profile = 0x560a48fb2d30
        profileFolder = {static null = {<No data fields>}, d = 0x560a48fb4410}
        myApp = {<QApplication> = {<No data fields>}, static staticMetaObject = {d = {superdata = {direct = 0x7fd673e01fa0 <QApplication::staticMetaObject>}, stringdata = 0x7fd67163ece0 <qt_meta_stringdata_QgsApplication>, data = 0x7fd67163eee0 <qt_meta_data_QgsApplication>, static_metacall = 0x7fd6704a904c <QgsApplication::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, static QGIS_ORGANIZATION_NAME = 0x7fd6717c2da2 "QGIS", static QGIS_ORGANIZATION_DOMAIN = 0x7fd6717c2da7 "qgis.org", static QGIS_APPLICATION_NAME = 0x7fd6717c2db0 "QGIS3", static settingsLocaleUserLocale = {<QgsSettingsEntryBase> = {_vptr.QgsSettingsEntryBase = 0x7fd672b4d800 <vtable for QgsSettingsEntryString+16>, mKey = {static null = {<No data fields>}, d = 0x7fd671627fa0 <QgsApplication::{lambda()#1}::operator()() const::qstring_literal>}, mDefaultValue = {d = {data = {c = 96 '`', uc = 96 '`', s = -5792, sc = 96 '`', us = 59744, i = 1928522080, u = 1928522080, l = 140559028250976, ul = 140559028250976, b = 96, d = 6.9445387071636476e-310, f = 9.6227207e+30, real = 6.9445387071636476e-310, ll = 140559028250976, ull = 140559028250976, o = 0x7fd672f2e960 <QArrayData::shared_null>, ptr = 0x7fd672f2e960 <QArrayData::shared_null>, shared = 0x7fd672f2e960 <QArrayData::shared_null>}, type = 10, is_shared = 0, is_null = 0}}, mSection = QgsSettings::NoSection, mDescription = {static null = {<No data fields>}, d = 0x7fd672f2e960 <QArrayData::shared_null>}, mPluginName = {static null = {<No data fields>}, d = 0x7fd672f2e960 <QArrayData::shared_null>}}, mMinLength = 0, mMaxLength = -1}, static settingsLocaleOverrideFlag = {<QgsSettingsEntryBase> = {_vptr.QgsSettingsEntryBase = 0x7fd672b4d790 <vtable for QgsSettingsEntryBool+16>, mKey = {static null = {<No data fields>}, d = 0x7fd671627fe0 <QgsApplication::{lambda()#2}::operator()() const::qstring_literal>}, mDefaultValue = {d = {data = {c = 0 '\000', uc = 0 '\000', s = -18176, sc = 0 '\000', us = 47360, i = 46184704, u = 46184704, l = 140724649638144, ul = 140724649638144, b = false, d = 6.9527214909252757e-310, f = 2.83180492e-37, real = 6.9527214909252757e-310, ll = 140724649638144, ull = 140724649638144, o = 0x7ffd02c0b900, ptr = 0x7ffd02c0b900, shared = 0x7ffd02c0b900}, type = 1, is_shared = 0, is_null = 0}}, mSection = QgsSettings::NoSection, mDescription = {static null = {<No data fields>}, d = 0x7fd672f2e960 <QArrayData::shared_null>}, mPluginName = {static null = {<No data fields>}, d = 0x7fd672f2e960 <QArrayData::shared_null>}}, <No data fields>}, static settingsLocaleGlobalLocale = {<QgsSettingsEntryBase> = {_vptr.QgsSettingsEntryBase = 0x7fd672b4d800 <vtable for QgsSettingsEntryString+16>, mKey = {static null = {<No data fields>}, d = 0x7fd671628020 <QgsApplication::{lambda()#3}::operator()() const::qstring_literal>}, mDefaultValue = {d = {data = {c = 96 '`', uc = 96 '`', s = -5792, sc = 96 '`', us = 59744, i = 1928522080, u = 1928522080, l = 140559028250976, ul = 140559028250976, b = 96, d = 6.9445387071636476e-310, f = 9.6227207e+30, real = 6.9445387071636476e-310, ll = 140559028250976, ull = 140559028250976, o = 0x7fd672f2e960 <QArrayData::shared_null>, ptr = 0x7fd672f2e960 <QArrayData::shared_null>, shared = 0x7fd672f2e960 <QArrayData::shared_null>}, type = 10, is_shared = 0, is_null = 0}}, mSection = QgsSettings::NoSection, mDescription = {static null = {<No data fields>}, d = 0x7fd672f2e960 <QArrayData::shared_null>}, mPluginName = {static null = {<No data fields>}, d = 0x7fd672f2e960 <QArrayData::shared_null>}}, mMinLength = 0, mMaxLength = -1}, static settingsLocaleShowGroupSeparator = {<QgsSettingsEntryBase> = {_vptr.QgsSettingsEntryBase = 0x7fd672b4d790 <vtable for QgsSettingsEntryBool+16>, mKey = {static null = {<No data fields>}, d = 0x7fd671628060 <QgsApplication::{lambda()#4}::operator()() const::qstring_literal>}, mDefaultValue = {d = {data = {c = 0 '\000', uc = 0 '\000', s = -18176, sc = 0 '\000', us = 47360, i = 46184704, u = 46184704, l = 140724649638144, ul = 140724649638144, b = false, d = 6.9527214909252757e-310, f = 2.83180492e-37, real = 6.9527214909252757e-310, ll = 140724649638144, ull = 140724649638144, o = 0x7ffd02c0b900, ptr = 0x7ffd02c0b900, shared = 0x7ffd02c0b900}, type = 1, is_shared = 0, is_null = 0}}, mSection = QgsSettings::NoSection, mDescription = {static null = {<No data fields>}, d = 0x7fd672f2e960 <QArrayData::shared_null>}, mPluginName = {static null = {<No data fields>}, d = 0x7fd672f2e960 <QArrayData::shared_null>}}, <No data fields>}, static settingsSearchPathsForSVG = {<QgsSettingsEntryBase> = {_vptr.QgsSettingsEntryBase = 0x7fd672b4d7c8 <vtable for QgsSettingsEntryStringList+16>, mKey = {static null = {<No data fields>}, d = 0x7fd6716280c0 <QgsApplication::{lambda()#5}::operator()() const::qstring_literal>}, mDefaultValue = {d = {data = {c = 112 'p', uc = 112 'p', s = -2960, sc = 112 'p', us = 62576, i = 1928524912, u = 1928524912, l = 140559028253808, ul = 140559028253808, b = 112, d = 6.944538707303567e-310, f = 9.62443254e+30, real = 6.944538707303567e-310, ll = 140559028253808, ull = 140559028253808, o = 0x7fd672f2f470 <QListData::shared_null>, ptr = 0x7fd672f2f470 <QListData::shared_null>, shared = 0x7fd672f2f470 <QListData::shared_null>}, type = 11, is_shared = 0, is_null = 0}}, mSection = QgsSettings::NoSection, mDescription = {static null = {<No data fields>}, d = 0x7fd672f2e960 <QArrayData::shared_null>}, mPluginName = {static null = {<No data fields>}, d = 0x7fd672f2e960 <QArrayData::shared_null>}}, <No data fields>}, static mFileOpenEventReceiver32100 = 0x0, static mInitialized32100 = true, static mRunningFromBuildDir32100 = false, static sMaxThreads32100 = -1, mIconCache = {d = 0x560a4919ffe0}, mCursorCache = {d = 0x7fd672f2f4a0 <QMapDataBase::shared_null>}, mQgisTranslator = 0x560a491afb50, mQtTranslator = 0x560a491a6ba0, mQtBaseTranslator = 0x560a490f4910, mDataItemProviderRegistry = 0x0, mAuthManager = 0x0, mApplicationMembers = 0x560a490d8eb0, static sApplicationMembers = 0x0, static sAuthManager = 0x0}
        settings = {<QObject> = {<No data fields>}, static staticMetaObject = {d = {superdata = {direct = 0x7fd6730d5100 <QObject::staticMetaObject>}, stringdata = 0x7fd67164d780 <qt_meta_stringdata_QgsSettings>, data = 0x7fd67164d7c0 <qt_meta_data_QgsSettings>, static_metacall = 0x7fd6704bb89a <QgsSettings::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, mUserSettings = 0x560a49136e20, mGlobalSettings = 0x560a490fe080, mUsingGlobalArray = false}
        libPaths = {<QList<QString>> = {<QListSpecialMethods<QString>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, static is_always_lock_free = true}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x560a497c8a50}, d = 0x560a497c8a50}}, <No data fields>}
        relLibPath = {static null = {<No data fields>}, d = 0x560a49848560}
        customizationsettings = 0x560a490ac270
        systemEnvVars = {d = 0x560a4916b9f0}
        useCustomVars = false
        desiredStyle = {static null = {<No data fields>}, d = 0x560a49362e80}
        theme = {static null = {<No data fields>}, d = 0x560a496b14c0}
        activeStyleName = {static null = {<No data fields>}, d = 0x560a49958090}
        mySplashPath = {static null = {<No data fields>}, d = 0x7fd6717c4060 <QgsApplication::splashPath()::{lambda()#1}::operator()() const::qstring_literal>}
        myPixmap = <incomplete type>
        w = 600
        h = 300
        mypSplash = 0x560a49221f30
        qgis = 0x7fd672d8911f <qRegisterResourceData(int, unsigned char const*, unsigned char const*, unsigned char const*)+399>
        sigwatch = {<QObject> = {<No data fields>}, static staticMetaObject = {d = {superdata = {direct = 0x7fd6730d5100 <QObject::staticMetaObject>}, stringdata = 0x560a481a6460 <qt_meta_stringdata_UnixSignalWatcher>, data = 0x560a481a6520 <qt_meta_data_UnixSignalWatcher>, static_metacall = 0x560a4816079e <UnixSignalWatcher::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, d_ptr = 0x560a48f1b3c0}
        retval = 1209688480
```

**Comment by nyalldawson** [comment]
Completely wipe your build folder and do a clean build -- there's old files sitting in your build folder causing this

**Comment by rduivenvoorde** [comment]
Ah, sorry. Thanks (this was coming from Telegram group... I just confirmed :-( )

**Comment by roya0045** [comment]
@rduivenvoorde should this be closed then?

**Comment by rduivenvoorde** [comment]
@roya0045 well... /me building... will close if it runs... 
Tim on Telegram group told he did a 'make clean', I just wiped my install and build dir...
Will close if OK

**Comment by rduivenvoorde** [comment]
Ok, fixed by clean build. Sorry for the fuzz
