### ISSUE TITLE
QGis 3.20 sous W10 - cartolinegen / LightPollutionToolbox

### ISSUE THREAD

**Issue by Geoscope19** [qgis/QGIS#44068]
Bonjour,

A l'ouverture de la version 3.20 de Qgis, 2 erreurs Python sont signalées :

Impossible de charger l'extension 'cartolinegen' provoque une erreur lors de l'appel à sa méthode classFactory() 

ModuleNotFoundError: No module named 'ogr' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\utils.py", line 335, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/-/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cartolinegen\__init__.py", line 35, in classFactory
    from .cartolinegen import CartoLineGen
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/-/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cartolinegen\cartolinegen.py", line 36, in 
    from .generalize import Generalize
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/-/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cartolinegen\generalize.py", line 24, in 
    import ogr,sys,math,random,os
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'ogr'

Version de Python : 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Version de QGIS : 3.20.0-Odense Odense, decaadbb31 

-----

Impossible de charger l'extension 'LightPollutionToolbox' provoque une erreur lors de l'appel à sa méthode classFactory() 

ModuleNotFoundError: No module named 'gdal' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\utils.py", line 335, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/-/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LightPollutionToolbox\__init__.py", line 38, in classFactory
    from .LightPollutionToolbox import LightPollutionToolboxPlugin
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/-/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LightPollutionToolbox\LightPollutionToolbox.py", line 38, in 
    from .algs.LightPollutionToolbox_provider import LightPollutionToolboxProvider
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/-/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LightPollutionToolbox\algs\LightPollutionToolbox_provider.py", line 38, in 
    from .fluxDensity_algorithm import FluxDensityAlgorithm, DSFLSymbology, DSFLSurface, DSFLRaw
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/-/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LightPollutionToolbox\algs\fluxDensity_algorithm.py", line 58, in 
    from ..qgis_lib_mc import utils, qgsUtils, qgsTreatments, styles
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/-/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LightPollutionToolbox\qgis_lib_mc\qgsTreatments.py", line 41, in 
    import gdal
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'gdal'

Version de Python : 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Version de QGIS : 3.20.0-Odense Odense, decaadbb31

**Comment by roya0045** [comment]
Plugin issue, not responsible and out of scope. Contact plugin authors instead.

**Comment by Geoscope19** [comment]
ok.
