### ISSUE TITLE
QGIS crashes when opening project

### ISSUE THREAD

**Issue by housepig83** [qgis/QGIS#44074]
Hi, QGIS keep crashing whenever I open project .qgz files

 Crash ID:05c1791246077518c1ef2f12d81c04e5fef9f941

Stack Trace

memcpy_repmovs memcpy.asm:114
VSICreateCachedFile :
SASetupDefaultHooks :
SHPReadObject :
SHPPartTypeName :
SHPPartTypeName :
QgsSQLiteExpressionCompiler::operator= :
QgsAbstractFeatureIterator::nextFeature :
QgsVectorLayerFeatureIterator::fetchFeature :
QgsAbstractFeatureIterator::nextFeature :
QgsVectorLayerJoinInfo::setEditable :
QgsVectorLayerJoinInfo::setEditable :
QgsMapRendererParallelJob::renderLayerStatic :
QgsMapRendererParallelJob::renderingFinished :
QgsImageOperation::overlayColor :
QgsImageOperation::stackBlur :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.8-Hannover
QGIS code revision: 8c50902e
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.0
Running against GDAL: 3.3.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by gioman** [comment]
@housepig83 try with a new QGIS profile, no 3rd party plugins installed.

**Comment by housepig83** [comment]
> @housepig83 try with a new QGIS profile, no 3rd party plugins installed.

I have tried...it still doesn't work. 
It just suddenly didn't work properly and crashed whenever I opened the project files. I had no problem opening these project files before yesterday.

**Comment by Edwrom** [comment]
Yes, the error is also present today in Linux Mint.
When trying to open a .qgz project from the file menu, or by dragging the project file to qgis, the program closes.

**However**, when you make a new profile, several third-party plugins are disabled, and when you open the project, it loads without any problem.


Version 3.20.0-Odense
QGIS code review: decaadbb31

Qt version 5.12.8
Python version 3.8.5
GDAL / OGR version 3.0.4
PROJ version 6.3.1
EPSG Registry database version v9.8.6 (2020-01-22)
Compiled against GEOS 3.8.0-CAPI-1.13.1
Running against GEOS 3.8.0-CAPI-1.13.1
SQLite version 3.31.1
PDAL version 2.0.1
PostgreSQL client version 12.7 (Ubuntu 12.7-0ubuntu0.20.04.1)
SpatiaLite version 4.3.0a
QWT version 6.1.4
QScintilla2 version 2.11.2
OS version Linux Mint 20.1

**Comment by gioman** [comment]
> **However**, when you make a new profile, several third-party plugins are disabled, But I get a message saying that processing was disabled because before it happened that qgis crash , and when you open the project, it loads without any problem.

@Edwrom then is likely to be a plugin issue, not a qgis one.

**Comment by Edwrom** [comment]
That's how it is. By disabling all plugins, including the kernel, you can work without problem.
But when trying to perform a geoprocess, it is necessary to enable "processing", and when doing so it throws the following error: 
`Ha ocurrido un error mientras se ejecutaba el código de Python: 

rasterio.errors.RasterioIOError: bad.tif: No existe el archivo o el directorio 
Traceback (most recent call last):
  File "rasterio/_base.pyx", line 216, in rasterio._base.DatasetBase.__init__
  File "rasterio/_shim.pyx", line 78, in rasterio._shim.open_dataset
  File "rasterio/_err.pyx", line 205, in rasterio._err.exc_wrap_pointer
rasterio._err.CPLE_OpenFailedError: bad.tif: No existe el archivo o el directorio

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/qgis/python/plugins/processing/script/ScriptAlgorithmProvider.py", line 121, in loadAlgorithms
    alg = ScriptUtils.loadAlgorithm(moduleName, filePath)
  File "/usr/share/qgis/python/plugins/processing/script/ScriptUtils.py", line 67, in loadAlgorithm
    spec.loader.exec_module(module)
  File "", line 848, in exec_module
  File "", line 219, in _call_with_frames_removed
  File "/home/david/.local/share/QGIS/QGIS3/profiles/default/processing/scripts/Reparar_ORTOFOFO_PIXELES_VACIOS.py", line 6, in 
    dataset = rasterio.open(filename)
  File "/usr/lib/python3/dist-packages/rasterio/env.py", line 434, in wrapper
    return f(*args, **kwds)
  File "/usr/lib/python3/dist-packages/rasterio/__init__.py", line 219, in open
    s = DatasetReader(path, driver=driver, sharing=sharing, **kwargs)
  File "rasterio/_base.pyx", line 218, in rasterio._base.DatasetBase.__init__
rasterio.errors.RasterioIOError: bad.tif: No existe el archivo o el directorio`

**Comment by gioman** [comment]
>That's how it is. By disabling all plugins, including the kernel, you can work without problem.
But when trying to perform a geoprocess, it is necessary to enable "processing", and when doing so it throws the following error:
`Ha ocurrido un error mientras se ejecutaba el código de Python:

```
rasterio.errors.RasterioIOError: bad.tif: No existe el archivo o el directorio
Traceback (most recent call last):
File "rasterio/_base.pyx", line 216, in rasterio._base.DatasetBase.init
File "rasterio/_shim.pyx", line 78, in rasterio._shim.open_dataset
File "rasterio/_err.pyx", line 205, in rasterio._err.exc_wrap_pointer
rasterio._err.CPLE_OpenFailedError: bad.tif: No existe el archivo o el directorio

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/share/qgis/python/plugins/processing/script/ScriptAlgorithmProvider.py", line 121, in loadAlgorithms
alg = ScriptUtils.loadAlgorithm(moduleName, filePath)
File "/usr/share/qgis/python/plugins/processing/script/ScriptUtils.py", line 67, in loadAlgorithm
spec.loader.exec_module(module)
File "", line 848, in exec_module
File "", line 219, in _call_with_frames_removed
File "/home/david/.local/share/QGIS/QGIS3/profiles/default/processing/scripts/Reparar_ORTOFOFO_PIXELES_VACIOS.py", line 6, in
dataset = rasterio.open(filename)
File "/usr/lib/python3/dist-packages/rasterio/env.py", line 434, in wrapper
return f(*args, **kwds)
File "/usr/lib/python3/dist-packages/rasterio/init.py", line 219, in open
s = DatasetReader(path, driver=driver, sharing=sharing, **kwargs)
File "rasterio/_base.pyx", line 218, in rasterio._base.DatasetBase.init
rasterio.errors.RasterioIOError: bad.tif: No existe el archivo o el directorio`
```

@Edwrom the above error comes frm a 3rd party python script.

**Comment by housepig83** [comment]
Hi, i think i have figured out the problem. Somehow one of my polygon Shapefiles is corrupted hence  why QGIS keep crashing whenever I opened the .qgz files that have that file loaded... However, my friend computer was fine when open the same .qgz file because we put it on shared google drive (but the polygon shapefile still corrupted)

**Comment by gioman** [comment]
> Hi, i think i have figured out the problem. Somehow one of my polygon Shapefiles is corrupted hence why QGIS keep crashing whenever I opened the .qgz files that have that file loaded... However, my friend computer was fine when open the same .qgz file because we put it on shared google drive (but the polygon shapefile still corrupted)

@housepig83 please attach the problematic project + data.
