### ISSUE TITLE
Unrelated outputs of "qgis_process run ..." command

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#44142]
I am running the following command and its output has unnecessary information imho
```
C:\OSGeo4W>qgis_process-qgis-dev run native:buffer
D:\src\osgeo4w\src\qgis-dev\qgis\src\core\providers\qgsproviderregistry.cpp(251) : (QgsProviderRegistry::init) [2691ms] Checking C:/OSGeo4W/apps/qgis-dev/plugins/grassplugin7.dll: ...invalid (lib not loadable): Cannot load library C:\OSGeo4W\apps\qgis-dev\plugins\grassplugin7.dll: Le module spÚcifiÚ est introuvable.
D:\src\osgeo4w\src\qgis-dev\qgis\src\core\providers\qgsproviderregistry.cpp(251) : (QgsProviderRegistry::init) [8ms] Checking C:/OSGeo4W/apps/qgis-dev/plugins/provider_grass7.dll: ...invalid (lib not loadable): Cannot load library C:\OSGeo4W\apps\qgis-dev\plugins\provider_grass7.dll: Le module spÚcifiÚ est introuvable.
D:\src\osgeo4w\src\qgis-dev\qgis\src\core\providers\qgsproviderregistry.cpp(251) : (QgsProviderRegistry::init) [2ms] Checking C:/OSGeo4W/apps/qgis-dev/plugins/provider_grassraster7.dll: ...invalid (lib not loadable): Cannot load library C:\OSGeo4W\apps\qgis-dev\plugins\provider_grassraster7.dll: Le module spÚcifiÚ est introuvable.
D:\src\osgeo4w\src\qgis-dev\qgis\src\core\providers\qgsproviderregistry.cpp(304) : (QgsProviderRegistry::init) [19ms] Loaded 25 providers (DB2;OAPIF;WFS;arcgisfeatureserver;arcgismapserver;delimitedtext;ept;gdal;geonode;gpx;hana;mdal;memory;mesh_memory;mssql;ogr;oracle;pdal;postgres;postgresraster;spatialite;vectortile;virtual;wcs;wms)
D:\src\osgeo4w\src\qgis-dev\qgis\src\process\qgsprocess.cpp(189) : (QgsProcessingExec::loadPythonSupport) [137ms] load library qgispython (3.21.0)
<string>:1: DeprecationWarning: setapi() is deprecated
D:\src\osgeo4w\src\qgis-dev\qgis\src\core\qgsmessagelog.cpp(29) : (QgsMessageLog::logMessage) [976ms] 2021-07-13T12:28:38 Python error[2] Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis-dev/./python\qgis\utils.py", line 335, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/pclocal/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cadastre\__init__.py", line 29, in classFactory
    return CadastreMenu(iface)
  File "C:\Users/pclocal/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cadastre\cadastre_menu.py", line 63, in __init__
    self.mapCanvas = iface.mapCanvas()
AttributeError: 'NoneType' object has no attribute 'mapCanvas'

Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis-dev/./python\qgis\utils.py", line 335, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/pclocal/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cadastre\__init__.py", line 29, in classFactory
    return CadastreMenu(iface)
  File "C:\Users/pclocal/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cadastre\cadastre_menu.py", line 63, in __init__
    self.mapCanvas = iface.mapCanvas()
AttributeError: 'NoneType' object has no attribute 'mapCanvas'

D:\src\osgeo4w\src\qgis-dev\qgis\src\core\qgsmessagelog.cpp(29) : (QgsMessageLog::logMessage) [27ms] 2021-07-13T12:28:38 Couldn't load plugin 'cadastre' due to an error when calling its classFactory() method[1] Couldn't load plugin 'cadastre' due to an error when calling its classFactory() method


AttributeError: 'NoneType' object has no attribute 'mapCanvas'


Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis-dev/./python\qgis\utils.py", line 335, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/pclocal/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cadastre\__init__.py", line 29, in classFactory
    return CadastreMenu(iface)
  File "C:\Users/pclocal/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cadastre\cadastre_menu.py", line 63, in __init__
    self.mapCanvas = iface.mapCanvas()
AttributeError: 'NoneType' object has no attribute 'mapCanvas'




Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]


QGIS version: 3.21.0-Master Master, f7646705c


Python Path:

C:/OSGeo4W/apps/qgis-dev/./pythonC:/Users/pclocal/AppData/Roaming/QGIS/QGIS3\profiles\default/pythonC:/Users/pclocal/AppData/Roaming/QGIS/QGIS3\profiles\default/python/pluginsC:/OSGeo4W/apps/qgis-dev/./python/pluginsC:\OSGeo4W\apps\qgis-dev\pythonC:\OSGeo4W64\apps\Python36\LibC:\OSGeo4W\bin\python39.zipC:\OSGeo4W\apps\Python39\DLLsC:\OSGeo4W\apps\Python39\libC:\OSGeo4W\apps\qgis-dev\binC:\OSGeo4W\apps\Python39C:\OSGeo4W\apps\Python39\lib\site-packagesC:/Users/pclocal/AppData/Roaming/QGIS/QGIS3\profiles\default/pythonC:\Users\pclocal\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\cadastre\forms

error starting plugin: cadastre

D:\src\osgeo4w\src\qgis-dev\qgis\src\core\qgsmessagelog.cpp(29) : (QgsMessageLog::logMessage) [193ms] 2021-07-13T12:28:38 Processing[2] Problem with GRASS installation: GRASS was not found or is not correctly installed
Problem with GRASS installation: GRASS was not found or is not correctly installed
D:\src\osgeo4w\src\qgis-dev\qgis\src\core\qgsmessagelog.cpp(29) : (QgsMessageLog::logMessage) [329ms] 2021-07-13T12:28:39 Processing[2] Problem with SAGA installation: SAGA was not found or is not correctly installed
Problem with SAGA installation: SAGA was not found or is not correctly installed

----------------
Inputs
----------------

ERROR: The following mandatory parameters were not specified

        INPUT:  Input layer
        OUTPUT: Buffered
```
Do not pay attention to the command itself. I think, since I'm running a specific command, it shouldn't report:
* errors of implementation related to other plugins (cadastre)
* missing providers (SAGA/GRASS) that I do not call

The output should only concern the command I ran (ie, the 6 last lines).

Tested with QGIS version: 3.21.0-Master Master, f7646705c

**Comment by Gustry** [comment]
You are using `qgis_process` so QGIS is loading all plugins having `hasProcessingProvider`. The culprit is "cadastre" not compatible with your version of QGIS.

So IMHO it looks normal to show errors related to "cadastre", no ?

**Comment by DelazJ** [comment]
I'm running `qgis_process run providerX:algorithmY`. I'd expect it to run that alg, IOW:
- is providerX correctly present?
- is algorithmY available?
- (try to) execute.

I'd not expect it to check and report whether unrelated providers are correctly installed. Would be correct if I had called `qgis_process list`, I guess.

**Comment by alexbruy** [comment]
To run algorithm it should load all the providers first.

**Comment by Gustry** [comment]
Well, indeed, it could load all providers, but not calling `loadAlgorithms` if the algorithm doesn't match the provider ID, no @alexbruy ?

But for a model, you would need to call all providers used in the model.

**Comment by alexbruy** [comment]
If I'm not wrong loading algorithms is a part of the provider initialization by design. Maybe you can separate them somehow if you want.

**Comment by gacarrillor** [comment]
Perhaps that long log (including unrelated providers info) could be the output of the `--verbose` parameter and could be hidden from users if `--verbose` is not present.

**Comment by DelazJ** [comment]
Thanks for clarification @alexbruy. If I correctly understand, going through these "unrelated items" is the expected behavior, according to our design. So not an issue _per se_.
> Perhaps that long log (including unrelated providers info) could be the output of the --verbose parameter and could be hidden from users if --verbose is not present.

Sounds like a good idea imho.

**Comment by nyalldawson** [comment]
You're only seeing a lot of this because your running a dev build. That's why all the debugging output is shown.

**Comment by agiudiceandrea** [comment]
There is also an issue with the encoding...

**Comment by nyalldawson** [comment]
> missing providers (SAGA/GRASS) that I do not call

That's not possible to determine in advance. The algorithm you call from one provider could quite easily be calling sub algorithms from other providers. Anyway, this particular situation isn't an issue anymore as it's possible to completely disable the grass/saga processing plugins independently of the main processing plugin

**Comment by nyalldawson** [comment]
I think this ticket can be closed
