### ISSUE TITLE
python error

### ISSUE THREAD

**Issue by dmaxit** [qgis/QGIS#44269]
2021-07-20T10:51:56     WARNING    Traceback (most recent call last):
              File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python/plugins\processing\algs\grass7\Grass7AlgorithmProvider.py", line 124, in loadAlgorithms
              version = Grass7Utils.installedVersion(True)
              File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python/plugins\processing\algs\grass7\Grass7Utils.py", line 116, in installedVersion
              with subprocess.Popen(
              File "C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\subprocess.py", line 951, in __init__
              self._execute_child(args, executable, preexec_fn, close_fds,
              File "C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\subprocess.py", line 1420, in _execute_child
              hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
             OSError: [WinError 87] El parámetro no es correcto

**Comment by gioman** [comment]
@dmaxit please add all the requested infos.
