### ISSUE TITLE
Start-up hang on QGIS 3.20.1

### ISSUE THREAD

**Issue by lnicola** [qgis/QGIS#44530]
### What is the bug or the crash?

After upgrading to 3.20.1, QGIS hangs on start-up (or hangs for a while, then quits, I'm not sure. Here's a stack trace:

```
Info: Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
[New Thread 0x7fffe3934640 (LWP 210072)]
[New Thread 0x7fffe3133640 (LWP 210073)]
[New Thread 0x7fffe2932640 (LWP 210074)]
[New Thread 0x7fffe210d640 (LWP 210075)]
^C
Thread 1 "qgis" received signal SIGINT, Interrupt.
0x00007ffff4fee531 in operator==(QString const&, QString const&) () from /usr/lib/libQt5Core.so.5
(gdb) bt
#0  0x00007ffff4fee531 in operator==(QString const&, QString const&) () at /usr/lib/libQt5Core.so.5
#1  0x00007fffee934567 in  () at /usr/lib/libQt5Xml.so.5
#2  0x00007fffee930e44 in QDomElement::attribute(QString const&, QString const&) const () at /usr/lib/libQt5Xml.so.5
#3  0x00007ffff383cae8 in QgsStyle::importXml(QString const&, int) () at /usr/lib/libqgis_core.so.3.20.1
#4  0x00007ffff383e860 in QgsStyle::upgradeIfRequired() () at /usr/lib/libqgis_core.so.3.20.1
#5  0x00007ffff383ec3e in QgsStyle::defaultStyle() () at /usr/lib/libqgis_core.so.3.20.1
#6  0x00007ffff3bc135e in QgsApplication::init(QString) () at /usr/lib/libqgis_core.so.3.20.1
#7  0x000055555555d2f0 in  ()
#8  0x00007ffff2debb25 in __libc_start_main () at /usr/lib/libc.so.6
#9  0x00005555555614be in  ()
```

### Steps to reproduce the issue

1. Start QGIS

### Versions

`3.20.1`

### Additional context

Happens on Arch Linux. `3.20.0` works with the same versions of the dependencies. Also filed downstream at https://bugs.archlinux.org/task/71713.

**Comment by lnicola** [comment]
I tried to compile it with debug info, no luck:

```
Info: Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
[New Thread 0x7fffe3812640 (LWP 249766)]
[New Thread 0x7fffe3011640 (LWP 249767)]
[New Thread 0x7fffe2801640 (LWP 249768)]
[New Thread 0x7fffe1feb640 (LWP 249769)]
[Thread 0x7fffe3011640 (LWP 249767) exited]
^C
Thread 1 "qgis" received signal SIGINT, Interrupt.
0x00005555555643f6 in QString::~QString (this=0x7fffffffcd90, __in_chrg=<optimized out>) at /usr/include/c++/11.1.0/bits/atomic_base.h:385
385	      operator--() noexcept
(gdb) bt
#0  0x00005555555643f6 in QString::~QString() (this=0x7fffffffcd90, __in_chrg=<optimized out>) at /usr/include/c++/11.1.0/bits/atomic_base.h:385
#1  0x00007ffff376cf94 in QgsStyle::importXml(QString const&, int) (this=0x555555a041a0, filename=..., sinceVersion=32000) at /usr/src/debug/qgis-3.20.1/src/core/symbology/qgsstyle.cpp:2809
#2  0x00007ffff376eec4 in QgsStyle::upgradeIfRequired() (this=0x555555a041a0) at /usr/src/debug/qgis-3.20.1/src/core/symbology/qgsstyle.cpp:3287
#3  0x00007ffff376f2ae in QgsStyle::defaultStyle() () at /usr/src/debug/qgis-3.20.1/src/core/symbology/qgsstyle.cpp:153
#4  0x00007ffff3b0f7de in QgsApplication::init(QString) (profileFolder=...) at /usr/src/debug/qgis-3.20.1/src/core/qgsapplication.cpp:409
#5  0x000055555555d318 in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/qgis-3.20.1/src/app/main.cpp:1082
```

**Comment by nicogodet** [comment]
linked to https://github.com/qgis/QGIS/issues/44293 ?

**Comment by lnicola** [comment]
Oh, thanks, I'm not sure how I failed to find that.
