### ISSUE TITLE
File downloader algorithm crash

### ISSUE THREAD

**Issue by Gustry** [qgis/QGIS#44905]
### What is the bug or the crash?

QGIS is crashing with the file downloader algorithm

### Steps to reproduce the issue

1. Open the file downloader algorithm from the toolbox
2. Set the URL `https://overpass-api.de/api/interpreter`
3. Let empty the `OUTPUT`
4. Run

### Versions

QGIS Master 3.22

The crash doesn't not happen with 3.16.10

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

@nirvn I saw you have some history in this area of the code. Maybe you have an idea ?
I'm not sure how to debug a crash.

**Comment by nirvn** [comment]
I can replicate crash, but can't see an obvious fix -- stack trace:

```
#0  std::__atomic_base<int>::load(std::memory_order) const (__m=std::memory_order_relaxed, this=0x0)
    at /usr/include/c++/10/bits/atomic_base.h:426
#1  QAtomicOps<int>::loadRelaxed<int>(std::atomic<int> const&) (_q_value=...)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_cxx11.h:239
#2  0x00007ffff00092a2 in QBasicAtomicInteger<int>::loadRelaxed() const (this=0x0)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qbasicatomic.h:107
#3  0x00007ffff0008cac in QtPrivate::RefCount::deref() (this=0x0)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qrefcount.h:66
#4  0x00007ffff005d8b9 in QList<QString>::~QList() (this=0x7fffffffa190, __in_chrg=<optimized out>)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h:873
#5  0x00007ffff01108a0 in QList<QString>::operator=(QList<QString> const&) (this=0x7fffc4bc2da8, l=...)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h:533
#6  0x00007ffff016c7a3 in QStringList::operator=(QStringList const&) (this=0x7fffc4bc2da8)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qstringlist.h:111
#7  0x00007ffff016ac6c in operator()(QStringList const&) const (__closure=0x7fffa80037e0, e=...)
    at /home/webmaster/dev/cpp/QGIS/src/analysis/processing/qgsalgorithmfiledownloader.cpp:84
#8  0x00007ffff016c20d in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<QStringList>, void, QgsFileDownloaderAlgorithm::processAlgorithm(const QVariantMap&, QgsProcessingContext&, QgsProcessingFeedback*)::<lambda(const QStringList&)> >::call(struct {...} &, void **) (f=..., arg=0x7fffa800fee8)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:146
#9  0x00007ffff016c1a7 in QtPrivate::Functor<QgsFileDownloaderAlgorithm::processAlgorithm(const QVariantMap&, QgsProcessingContext&, QgsProcessingFeedback*)::<lambda(const QStringList&)>, 1>::call<QtPrivate::List<QStringList>, void>(struct {...} &, void *, void **) (f=..., arg=0x7fffa800fee8)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:256
#10 0x00007ffff016c0e8 in QtPrivate::QFunctorSlotObject<QgsFileDownloaderAlgorithm::processAlgorithm(const QVariantMap&, QgsProcessingContext&, QgsProcessingFeedback*)::<lambda(const QStringList&)>, 1, QtPrivate::List<QStringList>, void>::impl(int, QtPrivate::QSlotObjectBase *, QObject *, void **, bool *)
    (which=1, this_=0x7fffa80037d0, r=0x55555a19b460, a=0x7fffa800fee8, ret=0x0)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:443
#11 0x00007ffff40bf10c in QObject::event(QEvent*) (this=0x55555a19b460, e=0x7fffa800fea0) at kernel/qobject.cpp:1314
#12 0x00007ffff4b81783 in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    (this=<optimized out>, receiver=0x55555a19b460, e=0x7fffa800fea0) at kernel/qapplication.cpp:3632
#13 0x00007ffff1be26b3 in QgsApplication::notify(QObject*, QEvent*) (this=
    0x7fffffffd5e0, receiver=0x55555a19b460, event=0x7fffa800fea0)
    at /home/webmaster/dev/cpp/QGIS/src/core/qgsapplication.cpp:509
```
