### ISSUE TITLE
IDW Interpolation Cannot Be Edited in Model Designer

### ISSUE THREAD

**Issue by dzar-aker** [qgis/QGIS#45077]
### What is the bug or the crash?

After instantiating an IDW Interpolation algorithm in the model designer, one cannot open it, again, to edit. When you try, you get the an error and in the Python error window you see:

`2021-09-15T11:31:24     WARNING    Traceback (most recent call last):
              File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins\processing\modeler\ModelerGraphicItem.py", line 161, in editComponent
              self.edit()
              File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins\processing\modeler\ModelerGraphicItem.py", line 135, in edit
              self.component().configuration())
              File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins\processing\modeler\ModelerParametersDialog.py", line 79, in __init__
              self.widget = ModelerParametersWidget(alg, model, algName, configuration, context=self.context, dialog=self)
              File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins\processing\modeler\ModelerParametersDialog.py", line 497, in __init__
              self.widget = ModelerParametersPanelWidget(alg, model, algName, configuration, dialog, context)
              File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins\processing\modeler\ModelerParametersDialog.py", line 193, in __init__
              self.setupUi()
              File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins\processing\modeler\ModelerParametersDialog.py", line 315, in setupUi
              self.setPreviousValues()
              File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins\processing\modeler\ModelerParametersDialog.py", line 378, in setPreviousValues
              wrapper.setValue(value)
              File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins\processing\algs\qgis\ui\InterpolationWidgets.py", line 214, in setValue
              self.widget.setValue(value)
              File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins\processing\algs\qgis\ui\InterpolationWidgets.py", line 161, in setValue
              self.addLayerData(v[0], v[1])
             AttributeError: 'InterpolationDataWidget' object has no attribute 'addLayerData'
             `
The model ran fine, but this model/algorithm cannot be edited.

### Steps to reproduce the issue

1. Have a valid layer for interpolation available 
2. Create a model
3. Add the IDW Interpolation algorithm
4. Use the layer from #1 to interpolate and set the other parameters so it produces some output.
5. After setting it up, try to edit it.

(The same happens if you have an invalid model... that is, you don't enter appropriate data in the dialog. When you close it, you are told it's invalid and you cannot re-open it to change the values.)

### Versions

QGIS version
3.16.7-Hannover
QGIS code revision
0471743889
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
db_manager; 
MetaSearch; 
processing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
>  The model ran fine, but this model/algorithm cannot be edited.

@dzar-aker can you please attach a sample model?

**Comment by alexbruy** [comment]
See #30029

**Comment by gioman** [comment]
@alexbruy Closing as duplicate?

**Comment by dzar-aker** [comment]
@giomanyes, looks the same.
