### ISSUE TITLE
QGIS external plug-in PLANHEAT

### ISSUE THREAD

**Issue by SanderBeun** [qgis/QGIS#45156]
### What is the bug or the crash?

Can someone help me?

unable to load plug-in 'planheat' due to an error when calling the mehtode classFactory() 

ModuleNotFoundError: No module named 'planheatclient' 
Traceback (most recent call last):
  File "C:\Users/Public/QGIS3.20/apps/qgis/./python\qgis\utils.py", line 335, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/Public/QGIS3.20/apps/qgis/./python/plugins\planheat\__init__.py", line 43, in classFactory
    from .planheat import PlanHeat
  File "C:\Users/Public/QGIS3.20/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Public/QGIS3.20/apps/qgis/./python/plugins\planheat\planheat.py", line 34, in 
    from .PlanheatMappingModule.planheat_integration import PlanheatIntegration
  File "C:\Users/Public/QGIS3.20/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Public/QGIS3.20/apps/qgis/./python/plugins\planheat\PlanheatMappingModule\planheat_integration.py", line 30, in 
    from .PLANHEAT import PLANHEAT as cmm
  File "C:\Users/Public/QGIS3.20/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Public/QGIS3.20/apps/qgis/./python/plugins\planheat\PlanheatMappingModule\PLANHEAT\PLANHEAT.py", line 10, in 
    from .dialog_utils import node_preferences_action, load_tree_dialog, open_right_click_menu, run_all_nodes, show_result_dialog
  File "C:\Users/Public/QGIS3.20/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Public/QGIS3.20/apps/qgis/./python/plugins\planheat\PlanheatMappingModule\PLANHEAT\dialog_utils.py", line 12, in 
    from .algorithm_utils import valid_structure, run_all, set_progress, run_algorithm_for_node, get_crop_and_straw_yield_value, get_crop_yield_value, \
  File "C:\Users/Public/QGIS3.20/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Public/QGIS3.20/apps/qgis/./python/plugins\planheat\PlanheatMappingModule\PLANHEAT\algorithm_utils.py", line 22, in 
    from .client_api_utils import get_map, clear_api_cache, get_crop_yield
  File "C:\Users/Public/QGIS3.20/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Public/QGIS3.20/apps/qgis/./python/plugins\planheat\PlanheatMappingModule\PLANHEAT\client_api_utils.py", line 4, in 
    from planheatclient import PlanHeatClient
  File "C:\Users/Public/QGIS3.20/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'planheatclient'

Python versie: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS versie: 3.20.3-Odense Odense, 495fbaec 

Python pad:
C:\Users/laptop Innoforte 1/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgissprp\sprp
C:/Users/Public/QGIS3.20/apps/qgis/./python
C:/Users/laptop Innoforte 1/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/laptop Innoforte 1/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/Users/Public/QGIS3.20/apps/qgis/./python/plugins
C:\Users\Public\QGIS3.20\bin\python39.zip
C:\Users\Public\QGIS3.20\apps\Python39\DLLs
C:\Users\Public\QGIS3.20\apps\Python39\lib
C:\Users\Public\QGIS3.20\bin
C:\Users\Public\QGIS3.20\apps\Python39
C:\Users\Public\QGIS3.20\apps\Python39\lib\site-packages
C:\Users\Public\QGIS3.20\apps\Python39\lib\site-packages\win32
C:\Users\Public\QGIS3.20\apps\Python39\lib\site-packages\win32\lib
C:\Users\Public\QGIS3.20\apps\Python39\lib\site-packages\Pythonwin
C:/Users/laptop Innoforte 1/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/laptop Innoforte 1/Documents/qgis

### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/91065948/134000397-02b14135-52c7-443d-a2cb-8feb13615ed0.png)

### Versions

QGIS 3.20.3
Python version 3.9.5

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Gustry** [comment]
The QGIS project can't do anything about a third party plugin. You must report the issue in the plugin code repository.
