### ISSUE TITLE
Adding a new point onto a memory multipoint layer kills QGIS

### ISSUE THREAD

**Issue by nirvn** [qgis/QGIS#45152]
### What is the bug or the crash?

Title says it all. Adding a point onto a multipoint layer kills QGIS. It's not limited to memory layer, I see it on postgis layers too.

### Steps to reproduce the issue

1. create a new project, set crs to wgs84
2. add a new memory layer, set it to multipoint and crs to wgs84 
3. add a new point
4. *boom*

### Versions

QGIS master

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nirvn** [comment]
gdb trace:

```
#1  0x00007ffff0746864 in __GI_abort () at abort.c:79
#2  0x0000555555563d50 in qgisCrash(int) (signal=-1) at /home/webmaster/dev/cpp/QGIS/src/app/main.cpp:361
#3  0x00005555555642f0 in myMessageOutput(QtMsgType, QMessageLogContext const&, QString const&) (type=QtFatalMsg, msg=...)
    at /home/webmaster/dev/cpp/QGIS/src/app/main.cpp:446
#4  0x00007ffff3e01bd8 in qt_message_print(QtMsgType, QMessageLogContext const&, QString const&) (msgType=QtFatalMsg, context=..., message=...)
    at global/qlogging.cpp:1843
#5  0x00007ffff3e01cf9 in qt_message(QtMsgType, const QMessageLogContext &, const char *, typedef __va_list_tag __va_list_tag *)
    (msgType=QtFatalMsg, context=..., msg=<optimized out>, ap=<optimized out>) at global/qlogging.cpp:378
#6  0x00007ffff3dcdc5e in QMessageLogger::fatal(char const*, ...) const
    (this=this@entry=0x7fffffffc258, msg=msg@entry=0x7ffff40dbea0 "ASSERT: \"%s\" in file %s, line %d") at global/qlogging.cpp:890
#7  0x00007ffff3dcd08c in qt_assert(char const*, char const*, int) (assertion=<optimized out>, file=<optimized out>, line=<optimized out>)
    at global/qglobal.cpp:3358
#8  0x00007ffff248c05c in QgsPoint::QgsPoint(QgsWkbTypes::Type, double, double, double, double) (this=
    0x7fffffffc3e0, wkbType=QgsWkbTypes::MultiPoint, x=-0.056882821387940874, y=0.31968145620022759, z=nan(0x8000000000000), m=nan(0x8000000000000))
    at /home/webmaster/dev/cpp/QGIS/src/core/geometry/qgspoint.cpp:94
#9  0x00007ffff634e5d0 in QgsMapToolDigitizeFeature::cadCanvasReleaseEvent(QgsMapMouseEvent*) (this=0x5555574fc100, e=0x55555a1e7f80)
    at /home/webmaster/dev/cpp/QGIS/src/gui/qgsmaptooldigitizefeature.cpp:174
#10 0x00007ffff6336593 in QgsMapToolAdvancedDigitizing::canvasReleaseEvent(QgsMapMouseEvent*) (this=0x5555574fc100, e=0x55555a1e7f80)
    at /home/webmaster/dev/cpp/QGIS/src/gui/qgsmaptooladvanceddigitizing.cpp:92

```

**Comment by uclaros** [comment]
```
Fatal: ASSERT: "QgsWkbTypes::flatType( wkbType ) == QgsWkbTypes::Point" in file ../src/core/geometry/qgspoint.cpp, line 94
```

**Comment by elpaso** [comment]
@nirvn I can have a look while I'm on https://github.com/qgis/QGIS/issues/45148
