### ISSUE TITLE
QGIS on Ubuntu 20.04 - DB Manager

### ISSUE THREAD

**Issue by christina-winkler** [qgis/QGIS#45383]
### What is the bug or the crash?

An error has occurred while executing Python code: 

TypeError: ' 
Traceback (most recent call last):
  File "/usr/share/qgis/python/plugins/db_manager/db_manager_plugin.py", line 111, in run
    from .db_manager import DBManager
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/plugins/db_manager/db_manager.py", line 40, in 
    from .info_viewer import InfoViewer
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/plugins/db_manager/info_viewer.py", line 28, in 
    from .db_plugins.plugin import BaseError, DbError, DBPlugin, Schema, Table
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/plugins/db_manager/db_plugins/__init__.py", line 76, in 
    initDbPluginList()
  File "/usr/share/qgis/python/plugins/db_manager/db_plugins/__init__.py", line 47, in initDbPluginList
    exec(u"from .%s import plugin as mod" % name, globals())
  File "", line 1, in 
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/plugins/db_manager/db_plugins/gpkg/plugin.py", line 25, in 
    from .connector import GPKGDBConnector
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/plugins/db_manager/db_plugins/gpkg/connector.py", line 44, in 
    from osgeo import gdal, ogr, osr
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3/dist-packages/osgeo/__init__.py", line 113, in 
    if python_version TypeError: '

Python version: 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0] 
QGIS version: 3.20.3-Odense Odense, 495fbaecaf 

Python Path:
/usr/share/qgis/python
/home/christina/.local/share/QGIS/QGIS3/profiles/default/python
/home/christina/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/home/christina/.local/lib/python3.8/site-packages
/usr/local/lib/python3.8/dist-packages
/usr/lib/python3/dist-packages
/home/christina/.local/share/QGIS/QGIS3/profiles/default/python

### Steps to reproduce the issue

1. Open QGIS Desktop Application
2. Go to Database Tab
3. Select & Click on DB Manager

### Versions

QGIS version | 3.20.3-Odense | QGIS code revision | 495fbaecaf
-- | -- | -- | --
Qt version | 5.12.8
Python version | 3.8.10
GDAL/OGR version | 3.0.4
PROJ version | 6.3.1
EPSG Registry database version | v10.008 (2020-12-16)
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.9.0-CAPI-1.16.2
SQLite version | 3.31.1
PDAL version | 2.0.1
PostgreSQL client version | 12.8 (Ubuntu 12.8-0ubuntu0.20.04.1)
SpatiaLite version | 5.0.0
QWT version | 6.1.4
QScintilla2 version | 2.11.2
OS version | Ubuntu 20.04.2 LTS
  |   |   |  
Active Python plugins | db_managerMetaSearch

</body></html>

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@christina-winkler how did you installed QGIS, with qgis.org's repos?

**Comment by christina-winkler** [comment]
I followed the instructions on the most recent version installation on this website: https://www.qgis.org/de/site/forusers/alldownloads.html#debian-ubuntu

**Comment by gioman** [comment]
@christina-winkler see https://github.com/qgis/QGIS/issues/45382#issuecomment-933718274
