### ISSUE TITLE
QGIS on Ubuntu 20.04 Bug - Couldn't load plugin 'processing'

### ISSUE THREAD

**Issue by christina-winkler** [qgis/QGIS#45382]
### What is the bug or the crash?

Couldn't load plugin 'processing' 

TypeError: ' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 313, in loadPlugin
    __import__(packageName)
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/plugins/processing/__init__.py", line 26, in 
    from processing.tools.general import *  # NOQA
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/plugins/processing/tools/general.py", line 32, in 
    from processing.core.Processing import Processing
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/plugins/processing/core/Processing.py", line 57, in 
    from processing.algs.qgis.QgisAlgorithmProvider import QgisAlgorithmProvider  # NOQA
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/plugins/processing/algs/qgis/QgisAlgorithmProvider.py", line 49, in 
    from .HypsometricCurves import HypsometricCurves
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/plugins/processing/algs/qgis/HypsometricCurves.py", line 27, in 
    from osgeo import gdal, ogr, osr
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3/dist-packages/osgeo/__init__.py", line 113, in 
    if python_version TypeError: '

Python version: 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0] 
QGIS version: 3.20.3-Odense Odense, 495fbaecaf 

Python Path:
/usr/share/qgis/python
/home/christina/.local/share/QGIS/QGIS3/profiles/default/python
/home/christina/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/home/christina/.local/lib/python3.8/site-packages
/usr/local/lib/python3.8/dist-packages
/usr/lib/python3/dist-packages
/home/christina/.local/share/QGIS/QGIS3/profiles/default/python

### Steps to reproduce the issue

1. Opening QGIS Desktop application on Ubuntu 20.04

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.20.3-Odense | QGIS code revision | 495fbaecaf
-- | -- | -- | --
Qt version | 5.12.8
Python version | 3.8.10
GDAL/OGR version | 3.0.4
PROJ version | 6.3.1
EPSG Registry database version | v10.008 (2020-12-16)
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.9.0-CAPI-1.16.2
SQLite version | 3.31.1
PDAL version | 2.0.1
PostgreSQL client version | 12.8 (Ubuntu 12.8-0ubuntu0.20.04.1)
SpatiaLite version | 5.0.0
QWT version | 6.1.4
QScintilla2 version | 2.11.2
OS version | Ubuntu 20.04.2 LTS
  |   |   |  
Active Python plugins | db_managerMetaSearch

</body></html>

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@christina-winkler try a new QGIS profile

settings > user profiles > new profile

**Comment by christina-winkler** [comment]
Unfortunately I get the same error message:

Couldn't load plugin 'processing' 

TypeError: ' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 313, in loadPlugin
    __import__(packageName)
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/plugins/processing/__init__.py", line 26, in 
    from processing.tools.general import *  # NOQA
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/plugins/processing/tools/general.py", line 32, in 
    from processing.core.Processing import Processing
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/plugins/processing/core/Processing.py", line 57, in 
    from processing.algs.qgis.QgisAlgorithmProvider import QgisAlgorithmProvider  # NOQA
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/plugins/processing/algs/qgis/QgisAlgorithmProvider.py", line 49, in 
    from .HypsometricCurves import HypsometricCurves
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/plugins/processing/algs/qgis/HypsometricCurves.py", line 27, in 
    from osgeo import gdal, ogr, osr
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3/dist-packages/osgeo/__init__.py", line 113, in 
    if python_version TypeError: '

Python version: 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0] 
QGIS version: 3.20.3-Odense Odense, 495fbaecaf 

Python Path:
/usr/share/qgis/python
/home/christina/.local/share/QGIS/QGIS3/profiles/cewinkler/python
/home/christina/.local/share/QGIS/QGIS3/profiles/cewinkler/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/home/christina/.local/lib/python3.8/site-packages
/usr/local/lib/python3.8/dist-packages
/usr/lib/python3/dist-packages
/home/christina/.local/share/QGIS/QGIS3/profiles/cewinkler/python

**Comment by gioman** [comment]
> Unfortunately I get the same error message:

@christina-winkler there seems to be something wrong with your installation (as this is not a general issue, but let me check that on my Ubuntu 20.04 machine).

Things I usually suggest: 

check if you are not mixing the qgis.org's repo that is not meant to be used together with the ubuntugis one

sudo apt-get purge ...

qgis and any package qgis related (python3-qgis, etc.)

delete /usr/share/qgis

re-install with apt-get install qgis python3-qgis

**Comment by christina-winkler** [comment]
I followed the steps and removed any QGIS dependencies and re-installed with:

$ sudo apt-get install qgis python3-qgis

However, there is no PostGresSQL Databank management button in this version. Is there a possibility to install it still ? I need it for my project.

Also now when launching the application I am getting a Python error:

```
Couldn't load SIP module.
Python support will be disabled.


Traceback (most recent call last):
  File "", line 1, in 
ModuleNotFoundError: No module named 'qgis'


Python version:
3.8.10 (default, Sep 28 2021, 16:10:42) 
[GCC 9.3.0]

QGIS version:
3.20.3-Odense 'Odense', 495fbaecaf

Python path:
['/usr/share/qgis/python', '/home/christina/.local/share/QGIS/QGIS3/profiles/cwinkler/python', '/home/christina/.local/share/QGIS/QGIS3/profiles/cwinkler/python/plugins', '/usr/share/qgis/python/plugins', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/home/christina/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/dist-packages', '/usr/lib/python3/dist-packages']


```

**Comment by gioman** [comment]
> However, there is no PostGresSQL Databank management button in this version. Is there a possibility to install it still ? I need it for my project.
> 
> Also now when launching the application I am getting a Python error:

@christina-winkler it seems you have some serious local installation issue.

**Comment by christina-winkler** [comment]
Do you by any chance have any recommendations on what I can do to fix it ? Thank you for your help !
