### ISSUE TITLE
Opening an hdf5 file in QGIS-LTR V 3.16.11-Hannover causes application to quit

### ISSUE THREAD

**Issue by g-studer-ellis** [qgis/QGIS#45416]
### What is the bug or the crash?

Scenario:
I am working with multispectral data downloaded from NASA Earthdata and am having trouble importing and opening the file in QGIS. Specifically, I have downloaded several granules of VIIRS/NPP Surface Reflectance 8-Day L3 Global 1km SIN Grid V001 products and cannot open them successfully. I can start a new project and open various other file types including NetCDF, GeoTIFF, and png files. However, when I attempt to load a new layer from an HDF5 file QGIS will crash and close.

QGIS Version:
QGIS-LTR V 3.16.11-Hannover

Example File Name:
VNP09A1.A2021265.h17v05.001.2021277005531.h5

Desired Outcome:
The ability to open my files in QGIS and work with the multispectral data to produce various false color images.

What I’ve Tried:
I have tried a variety of different HDF5 files, including different multispectral types. I did run one file through a conversion tool from NASA, which produced a NetCDF file which did open in QGIS. However this adds a few extra steps and is something I would like to avoid if possible.

Operating System: macOS Big Sur 11.6
QGIS Install: Official All-in-one signed installer: QGIS macOS Installer Version 3.16 Long Term Release 

### Steps to reproduce the issue

In a blank new project:

1. Go to "Layer"
2. Scroll down to "Add Layer"
3. Roll mouse over to “Add Raster Layer”
4. Click the "..." box to the right of the "Source" field
5. Navigate to the HDF5 file and click "open"
6. Click "Add"
7. Select bands to render
8. Verify that add layers to a group box is checked (I have tried this checked and unchecked with the same result)
9. Click "OK" 

<img width="1041" alt="Screen Shot 2021-10-05 at 3 19 04 PM" src="https://user-images.githubusercontent.com/81666938/136088946-473d1bb9-b99b-4124-a1ff-513c6568c342.png">

At this point QGIS quits.

### Versions

QGIS version | 3.16.11-Hannover | QGIS code revision | 26cc1c762f
-- | -- | -- | --
Compiled against Qt | 5.14.2 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 3.2.1 | Running against GDAL/OGR | 3.2.1
Compiled against GEOS | 3.9.1-CAPI-1.14.2 | Running against GEOS | 3.9.1-CAPI-1.14.2
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.4
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | macOS 11.6
Active python plugins | processing; db_manager; MetaSearch

<img width="927" alt="Screen Shot 2021-10-05 at 3 22 21 PM" src="https://user-images.githubusercontent.com/81666938/136089170-201dbfad-0924-4a8f-9a1b-a706f903a03f.png">

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by g-studer-ellis** [comment]
Try this link:
https://drive.google.com/file/d/1w2QV2og2c4mLVc2dhDDdPvVnp9vWRzb4/view?usp=sharing

**Comment by gioman** [comment]
>  https://drive.google.com/file/d/1w2QV2og2c4mLVc2dhDDdPvVnp9vWRzb4/view?usp=sharing

can't replicate the problem on Linux and Windows. Will try also on my mac mini.

**Comment by gioman** [comment]
Yes, crash confirmed on macOS Big Sur.

**Comment by g-studer-ellis** [comment]
QGIS still crashes for me when importing an hdf5 file. Is there an eta on when this will be addressed?

**Comment by g-studer-ellis** [comment]
Checking in about an update for this crash issue.

**Comment by fabianlang** [comment]
Happens as well on macOS 12.5 running QGIS 3.22 and QGIS 3.26.

**Comment by richardhyy** [comment]
Also happens on macOS 13.0.1 running QGIS 3.28.

**Comment by GSeyfried** [comment]
Still happening to me :(

**Comment by roger-downing** [comment]
Crash also happens with hdf5 files holding line geometry such as:
https://github.com/ioos/compliance-checker/blob/master/compliance_checker/tests/data/line_geometry.cdl

Just selecting the line geometry layer works and displays the line features, but choosing to load data layers alongside causes a segfault. This is on Mac OS 13.2.1 with QGIS 3.28.3.

**Comment by vbrancat** [comment]
Confirming that qGIS Firenze LTR crashes when opening a HDF5 on Mac OS Ventura 13.6. However, if when opening the HDF5 file, I specify the path to a specific dataset like "`HDF5:"path_to_HDF5_product":/path_to_hdf5_dataset`
then I am able to correctly visualize the dataset without qGIS crashing. However, the dataset is not geolocated properly.

If the same HDF5 file is converted to NetCDF, then it can be opened without any problem.

Is there a plan to address this issue? Most of the dataset generated by NASA mission used HDF5 as their main data format. Not able to correctly visualize them in qGIS is a big loss (and missed opportunity) for all the scientific community.

**Comment by illegalcoding** [comment]
Getting the same thing on FreeBSD 14.0-RELEASE-p5 with both `qgis` and `qgis-ltr` (installed from `pkg`).
Here's the backtrace from the coredump of `qgis` (3.34 Prizren):
```
#0  0x000000087450386a in thr_kill () at /lib/libc.so.7
#1  0x000000087447bf54 in raise () at /lib/libc.so.7
#2  0x000000085da5053f in  () at /lib/libthr.so.3
#3  0x000000085da4fafb in  () at /lib/libthr.so.3
#4  0x0000000820e132d3 in <signal handler called> ()
#5  0x000000087450386a in thr_kill () at /lib/libc.so.7
#6  0x000000087447bf54 in raise () at /lib/libc.so.7
#7  0x000000087452cfc9 in abort () at /lib/libc.so.7
#8  0x000000000024de37 in  ()
#9  0x000000085da5053f in  () at /lib/libthr.so.3
#10 0x000000085da4fafb in  () at /lib/libthr.so.3
#11 0x0000000820e132d3 in <signal handler called> ()
#12 0x000000088dd4a6c2 in H5FL_reg_malloc () at /usr/local/lib/libhdf5.so.200
#13 0x000000088de5dc3b in H5SL_create () at /usr/local/lib/libhdf5.so.200
#14 0x000000088de1a5ba in H5P_create_id () at /usr/local/lib/libhdf5.so.200
#15 0x000000088ddef674 in H5Pcreate () at /usr/local/lib/libhdf5.so.200
#16 0x000000083baadcf2 in  () at /usr/local/lib/libgdal.so.34
#17 0x000000083bab3ebd in  () at /usr/local/lib/libgdal.so.34
#18 0x000000083c100ce5 in GDALDriver::Open(GDALOpenInfo*, bool) () at /usr/local/lib/libgdal.so.34
#19 0x000000083c111204 in GDALOpenEx () at /usr/local/lib/libgdal.so.34
#20 0x0000000834896e4e in  () at /usr/local/lib/libqgis_core.so.3.34.3
#21 0x000000083489adac in  () at /usr/local/lib/libqgis_core.so.3.34.3
#22 0x000000083489f315 in  () at /usr/local/lib/libqgis_core.so.3.34.3
#23 0x0000000834f7bbb2 in QgsSingleBandGrayRenderer::block(int, QgsRectangle const&, int, int, QgsRasterBlockFeedback*) () at /usr/local/lib/libqgis_core.so.3.34.3
#24 0x0000000834f5a201 in QgsBrightnessContrastFilter::block(int, QgsRectangle const&, int, int, QgsRasterBlockFeedback*) () at /usr/local/lib/libqgis_core.so.3.34.3
#25 0x0000000834f5b28b in QgsHueSaturationFilter::block(int, QgsRectangle const&, int, int, QgsRasterBlockFeedback*) () at /usr/local/lib/libqgis_core.so.3.34.3
#26 0x0000000834f79e66 in QgsRasterResampleFilter::block(int, QgsRectangle const&, int, int, QgsRasterBlockFeedback*) () at /usr/local/lib/libqgis_core.so.3.34.3
#27 0x0000000834f33067 in QgsRasterIterator::readNextRasterPartInternal(int, int&, int&, std::__1::unique_ptr<QgsRasterBlock, std::__1::default_delete<QgsRasterBlock> >*, int&, int&, QgsRectangle*, int&, int&, int&, int&) () at /usr/local/lib/libqgis_core.so.3.34.3
#28 0x0000000834f33210 in QgsRasterIterator::readNextRasterPart(int, int&, int&, std::__1::unique_ptr<QgsRasterBlock, std::__1::default_delete<QgsRasterBlock> >&, int&, int&, QgsRectangle*, int*, int*, int*, int*) () at /usr/local/lib/libqgis_core.so.3.34.3
#29 0x0000000834f6a140 in QgsRasterDrawer::draw(QPainter*, QgsRasterViewPort*, QgsMapToPixel const*, QgsRasterBlockFeedback*) () at /usr/local/lib/libqgis_core.so.3.34.3
#30 0x0000000834f4a07c in QgsRasterLayerRenderer::render() () at /usr/local/lib/libqgis_core.so.3.34.3
#31 0x0000000834df92ab in QgsMapRendererParallelJob::renderLayerStatic(LayerRenderJob&) () at /usr/local/lib/libqgis_core.so.3.34.3
#32 0x0000000834dfa33d in  () at /usr/local/lib/libqgis_core.so.3.34.3
#33 0x0000000834dfa392 in  () at /usr/local/lib/libqgis_core.so.3.34.3
#34 0x0000000834dfa504 in  () at /usr/local/lib/libqgis_core.so.3.34.3
#35 0x0000000835fe8640 in QtConcurrent::ThreadEngineBase::run() () at /usr/local/lib/qt5/libQt5Concurrent.so.5
#36 0x000000082a472302 in  () at /usr/local/lib/qt5/libQt5Core.so.5
#37 0x000000082a46e0b9 in  () at /usr/local/lib/qt5/libQt5Core.so.5
#38 0x000000085da46a75 in  () at /lib/libthr.so.3
#39 0x0000000000000000 in  ()
```

**Comment by vbrancat** [comment]
It seems that this issue might be resolved by downloading the new version of the HDF5 files from the HDF Group page and replace them in the qGIS package. So it seems that the solution for this issue is just to update the HDF5 drivers on Mac and Linux platforms.

**Comment by leoleo-1** [comment]
@vbrancat Can you give us more details on what you did to solve this issue? QGIS v.3.34.7 crashes on Mac OS 14.4.1 when trying to open an h5 downloaded from the NASA Earth Explorer (similar to what the user g-studer-ellis had described).

**Comment by g8sqh** [comment]
in https://github.com/qgis/QGIS/issues/30054 I raised a similar issue. You need to build libhdf5 with threadsafe turned on. I'm not a Mac person, so don't know if this is how Mac builds it, but it's essential for QGIS to work well with multiple HDF5 (in my case BAG) files

**Comment by timlinux** [comment]
From the mailing list:


> Over the last few months I've made good progress on the mac build front.
> Since the beginning of the year, a pull request has been open that builds QGIS against recent, updated dependencies and Qt6 and creates a dmg installer for download.
> These packages provide universal binaries that work natively on Intel x64 and ARM machines.

> Overall, the feedback of testers has been encouraging and many things could already be ironed out.

> Since last week it is now also possible to download notarized versions of these builds. The scripts are in https://github.com/opengisch/qgis-notarize/ and in the actions on this repository, the notarized packages can be downloaded and we also have encouraging feedback there.
> Eventually I would like to only notarize releases (and not pull requests) and use an OSGEO certificate (not the current OPENGIS.ch one) and produce the packages on a repository under the qgis organization. I'll handle that in the upcoming weeks.

> Since this is a complete refactoring and cleanup of the mac build chain, it would break the current Qt5 builds and was therefore not merged to not break releases on the QGIS 3 series.

> With the last minor release QGIS 3 approaching, I would like to proceed with merging this right after 3.44 has been branched off. The pull request is rather large so it's good if this has a long cooldown period before it's released with QGIS 4 later this year. Whoever feels comfortable reviewing cmake code changes, please do so before Friday next week, June 20.

> Thanks a lot and best wishes
> Matthias

Could you test with this build so we can see if it is still an issue?
