### ISSUE TITLE
DB Manager: RuntimeError: wrapped C/C++ object of type PGDatabase has been deleted 

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#46051]
### What is the bug or the crash?

I have been using DB Manager on QGIS 3.22 on Windows, and while mosving in between tabs, inclusing the SQL console, I have been getting very often the following error

```
RuntimeError: wrapped C/C++ object of type PGDatabase has been deleted 

Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis-dev/./python/plugins\db_manager\dlg_sql_window.py", line 506, in loadSqlLayer
    layer = self._getSqlLayer(self.filter)
  File "C:\OSGeo4W/apps/qgis-dev/./python/plugins\db_manager\dlg_sql_window.py", line 495, in _getSqlLayer
    layer = self.db.toSqlLayer(query, geomFieldName, uniqueFieldName, newLayerName, layerType,
  File "C:\OSGeo4W/apps/qgis-dev/./python/plugins\db_manager\db_plugins\plugin.py", line 339, in toSqlLayer
    provider = self.dbplugin().providerName()
  File "C:\OSGeo4W/apps/qgis-dev/./python/plugins\db_manager\db_plugins\plugin.py", line 280, in dbplugin
    return self.parent()
RuntimeError: wrapped C/C++ object of type PGDatabase has been deleted
```

### Steps to reproduce the issue

Unclear what the exact steps are. I have seen many times this error while using DB Manager and moving between its tabs, inclusing the SQL console where I was running queries like SELECT and CREATE TABLE

### Versions

QGIS 3.22.0, Windows 10.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by Dumpstar56** [comment]
I am also getting this bug when executing a query in the DB Manager and then trying to load as new layer. I have tried even very simple queries and all throw the same error. No error message other than in the log, which shows this:
 File "D:\Programs/QGIS/apps/qgis/./python/plugins\db_manager\dlg_sql_window.py", line 506, in loadSqlLayer
              layer = self._getSqlLayer(self.filter)
              File "D:\Programs/QGIS/apps/qgis/./python/plugins\db_manager\dlg_sql_window.py", line 495, in _getSqlLayer
              layer = self.db.toSqlLayer(query, geomFieldName, uniqueFieldName, newLayerName, layerType,
              File "D:\Programs/QGIS/apps/qgis/./python/plugins\db_manager\db_plugins\plugin.py", line 339, in toSqlLayer
              provider = self.dbplugin().providerName()
              File "D:\Programs/QGIS/apps/qgis/./python/plugins\db_manager\db_plugins\plugin.py", line 280, in dbplugin
              return self.parent()
             RuntimeError: wrapped C/C++ object of type PGDatabase has been deleted

**Comment by nyalldawson** [comment]
As per https://github.com/qgis/QGIS-Enhancement-Proposals/blob/master/qep-426-demote_dbmanager.md, the db manager plugin is no longer maintained by the QGIS project. Closing as a wont-fix.
