### ISSUE TITLE
"TIN interpolation" in modeller, multiple python errors

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#46168]
### What is the bug or the crash?

When using the TIN interpolation tool in the Modeller, it returns a few different python errors.

### Steps to reproduce the issue

1) add a point or line layer in the project

2) open the modeller, add the TIN interpolation tool

3) set the input with the project layer, set the extent, set the output, press OK

4) not right click "TIn interpolation" in the model  and chose "edit"

```
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis-ltr/./python/plugins\processing\modeler\ModelerGraphicItem.py", line 161, in editComponent
    self.edit()
  File "C:\OSGeo4W/apps/qgis-ltr/./python/plugins\processing\modeler\ModelerGraphicItem.py", line 134, in edit
    dlg = ModelerParametersDialog(elemAlg, self.model(), self.component().childId(),
  File "C:\OSGeo4W/apps/qgis-ltr/./python/plugins\processing\modeler\ModelerParametersDialog.py", line 79, in __init__
    self.widget = ModelerParametersWidget(alg, model, algName, configuration, context=self.context, dialog=self)
  File "C:\OSGeo4W/apps/qgis-ltr/./python/plugins\processing\modeler\ModelerParametersDialog.py", line 497, in __init__
    self.widget = ModelerParametersPanelWidget(alg, model, algName, configuration, dialog, context)
  File "C:\OSGeo4W/apps/qgis-ltr/./python/plugins\processing\modeler\ModelerParametersDialog.py", line 193, in __init__
    self.setupUi()
  File "C:\OSGeo4W/apps/qgis-ltr/./python/plugins\processing\modeler\ModelerParametersDialog.py", line 315, in setupUi
    self.setPreviousValues()
  File "C:\OSGeo4W/apps/qgis-ltr/./python/plugins\processing\modeler\ModelerParametersDialog.py", line 378, in setPreviousValues
    wrapper.setValue(value)
  File "C:\OSGeo4W/apps/qgis-ltr/./python/plugins\processing\algs\qgis\ui\InterpolationWidgets.py", line 214, in setValue
    self.widget.setValue(value)
  File "C:\OSGeo4W/apps/qgis-ltr/./python/plugins\processing\algs\qgis\ui\InterpolationWidgets.py", line 161, in setValue
    self.addLayerData(v[0], v[1])
AttributeError: 'InterpolationDataWidget' object has no attribute 'addLayerData'
```

**or**

1) blank project

2) open the modeller, add the TIN interpolation tool

3) Press the green "+" button

```
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis-ltr/./python/plugins\processing\algs\qgis\ui\InterpolationWidgets.py", line 117, in addLayer
    self._addLayerData(layer.name(), attribute)
AttributeError: 'NoneType' object has no attribute 'name'

```

**or**

1) blank project

2) open the modeller, add the TIN interpolation tool

3) define an output name, press OK

4) try edit the TIN interpolation tool

```
2021-11-22T22:01:58     WARNING    Traceback (most recent call last):
              File "C:\OSGeo4W/apps/qgis-ltr/./python/plugins\processing\modeler\ModelerGraphicItem.py", line 161, in editComponent
              self.edit()
              File "C:\OSGeo4W/apps/qgis-ltr/./python/plugins\processing\modeler\ModelerGraphicItem.py", line 134, in edit
              dlg = ModelerParametersDialog(elemAlg, self.model(), self.component().childId(),
              File "C:\OSGeo4W/apps/qgis-ltr/./python/plugins\processing\modeler\ModelerParametersDialog.py", line 79, in __init__
              self.widget = ModelerParametersWidget(alg, model, algName, configuration, context=self.context, dialog=self)
              File "C:\OSGeo4W/apps/qgis-ltr/./python/plugins\processing\modeler\ModelerParametersDialog.py", line 497, in __init__
              self.widget = ModelerParametersPanelWidget(alg, model, algName, configuration, dialog, context)
              File "C:\OSGeo4W/apps/qgis-ltr/./python/plugins\processing\modeler\ModelerParametersDialog.py", line 193, in __init__
              self.setupUi()
              File "C:\OSGeo4W/apps/qgis-ltr/./python/plugins\processing\modeler\ModelerParametersDialog.py", line 315, in setupUi
              self.setPreviousValues()
              File "C:\OSGeo4W/apps/qgis-ltr/./python/plugins\processing\modeler\ModelerParametersDialog.py", line 378, in setPreviousValues
              wrapper.setValue(value)
              File "C:\OSGeo4W/apps/qgis-ltr/./python/plugins\processing\algs\qgis\ui\InterpolationWidgets.py", line 214, in setValue
              self.widget.setValue(value)
              File "C:\OSGeo4W/apps/qgis-ltr/./python/plugins\processing\algs\qgis\ui\InterpolationWidgets.py", line 158, in setValue
              rows = value.split(';')
             AttributeError: 'NoneType' object has no attribute 'split'
```

### Versions

QGIS 3.16.14

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by jonnyforestGIS** [comment]
I try the same workflows in a fresh install and I can report the same behavior.

**Comment by alexbruy** [comment]
This was already reported multiple times, see #30029, #33406, #38139, #38717, #42484, #45077.

The root of the issue is that TIN interpolation tool uses custom parameter type which does not have modeler wrapper implemented. Moreover this parameter type implementation also needs some love, but it can't be done without breaking API. It is in my TODO.

**Comment by Giemme2701** [comment]
Do you know a method for interpolating analogous to TIN and IDW, but which works in the model designer? My problem is that I have a flooding map which results without datain correspondance of the buildings. I would like to interpolate the water depth values ​​for these holes as well and create a script with model designer. 

![immagine](https://user-images.githubusercontent.com/114734711/193239025-2907bdc2-2631-4bba-9408-69542d18bca2.png)
