### ISSUE TITLE
Metasearch fails to load with:  File Not Found Error

### ISSUE THREAD

**Issue by epifanio** [qgis/QGIS#46289]
### What is the bug or the crash?

A python error when loading the metasearch plugin - I checked and the mentioned file is not in the source tree

![image](https://user-images.githubusercontent.com/18949/144056585-ae68229e-17fc-4807-805b-999dad321f11.png)

```
2021-11-30T14:38:15     CRITICAL    Traceback (most recent call last):
              File "/usr/local/share/qgis/python/qgis/utils.py", line 423, in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              File "/usr/local/share/qgis/python/plugins/MetaSearch/__init__.py", line 29, in classFactory
              from MetaSearch.plugin import MetaSearchPlugin
              File "/usr/local/share/qgis/python/qgis/utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "/usr/local/share/qgis/python/plugins/MetaSearch/plugin.py", line 34, in 
              from MetaSearch.dialogs.maindialog import MetaSearchDialog
              File "/usr/local/share/qgis/python/qgis/utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "/usr/local/share/qgis/python/plugins/MetaSearch/dialogs/maindialog.py", line 51, in 
              from MetaSearch.dialogs.apidialog import APIRequestResponseDialog
              File "/usr/local/share/qgis/python/qgis/utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "/usr/local/share/qgis/python/plugins/MetaSearch/dialogs/apidialog.py", line 30, in 
              BASE_CLASS = get_ui_class('apidialog.ui')
              File "/usr/local/share/qgis/python/plugins/MetaSearch/util.py", line 64, in get_ui_class
              return loadUiType(ui_file_full)[0]
              File "/usr/local/share/qgis/python/qgis/PyQt/uic/__init__.py", line 36, in __loadUiType
              return __PyQtLoadUiType(*args, **kwargs)
              File "/usr/lib/python3/dist-packages/PyQt5/uic/__init__.py", line 200, in loadUiType
              winfo = compiler.UICompiler().compileUi(uifile, code_string, from_imports,
              File "/usr/lib/python3/dist-packages/PyQt5/uic/Compiler/compiler.py", line 111, in compileUi
              w = self.parse(input_stream, resource_suffix)
              File "/usr/lib/python3/dist-packages/PyQt5/uic/uiparser.py", line 1020, in parse
              document = parse(filename)
              File "/usr/lib/python3.9/xml/etree/ElementTree.py", line 1229, in parse
              tree.parse(source, parser)
              File "/usr/lib/python3.9/xml/etree/ElementTree.py", line 569, in parse
              source = open(source, "rb")
             FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/share/qgis/python/plugins/MetaSearch/ui/apidialog.ui'
```

### Steps to reproduce the issue

Build latest Git Master from source  && run the program

### Versions

Git Master at the time of filling this issue

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

### Additional context

```
2021-11-30T14:38:16     INFO    Application state:
             QGIS_PREFIX_PATH env var: 
             Prefix: /usr/local
             Plugin Path: /usr/local/lib/qgis/plugins
             Package Data Path: /usr/local/share/qgis
             Active Theme Name: default
             Active Theme Path: /usr/local/share/qgis/resources/themes/default/icons/
             Default Theme Path: :/images/themes/default/
             SVG Search Paths: /usr/local/share/qgis/svg/
              /home/epinux/.local/share/QGIS/QGIS3/profiles/default/svg/
             User DB Path: /usr/local/share/qgis/resources/qgis.db
             Auth DB Path: /home/epinux/.local/share/QGIS/QGIS3/profiles/default/qgis-auth.db
```

**Comment by agiudiceandrea** [comment]
This should be fixed in https://github.com/qgis/QGIS/pull/46292

**Comment by DelazJ** [comment]
#46292 is now merged
