### ISSUE TITLE
Export layers to DXF can't use multiple input from other algorithms in Model

### ISSUE THREAD

**Issue by FelisPimeja** [qgis/QGIS#46387]
### What is the bug or the crash?

While in Model Designer one can't export muliple algorithms outputs at once using Export layers to DXF.

### Steps to reproduce the issue

1. Start QGIS using new profile
2. Go to model Designer
3. Create simple model that generates 2 buffers from vector layer
4. Try to use **Export layers to DXF** to export both buffers to 1 dxf file
5. No way to select both buffer algorithms outputs at once

### Versions

QGIS version
3.22.1-Białowieża
QGIS code revision
663dcf8fb9
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.0
PROJ version
8.2.0
EPSG Registry database version
v10.038 (2021-10-21)
GEOS version
3.10.0-CAPI-1.16.0
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2004

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by AlisterH** [comment]
I thought it would be possible to workaround this by using the "build virtual vector" algorithm, but unfortunately that fails when used with algorithm outputs, I think because they are generated as memory layers:
```
Traceback (most recent call last):
File "C:\PROGRA~1/QGIS33~1.3/apps/qgis/./python/plugins\processing\algs\gdal\Datasources2Vrt.py", line 124, in processAlgorithm
vrt += f'<OGRVRTLayer name="{html.escape(layerName, True)}">'
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\PROGRA~1\QGIS33~1.3\apps\Python312\Lib\html\__init__.py", line 19, in escape
s = s.replace("&", "&amp;") # Must be done first!
^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'replace'

Execution failed after 0.01 seconds
