### ISSUE TITLE
Uncaught FileNotFoundError: [Errno 2] No existe el archivo o el directorio: '/tmp/DEM90mGAlvarado301638882426_piped.tif'


### ISSUE THREAD

**Issue by matiasvaldivia** [qgis/QGIS#46400]
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "/home/mat/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/utils.py", line 419, in exportRaster
    processing.run("gdal:warpreproject", warpArgs)
  File "/usr/share/qgis/python/plugins/processing/tools/general.py", line 108, in run
    return Processing.runAlgorithm(algOrName, parameters, onFinish, feedback, context)
  File "/usr/share/qgis/python/plugins/processing/core/Processing.py", line 168, in runAlgorithm
    raise QgsProcessingException(msg)
_core.QgsProcessingException: No se puede ejecutar el algoritmo
No se pudo cargar la capa de origen para INPUT: no se encontró /tmp/DEM90mGAlvarado301638882426_piped.tif

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mat/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/maindialog.py", line 337, in previewMap
    preview_file = self.createPreview()
  File "/home/mat/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/maindialog.py", line 299, in createPreview
    return writer.write(self.iface,
  File "/home/mat/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/olwriter.py", line 81, in write
    self.preview_file = self.writeOL(iface, feedback,
  File "/home/mat/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/olwriter.py", line 130, in writeOL
    exportLayers(iface, layers, folder, precision, optimize,
  File "/home/mat/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/utils.py", line 237, in exportLayers
    exportRaster(layer, count, layersFolder, feedback, iface, matchCRS)
  File "/home/mat/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/utils.py", line 421, in exportRaster
    shutil.copyfile(piped_file, piped_3857)
  File "/usr/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No existe el archivo o el directorio: '/tmp/DEM90mGAlvarado301638882426_piped.tif'

```
processing 2.12.99, QGIS 3.20.1-Odense on Linux 5.11.0-41-generic

**Comment by gioman** [comment]
> File "/home/mat/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/maindialog.py", line 337, in previewMap

@matiasvaldivia there error comes from the qgis2web plugin, you must report this to the plugin author/s, not here.
