### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 127: invalid continuation byte

### ISSUE THREAD

**Issue by priambiente** [qgis/QGIS#46646]
### What is the bug or the crash?

2021-12-27T19:14:11     WARNING    Traceback (most recent call last):
              File "C:\Users/Priscilla/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QSWATPlus3_9\QSWATPlus\delineation.py", line 1502, in runTauDEM1
              self.runTauDEM(None, False)
              File "C:\Users/Priscilla/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QSWATPlus3_9\QSWATPlus\delineation.py", line 1626, in runTauDEM
              ok = TauDEMUtils.runPitFill(delineationDem, depmask, felFile, numProcesses, self._dlg.taudemOutput)
              File "C:\Users/Priscilla/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QSWATPlus3_9\QSWATPlus\TauDEMUtils.py", line 45, in runPitFill
              return TauDEMUtils.run('pitremove', inFiles, [], [('-fel', felFile)], numProcesses, output, False)
              File "C:\Users/Priscilla/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QSWATPlus3_9\QSWATPlus\TauDEMUtils.py", line 232, in run
              proc = subprocess.run(procCommand,
              File "C:\PROGRA~1\QGIS31~1.15\apps\Python39\lib\subprocess.py", line 507, in run
              stdout, stderr = process.communicate(input, timeout=timeout)
              File "C:\PROGRA~1\QGIS31~1.15\apps\Python39\lib\subprocess.py", line 1121, in communicate
              stdout = self.stdout.read()
              File "C:\PROGRA~1\QGIS31~1.15\apps\Python39\lib\codecs.py", line 322, in decode
              (result, consumed) = self._buffer_decode(data, self.errors, final)
             UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 127: invalid continuation byte

### Steps to reproduce the issue

Install the QGIS 3.16.15 and QSWAT 3.9 installer 2.1.7 ( https://bitbucket.org/ChrisWGeorge/qswatplus3/downloads/ )
Then create a new project, select the DEN and button "Create Streams

### Versions

QGIS 3.16.15 and QSWAT 3.9 installer 2.1.7

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
> and QSWAT 3.9 installer 2.1.7

@priambiente you must report this to the plugin author/s, not here.
