### ISSUE TITLE
DB manager python error

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#46789]
### What is the bug or the crash?

While/after using the SQL console and returning to the "info" tab.

```
TypeError: 'NoneType' object is not iterable 

Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis/./python/plugins\db_manager\dlg_sql_window.py", line 342, in loadAsLayerToggled
    self.fillColumnCombos()
  File "C:\OSGeo4W/apps/qgis/./python/plugins\db_manager\dlg_sql_window.py", line 543, in fillColumnCombos
    for col in cols:
TypeError: 'NoneType' object is not iterable
```

### Steps to reproduce the issue

Not 100% sure about the necessary steps, the event that seems to trigger the error is using the SQL console (load some SELECT query result as layer) and then move to the "info" tab.

### Versions

3.22.2 on Windows 10.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
The error is triggered when checking "Load as new layer"

**Comment by nicogodet** [comment]
https://github.com/qgis/QGIS/blob/24a498b57cc39c7ef2ddcb8bf11eaab7c9d05a8e/python/plugins/db_manager/dlg_sql_window.py#L535

Setting the LIMIT to 1 seems to fix the warning on my side.

**Comment by nyalldawson** [comment]
As per https://github.com/qgis/QGIS-Enhancement-Proposals/blob/master/qep-426-demote_dbmanager.md, the db manager plugin is no longer maintained by the QGIS project. Closing as a wont-fix.
