### ISSUE TITLE
Failed to build QGIS from source

### ISSUE THREAD

**Issue by jiapei100** [qgis/QGIS#46811]
### What is the issue about the documentation?

```console
[ 76%] Updating appinfo files...
cd ....../QGIS && /usr/bin/python3.8 ....../QGIS/scripts/ts2appinfo.py ....../QGIS/build
Traceback (most recent call last):
  File "....../QGIS/scripts/ts2appinfo.py", line 26, in <module>
    from PyQt5.QtCore import QCoreApplication, QTranslator
ModuleNotFoundError: No module named 'PyQt5.QtCore'
make[2]: *** [i18n/CMakeFiles/translations.dir/build.make:156: org.qgis.qgis.desktop] Error 1
make[2]: Leaving directory '....../QGIS/build'
make[1]: *** [CMakeFiles/Makefile2:9527: i18n/CMakeFiles/translations.dir/all] Error 2
make[1]: Leaving directory '....../QGIS/build'
```

When I did **cmake** configuration, I got:

```console
 Traceback (most recent call last):
   File "<string>", line 1, in <module>
 ModuleNotFoundError: No module named 'PyQt5.Qsci'
 Found FCGI: /usr/lib/x86_64-linux-gnu/libfcgi.so
 Using PROJ >= 6 srs database.
 Qsci sip file not found - disabling bindings for derived classes
```

Any suggestions?

**Comment by gioman** [comment]
@jiapei100 for problems building from source please use the QGIS developers mailing list,
