### ISSUE TITLE
compilation fails against SIP 6.5.1 for QGIS 3.22.3

### ISSUE THREAD

**Issue by okanisis** [qgis/QGIS#47313]
### What is the bug or the crash?

When compiling against SIP 6.5.1 on Arch Linux it fails with:
```
[ 77%] Generating core/build/_core/sip_corepart0.cpp, core/build/_core/sip_corepart1.cpp, core/build/_core/sip_corepart2.cpp, core/build/_core/sip_corepart3.cpp, core/build/_core/sip_corepart4.cpp, core/build/_core/sip_corepart5.cpp, core/build/_core/sip_corepart6.cpp, core/build/_core/sip_corepart7.cpp, core/build/_core/sip_corepart8.cpp, core/build/_core/sip_corepart9.cpp, core/build/_core/sip_corepart10.cpp, core/build/_core/sip_corepart11.cpp, core/build/_core/sip_corepart12.cpp, core/build/_core/sip_corepart13.cpp, core/build/_core/sip_corepart14.cpp, core/build/_core/sip_corepart15.cpp

Traceback (most recent call last):
  File "/usr/bin/sip-build", line 33, in <module>
    sys.exit(load_entry_point('sip==6.5.1', 'console_scripts', 'sip-build')())
  File "/usr/bin/sip-build", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration
make[2]: *** [python/CMakeFiles/python_module_qgis__core.dir/build.make:765: python/core/build/_core/sip_corepart0.cpp] Error 1
make[1]: *** [CMakeFiles/Makefile2:9159: python/CMakeFiles/python_module_qgis__core.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```

### Steps to reproduce the issue

Using `makepkg` with the following PKGBUILD here is the `build()` function with `cmake`:
```
build() {
  cmake -B build -S $pkgname-$pkgver \
    -D CMAKE_INSTALL_PREFIX=/usr \
    -D WITH_3D=TRUE \
    -D WITH_SERVER=TRUE \
    -D WITH_CUSTOM_WIDGETS=TRUE \
    -D BINDINGS_GLOBAL_INSTALL=TRUE \
    -D QGIS_MANUAL_SUBDIR=share/man \
    -D WITH_QWTPOLAR=TRUE \
    -D QWTPOLAR_LIBRARY=/usr/lib/libqwt.so \
    -D QWTPOLAR_INCLUDE_DIR=/usr/include/qwt \
    -D CMAKE_CXX_FLAGS="${CXXFLAGS} -DQWT_POLAR_VERSION=0x060200" \
    -D WITH_INTERNAL_QWTPOLAR=FALSE \
    -D WITH_PDAL=TRUE \
    -D LazPerf_INCLUDE_DIR=/usr/include/lazperf \
    -D PROJ_INCLUDE_DIR=/usr/include

  cmake --build build
}
```

### Versions

QGIS: 3.22.3
OS: ```% uname -a
Linux archasus 5.16.8-arch1-1 #1 SMP PREEMPT Tue, 08 Feb 2022 21:21:08 +0000 x86_64 GNU/Linux```
SIP: 6.5.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
@okanisis you should post your compiling troubles on the developers mailing list rather than here.
