### ISSUE TITLE
Crash from Geometry Generator expression

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#47405]
### What is the bug or the crash?

QGIS crashes when trying to use some expressions

### Steps to reproduce the issue

1. Have a line layer in UTM or something metricish.
2. Make a Geometry Generator Point symbol layer

```
collect_geometries(
	array_foreach(
		generate_series(
			0,
			length($geometry),
			5000
		),
		line_interpolate_point(
			$geometry,
			@element
		)
	)
)
```

3. Display it with a font marker and set its rotation to

```
line_interpolate_angle(
	geometry:=$geometry,
	distance:=(@geometry_part_num-1)*1000
)
```

QGIS crashes.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS-Version | 3.23.0-Master | QGIS-Codeversion | bbfa18f3a2
-- | -- | -- | --
Qt-Version | 5.12.8
Python-Version | 3.8.10
GDAL-Version | 3.0.4
PROJ-Version | 6.3.1
EPSG-Registraturdatenbankversion | v9.8.6 (2020-01-22)
Kompiliert mit GEOS | 3.8.0-CAPI-1.13.1 | Läuft mit GEOS | 3.8.0-CAPI-1.13.1
SQLite-Version | 3.31.1
PDAL-Version | 2.0.1
PostgreSQL-Client-Version | 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)
SpatiaLite-Version | 4.3.0a
QWT-Version | 6.1.4
QScintilla2-Version | 2.11.2
BS-Version | Ubuntu 20.04.3 LTS
  |   |   |  
Diese QGIS-Kopie schreibt Debugausgaben.
  |   |   |  

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> 3.23.0-Master

@kannes does it crash on 3.22.3?

**Comment by kannes** [comment]
I can confirm it crashes in 3.22.3 too.

Don't pay attention to what this is trying to do, it was happening in the middle of some reworking ;)

Backtrace from master:
```
Thread 1 "qgis-git" received signal SIGSEGV, Segmentation fault.
0x00007ffff3902b0b in QgsGeometryCollection::vertexAt (this=<optimized out>, id=...) at /usr/src/debug/qgis/src/core/geometry/qgsgeometrycollection.cpp:901
901	/usr/src/debug/qgis/src/core/geometry/qgsgeometrycollection.cpp: No such file or directory.
(gdb) bt
#0  0x00007ffff3902b0b in QgsGeometryCollection::vertexAt(QgsVertexId) const (this=<optimized out>, id=...) at /usr/src/debug/qgis/src/core/geometry/qgsgeometrycollection.cpp:901
#1  0x00007ffff38f02e7 in QgsGeometry::interpolateAngle(double) const (this=this@entry=0x7fffffff9950, distance=<optimized out>) at /usr/src/debug/qgis/src/core/geometry/qgsgeometry.cpp:2610
#2  0x00007ffff3084abc in fcnLineInterpolateAngle(QVariantList const&, QgsExpressionContext const*, QgsExpression*, QgsExpressionNodeFunction const*) (values=..., parent=0x5555603c2a18) at /usr/src/debug/qgis/src/core/expression/qgsexpressionfunction.cpp:5002
#3  0x00007ffff30a577e in QgsStaticExpressionFunction::func(QList<QVariant> const&, QgsExpressionContext const*, QgsExpression*, QgsExpressionNodeFunction const*) (this=<optimized out>, values=<optimized out>, context=<optimized out>, parent=<optimized out>, node=<optimized out>) at /usr/src/debug/qgis/src/core/expression/qgsexpressionfunction.h:469
#4  0x00007ffff30424c5 in QgsExpressionFunction::run(QgsExpressionNode::NodeList*, QgsExpressionContext const*, QgsExpression*, QgsExpressionNodeFunction const*) (this=0x5555560b9370, args=<optimized out>, context=<optimized out>, parent=<optimized out>, node=<optimized out>) at /usr/src/debug/qgis/src/core/expression/qgsexpressionfunction.cpp:119
#5  0x00007ffff301da06 in QgsExpressionNodeFunction::evalNode(QgsExpression*, QgsExpressionContext const*) (this=0x5555603c0850, parent=0x5555603c2a18, context=0x7fffffffa900) at /usr/src/debug/qgis/src/core/expression/qgsexpressionnodeimpl.cpp:1059
#6  0x00007ffff301ca1c in QgsExpressionNode::eval(QgsExpression*, QgsExpressionContext const*) (this=<optimized out>, parent=parent@entry=0x5555603c2a18, context=context@entry=0x7fffffffa900) at /usr/src/debug/qgis/src/core/expression/qgsexpressionnode.cpp:32
#7  0x00007ffff2fff059 in QgsExpression::evaluate(QgsExpressionContext const*) (this=0x5555603c2a18, context=context@entry=0x7fffffffa900) at /usr/src/debug/qgis/src/core/expression/qgsexpression.cpp:374
#8  0x00007ffff344d648 in QgsProperty::propertyValue(QgsExpressionContext const&, QVariant const&, bool*) const (this=0x7fffffff9d30, context=..., defaultValue=..., ok=0x7fffffff9c0f) at /usr/include/qt/QtCore/qshareddata.h:160
#9  0x00007ffff344d7d7 in QgsProperty::value(QgsExpressionContext const&, QVariant const&, bool*) const (this=0x7fffffff9d30, context=..., defaultValue=..., ok=0x7fffffff9caf) at /usr/src/debug/qgis/src/core/qgsproperty.cpp:591
#10 0x00007ffff344df68 in QgsProperty::valueAsDouble(QgsExpressionContext const&, double, bool*) const (this=this@entry=0x7fffffff9d30, context=..., defaultValue=defaultValue@entry=0, ok=ok@entry=0x7fffffff9d8f) at /usr/src/debug/qgis/src/core/qgsproperty.cpp:696
#11 0x00007ffff344ee21 in QgsAbstractPropertyCollection::valueAsDouble(int, QgsExpressionContext const&, double, bool*) const (this=this@entry=0x55555ab28538, key=key@entry=1, context=..., defaultValue=0, ok=ok@entry=0x7fffffff9d8f) at /usr/src/debug/qgis/src/core/qgspropertycollection.cpp:74
#12 0x00007ffff2e81d34 in QgsFontMarkerSymbolLayer::calculateOffsetAndRotation(QgsSymbolRenderContext&, double, bool&, QPointF&, double&) const (this=0x55555ab28510, context=..., scaledSize=<optimized out>, hasDataDefinedRotation=@0x7fffffff9e37: false, offset=..., angle=@0x7fffffff9e48: 0) at /usr/src/debug/qgis/src/core/symbology/qgsmarkersymbollayer.cpp:3353
#13 0x00007ffff2e82313 in QgsFontMarkerSymbolLayer::renderPoint(QPointF, QgsSymbolRenderContext&) (this=0x55555ab28510, point=..., context=...) at /usr/src/debug/qgis/src/core/symbology/qgsmarkersymbollayer.cpp:3499
#14 0x00007ffff2e6b3c5 in QgsMarkerSymbol::renderPointUsingLayer(QgsMarkerSymbolLayer*, QPointF, QgsSymbolRenderContext&) (this=<optimized out>, layer=0x55555ab28510, point=..., context=...) at /usr/src/debug/qgis/src/core/symbology/qgsmarkersymbol.cpp:410
#15 0x00007ffff2e6d026 in QgsMarkerSymbol::renderPoint(QPointF, QgsFeature const*, QgsRenderContext&, int, bool) (this=this@entry=0x5555603bf490, point=..., f=f@entry=0x7fffffffa3e0, context=..., layerIdx=layerIdx@entry=0, selected=selected@entry=false) at /usr/src/debug/qgis/src/core/symbology/qgsmarkersymbol.cpp:431
#16 0x00007ffff2f18bdd in QgsSymbol::renderFeature(QgsFeature const&, QgsRenderContext&, int, bool, bool, Qgis::VertexMarkerType, double) (this=0x5555603bf490, feature=..., context=..., layer=<optimized out>, layer@entry=-1, selected=false, drawVertexMarker=drawVertexMarker@entry=false, currentVertexMarkerType=Qgis::VertexMarkerType::SemiTransparentCircle, currentVertexMarkerSize=currentVertexMarkerSize@entry=0) at /usr/src/debug/qgis/src/core/symbology/qgssymbol.cpp:1282
#17 0x00007ffff2e3022f in QgsGeometryGeneratorSymbolLayer::render(QgsSymbolRenderContext&, QgsWkbTypes::GeometryType, QPolygonF const*, QVector<QPolygonF> const*) (this=0x7fffdc01f990, context=..., geometryType=geometryType@entry=QgsWkbTypes::LineGeometry, points=points@entry=0x7fffffffa6c0, rings=rings@entry=0x0) at /usr/src/debug/qgis/src/core/symbology/qgssymbolrendercontext.h:62
#18 0x00007ffff2f1190b in QgsSymbol::renderUsingLayer(QgsSymbolLayer*, QgsSymbolRenderContext&, QgsWkbTypes::GeometryType, QPolygonF const*, QVector<QPolygonF> const*) (this=this@entry=0x5555603499c0, layer=<optimized out>, context=..., geometryType=geometryType@entry=QgsWkbTypes::LineGeometry, points=points@entry=0x7fffffffa6c0, rings=rings@entry=0x0) at /usr/src/debug/qgis/src/core/symbology/qgssymbol.cpp:817
#19 0x00007ffff2e4b33d in QgsLineSymbol::renderPolyline(QPolygonF const&, QgsFeature const*, QgsRenderContext&, int, bool) (this=this@entry=0x5555603499c0, points=..., f=f@entry=0x0, context=..., layerIdx=layerIdx@entry=-1, selected=selected@entry=false) at /usr/src/debug/qgis/src/core/symbology/qgslinesymbol.cpp:248
#20 0x00007ffff2f165a3 in QgsSymbol::bigSymbolPreviewImage(QgsExpressionContext*, QFlags<Qgis::SymbolPreviewFlag>) (this=this@entry=0x5555603499c0, expressionContext=expressionContext@entry=0x55555b799088, flags=..., flags@entry=...) at /usr/src/debug/qgis/src/core/symbology/qgssymbol.cpp:725
#21 0x00007ffff674fd2d in QgsSymbolSelectorWidget::updatePreview() (this=0x55555b798f20) at /usr/include/qt/QtCore/qflags.h:120
#22 0x00007ffff4fffd93 in  () at /usr/lib/libQt5Core.so.5
#23 0x00007ffff66943f3 in QgsLayerPropertiesWidget::emitSignalChanged() (this=0x55555a99b950) at /usr/src/debug/qgis/src/gui/symbology/qgslayerpropertieswidget.cpp:441
#24 0x00007ffff4fffd93 in  () at /usr/lib/libQt5Core.so.5
#25 0x00007ffff4fffd93 in  () at /usr/lib/libQt5Core.so.5
#26 0x00007ffff6dbe874 in QgsPropertyOverrideButton::showExpressionDialog() (this=0x55555d37f730) at /usr/src/debug/qgis/src/gui/qgspropertyoverridebutton.cpp:674
#27 0x00007ffff4fffd93 in  () at /usr/lib/libQt5Core.so.5
#28 0x00007ffff5bbb647 in QMenu::triggered(QAction*) () at /usr/lib/libQt5Widgets.so.5
#29 0x00007ffff5bc33f5 in  () at /usr/lib/libQt5Widgets.so.5
#30 0x00007ffff4fffddf in  () at /usr/lib/libQt5Core.so.5
#31 0x00007ffff5a34417 in QAction::triggered(bool) () at /usr/lib/libQt5Widgets.so.5
#32 0x00007ffff5a39eb0 in QAction::activate(QAction::ActionEvent) () at /usr/lib/libQt5Widgets.so.5
#33 0x00007ffff5bbbee3 in  () at /usr/lib/libQt5Widgets.so.5
#34 0x00007ffff5bbbfc1 in  () at /usr/lib/libQt5Widgets.so.5
#35 0x00007ffff5a77616 in QWidget::event(QEvent*) () at /usr/lib/libQt5Widgets.so.5
#36 0x00007ffff5a411a6 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#37 0x00007ffff5a45fd7 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#38 0x00007ffff32a8a54 in QgsApplication::notify(QObject*, QEvent*) (this=0x7fffffffd300, receiver=0x55555d380020, event=0x7fffffffb7b0) at /usr/src/debug/qgis/src/core/qgsapplication.cpp:515
#39 0x00007ffff4fcf16a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#40 0x00007ffff5a4499f in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () at /usr/lib/libQt5Widgets.so.5
#41 0x00007ffff5a962f3 in  () at /usr/lib/libQt5Widgets.so.5
#42 0x00007ffff5a9737c in  () at /usr/lib/libQt5Widgets.so.5
#43 0x00007ffff5a411a6 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#44 0x00007ffff32a8a54 in QgsApplication::notify(QObject*, QEvent*) (this=0x7fffffffd300, receiver=0x55555d6631b0, event=0x7fffffffbba0) at /usr/src/debug/qgis/src/core/qgsapplication.cpp:515
#45 0x00007ffff4fcf16a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#46 0x00007ffff539df60 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /usr/lib/libQt5Gui.so.5
#47 0x00007ffff53895e5 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Gui.so.5
#48 0x00007fffe146cd90 in  () at /usr/lib/libQt5XcbQpa.so.5
#49 0x00007fffe9d30f13 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#50 0x00007fffe9d870d9 in  () at /usr/lib/libglib-2.0.so.0
#51 0x00007fffe9d2e485 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#52 0x00007ffff501a44a in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#53 0x00007ffff4fc744b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#54 0x00007ffff5bc399d in  () at /usr/lib/libQt5Widgets.so.5
#55 0x00007ffff5c2399f in  () at /usr/lib/libQt5Widgets.so.5
#56 0x00007ffff4fffddf in  () at /usr/lib/libQt5Core.so.5
#57 0x00007ffff5b27cef in  () at /usr/lib/libQt5Widgets.so.5
#58 0x00007ffff5b29ae7 in QAbstractButton::mousePressEvent(QMouseEvent*) () at /usr/lib/libQt5Widgets.so.5
#59 0x00007ffff5c23dec in QToolButton::mousePressEvent(QMouseEvent*) () at /usr/lib/libQt5Widgets.so.5
#60 0x00007ffff5a77916 in QWidget::event(QEvent*) () at /usr/lib/libQt5Widgets.so.5
#61 0x00007ffff5a411a6 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#62 0x00007ffff5a45fd7 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#63 0x00007ffff32a8a54 in QgsApplication::notify(QObject*, QEvent*) (this=0x7fffffffd300, receiver=0x55555d37f730, event=0x7fffffffc7d0) at /usr/src/debug/qgis/src/core/qgsapplication.cpp:515
#64 0x00007ffff4fcf16a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#65 0x00007ffff5a4499f in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () at /usr/lib/libQt5Widgets.so.5
#66 0x00007ffff5a957d7 in  () at /usr/lib/libQt5Widgets.so.5
#67 0x00007ffff5a9737c in  () at /usr/lib/libQt5Widgets.so.5
#68 0x00007ffff5a411a6 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#69 0x00007ffff32a8a54 in QgsApplication::notify(QObject*, QEvent*) (this=0x7fffffffd300, receiver=0x55555a2d4810, event=0x7fffffffcbc0) at /usr/src/debug/qgis/src/core/qgsapplication.cpp:515
#70 0x00007ffff4fcf16a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#71 0x00007ffff539df60 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /usr/lib/libQt5Gui.so.5
#72 0x00007ffff53895e5 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Gui.so.5
#73 0x00007fffe146cd90 in  () at /usr/lib/libQt5XcbQpa.so.5
#74 0x00007fffe9d30f13 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#75 0x00007fffe9d870d9 in  () at /usr/lib/libglib-2.0.so.0
#76 0x00007fffe9d2e485 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#77 0x00007ffff501a44a in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#78 0x00007ffff4fc744b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#79 0x00007ffff4fd2b97 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#80 0x0000555555560871 in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/qgis/src/app/main.cpp:1681

```

**Comment by kannes** [comment]
Thanks @nyalldawson <3
