### ISSUE TITLE
Metasearch: python error starting QGIS 3.24.0

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#47444]
### What is the bug or the crash?

```
ModuleNotFoundError: No module named 'owslib.ogcapi.records' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/usr/share/qgis/python/plugins/MetaSearch/__init__.py", line 29, in classFactory
    from MetaSearch.plugin import MetaSearchPlugin
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/plugins/MetaSearch/plugin.py", line 34, in 
    from MetaSearch.dialogs.maindialog import MetaSearchDialog
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/plugins/MetaSearch/dialogs/maindialog.py", line 49, in 
    from MetaSearch.dialogs.newconnectiondialog import NewConnectionDialog
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/plugins/MetaSearch/dialogs/newconnectiondialog.py", line 34, in 
    from MetaSearch.search_backend import CATALOG_TYPES
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/plugins/MetaSearch/search_backend.py", line 29, in 
    from owslib.ogcapi.records import Records
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'owslib.ogcapi.records'
```

### Steps to reproduce the issue

QGIS 3.24.0 update from QGIS 3.22.3 using QGIS.org's repos, on Linux Mint 20.2.

### Versions

QGIS version
3.24.0-Tisler
QGIS code revision
6b44a42058
Qt version
5.12.8
Python version
3.8.10
GDAL/OGR version
3.0.4
PROJ version
6.3.1
EPSG Registry database version
v9.8.6 (2020-01-22)
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
SQLite version
3.31.1
PDAL version
2.0.1
PostgreSQL client version
12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)
SpatiaLite version
4.3.0a
QWT version
6.1.4
QScintilla2 version
2.11.2
OS version
Linux Mint 20.2

Active Python plugins
processing
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
Should be fixed in #47540.
