### ISSUE TITLE
Metasearch crash in 3.24

### ISSUE THREAD

**Issue by gubuntu** [qgis/QGIS#47667]
### What is the bug or the crash?

2022-03-07T10:54:15     CRITICAL    Traceback (most recent call last):
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 423, in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins/MetaSearch/__init__.py", line 29, in classFactory
              from MetaSearch.plugin import MetaSearchPlugin
              File "/Users/gavinfleming/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/__init__.py", line 32, in __wrapping_ee_import__
              _module_ = __builtin_import__(name, *args, **kwargs)
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins/MetaSearch/plugin.py", line 34, in 
              from MetaSearch.dialogs.maindialog import MetaSearchDialog
              File "/Users/gavinfleming/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/__init__.py", line 32, in __wrapping_ee_import__
              _module_ = __builtin_import__(name, *args, **kwargs)
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins/MetaSearch/dialogs/maindialog.py", line 49, in 
              from MetaSearch.dialogs.newconnectiondialog import NewConnectionDialog
              File "/Users/gavinfleming/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/__init__.py", line 32, in __wrapping_ee_import__
              _module_ = __builtin_import__(name, *args, **kwargs)
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins/MetaSearch/dialogs/newconnectiondialog.py", line 34, in 
              from MetaSearch.search_backend import CATALOG_TYPES
              File "/Users/gavinfleming/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/__init__.py", line 32, in __wrapping_ee_import__
              _module_ = __builtin_import__(name, *args, **kwargs)
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins/MetaSearch/search_backend.py", line 29, in 
              from owslib.ogcapi.records import Records
              File "/Users/gavinfleming/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/__init__.py", line 32, in __wrapping_ee_import__
              _module_ = __builtin_import__(name, *args, **kwargs)
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
             ModuleNotFoundError: No module named 'owslib.ogcapi.records'

### Steps to reproduce the issue

open QGIS

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.24.0-Tisler | QGIS code revision | e6ab9473e0
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 12.2
  |   |   |  
Active Python plugins
QgisModelBaker | v7.0.3
ORStools | 1.5.2
ee_plugin | 0.0.4
geetimeseriesexplorer | 1.1
dataset_qa_workbench | 0.7.1
pg_metadata | 1.1.1
quick_map_services | 0.19.28
stream_feature_extractor | 2.0.0
cartography_tools | 1.2.1
nominatim | 1.4.1
QWater | 3.1.8
SentinelHub | 2.0.0
qgis_stac | 1.0.0
qfieldsync | v4.0.0-beta16
parcel_plugin | 3.8
lizmap | 3.7.4
LDMP | 1.99.1
Projestions | 1.0.1
tile_plus | 0.1
SGDiagramDownloader | 3.0
Mergin | 2021.5.1
geocatbridge | 4.2.1
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20

</body></html>QGIS version
3.24.0-Tisler
QGIS code revision
[e6ab9473e0](https://github.com/qgis/QGIS/commit/e6ab9473e0)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.2
PROJ version
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.11.5
OS version
macOS 12.2

Active Python plugins
QgisModelBaker
v7.0.3
ORStools
1.5.2
ee_plugin
0.0.4
geetimeseriesexplorer
1.1
dataset_qa_workbench
0.7.1
pg_metadata
1.1.1
quick_map_services
0.19.28
stream_feature_extractor
2.0.0
cartography_tools
1.2.1
nominatim
1.4.1
QWater
3.1.8
SentinelHub
2.0.0
qgis_stac
1.0.0
qfieldsync
v4.0.0-beta16
parcel_plugin
3.8
lizmap
3.7.4
LDMP
1.99.1
Projestions
1.0.1
tile_plus
0.1
SGDiagramDownloader
3.0
Mergin
2021.5.1
geocatbridge
4.2.1
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
Already fixed. See #47540
