### ISSUE TITLE
Error when generating XYZ MBTiles, not present in older release of QGis

### ISSUE THREAD

**Issue by AMG1978** [qgis/QGIS#48034]
### What is the bug or the crash?

QGIS version: 3.22.5-Białowieża
QGIS code revision: c2723178
Qt version: 5.15.2
Python version: 3.9.5
GDAL version: 3.4.1
GEOS version: 3.10.2-CAPI-1.16.0
PROJ version: Rel. 8.2.1, January 1st, 2022
PDAL version: 2.3.0 (git-version: 9f35b7)
Algorithm started at: 2022-03-30T08:53:33
Algorithm 'Generate XYZ tiles (MBTiles)' starting…
Input parameters:
{ 'BACKGROUND_COLOR' : QColor(0, 0, 0, 0), 'DPI' : 96, 'EXTENT' : '-12758269.695300000,-11391312.228000000,3827480.908600000,4647655.389000000 [EPSG:3857]', 'METATILESIZE' : 4, 'OUTPUT_FILE' : 'C:/Users/aaron/Downloads/ctmoutpu2t.mbtiles', 'QUALITY' : 75, 'TILE_FORMAT' : 0, 'ZOOM_MAX' : 16, 'ZOOM_MIN' : 8 }

Using 16 CPU Threads:
Generating tiles for zoom level: 8
Generating tiles for zoom level: 9
Generating tiles for zoom level: 10
Generating tiles for zoom level: 11
Traceback (most recent call last):
File "C:\PROGRA~1/QGIS32~1.5/apps/qgis-ltr/./python/plugins\processing\algs\qgis\TilesXYZ.py", line 455, in processAlgorithm
self.generate(writer, parameters, context, feedback)
File "C:\PROGRA~1/QGIS32~1.5/apps/qgis-ltr/./python/plugins\processing\algs\qgis\TilesXYZ.py", line 316, in generate
for result in threadPool.map(self.renderSingleMetatile, metatiles_by_zoom[zoom]):
File "C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\concurrent\futures\_base.py", line 608, in result_iterator
yield fs.pop().result()
File "C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\concurrent\futures\_base.py", line 445, in result
return self.__get_result()
File "C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\concurrent\futures\_base.py", line 390, in __get_result
raise self._exception
File "C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\concurrent\futures\thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "C:\PROGRA~1/QGIS32~1.5/apps/qgis-ltr/./python/plugins\processing\algs\qgis\TilesXYZ.py", line 230, in renderSingleMetatile
self.writer.write_tile(tile, tileImage)
File "C:\PROGRA~1/QGIS32~1.5/apps/qgis-ltr/./python/plugins\processing\algs\qgis\TilesXYZ.py", line 401, in write_tile
self._init_zoom_layer(tile.z)
File "C:\PROGRA~1/QGIS32~1.5/apps/qgis-ltr/./python/plugins\processing\algs\qgis\TilesXYZ.py", line 393, in _init_zoom_layer
self._execute_sqlite("UPDATE metadata SET value='{}' WHERE name='bounds'".format(bounds))
File "C:\PROGRA~1/QGIS32~1.5/apps/qgis-ltr/./python/plugins\processing\algs\qgis\TilesXYZ.py", line 373, in _execute_sqlite
conn.execute(cmd)
sqlite3.OperationalError: database is locked

Execution failed after 45.24 seconds

Loading resulting layers
Algorithm 'Generate XYZ tiles (MBTiles)' finished

### Steps to reproduce the issue

Raster Tools -> Generate XYZ Tiles (MBtiles) -> Draw on canvas, Go.

### Versions

3.24.1 - Failed
3.22.5 - Failed
3.25.0 Nightly - Failed
3.16.9 - Success!
***

QGIS version
3.16.9-Hannover
QGIS code revision
9f8d2f7942
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
db_manager; 
MetaSearch; 
processing

### Supported QGIS version

- [x] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

There's a post on stackexchange from another user about this, but I cannot reply to anything on stackexchange due to spam from my network (Spectrum cable)???   Anyhow, this is on Windows 11 x64 (me) and all the new recent builds dont seem to work, so I went and grabbed that 3.16.9 from mid 2021 and it works perfectly.  Something was introduced, but I have no idea when exactly.

**Comment by agiudiceandrea** [comment]
Some issue as https://github.com/qgis/QGIS/issues/47738?

**Comment by AMG1978** [comment]
ah... yes same issue I believe.  Sorry for double posting.  I dont really
post to things like this.  Thank you.

**Comment by alexbruy** [comment]
Duplicates #47738.
