### ISSUE TITLE
Couldn't load SIP module. Python support will be disabled. QtCore.abi3.so: undefined symbol: _ZdlPvm, version Qt_5

### ISSUE THREAD

**Issue by swiss-knight** [qgis/QGIS#48368]
### What is the bug or the crash?

Hi,

the following error is displayed in a pop-up windows when starting a freshly installed QGIS `3.24.2-Tisler` on Ubuntu 22.04:
```
Couldn't load SIP module.
Python support will be disabled.

Traceback (most recent call last):
  File "", line 1, in 
  File "/usr/lib/python3/dist-packages/qgis/__init__.py", line 78, in 
    from qgis.PyQt import QtCore
  File "/usr/lib/python3/dist-packages/qgis/PyQt/QtCore.py", line 24, in 
    from PyQt5.QtCore import *
ImportError: /usr/local/lib/python3.10/dist-packages/PyQt5/QtCore.abi3.so: undefined symbol: _ZdlPvm, version Qt_5

Python version:
3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0]

QGIS version:
3.24.2-Tisler 'Tisler', 13c1a02865

Python path:
['/usr/share/qgis/python',    
'/home/username/.local/share/QGIS/QGIS3/profiles/default/python',    
'/home/username/.local/share/QGIS/QGIS3/profiles/default/python/plugins',    
'/usr/share/qgis/python/plugins',    
'/usr/lib/python310.zip',    
'/usr/lib/python3.10',    
'/usr/lib/python3.10/lib-dynload',    
'/usr/local/lib/python3.10/dist-packages',    
'/usr/lib/python3/dist-packages']
```
QGIS is actually starting, but most of the menus (probably all those related with some Python code under the hood?!) are not there, it's especially true with Plugins; I can only see 4 plugins in the list of the plugin manager...

Here's my apt source file, I strictly followed the [debian/ubuntu section of the documentation](https://www.qgis.org/en/site/forusers/alldownloads.html#debian-ubuntu) for the installation and everything went fine:
```
$ cat /etc/apt/sources.list.d/archive_uri-https_qgis_org_ubuntu-jammy.list 
deb https://qgis.org/ubuntu jammy main
# deb-src https://qgis.org/ubuntu jammy main
```

plus:
```
$ sudo apt-cache policy qgis
qgis:
  Installed: 1:3.24.2+36jammy
  Candidate: 1:3.24.2+36jammy
  Version table:
 *** 1:3.24.2+36jammy 500
        500 https://qgis.org/ubuntu jammy/main amd64 Packages
        100 /var/lib/dpkg/status
     3.22.4+dfsg-3build1 500
        500 http://ch.archive.ubuntu.com/ubuntu jammy/universe amd64 Packages
```

and here are my Python Qt related packages (which mostly came along during the QGIS installation):
```
$ pip3 list | grep -i qt
PyQt5                         5.15.6
PyQt5-Qt5                     5.15.2
PyQt5-sip                     12.10.1
PyQtWebEngine                 5.15.5
PyQtWebEngine-Qt5             5.15.2
QtAwesome                     1.1.1
qtconsole                     5.3.0
QtPy                          2.0.1
sphinxcontrib-qthelp          1.0.3
```

more on Python if needed:
```
$ pip --version
pip 22.0.4 from /usr/local/lib/python3.10/dist-packages/pip (python 3.10)

$ python3 --version
Python 3.10.4
```

and within the standard Python console, in case this could cause some conflicts (?):
```
Python 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyQt5.QtCore import QT_VERSION_STR
>>> from PyQt5.Qt import PYQT_VERSION_STR
>>> from sip import SIP_VERSION_STR
>>> print("Qt version:", QT_VERSION_STR)
Qt version: 5.15.2
>>> print("SIP version:", SIP_VERSION_STR)
SIP version: 6.6.1
>>> print("PyQt version:", PYQT_VERSION_STR)
PyQt version: 5.15.6
>>> 
```

OS and hardware:
```
OS: Ubuntu 22.04 LTS x86_64 
Kernel: 5.15.0-27-generic 
Shell: bash 5.1.16 
DE: GNOME 42.0 
WM: Mutter 
WM Theme: Adwaita 
Terminal: gnome-terminal 
CPU: 11th Gen Intel i7-1165G7 (8) @ 4.700GHz 
GPU: NVIDIA Quadro T500 Mobile 
GPU: Intel TigerLake-LP GT2 [Iris Xe Graphics] 
Memory: 8659MiB / 31827MiB
```

Any hints on how to solve this are welcome.
Thanks a lot!

### Steps to reproduce the issue

- Download QGIS from the deb source `deb https://qgis.org/ubuntu jammy main` on Ubuntu 22.04 (fresh install).    
- Start it.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

QGIS version | 3.24.2-Tisler | QGIS code revision | 13c1a02865
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.4
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04 LTS

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by terezano** [comment]
Hi, I was dealing with this problem earlier today. After several other solutions, what helped me was simply remove the current PyQt5 and now my QGIS (v.22 and v.24) runs on my system (Ubuntu 22.04) with no problems. 

`pip3 uninstall PyQt5`

Hopefully, this will help someone :)

**Comment by swiss-knight** [comment]
Hi,

Thank you for your kind feedback and workaround @terezano 

It seems indeed to fix the issue, but when trying to remove PyQt5 with pip3, there's plenty (1739 !) of files that are not removed:
```
Found existing installation: PyQt5 5.15.6
Uninstalling PyQt5-5.15.6:
  Would remove:
    /usr/local/bin/pylupdate5
    /usr/local/bin/pyrcc5
    /usr/local/bin/pyuic5
    /usr/local/lib/python3.10/dist-packages/PyQt5-5.15.6.dist-info/*
    /usr/local/lib/python3.10/dist-packages/PyQt5/*
  Would not remove (might be manually added):
    /usr/local/lib/python3.10/dist-packages/PyQt5/Qt5/lib/libQt5Bluetooth.so.5
    /usr/local/lib/python3.10/dist-packages/PyQt5/Qt5/lib/libQt5Concurrent.so.5
    /usr/local/lib/python3.10/dist-packages/PyQt5/Qt5/lib/libQt5Core.so.5
    /usr/local/lib/python3.10/dist-packages/PyQt5/Qt5/lib/libQt5DBus.so.5
    /usr/local/lib/python3.10/dist-packages/PyQt5/Qt5/lib/libQt5Designer.so.5
......
```
Which may (or may not) cause some troubles in the future. Hopefully not.

If you still need `pyrcc5` and their command lines friends (`pylupdate5`, `pyuic5`), it seems that you can reinstall them using `apt` instead of `pip3` and QGIS will continue booting normally, without errors.

You can install them with the following command:    
```
$ sudo apt-get install pyqt5-dev-tool
```

But I guess those pip packages were actually coming while installing QGIS itself... I cannot remember exactly but I didn't installed any other software needing them.

**Comment by nyalldawson** [comment]
This is a local issue with a broken Python/Qt environment, not a bug in QGIS

**Comment by dinbach** [comment]
Hi Kyriaki,

Looks like qgis misses the path to python libs.  Could you try something like the following, worked for me ;-)
```
export PYTHONPATH=/usr/lib/python3.8
```
and then simply try to run it with:
qgis

**Comment by Yozpoz64** [comment]
Hi, 

I am getting this same issue and none of the proposed solutions are working.

When I try:
`pip3 uninstall pyqt5`
It tells me PyQt5 is not installed, which is presumably what I want.

When I try:
`export PYTHONPATH=/usr/lib/python3.9`
Nothing changes

I have also tried uninstalling/reinstalling qgis and dependencies and testing the LTR instead of the default stable package.

This error does not appear if I run qgis as root. But I would like to avoid this.

Any help would be much appreciated

**Comment by kyriakima** [comment]
- You can check your packages within your environment with: `pip freeze | grep pyqt ` or `conda list | grep pyqt`
- You will need first to do `conda deactivate` to get out of your environment if you have one then again `conda deactivate` to get out of base and then try to export your python path.
- Then try again to run from terminal `qgis`

**Comment by jef-n** [comment]
> I successfully uninstalled PyQt5-5.15.7. Then pip3 install PyQt5==5.15.5, but still does not like.

You should use jammy's own version (ie. 5.15.6) and not mess with pip.

**Comment by jcaple** [comment]
Thanks for your response.  The issue definitely seems to be a Python Qt5 environment issue, as I can duplicate the qgis python import error from the cli:

>>> from PyQt5.QtCore import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/jc/.local/lib/python3.10/site-packages/PyQt5/QtCore.abi3.so: undefined symbol: _ZdlPvm, version Qt_5

I'll see if I can rectify this outside this forum.

**Comment by jcaple** [comment]
Solved on Ubuntu 22 with python3.10 and Qt 5.15.3.  The trick, as mentioned above, was to uninstall PyQt5 using pip3, which is not intuitively obvious at first.  Apparently pip3 installs some shared libs that are not compatible with the underlying Qt5 installation, so use the apt installation of those instead.  Uninstalling Qt5 and qgis and reinstalling again alllows python to now work in qgis.  Geez.

sudo apt-get install python3-pyqt5
sudo apt-get install qtcreator pyqt5-dev-tools
sudo apt-get install qttools5-dev-tools

**Comment by redhumus** [comment]
HI, I'm experiencing same problem in an almost fresh install of Manjaro and of QGIS. Uninstalling/reinstalling does not solved the problem

**Comment by joh4nd** [comment]
to provide more information, indeed, the following packages are installed with qgis:

```
The following additional packages will be installed:
 python3-pyqt5.qsci python3-pyqt5.qtsql python3-pyqt5.qtsvg python3-pyqt5.qtwebkit python3-qgis python3-qgis-common python3-retrying python3-sip qdoc-qt5 qgis-common qgis-plugin-grass qgis-plugin-grass-common qgis-provider-grass qgis-providers qgis-providers-common qhelpgenerator-qt5 qt3d-assimpsceneimport-plugin qt3d-defaultgeometryloader-plugin qt3d-gltfsceneio-plugin qt3d-scene2d-plugin qt5-assistant qt5-image-formats-plugins qtattributionsscanner-qt5 qtchooser qttools5-dev-tools

The following NEW packages will be installed:
gdal-bin gdal-data grass-core grass-doc libarmadillo10 libassimp5 libcfitsio9 libcharls2 libdap27 libdapclient6v5 libepsilon1 libfreexl1
  libfyba0 libgdal28 libgeos-3.9.0 libgeos-c1v5 libgeotiff5 libhdf4-0-alt libhdf5-cpp-103-1 libkmlbase1 libkmldom1 libkmlengine1
  liblaszip8 libmng1 libnetcdf18 libodbc1 libogdi4.1 libpdal-base12 libpdal-plugin-e57 libpdal-plugin-faux libpdal-plugin-hdf
  libpdal-plugin-i3s libpdal-plugin-icebridge libpdal-plugin-pgpointcloud libpdal-plugins libpdal-util12 libproj19 libqca-qt5-2
  libqca-qt5-2-plugins libqgis-3d3.10.14 libqgis-analysis3.10.14 libqgis-app3.10.14 libqgis-core3.10.14 libqgis-customwidgets
  libqgis-gui3.10.14 libqgis-native3.10.14 libqgis-server3.10.14 libqgisgrass7-3.10.14 libqgispython3.10.14 libqhull8.0
  libqscintilla2-qt5-15 libqscintilla2-qt5-l10n libqt53danimation5 libqt53dcore5 libqt53dextras5 libqt53dinput5 libqt53dlogic5
  libqt53dquickscene2d5 libqt53drender5 libqt5concurrent5 libqt5designercomponents5 libqt5keychain1 libqt5sensors5 libqt5serialport5
  libqt5webkit5 libqwt-qt5-6 librttopo1 libspatialindex6 libspatialite7 libsqlite3-mod-spatialite libsuperlu5 liburiparser1 libxerces-c3.2
  odbcinst odbcinst1debian2 proj-bin proj-data python3-future python3-gdal python3-owslib python3-plotly python3-psycopg2 python3-pyproj
  python3-pyqt5.qsci python3-pyqt5.qtsql python3-pyqt5.qtsvg python3-pyqt5.qtwebkit python3-qgis python3-qgis-common python3-retrying
  python3-sip qdoc-qt5 qgis qgis-common qgis-plugin-grass qgis-plugin-grass-common qgis-provider-grass qgis-providers
  qgis-providers-common qhelpgenerator-qt5 qt3d-assimpsceneimport-plugin qt3d-defaultgeometryloader-plugin qt3d-gltfsceneio-plugin
  qt3d-scene2d-plugin qt5-assistant qt5-image-formats-plugins qtattributionsscanner-qt5 qtchooser qttools5-dev-tools

Get...
qt5-image-formats-plugins
libqt53dcore5
libqt53drender5
libqt53danimation5
libqt53dinput5
libqt53dlogic5
libqt53dextras5
qt3d-assimpsceneimport-plugin
qt3d-defaultgeometryloader-plugin
qt3d-gltfsceneio-plugin
libqt53dquickscene2d5
qt3d-scene2d-plugin
qtchooser
qdoc-qt5
qhelpgenerator-qt5
qt5-assistant
qtattributionsscanner-qt5
libqt5designercomponents5
qttools5-dev-tools
python3-pyqt5.qsci
```

**Comment by JamieMacManaway** [comment]
I encountered this same issue on Debian 13 running qgis 4.0 

What worked for me:

pip uninstall pyqt6 pyqt6-sip
sudo apt purge qgis && sudo apt autoremove
sudo apt update && sudo apt install qgis qgis-plugin-grass

Thanks to all who figured this out!
