### ISSUE TITLE
Update of QGIS and QGIS LTR with OSGEO4W disables processing and other plugins

### ISSUE THREAD

**Issue by antoniolocandro** [qgis/QGIS#48489]
### What is the bug or the crash?

2022-05-09T08:57:54     CRITICAL    Traceback (most recent call last):
              File "C:\OSGeo4W\apps\gdal-dev\lib\site-packages\osgeo\__init__.py", line 30, in swig_import_helper
              return importlib.import_module(mname)
              File "C:\OSGeo4W\apps\Python39\lib\importlib\__init__.py", line 127, in import_module
              return _bootstrap._gcd_import(name[level:], package, level)
              File "", line 1030, in _gcd_import
              File "", line 1007, in _find_and_load
              File "", line 986, in _find_and_load_unlocked
              File "", line 666, in _load_unlocked
              File "", line 565, in module_from_spec
              File "", line 1173, in create_module
              File "", line 228, in _call_with_frames_removed
             ImportError: DLL load failed while importing _gdal: The specified module could not be found.
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              File "C:\Users/Locandro/AppData/Roaming/QGIS/QGIS3\profiles\minimalist/python/plugins\latlontools\__init__.py", line 2, in classFactory
              from .latLonTools import LatLonTools
              File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\Users/Locandro/AppData/Roaming/QGIS/QGIS3\profiles\minimalist/python/plugins\latlontools\latLonTools.py", line 6, in 
              import processing
              File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\OSGeo4W/apps/qgis/./python/plugins\processing\__init__.py", line 26, in 
              from processing.tools.general import * # NOQA
              File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\OSGeo4W/apps/qgis/./python/plugins\processing\tools\general.py", line 32, in 
              from processing.core.Processing import Processing
              File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\OSGeo4W/apps/qgis/./python/plugins\processing\core\Processing.py", line 58, in 
              from processing.algs.qgis.QgisAlgorithmProvider import QgisAlgorithmProvider # NOQA
              File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\OSGeo4W/apps/qgis/./python/plugins\processing\algs\qgis\QgisAlgorithmProvider.py", line 49, in 
              from .HypsometricCurves import HypsometricCurves
              File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\OSGeo4W/apps/qgis/./python/plugins\processing\algs\qgis\HypsometricCurves.py", line 27, in 
              from osgeo import gdal, ogr, osr
              File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\OSGeo4W\apps\gdal-dev\lib\site-packages\osgeo\__init__.py", line 46, in 
              _gdal = swig_import_helper()
              File "C:\OSGeo4W\apps\gdal-dev\lib\site-packages\osgeo\__init__.py", line 42, in swig_import_helper
              raise ImportError(traceback_string + '\n' + msg)
             ImportError: Traceback (most recent call last):
              File "C:\OSGeo4W\apps\gdal-dev\lib\site-packages\osgeo\__init__.py", line 30, in swig_import_helper
              return importlib.import_module(mname)
              File "C:\OSGeo4W\apps\Python39\lib\importlib\__init__.py", line 127, in import_module
              return _bootstrap._gcd_import(name[level:], package, level)
              File "", line 1030, in _gcd_import
              File "", line 1007, in _find_and_load
              File "", line 986, in _find_and_load_unlocked
              File "", line 666, in _load_unlocked
              File "", line 565, in module_from_spec
              File "", line 1173, in create_module
              File "", line 228, in _call_with_frames_removed
             ImportError: DLL load failed while importing _gdal: The specified module could not be found.
             
             On Windows, with Python >= 3.8, DLLs are no longer imported from the PATH.
             If gdalXXX.dll is in the PATH, then set the USE_PATH_FOR_GDAL_PYTHON=YES environment variable
             to feed the PATH into os.add_dll_directory().
             
### Steps to reproduce the issue

Update using osgeo4w, don't know if it is QGIS related or osgeo4w as there is a similar ticket but for dev version which I don't experience https://trac.osgeo.org/osgeo4w/ticket/742 but I can't open ticket there as it needs user/password and some additional hoops to get one

### Versions

QGIS version
3.24.2-Tisler
QGIS code revision
13c1a02865
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.4.3
PROJ version
9.0.0
EPSG Registry database version
v10.054 (2022-02-13)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
DigitizingTools
1.5.1
MemoryLayerSaver
4.0.4
mmqgis
2021.9.10
quick_map_services
0.19.29
db_manager
0.1.20

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Another set of messages, QGIS dev version works OK so I suspect something is borked 

2022-05-09T08:57:54     WARNING    Python error : Couldn't load plugin 'latlontools' due to an error when calling its classFactory() method See message log (Python Error) for more details.
2022-05-09T08:57:54     WARNING    Python error : Couldn't load plugin 'qconsolidate3' due to an error when calling its classFactory() method See message log (Python Error) for more details.
2022-05-09T08:57:54     WARNING    Python error : Couldn't load plugin 'shapetools' due to an error when calling its classFactory() method See message log (Python Error) for more details.
2022-05-09T08:57:55     WARNING    Python error : Couldn't load plugin 'grassprovider' due to an error when calling its classFactory() method See message log (Python Error) for more details.
2022-05-09T08:57:55     WARNING    Python error : Couldn't load plugin 'processing' See message log (Python Error) for more details.

**Comment by DelazJ** [comment]
@antoniolocandro Am I wrong in that the "what is the bug or the crash?" section contains the same stack trace multiple times?

**Comment by agiudiceandrea** [comment]
@antoniolocandro the first lines of error messages are related to qgis-dev, while the long block of error messages is related to qgis, so it is not clear to me for which QGIS version the issue occurs.
Anyway, have you updated also the gdal* packages? Have you installed qgis / qgis-dev using the OSGeo4W installer in an empty folder?

**Comment by agiudiceandrea** [comment]
I've installed the current version of "QGIS Desktop 3.24.2" (qgis-full 3.24.2-2 and all its dependencies) using the OSGeo4W Network Installer: no Python errors reported and Processing plugin enabled and working.

I've afterwards also installed "QGIS Desktop 3.25.0 (Nightly)" (qgis-dev-full 3.25.0-235-9d492effcb-1 and all its dependencies): no Python errors reported and Processing plugin enabled and working for both QGIS Desktop 3.24.2 and QGIS Desktop 3.25.0 (Nightly).

**Comment by antoniolocandro** [comment]
I will try once again to install, but this happened again today , I am running Windows 11 @agiudiceandrea if that makes any difference

 CRITICAL    Traceback (most recent call last):
              File "C:\OSGeo4W\apps\gdal-dev\lib\site-packages\osgeo\__init__.py", line 30, in swig_import_helper
              return importlib.import_module(mname)
              File "C:\OSGeo4W\apps\Python39\lib\importlib\__init__.py", line 127, in import_module
              return _bootstrap._gcd_import(name[level:], package, level)
              File "", line 1030, in _gcd_import
              File "", line 1007, in _find_and_load
              File "", line 986, in _find_and_load_unlocked
              File "", line 666, in _load_unlocked
              File "", line 565, in module_from_spec
              File "", line 1173, in create_module
              File "", line 228, in _call_with_frames_removed
             ImportError: DLL load failed while importing _gdal: The specified module could not be found.

**Comment by agiudiceandrea** [comment]
> I am running Windows 11 @agiudiceandrea if that makes any difference

Maybe. I'm using Windows 10.
Anyway I've just installed the latest currently available qgis-dev 3.25.0-242-2455942568-1 and gdal-dev 3.6.0-16-8e2e7c1840-1 without issues.
You could follow the advise (adapting it to your case) of @jef-n in order to spot the missing dll: https://github.com/qgis/QGIS/issues/26891#issuecomment-495889169 - https://issues.qgis.org/issues/19061#note-16

**Comment by antoniolocandro** [comment]
This is what I get, unfortunately this is how far I can get on the tech side, I do not know how to interpret the result 

[qgis_app.zip](https://github.com/qgis/QGIS/files/8741665/qgis_app.zip)

I did found something interesting, if I double click the qgis.bat file I do not get the error (only found out using your tip above as it mentions to double click the bat file) , but if I use the shell then it does. Also double clicking the exe works fine

![image](https://user-images.githubusercontent.com/4627073/169565449-b752a6fc-8e9c-4c78-b4a9-0de9c022c096.png)

**Comment by agiudiceandrea** [comment]
@antoniolocandro, is this issue report still valid with latest QGIS versions?

**Comment by antoniolocandro** [comment]
I will close it as it is not happening this at the moment but something different which I will open a ticket in the future if it keeps popping up
