### ISSUE TITLE
startup issue 

### ISSUE THREAD

**Issue by rsadasivuni** [qgis/QGIS#48552]
### What is the bug or the crash?

Couldn't load plugin 'deep-learning-datasets-maker' due to an error when calling its classFactory() method 

subprocess.CalledProcessError: Command '['python3', '-m', 'pip', 'install', 'Cython', 'scikit-image', 'Pillow', 'pycocotools']' returned non-zero exit status 1. 
Traceback (most recent call last):
  File "C:\Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\deep-learning-datasets-maker\utils\COCO\pycococreatortools\pycococreatortools.py", line 10, in 
    from pycocotools import mask
  File "C:\PROGRA~1/QGIS32~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'pycocotools'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.2/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\deep-learning-datasets-maker\__init__.py", line 35, in classFactory
    from .split_rs_data import SplitRSData
  File "C:\PROGRA~1/QGIS32~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\deep-learning-datasets-maker\split_rs_data.py", line 46, in 
    from .utils.COCO import clip_from_file, slice, from_mask_to_coco
  File "C:\PROGRA~1/QGIS32~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\deep-learning-datasets-maker\utils\COCO\__init__.py", line 1, in 
    from .shape_to_coco import clip_from_file, slice, from_mask_to_coco
  File "C:\PROGRA~1/QGIS32~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\deep-learning-datasets-maker\utils\COCO\shape_to_coco.py", line 16, in 
    from .pycococreatortools import *
  File "C:\PROGRA~1/QGIS32~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\deep-learning-datasets-maker\utils\COCO\pycococreatortools\__init__.py", line 1, in 
    from .pycococreatortools import *
  File "C:\PROGRA~1/QGIS32~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\deep-learning-datasets-maker\utils\COCO\pycococreatortools\pycococreatortools.py", line 15, in 
    subprocess.check_call(
  File "C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python3', '-m', 'pip', 'install', 'Cython', 'scikit-image', 'Pillow', 'pycocotools']' returned non-zero exit status 1.

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.24.2-Tisler Tisler, 13c1a028 

Python Path:
C:\Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\leastcostpath
C:\Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Coregistration
C:/PROGRA~1/QGIS32~1.2/apps/qgis/./python
C:/Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.2/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.24.2\bin\python39.zip
C:\PROGRA~1\QGIS32~1.2\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib
C:\Program Files\QGIS 3.24.2\bin
C:\PROGRA~1\QGIS32~1.2\apps\Python39
C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\site-packages\GDAL-3.4.2-py3.9-win-amd64.egg
C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\site-packages\Pythonwin
C:/Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\Admin\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows
C:\Users\Admin\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qLidar
C:\Users\Admin\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qLidar\libCpp
C:\Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qLidar

### Steps to reproduce the issue

Couldn't load plugin 'deep-learning-datasets-maker' due to an error when calling its classFactory() method 

subprocess.CalledProcessError: Command '['python3', '-m', 'pip', 'install', 'Cython', 'scikit-image', 'Pillow', 'pycocotools']' returned non-zero exit status 1. 
Traceback (most recent call last):
  File "C:\Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\deep-learning-datasets-maker\utils\COCO\pycococreatortools\pycococreatortools.py", line 10, in 
    from pycocotools import mask
  File "C:\PROGRA~1/QGIS32~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'pycocotools'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.2/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\deep-learning-datasets-maker\__init__.py", line 35, in classFactory
    from .split_rs_data import SplitRSData
  File "C:\PROGRA~1/QGIS32~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\deep-learning-datasets-maker\split_rs_data.py", line 46, in 
    from .utils.COCO import clip_from_file, slice, from_mask_to_coco
  File "C:\PROGRA~1/QGIS32~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\deep-learning-datasets-maker\utils\COCO\__init__.py", line 1, in 
    from .shape_to_coco import clip_from_file, slice, from_mask_to_coco
  File "C:\PROGRA~1/QGIS32~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\deep-learning-datasets-maker\utils\COCO\shape_to_coco.py", line 16, in 
    from .pycococreatortools import *
  File "C:\PROGRA~1/QGIS32~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\deep-learning-datasets-maker\utils\COCO\pycococreatortools\__init__.py", line 1, in 
    from .pycococreatortools import *
  File "C:\PROGRA~1/QGIS32~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\deep-learning-datasets-maker\utils\COCO\pycococreatortools\pycococreatortools.py", line 15, in 
    subprocess.check_call(
  File "C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python3', '-m', 'pip', 'install', 'Cython', 'scikit-image', 'Pillow', 'pycocotools']' returned non-zero exit status 1.

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.24.2-Tisler Tisler, 13c1a028 

Python Path:
C:\Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\leastcostpath
C:\Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Coregistration
C:/PROGRA~1/QGIS32~1.2/apps/qgis/./python
C:/Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.2/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.24.2\bin\python39.zip
C:\PROGRA~1\QGIS32~1.2\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib
C:\Program Files\QGIS 3.24.2\bin
C:\PROGRA~1\QGIS32~1.2\apps\Python39
C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\site-packages\GDAL-3.4.2-py3.9-win-amd64.egg
C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\site-packages\Pythonwin
C:/Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\Admin\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows
C:\Users\Admin\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qLidar
C:\Users\Admin\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qLidar\libCpp
C:\Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qLidar

### Versions

QGIS version
3.24.2-Tisler
QGIS code revision
13c1a028
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.2
PROJ version
9.0.0
EPSG Registry database version
v10.054 (2022-02-13)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
coordinates_converter
1.0
Coordtransform
1.1
Coregistration
21.11.20
ee_plugin
0.0.4
GeoCoding
2.18
leastcostpath
1.0
lrs
1.2.1
qLidar
0.7
scpplugin
2.0
SemiAutomaticClassificationPlugin
7.10.6
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

loading issue

**Comment by nicogodet** [comment]
Not a QGIS issue
You should report this on the faulty plugin repo.

**Comment by rduivenvoorde** [comment]
Yep, you should be here: https://github.com/deepbands/deep-learning-datasets-maker/issues

The plugin is trying to install some python plugins, which is failing.

Please close this one here, and address your problem to the plugin authors

**Comment by uclaros** [comment]
This is a plugin issue as mentioned above
