### ISSUE TITLE
Fail to build qgis 3.24.3 and 3.22.7 with SIP 6.6

### ISSUE THREAD

**Issue by kikislater** [qgis/QGIS#48569]
### What is the bug or the crash?

Unable to build Qgis with SIP 6.6.1

### Steps to reproduce the issue

1. cmake options : 
```
  cmake -S $pkgname-$pkgver -B build -G Ninja \
    -DCMAKE_INSTALL_PREFIX='/usr' \
    -DWITH_3D=TRUE \
    -DWITH_SERVER=TRUE \
    -DWITH_CUSTOM_WIDGETS=TRUE \
    -DBINDINGS_GLOBAL_INSTALL=TRUE \
    -DQGIS_MANUAL_SUBDIR=share/man \
    -DWITH_QWTPOLAR=TRUE \
    -DQWTPOLAR_LIBRARY=/usr/lib/libqwt.so \
    -DQWTPOLAR_INCLUDE_DIR=/usr/include/qwt \
    -DCMAKE_CXX_FLAGS="${CXXFLAGS} -DQWT_POLAR_VERSION=0x060200" \
    -DWITH_INTERNAL_QWTPOLAR=FALSE \
    -DWITH_PDAL=TRUE \
    -DUSE_OPENCL=ON

```

2. Error : 
```
Traceback (most recent call last):
  File "/usr/bin/sip-build", line 33, in <module>
    sys.exit(load_entry_point('sip==6.6.1', 'console_scripts', 'sip-build')())
  File "/usr/bin/sip-build", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration

```

### Versions

Qgis 3.24.3
Qgis 3.22.7

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Sip version patched according to https://www.mail-archive.com/qgis-developer@lists.osgeo.org/msg54040.html

```
$ pacman -Q sip
sip 6.6.1-3
```

**Comment by kikislater** [comment]
Same as here : https://github.com/qgis/QGIS/issues/47313

I had python-sip4 and sip 6 installed which cause the problem : 
```
  File "/usr/bin/sip-build", line 33, in <module>
    sys.exit(load_entry_point('sip==6.5.1', 'console_scripts', 'sip-build')())
  File "/usr/bin/sip-build", line 25, in importlib_load_entry_point
    return next(matches).load()
```

Removing python-sip4 solves the problem
