### ISSUE TITLE
PyQgsLocalServer test fails: AttributeError: module 'platform' has no attribute 'dist'

### ISSUE THREAD

**Issue by strk** [qgis/QGIS#48962]
### What is the bug or the crash?

```
 2/47 Test #374: PyQgsLocalServer ..............................***Failed    1.04 sec
export =
export PYTHONPATH=/home/src/qgis/qgis/src/ci/build-ci/output/python:/home/src/qgis/qgis/src/ci/build-ci/output/python/plugins:/home/src/qgis/qgis/src/ci/tests/src/python:
-- Running timeout -sSIGSEGV 55s /usr/bin/python3.8 /home/src/qgis/qgis/src/ci/tests/src/python/test_qgis_local_server.py
Application state:
QGIS_PREFIX_PATH env var:               /home/src/qgis/qgis/src/ci/build-ci/output
Prefix:
Plugin Path:            /home/src/qgis/qgis/src/ci/build-ci/output/lib/qgis/plugins
Package Data Path:      /home/src/qgis/qgis/src/ci/build-ci/output/data
Active Theme Name:
Active Theme Path:      /home/src/qgis/qgis/src/ci/build-ci/output/data/resources/themes//icons/
Default Theme Path:     :/images/themes/default/
SVG Search Paths:       /home/src/qgis/qgis/src/ci/build-ci/output/data/svg/
                /tmp/QGIS-PythonTestConfigPathfgcsoqy7/profiles/default/svg/
User DB Path:   /home/src/qgis/qgis/src/ci/build-ci/output/data/resources/qgis.db
Auth DB Path:   /tmp/QGIS-PythonTestConfigPathfgcsoqy7/profiles/default/qgis-auth.db

Traceback (most recent call last):
  File "/home/src/qgis/qgis/src/ci/tests/src/python/test_qgis_local_server.py", line 44, in <module>
    MAPSERV = getLocalServer()
  File "/home/src/qgis/qgis/src/ci/tests/src/python/qgis_local_server.py", line 693, in getLocalServer
    srv = QgisLocalServer(FCGIBIN)
  File "/home/src/qgis/qgis/src/ci/tests/src/python/qgis_local_server.py", line 297, in __init__
    self._fcgiserv_process = FcgiServerProcess(
  File "/home/src/qgis/qgis/src/ci/tests/src/python/qgis_local_server.py", line 201, in __init__
    ServerProcess.__init__(self)
  File "/home/src/qgis/qgis/src/ci/tests/src/python/qgis_local_server.py", line 75, in __init__
    self._resolve_platform()
  File "/home/src/qgis/qgis/src/ci/tests/src/python/qgis_local_server.py", line 163, in _resolve_platform
    self._dist = platform.dist()
AttributeError: module 'platform' has no attribute 'dist'
CMake Error at PyQgsLocalServer.cmake:23 (message):
  Test failed: 1
```

### Steps to reproduce the issue

Run:
`xvfb-run ctest --output-on-failure -R PyQgsLocalServer`

### Versions

Current master branch as of June 11, 2022 - fc85694420899d4b091765adccfc06116081c874

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

This was run within the docker container also used by CI, with the .ci/run_tests.sh script:

> .ci/run_tests.sh --interactive

**Comment by elpaso** [comment]
I think this test can be removed, it's been in blocklist for years and we have much better tests for the server.

.ci/test_blocklist_qt6.txt
.ci/test_blocklist_qt5.txt
