### ISSUE TITLE
Export Layer(s) Information processing tool suggests unsupported Annotations layer as input

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#49010]
### What is the bug or the crash?

The Export Layer(s) Information processing tool lists the Annotations layer(s?) as potential input for itself.
If one tries to run it on an Annotation layer, it will fail though.

### Steps to reproduce the issue

1. Have a project open
2. Open the Export Layer(s) Information processing tool
3. Click the [...] button to select Input layer(s)
4. Choose the Annotations layer
5. Click run

You get an "Unable to execute algorithm" error dialog with the message "Incorrect parameter value for LAYERS".

![image](https://user-images.githubusercontent.com/7661092/173809442-f4904e9b-4033-4bdd-9571-2b6ee017cff0.png)

The tool should not list the Annotations layer(s) as potential input for itself I guess :)

### Versions

master

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by ismailsunni** [comment]
I tried on Ubuntu 20.04, QGIS 3.22, and I got a result as the following:
![image](https://user-images.githubusercontent.com/1421861/174660398-c2da08cf-6de9-403c-9df1-760d86d109da.png)


but I also got a python error:
```
An error has occurred while executing Python code: 

RuntimeError: wrapped C/C++ object of type QgsProcessingToolboxTreeView has been deleted 
Traceback (most recent call last):
  File "/usr/share/qgis/python/plugins/processing/ProcessingPlugin.py", line 422, in sync_in_place_button_state
    self.toolbox.set_in_place_edit_mode(new_enabled_state and self.editInPlaceAction.isChecked())
  File "/usr/share/qgis/python/plugins/processing/gui/ProcessingToolbox.py", line 132, in set_in_place_edit_mode
    self.algorithmTree.setFilters(filters)
RuntimeError: wrapped C/C++ object of type QgsProcessingToolboxTreeView has been deleted


Python version: 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0] 
QGIS version: 3.24.3-Tisler Tisler, cf22b74e01 

Python Path:
/usr/share/qgis/python
/home/isunni/.local/share/QGIS/QGIS3/profiles/default/python
/home/isunni/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/home/isunni/.local/lib/python3.8/site-packages
/usr/local/lib/python3.8/dist-packages
/usr/lib/python3/dist-packages
/home/isunni/.local/share/QGIS/QGIS3/profiles/default/python
/home/isunni/Documents/qgis/GSoC2019
```

And when I deleted the output layer, I got the same Python error.

**Comment by sladepb** [comment]
I have used the annotations tool to place extensive annotations onto a communications services drawing set (around 256 drawings per set for 4 sets in total in different parts of Australia. I then exported all of my project layers into a gpkg but there was no mechanism which would allow me to export the annotations. Given the usefulness of annotations in developing large area maps it would be very useful to be able to extract the annotations out to a separate element in a gpkg or a postgis database.
