### ISSUE TITLE
AttributeError: 'ScopedName' object has no attribute 'replace'

### ISSUE THREAD

**Issue by ArchangeGabriel** [qgis/QGIS#49214]
When trying to build QGIS 3.26 against Python 3.10.5/Sip 6.6.2, I get the following error:
```python
sip-build: An internal error occurred...
Traceback (most recent call last):
  File "/usr/bin/sip-build", line 33, in <module>
    sys.exit(load_entry_point('sip==6.6.2', 'console_scripts', 'sip-build')())
  File "/usr/lib/python3.10/site-packages/sipbuild/tools/build.py", line 37, in main
    handle_exception(e)
  File "/usr/lib/python3.10/site-packages/sipbuild/exceptions.py", line 81, in handle_exception
    raise e
  File "/usr/lib/python3.10/site-packages/sipbuild/tools/build.py", line 34, in main
    project.build()
  File "/usr/lib/python3.10/site-packages/sipbuild/project.py", line 244, in build
    self.builder.build()
  File "/usr/lib/python3.10/site-packages/sipbuild/builder.py", line 48, in build
    self._generate_bindings()
  File "/usr/lib/python3.10/site-packages/sipbuild/builder.py", line 277, in _generate_bindings
    buildable = bindings.generate()
  File "/usr/lib/python3.10/site-packages/sipbuild/bindings.py", line 166, in generate
    spec, sip_files = parse(self.sip_file, SIP_VERSION, encoding,
  File "/usr/lib/python3.10/site-packages/sipbuild/generator/parser/parser.py", line 35, in parse
    protected_is_public, include_dirs, strict).parse(sip_file)
  File "/usr/lib/python3.10/site-packages/sipbuild/generator/parser/parser_manager.py", line 1507, in parse
    self._parser.parse(self._read(sip_file, raw_sip_file),
  File "/usr/lib/python3.10/site-packages/ply/yacc.py", line 331, in parse
    return self.parseopt(input, lexer, debug, tracking, tokenfunc)
  File "/usr/lib/python3.10/site-packages/ply/yacc.py", line 823, in parseopt
    p.callable(pslice)
  File "/usr/lib/python3.10/site-packages/sipbuild/generator/parser/rules.py", line 3029, in p_typedef_decl
    instantiated = pm.instantiate_class_template(p, name_symbol,
  File "/usr/lib/python3.10/site-packages/sipbuild/generator/parser/parser_manager.py", line 1480, in instantiate_class_template
    instantiate_class(p, symbol, fq_cpp_name, tmpl_names, proto_class,
  File "/usr/lib/python3.10/site-packages/sipbuild/generator/parser/instantiations.py", line 131, in instantiate_class
    i_class.ctors = _instantiate_ctors(tmpl_names, proto_class, template,
  File "/usr/lib/python3.10/site-packages/sipbuild/generator/parser/instantiations.py", line 235, in _instantiate_ctors
    i_ctor.py_signature = _instantiate_signature(proto_ctor.py_signature,
  File "/usr/lib/python3.10/site-packages/sipbuild/generator/parser/instantiations.py", line 368, in _instantiate_signature
    i_arg = _instantiate_argument(proto_arg, proto_class, tmpl_names,
  File "/usr/lib/python3.10/site-packages/sipbuild/generator/parser/instantiations.py", line 191, in _instantiate_argument
    i_arg.default_value = [_instantiate_value(v, expansions)
  File "/usr/lib/python3.10/site-packages/sipbuild/generator/parser/instantiations.py", line 191, in <listcomp>
    i_arg.default_value = [_instantiate_value(v, expansions)
  File "/usr/lib/python3.10/site-packages/sipbuild/generator/parser/instantiations.py", line 437, in _instantiate_value
    i_name = ScopedName.parse(template_string(proto_name, expansions))
  File "/usr/lib/python3.10/site-packages/sipbuild/generator/templates.py", line 201, in template_string
    proto_str = proto_str.replace(name, value)
AttributeError: 'ScopedName' object has no attribute 'replace'
```
Not sure the issue is withing QGIS though…

**Comment by rduivenvoorde** [comment]
@ArchangeGabriel I'am using the exact same versions (Python 3.10.5/Sip 6.6.2, probably you are on Debian Bookworm :-) ), and I'm succesfully building (master AND 3.26) here.

Can you cleanup your build dir and build with a clean environment?

**Comment by ArchangeGabriel** [comment]
Actually I’m building on Arch in a clean chroot. Maybe it’s another option causing this, here is the CMake command:
```
  cmake -S $pkgname-$pkgver -B build -G Ninja \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DWITH_3D=TRUE \
    -DWITH_QUICK=TRUE \
    -DBINDINGS_GLOBAL_INSTALL=TRUE \
    -DSIP_GLOBAL_INSTALL=TRUE \
    -DWITH_STAGED_PLUGINS=FALSE \
    -DWITH_SERVER=TRUE \
    -DWITH_CUSTOM_WIDGETS=TRUE \
    -DWITH_PDAL=TRUE \
    -DHAS_KDE_QT5_PDF_TRANSFORM_FIX=TRUE \
    -DHAS_KDE_QT5_SMALL_CAPS_FIX=TRUE \
    -DHAS_KDE_QT5_FONT_STRETCH_FIX=TRUE
```

**Comment by dhdeangelis** [comment]
> Also, I’ve found one hit on the web: https://www.mail-archive.com/qgis-developer@lists.osgeo.org/msg54150.html So not exactly specific to me either.

Thank you @ArchangeGabriel for opening this issue. I posted the message you mention in the QGIS developer list. I have not yet solved the issue and would be glad to hear the opinions of others on this matter. @rduivenvoorde : cleaning the build environment does not solve the problem.

**Comment by nyalldawson** [comment]
This is an upstream sip/PyQt bug -- you need a newer patch release of the sip build tool to fix it.

**Comment by ArchangeGabriel** [comment]
A newer patch release that does not exist, we even have https://riverbankcomputing.com/hg/sip/rev/1430b279a3c9 on Arch, which is current tip… But I’m OK to say it’s an upstream bug, though this is almost the worst kind of upstream with only a general purpose mailing list as bug tracker.

**Comment by kikitte** [comment]
A possible fix is to replace proto_name with proto_name.base_name in file /usr/lib/python3.10/site-packages/sipbuild/generator/parser/instantiations.py, line 437. Hope it helps. I've build qgis master successfully with this patch.
```python
def _instantiate_value(proto_value, expansions):
    """ Return an instantiated Value object. """
        
       # ...

        if proto_name.is_simple:
            #  old: i_name = ScopedName.parse(template_string(proto_name, expansions))
            i_name = ScopedName.parse(template_string(proto_name.base_name, expansions))

       # ...
```
