### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'mapCanvas' and AttributeError: 'list' object has no attribute 'dataProvider'

### ISSUE THREAD

**Issue by Avijit009** [qgis/QGIS#49557]
### What is the bug or the crash?

ERROR:
```
Traceback (most recent call last):
  File "F:\Code\QGIS\for_nothing.py", line 33, in <module>
    layer = iface.mapCanvas()
AttributeError: 'NoneType' object has no attribute 'mapCanvas'
```

Code:

```
import pandas as pd
import sys
# print (sys.path)
import os.path
import qgis.utils

from qgis.core import QgsApplication
qgishome = 'C:\Program Files\QGIS 3.22.9\apps\qgis-ltr'
app = QgsApplication([], True)
QgsApplication.setPrefixPath(qgishome, True) 

from PyQt5.QtCore import *

from qgis.gui import *
from qgis.utils import iface
from qgis import processing
from PyQt5 import QtGui, QtCore
from qgis.core import *
from qgis.analysis import *
from qgis.core.additions.edit import edit
from PyQt5.QtCore import QVariant

# context = QgsProcessingContext() 
# context.setProject(QgsProject.instance())

# network_layer = QgsProcessingUtils.mapLayerFromString ("/D:/M.Tech/Fifth Sem/MTP/snr/Transport_Road.shp",context)
# point_layer = QgsProcessingUtils.mapLayerFromString ("/D:/M.Tech/Fifth Sem/MTP/snr/projection.shp",context)

# outputpath = "/D:/M.Tech/Fifth Sem/MTP/snr/sinnar.shp"

#creating an empty layer

# layer = iface.mapCanvas()
# cLayer = layer.currentLayer()
cLayer = QgsProject.instance ().mapLayersByName ("None")
provider = cLayer.dataProvider()
# provider = cLayer.QgsDataProvider()
print (provider.encoding(),",", provider.fields(), ",", provider.crs())
```

Error:

```
Traceback (most recent call last):
  File "F:\Code\QGIS\for_nothing.py", line 36, in <module>
    provider = cLayer.dataProvider()
AttributeError: 'list' object has no attribute 'dataProvider'
```
Code: 

```
cLayer = QgsProject.instance (). mapLayersByName ("None")
provider = cLayer.dataProvider()
print (provider.encoding(),",", provider.fields(), ",", provider.crs())
```

also provider.crs() not working. 

How can I resolve this problem?

`QGis.WKBLineString` also not working. It may be changed to another name but I an not able to understand the problem.

### Steps to reproduce the issue

In the first place.
I have tried this both on VS Code and QGIS python console. 
Qgis python console is also problematic because if there is an error for the first time then if I run the code for the second time it is crushing. 

### Versions

QGIS version 3.22.9 Białowieża QGIS code revisiona8e9e6fa
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.1
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
14.3
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
networks
2.6.9
OSMDownloader
1.0.3
qgis2web
3.16.0
realcentroid
1.0.3
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Using QGIS API in VS Code is tricky, you can find a lot of tutorial online (not all up to date).

But in QGIS Python console, it should work fine.

First.
Please copy and paste the content of Help -> About (as requested in issue template).

Second.
Describe step by step how to replicate.
Pasting parts of script is not enough as it depends how this is executed.

Additionaly, `QGis.WKBLineString` is old QGIS API, please read https://api.qgis.org/api/api_break.html

**Comment by Avijit009** [comment]
@nicogodet HI.
While I run this code in qgis python console (Code: https://paste.ofcode.org/Y2Pdf8CeRHQRb76AvDyVBQ ) same error was there. for `mapCanvas ()` first error and `dataProvider() `second error that I have mentioned in the post.

NB: I have pasted the full code on ofcode (though it's wrong but I have debugging this code for last 10 days and still the same)

**Comment by nicogodet** [comment]
your `qgishome` with `\` is incorrect

```python
>>> qgishome = 'C:\Program Files\QGIS 3.22.9\apps\qgis-ltr'
>>> qgishome
'C:\\Program Files\\QGIS 3.22.9\x07pps\\qgis-ltr'
```

If you run your script in QGIS Python console without line 4->7, do you still have an error at `cLayer = qgis.utils.iface.mapCanvas().currentLayer()` ?

**Comment by nicogodet** [comment]
See https://docs.qgis.org/3.22/en/docs/pyqgis_developer_cookbook/intro.html#using-pyqgis-in-standalone-scripts

**Comment by Avijit009** [comment]
> 



> your `qgishome` with `\` is incorrect
> 
> ```python
> >>> qgishome = 'C:\Program Files\QGIS 3.22.9\apps\qgis-ltr'
> >>> qgishome
> 'C:\\Program Files\\QGIS 3.22.9\x07pps\\qgis-ltr'
> ```
> 
> If you run your script in QGIS Python console without line 4->7, do you still have an error at `cLayer = qgis.utils.iface.mapCanvas().currentLayer()` ?
4->7 means which line are you referring to? modeule?

**Comment by Avijit009** [comment]
Also, qgis stop working if I run a code and it failed for two times in a row

**Comment by nicogodet** [comment]
```python
from qgis.core import QgsApplication
qgishome = 'C:\Program Files\QGIS 3.22.9\apps\qgis-ltr'
app = QgsApplication([], True)
QgsApplication.setPrefixPath(qgishome, True) 
```
of https://paste.ofcode.org/Y2Pdf8CeRHQRb76AvDyVBQ

**Comment by Avijit009** [comment]
Then the mapCanvas() working fine but `dataProvider()` is not

```
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS32~1.9\apps\Python39\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "<string>", line 34, in <module>
AttributeError: 'NoneType' object has no attribute 'dataProvider'
```

facing this error.

**Comment by nicogodet** [comment]
Well do you have a layer in you project ?

Try to debug step by step, execute line by line and check output of each line.
I will not do it for you. Come on.

**Comment by Avijit009** [comment]
Okay, I will try that. 

And let you know.

**Comment by nicogodet** [comment]
I think QGIS works fine, you just need to RTFM a bit and debug by your self.

If you still face an issue after debug and you don't understand how you should do, try qgis developer mailing first before opening an issue.

**Comment by Avijit009** [comment]
> 

Okay thank you for your suggestion.

**Comment by roya0045** [comment]
This is clearly not a QGIS issue.

**Comment by gioman** [comment]
> This is clearly not a QGIS issue.

Closing?
