### ISSUE TITLE
Couldn't load plugin 'processing': No module named 'math'

### ISSUE THREAD

**Issue by feefladder** [qgis/QGIS#50278]
### What is the bug or the crash?

On a freshly installed QGIS 3.22

QGIS processing is not working due to spurious errors that may be related to api changes with Python 3.10?
Also I'm unable to use the console.

<details>

```
Couldn't load plugin 'processing' 

ModuleNotFoundError: No module named 'math' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 401, in loadPlugin
    __import__(packageName)
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/plugins/processing/__init__.py", line 24, in 
    from processing.tools.dataobjects import *  # NOQA
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/plugins/processing/tools/dataobjects.py", line 42, in 
    from processing.core.ProcessingConfig import ProcessingConfig
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/plugins/processing/core/ProcessingConfig.py", line 25, in 
    import tempfile
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3.10/tempfile.py", line 184, in 
    from random import Random as _Random
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3.10/random.py", line 49, in 
    from math import log as _log, exp as _exp, pi as _pi, e as _e, ceil as _ceil
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'math'


Python version: 3.10.2 (main, Mar 31 2022, 14:16:47) [GCC 11.2.0] 
QGIS version: 3.22.11-Białowieża Białowieża, 106d33d759 

Python Path:
/usr/share/qgis/python
/home/fee/.local/share/QGIS/QGIS3/profiles/default/python
/home/fee/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python310.zip
/usr/lib/python3.10
/usr/lib/python3.10/lib-dynload
/home/fee/.local/lib/python3.10/site-packages
/usr/local/lib/python3.10/dist-packages
/usr/lib/python3/dist-packages
/home/fee/.local/share/QGIS/QGIS3/profiles/default/python
```
```
Couldn't load plugin 'MetaSearch' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named '_struct' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/usr/share/qgis/python/plugins/MetaSearch/__init__.py", line 29, in classFactory
    from MetaSearch.plugin import MetaSearchPlugin
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/plugins/MetaSearch/plugin.py", line 34, in 
    from MetaSearch.dialogs.maindialog import MetaSearchDialog
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/plugins/MetaSearch/dialogs/maindialog.py", line 33, in 
    from urllib.request import build_opener, install_opener, ProxyHandler
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3.10/urllib/request.py", line 84, in 
    import base64
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3.10/base64.py", line 10, in 
    import struct
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3.10/struct.py", line 13, in 
    from _struct import *
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named '_struct'


Python version: 3.10.2 (main, Mar 31 2022, 14:16:47) [GCC 11.2.0] 
QGIS version: 3.22.11-Białowieża Białowieża, 106d33d759 

Python Path:
/usr/share/qgis/python
/home/fee/.local/share/QGIS/QGIS3/profiles/default/python
/home/fee/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python310.zip
/usr/lib/python3.10
/usr/lib/python3.10/lib-dynload
/home/fee/.local/lib/python3.10/site-packages
/usr/local/lib/python3.10/dist-packages
/usr/lib/python3/dist-packages
/home/fee/.local/share/QGIS/QGIS3/profiles/default/python
```
```
Couldn't load plugin 'sagaprovider' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'math' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/usr/share/qgis/python/plugins/sagaprovider/__init__.py", line 26, in classFactory
    from sagaprovider.SagaProviderPlugin import SagaProviderPlugin
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/plugins/sagaprovider/SagaProviderPlugin.py", line 28, in 
    from sagaprovider.SagaAlgorithmProvider import SagaAlgorithmProvider
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/plugins/sagaprovider/SagaAlgorithmProvider.py", line 33, in 
    from processing.core.ProcessingConfig import ProcessingConfig, Setting
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/plugins/processing/core/ProcessingConfig.py", line 25, in 
    import tempfile
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3.10/tempfile.py", line 184, in 
    from random import Random as _Random
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3.10/random.py", line 49, in 
    from math import log as _log, exp as _exp, pi as _pi, e as _e, ceil as _ceil
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'math'


Python version: 3.10.2 (main, Mar 31 2022, 14:16:47) [GCC 11.2.0] 
QGIS version: 3.22.11-Białowieża Białowieża, 106d33d759 

Python Path:
/usr/share/qgis/python
/home/fee/.local/share/QGIS/QGIS3/profiles/default/python
/home/fee/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python310.zip
/usr/lib/python3.10
/usr/lib/python3.10/lib-dynload
/home/fee/.local/lib/python3.10/site-packages
/usr/local/lib/python3.10/dist-packages
/usr/lib/python3/dist-packages
/home/fee/.local/share/QGIS/QGIS3/profiles/default/python
```
```
Couldn't load plugin 'grassprovider' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'math' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/usr/share/qgis/python/plugins/grassprovider/__init__.py", line 26, in classFactory
    from grassprovider.GrassProviderPlugin import GrassProviderPlugin
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/plugins/grassprovider/GrassProviderPlugin.py", line 28, in 
    from grassprovider.Grass7AlgorithmProvider import Grass7AlgorithmProvider
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/plugins/grassprovider/Grass7AlgorithmProvider.py", line 33, in 
    from processing.core.ProcessingConfig import (ProcessingConfig, Setting)
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/plugins/processing/core/ProcessingConfig.py", line 25, in 
    import tempfile
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3.10/tempfile.py", line 184, in 
    from random import Random as _Random
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3.10/random.py", line 49, in 
    from math import log as _log, exp as _exp, pi as _pi, e as _e, ceil as _ceil
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'math'


Python version: 3.10.2 (main, Mar 31 2022, 14:16:47) [GCC 11.2.0] 
QGIS version: 3.22.11-Białowieża Białowieża, 106d33d759 

Python Path:
/usr/share/qgis/python
/home/fee/.local/share/QGIS/QGIS3/profiles/default/python
/home/fee/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python310.zip
/usr/lib/python3.10
/usr/lib/python3.10/lib-dynload
/home/fee/.local/lib/python3.10/site-packages
/usr/local/lib/python3.10/dist-packages
/usr/lib/python3/dist-packages
/home/fee/.local/share/QGIS/QGIS3/profiles/default/python
```
```
An error occurred during execution of following code:
import pyplugin_installer


Traceback (most recent call last):
  File "", line 1, in 
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/pyplugin_installer/__init__.py", line 31, in 
    from . import installer
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/pyplugin_installer/installer.py", line 28, in 
    import zipfile
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3.10/zipfile.py", line 6, in 
    import binascii
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'binascii'


Python version:
3.10.2 (main, Mar 31 2022, 14:16:47) [GCC 11.2.0]

QGIS version:
3.22.11-Białowieża 'Białowieża', 106d33d759

Python path:
['/usr/share/qgis/python', '/home/fee/.local/share/QGIS/QGIS3/profiles/default/python', '/home/fee/.local/share/QGIS/QGIS3/profiles/default/python/plugins', '/usr/share/qgis/python/plugins', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/home/fee/.local/lib/python3.10/site-packages', '/usr/local/lib/python3.10/dist-packages', '/usr/lib/python3/dist-packages', '/home/fee/.local/share/QGIS/QGIS3/profiles/default/python']
```
```
An error occurred during execution of following code:
pyplugin_installer.initPluginInstaller()


Traceback (most recent call last):
  File "", line 1, in 
NameError: name 'pyplugin_installer' is not defined


Python version:
3.10.2 (main, Mar 31 2022, 14:16:47) [GCC 11.2.0]

QGIS version:
3.22.11-Białowieża 'Białowieża', 106d33d759

Python path:
['/usr/share/qgis/python', '/home/fee/.local/share/QGIS/QGIS3/profiles/default/python', '/home/fee/.local/share/QGIS/QGIS3/profiles/default/python/plugins', '/usr/share/qgis/python/plugins', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/home/fee/.local/lib/python3.10/site-packages', '/usr/local/lib/python3.10/dist-packages', '/usr/lib/python3/dist-packages', '/home/fee/.local/share/QGIS/QGIS3/profiles/default/python']
```
```
An error occurred during execution of following code:
import console


Traceback (most recent call last):
  File "", line 1, in 
NameError: name 'pyplugin_installer' is not defined


Python version:
3.10.2 (main, Mar 31 2022, 14:16:47) [GCC 11.2.0]

QGIS version:
3.22.11-Białowieża 'Białowieża', 106d33d759

Python path:
['/usr/share/qgis/python', '/home/fee/.local/share/QGIS/QGIS3/profiles/default/python', '/home/fee/.local/share/QGIS/QGIS3/profiles/default/python/plugins', '/usr/share/qgis/python/plugins', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/home/fee/.local/lib/python3.10/site-packages', '/usr/local/lib/python3.10/dist-packages', '/usr/lib/python3/dist-packages', '/home/fee/.local/share/QGIS/QGIS3/profiles/default/python']
```
```
An error occurred during execution of following code:
console.init_options_widget()


Traceback (most recent call last):
  File "", line 1, in 
NameError: name 'console' is not defined


Python version:
3.10.2 (main, Mar 31 2022, 14:16:47) [GCC 11.2.0]

QGIS version:
3.22.11-Białowieża 'Białowieża', 106d33d759

Python path:
['/usr/share/qgis/python', '/home/fee/.local/share/QGIS/QGIS3/profiles/default/python', '/home/fee/.local/share/QGIS/QGIS3/profiles/default/python/plugins', '/usr/share/qgis/python/plugins', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/home/fee/.local/lib/python3.10/site-packages', '/usr/local/lib/python3.10/dist-packages', '/usr/lib/python3/dist-packages', '/home/fee/.local/share/QGIS/QGIS3/profiles/default/python']
```

</details>

### Steps to reproduce the issue

Start Qgis on Pop OS

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.11-Białowieża | QGIS code revision | 106d33d759
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.4
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | 14.5 (Ubuntu 14.5-0ubuntu0.22.04.1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Pop!_OS 22.04 LTS
  |   |   |  
Active Python plugins
db_manager | 0.1.20

</body></html>QGIS version
3.22.11-Białowieża
QGIS code revision
[106d33d759](https://github.com/qgis/QGIS/commit/106d33d759)
Qt version
5.15.3
Python version
3.10.4
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
14.5 (Ubuntu 14.5-0ubuntu0.22.04.1)
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Pop!_OS 22.04 LTS

Active Python plugins
db_manager
0.1.20

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

### Additional context

I will be giving a course on GIS soon, and this is a major problem. Please help!

**Comment by nicogodet** [comment]
Your python install seems broken...
Not related to QGIS itself

**Comment by feefladder** [comment]
Hmm yeah that's also what I initially thought, so I ran
```
$ python
>>> import math
```
Without any problem...
But it's a good one to look into! My file explorer also segfaults bc of some python problem...

**Comment by nicogodet** [comment]
I'm closing as not related to QGIS

**Comment by feefladder** [comment]
Hmm, this is weird... QGIS sees Python 3.10.2, while I have 3.10.4 installed....

**Comment by nicogodet** [comment]
<html>
<body>


Python version | 3.10.4
-- | --



</body>
</html>

QGIS sees 3.10.4

**Comment by feefladder** [comment]
but not in the error messages in the details

**Comment by feefladder** [comment]
![image](https://user-images.githubusercontent.com/33122845/191714627-fab4117f-b5b7-41f3-b632-5cc54c81b7cc.png)

**Comment by feefladder** [comment]
Turned out I had messed up my system python by messing with pip/apt dependencies...
