### ISSUE TITLE
Crash when opening or zooming into HDF5 dataset

### ISSUE THREAD

**Issue by lnicola** [qgis/QGIS#50318]
### What is the bug or the crash?

Crashes when opening attached dataset.

[VNP46A2.A2022074.h20v04.001.2022083020550.zip](https://github.com/qgis/QGIS/files/9639225/VNP46A2.A2022074.h20v04.001.2022083020550.zip)

### Steps to reproduce the issue

1. Load all the variables, it might/should crash immediately.

```
Thread 13 "Thread (pooled)" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffc98d86c0 (LWP 174954)]
0x00007fff80328eac in H5FL_reg_malloc () from /usr/lib/libhdf5.so.200
(gdb) bt
#0  0x00007fff80328eac in H5FL_reg_malloc () at /usr/lib/libhdf5.so.200
#1  0x00007fff8042d7c0 in  () at /usr/lib/libhdf5.so.200
#2  0x00007fff8042f669 in  () at /usr/lib/libhdf5.so.200
#3  0x00007fff8042fd15 in H5SL_insert () at /usr/lib/libhdf5.so.200
#4  0x00007fff803f144f in H5P_copy_plist () at /usr/lib/libhdf5.so.200
#5  0x00007fff802bf559 in  () at /usr/lib/libhdf5.so.200
#6  0x00007fff802c5cfc in H5D_open () at /usr/lib/libhdf5.so.200
#7  0x00007fff802c6860 in H5D__open_name () at /usr/lib/libhdf5.so.200
#8  0x00007fff804ef2c3 in H5VL__native_dataset_open () at /usr/lib/libhdf5.so.200
#9  0x00007fff804d4abe in  () at /usr/lib/libhdf5.so.200
#10 0x00007fff804dc767 in H5VL_dataset_open () at /usr/lib/libhdf5.so.200
#11 0x00007fff802b7c5e in H5Dopen1 () at /usr/lib/libhdf5.so.200
#12 0x00007fff806fcb7b in  () at /usr/lib/gdalplugins/gdal_HDF5.so
#13 0x00007fff80346d5d in H5G__node_iterate () at /usr/lib/libhdf5.so.200
#14 0x00007fff8026f4f8 in  () at /usr/lib/libhdf5.so.200
#15 0x00007fff8026f6bb in H5B_iterate () at /usr/lib/libhdf5.so.200
#16 0x00007fff8034a2a8 in H5G__stab_iterate () at /usr/lib/libhdf5.so.200
#17 0x00007fff8034b0ab in H5G__obj_iterate () at /usr/lib/libhdf5.so.200
#18 0x00007fff80343acb in H5G_iterate () at /usr/lib/libhdf5.so.200
#19 0x00007fff804f3a15 in H5VL__native_group_optional () at /usr/lib/libhdf5.so.200
#20 0x00007fff804dea4c in  () at /usr/lib/libhdf5.so.200
#21 0x00007fff804e4490 in H5VL_group_optional () at /usr/lib/libhdf5.so.200
#22 0x00007fff8033cbfa in H5Giterate () at /usr/lib/libhdf5.so.200
#23 0x00007fff806fcda0 in  () at /usr/lib/gdalplugins/gdal_HDF5.so
#24 0x00007fff80346d5d in H5G__node_iterate () at /usr/lib/libhdf5.so.200
#25 0x00007fff8026f4f8 in  () at /usr/lib/libhdf5.so.200
#26 0x00007fff8026f6bb in H5B_iterate () at /usr/lib/libhdf5.so.200
#27 0x00007fff8034a2a8 in H5G__stab_iterate () at /usr/lib/libhdf5.so.200
#28 0x00007fff8034b0ab in H5G__obj_iterate () at /usr/lib/libhdf5.so.200
#29 0x00007fff80343acb in H5G_iterate () at /usr/lib/libhdf5.so.200
#30 0x00007fff804f3a15 in H5VL__native_group_optional () at /usr/lib/libhdf5.so.200
#31 0x00007fff804dea4c in  () at /usr/lib/libhdf5.so.200
#32 0x00007fff804e4490 in H5VL_group_optional () at /usr/lib/libhdf5.so.200
#33 0x00007fff8033cbfa in H5Giterate () at /usr/lib/libhdf5.so.200
#34 0x00007fff8072244b in  () at /usr/lib/gdalplugins/gdal_HDF5.so
#35 0x00007fff80700072 in  () at /usr/lib/gdalplugins/gdal_HDF5.so
#36 0x00007fffed9f1917 in GDALOpenEx () at /usr/lib/libgdal.so.31
#37 0x00007ffff34157ad in  () at /usr/lib/libqgis_core.so.3.26.2
#38 0x00007ffff3429aeb in  () at /usr/lib/libqgis_core.so.3.26.2
#39 0x00007ffff341d09b in  () at /usr/lib/libqgis_core.so.3.26.2
#40 0x00007ffff38e0ffb in QgsSingleBandGrayRenderer::block(int, QgsRectangle const&, int, int, QgsRasterBlockFeedback*) () at /usr/lib/libqgis_core.so.3.26.2
#41 0x00007ffff38c4af1 in QgsBrightnessContrastFilter::block(int, QgsRectangle const&, int, int, QgsRasterBlockFeedback*) () at /usr/lib/libqgis_core.so.3.26.2
#42 0x00007ffff38c4fed in QgsHueSaturationFilter::block(int, QgsRectangle const&, int, int, QgsRasterBlockFeedback*) () at /usr/lib/libqgis_core.so.3.26.2
#43 0x00007ffff38e04bf in QgsRasterResampleFilter::block(int, QgsRectangle const&, int, int, QgsRasterBlockFeedback*) () at /usr/lib/libqgis_core.so.3.26.2
#44 0x00007ffff3892efe in QgsRasterIterator::readNextRasterPartInternal(int, int&, int&, std::unique_ptr<QgsRasterBlock, std::default_delete<QgsRasterBlock> >*, int&, int&, QgsRectangle*) () at /usr/lib/libqgis_core.so.3.26.2
#45 0x00007ffff38c27d2 in QgsRasterDrawer::draw(QPainter*, QgsRasterViewPort*, QgsMapToPixel const*, QgsRasterBlockFeedback*) () at /usr/lib/libqgis_core.so.3.26.2
#46 0x00007ffff38b6cdc in QgsRasterLayerRenderer::render() () at /usr/lib/libqgis_core.so.3.26.2
#47 0x00007ffff37ec204 in QgsMapRendererParallelJob::renderLayerStatic(LayerRenderJob&) () at /usr/lib/libqgis_core.so.3.26.2
#48 0x00007ffff37e6c48 in  () at /usr/lib/libqgis_core.so.3.26.2
#49 0x00007ffff37e6e1d in  () at /usr/lib/libqgis_core.so.3.26.2
#50 0x00007ffff7e0d5b5 in QtConcurrent::ThreadEngineBase::run() (this=0x5555596820a0) at /usr/src/debug/qtbase/src/concurrent/qtconcurrentthreadengine.cpp:302
#51 0x00007ffff48e8491 in QThreadPoolThread::run() (this=0x555555b4ed10) at thread/qthreadpool.cpp:100
#52 0x00007ffff48e42ba in QThreadPrivate::start(void*) (arg=0x555555b4ed10) at thread/qthread_unix.cpp:330
#53 0x00007ffff249f74d in start_thread (arg=<optimized out>) at pthread_create.c:442
#54 0x00007ffff2521700 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

```
HDF5-DIAG: Error detected in HDF5 (1.12.2) thread 0:
  #000: H5Adeprec.c line 330 in H5Aget_num_attrs(): unable to get attribute count for object
    major: Attribute
    minor: Can't get value
  #001: H5VLcallback.c line 5612 in H5VL_object_get(): can't reset VOL wrapper info
    major: Virtual Object Layer
    minor: Can't reset object
  #002: H5VLint.c line 2358 in H5VL_reset_vol_wrapper(): no VOL object wrap context?
    major: Virtual Object Layer
    minor: Bad value
munmap_chunk(): invalid pointer
```

1. Load e.g. `//HDFEOS/GRIDS/VNP_Grid_DNB/Data_Fields/DNB_Lunar_Irradiance`, it shouldn't crash
2. Zoom in, it should crash.

```
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007f0a63aa1503 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007f0a63a51958 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007f0a63a3b53d in __GI_abort () at abort.c:79
#4  0x00007f0a63a9563e in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f0a63bb4432 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#5  0x00007f0a63aab22c in malloc_printerr (str=str@entry=0x7f0a63bb70b8 "double free or corruption (!prev)") at malloc.c:5660
#6  0x00007f0a63aad36c in _int_free (av=0x7f0a10000030, p=0x7f0a10630e20, have_lock=<optimized out>, have_lock@entry=0) at malloc.c:4587
#7  0x00007f0a63aaf9f3 in __GI___libc_free (mem=<optimized out>) at malloc.c:3385
#8  0x00007f0a04b83fb3 in H5MM_xfree () at /usr/lib/libhdf5.so.200
#9  0x00007f0a04aa76ae in H5D__chunk_mem_xfree () at /usr/lib/libhdf5.so.200
#10 0x00007f0a04aaaada in  () at /usr/lib/libhdf5.so.200
#11 0x00007f0a04aab010 in  () at /usr/lib/libhdf5.so.200
#12 0x00007f0a04aac648 in  () at /usr/lib/libhdf5.so.200
#13 0x00007f0a04aad567 in  () at /usr/lib/libhdf5.so.200
#14 0x00007f0a04aca92a in H5D__read () at /usr/lib/libhdf5.so.200
#15 0x00007f0a04cef425 in H5VL__native_dataset_read () at /usr/lib/libhdf5.so.200
#16 0x00007f0a04cd4b96 in  () at /usr/lib/libhdf5.so.200
#17 0x00007f0a04cdc93d in H5VL_dataset_read () at /usr/lib/libhdf5.so.200
#18 0x00007f0a04ac9457 in H5Dread () at /usr/lib/libhdf5.so.200
#19 0x00007f0a19fc0c10 in  () at /usr/lib/gdalplugins/gdal_HDF5.so
#20 0x00007f0a5effa464 in GDALRasterBand::GetLockedBlockRef(int, int, int) () at /usr/lib/libgdal.so.31
#21 0x00007f0a5f0614f4 in GDALRasterBand::IRasterIO(GDALRWFlag, int, int, int, int, void*, int, int, GDALDataType, long long, long long, GDALRasterIOExtraArg*) () at /usr/lib/libgdal.so.31
#22 0x00007f0a5efed466 in GDALRasterBand::RasterIO(GDALRWFlag, int, int, int, int, void*, int, int, GDALDataType, long long, long long, GDALRasterIOExtraArg*) () at /usr/lib/libgdal.so.31
#23 0x00007f0a64a1bc11 in  () at /usr/lib/libqgis_core.so.3.26.2
#24 0x00007f0a64a1d219 in  () at /usr/lib/libqgis_core.so.3.26.2
#25 0x00007f0a64ee0ffb in QgsSingleBandGrayRenderer::block(int, QgsRectangle const&, int, int, QgsRasterBlockFeedback*) () at /usr/lib/libqgis_core.so.3.26.2
#26 0x00007f0a64ec4af1 in QgsBrightnessContrastFilter::block(int, QgsRectangle const&, int, int, QgsRasterBlockFeedback*) () at /usr/lib/libqgis_core.so.3.26.2
#27 0x00007f0a64ec4fed in QgsHueSaturationFilter::block(int, QgsRectangle const&, int, int, QgsRasterBlockFeedback*) () at /usr/lib/libqgis_core.so.3.26.2
#28 0x00007f0a64ee04bf in QgsRasterResampleFilter::block(int, QgsRectangle const&, int, int, QgsRasterBlockFeedback*) () at /usr/lib/libqgis_core.so.3.26.2
#29 0x00007f0a64e92efe in QgsRasterIterator::readNextRasterPartInternal(int, int&, int&, std::unique_ptr<QgsRasterBlock, std::default_delete<QgsRasterBlock> >*, int&, int&, QgsRectangle*) () at /usr/lib/libqgis_core.so.3.26.2
#30 0x00007f0a64ec27d2 in QgsRasterDrawer::draw(QPainter*, QgsRasterViewPort*, QgsMapToPixel const*, QgsRasterBlockFeedback*) () at /usr/lib/libqgis_core.so.3.26.2
#31 0x00007f0a64eb6cdc in QgsRasterLayerRenderer::render() () at /usr/lib/libqgis_core.so.3.26.2
#32 0x00007f0a64dec204 in QgsMapRendererParallelJob::renderLayerStatic(LayerRenderJob&) () at /usr/lib/libqgis_core.so.3.26.2
#33 0x00007f0a64de6c48 in  () at /usr/lib/libqgis_core.so.3.26.2
#34 0x00007f0a64de6e1d in  () at /usr/lib/libqgis_core.so.3.26.2
#35 0x00007f0a687fc5b5 in QtConcurrent::ThreadEngineBase::run() (this=0x55892fcf2770) at /usr/src/debug/qtbase/src/concurrent/qtconcurrentthreadengine.cpp:302
#36 0x00007f0a65ee8491 in QThreadPoolThread::run() (this=0x55892f8bd5d0) at thread/qthreadpool.cpp:100
#37 0x00007f0a65ee42ba in QThreadPrivate::start(void*) (arg=0x55892f8bd5d0) at thread/qthread_unix.cpp:330
#38 0x00007f0a63a9f74d in start_thread (arg=<optimized out>) at pthread_create.c:442
#39 0x00007f0a63b21700 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

```
HDF5-DIAG: Error detected in HDF5 (1.12.2) thread 0:
  #000: H5Dio.c line 179 in H5Dread(): can't read data
    major: Dataset
    minor: Read failed
  #001: H5VLcallback.c line 2011 in H5VL_dataset_read(): dataset read failed
    major: Virtual Object Layer
    minor: Read failed
  #002: H5VLcallback.c line 1978 in H5VL__dataset_read(): dataset read failed
    major: Virtual Object Layer
    minor: Read failed
  #003: H5VLnative_dataset.c line 166 in H5VL__native_dataset_read(): can't read data
    major: Dataset
    minor: Read failed
  #004: H5Dio.c line 534 in H5D__read(): can't initialize I/O info
    major: Dataset
    minor: Unable to initialize object
  #005: H5Dchunk.c line 1124 in H5D__chunk_io_init(): unable to create file and memory chunk selections
    major: Dataset
    minor: Unable to initialize object
  #006: H5Dchunk.c line 1245 in H5D__chunk_io_init_selections(): unable to create file chunk selections
    major: Dataset
    minor: Unable to initialize object
  #007: H5Dchunk.c line 1899 in H5D__create_chunk_file_map_hyper(): can't insert chunk into skip list
    major: Dataspace
    minor: Unable to insert object
  #008: H5SL.c line 1051 in H5SL_insert(): can't create new skip list node
    major: Skip Lists
    minor: Unable to insert object
  #009: H5SL.c line 724 in H5SL__insert_common(): can't insert duplicate key
    major: Skip Lists
    minor: Unable to insert object
ERROR 1: H5Dread() failed for block.
```

### Versions

QGIS version | 3.26.2-Buenos Aires | QGIS code branch | Release 3.26
-- | -- | -- | --
Compiled against Qt | 5.15.5 | Running against Qt | 5.15.6
Python version | 3.10.6
GDAL/OGR version | 3.5.1
PROJ version | 9.0.1
EPSG Registry database version | v10.064 (2022-05-19)
GEOS version | 3.11.0-CAPI-1.17.0
Compiled against SQLite | 3.39.2 | Running against SQLite | 3.39.3
PDAL version | 2.4.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.2.0
QScintilla2 version | 2.13.3
OS version | Arch Linux
  |   |   |  
Active Python plugins
temporalprofiletool | 2.0.3
QuickWKT | 3.1
grassprovider | 2.12.99
db_manager | 0.1.20
sagaprovider | 2.12.99

</body></html>QGIS version
3.26.2-Buenos Aires
QGIS code branch
[Release 3.26](https://github.com/qgis/QGIS/tree/release-3_26)
Compiled against Qt
5.15.5
Running against Qt
5.15.6
Python version
3.10.6
GDAL/OGR version
3.5.1
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.11.0-CAPI-1.17.0
Compiled against SQLite
3.39.2
Running against SQLite
3.39.3
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.2.0
QScintilla2 version
2.13.3
OS version
Arch Linux

Active Python plugins
temporalprofiletool
2.0.3
QuickWKT
3.1
grassprovider
2.12.99
db_manager
0.1.20
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

I haven't tried the Flatpak version yet. Quite likely a GDAL or HDF5 bug, but opening for visibility.

Data courtesy of https://ladsweb.modaps.eosdis.nasa.gov/.

**Comment by rouault** [comment]
I cannot reproduce with recent GDAL version. Closing as likely duplicate of https://github.com/OSGeo/gdal/issues/7340
