### ISSUE TITLE
Add Ring/Fill ring tools create a mixed Polygon/CompoundCurve geometry

### ISSUE THREAD

**Issue by uclaros** [qgis/QGIS#50869]
### What is the bug or the crash?

When using the Add Ring or Fill Ring map tools to create holes in a polygon, the resulting geometry is a combination of Polygon and CompoundCurve with a WKT like 
```
Polygon ((1 2, 4 2, 4 5, 1 5, 1 2),CompoundCurve ((2 4, 2 3, 3 3, 3 4, 2 4)))
```
 instead of the expected
```
Polygon ((1 2, 1 5, 4 5, 4 2, 1 2),(2 4, 2 3, 3 3, 3 4, 2 4))
```

### Steps to reproduce the issue

1. Add a temporary scratch layer of type Polygon
2. Digitize a feature
3. Use Add Ring map tool to punch a hole in your polygon
4. Check the feature's geometry: `print([f.geometry().asWkt() for f in iface.activeLayer().getFeatures()][0])`

### Versions

6cb9a64f8

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Fix geometries / 0 buffer fixes the geometry to `Polygon ((1 2, 1 5, 4 5, 4 2, 1 2),(2 4, 2 3, 3 3, 3 4, 2 4))`

Achieving the same result with the _Split_ tool gives the expected result `Polygon ((1 2, 1 5, 4 5, 4 2, 1 2),(2 4, 2 3, 3 3, 3 4, 2 4))`

**Comment by MattiasSp** [comment]
This one deserves a little more attention :)

The presence of the CompoundCurve part also causes us to be unable to save these objects to our MS SQL Server (2016) database. Instead we get this error:

```
Could not commit changes to layer my_layer_with_holes

Errors: ERROR: 1 geometries not changed.
  
  Provider errors:
      [Microsoft][ODBC SQL Server Driver][SQL Server]A .NET Framework error occurred during execution of user-defined routine or aggregate "geometry": 
    System.FormatException: 24142: Expected "(" at position 276. The input has "C".
    System.FormatException: 
       at Microsoft.SqlServer.Types.WellKnownTextReader.RecognizeToken(Char token)
       at Microsoft.SqlServer.Types.WellKnownTextReader.ParseLineStringText()
       at Microsoft.SqlServer.Types.WellKnownTextReader.ParsePolygonText()
       at Microsoft.SqlServer.Types.WellKnownTextReader.ParseMultiPolygonText()
       at Microsoft.SqlServer.Types.WellKnownTextReader.ParseTaggedText(OpenGisType type)
       at Microsoft.SqlServer.Types.WellKnownTextReader.Read(OpenGisType type, Int32 srid)
       at Microsoft.SqlServer.Types.SqlGeometry.GeometryFromText(OpenGisType type, SqlChars text, Int32 srid)
    . [Microsoft][ODBC SQL Server Driver][SQL Server]The statement has been terminated. QODBC3: Unable to execute statement
```

Presumably the "C" is the first letter of the "CompoundCurve" part of the WKT, which the database does not seem to handle very well.

Tested on 3.28.1 and 3.28.3.

**Comment by MattiasSp** [comment]
It looks to me like this was introduced back in https://github.com/qgis/QGIS/commit/e2e8a1285022478a257c61e92f130b7ad715a591 where there used to be a conversion from curve to linestring:
```
    //does compoundcurve contain circular strings?	
    //does provider support circular strings?	
    const bool hasCurvedSegments = captureCurve()->hasCurvedSegments();	
    const bool providerSupportsCurvedSegments = vlayer->dataProvider()->capabilities() & QgsVectorDataProvider::CircularGeometries;	

    QgsCurve *curveToAdd = nullptr;	
    if ( hasCurvedSegments && providerSupportsCurvedSegments )	
    {	
      curveToAdd = captureCurve()->clone();	
    }	
    else	
    {	
      curveToAdd = captureCurve()->curveToLine();	
    }
```

That part, as well as the check whether or not the provider supports curves, seems to have been lost in the refactor.

**Comment by agiudiceandrea** [comment]
According to the comment at https://github.com/qgis/QGIS/pull/55371#pullrequestreview-1779309845, this issue is not yet completely fixed.

**Comment by elpaso** [comment]
@agiudiceandrea maybe a duplicate of https://github.com/qgis/QGIS/issues/53698

**Comment by agiudiceandrea** [comment]
#53698 si reported as a MSSQL issue and your recent PR https://github.com/qgis/QGIS/pull/55588 to fix it is also tagged as a fix for MSSQL. Doesn't it? This issue looks like a more general issue, instead. Does your PR fixes the the issue also for data providers other than MSSQL?

**Comment by elpaso** [comment]
> #53698 si reported as a MSSQL issue and your recent PR #55588 to fix it is also tagged as a fix for MSSQL. Doesn't it? This issue looks like a more general issue, instead. Does your PR fixes the the issue also for data providers other than MSSQL?

My fix has nothing specific about MSSQL but I only tested it with MSSQL. 

The only MSSQL specific code in that PR is about logging some more queries in the dev tools query logger.

**Comment by agiudiceandrea** [comment]
> this issue is not yet completely fixed.

Moreover, the issue is only partially fixed in master branch, but it is completely unfixed for QGIS 3.34 and QGIS 3.28.

**Comment by elpaso** [comment]
@agiudiceandrea maybe you should have the permissions to tag a PR, this should in part automate the backport process. Do you have those permissions?

**Comment by agiudiceandrea** [comment]
> Do you have those permissions?

Yes. I've tagged the PR, but the automatic backports failed (since another previous PR on wich it partially relies on, was not backported).
I'll submit a manual backport.

**Comment by Jean-Roc** [comment]
Hi, one of our team got this issue with sql server and the ring with a CoumpoundCurve on QGIS 3.34.7, it seems to be fixed in 3.34.13 and qgis-dev.

**Comment by uclaros** [comment]
Fixed in #55371 and #55588
