### ISSUE TITLE
OSGeo4W shell: Couldn't load plugin 'processing'

### ISSUE THREAD

**Issue by jakimowb** [qgis/QGIS#50890]
### What is the bug or the crash?

To test QGIS plugin, I frequently have to switch between different QGIS versions. On windows systems I use the OSGeo4W shell for. If 'qgis-dev' has been started first, a following start of 'qgis' raises a `Couldn't load plugin 'processing' ` error due to broken GDAL pathes (see below).

Of course, the error can be avoided by simply calling `qgis` in a new shell window. Nevertheless it would be nice if the `qgis` stat script could set all required environmental settings explicitely.

![grafik](https://user-images.githubusercontent.com/1404870/201870556-f28a14f7-814a-4bc1-aef3-b21833982de8.png)

<details>
<summary>
Couldn't load plugin 'processing' 

ImportError: Traceback (most recent call last):   File "F:\OSGeo4W\apps\gdal-dev\lib\site-packages\osgeo\__init__.py", line 30, in swig_import_helper     return importlib.import_module(mname)   File "F:\OSGeo4W\apps\Python39\lib\importlib\__init__.py", line 127, in import_module     return _bootstrap._gcd_import(name[level:], package, level)   File "", line 1030, in _gcd_import   File "", line 1007, in _find_and_load   File "", line 986, in _find_and_load_unlocked   File "", line 666, in _load_unlocked   File "", line 565, in module_from_spec   File "", line 1173, in create_module   File "", line 228, in _call_with_frames_removed ImportError: DLL load failed while importing _gdal: The specified module could not be found. On Windows, with Python >= 3.8, DLLs are no longer imported from the PATH. If gdalXXX.dll is in the PATH, then set the USE_PATH_FOR_GDAL_PYTHON=YES environment variable to feed the PATH into os.add_dll_directory(). 

</summary>

Traceback (most recent call last):
  File "F:\OSGeo4W\apps\gdal-dev\lib\site-packages\osgeo\__init__.py", line 30, in swig_import_helper
    return importlib.import_module(mname)
  File "F:\OSGeo4W\apps\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "", line 1030, in _gcd_import
  File "", line 1007, in _find_and_load
  File "", line 986, in _find_and_load_unlocked
  File "", line 666, in _load_unlocked
  File "", line 565, in module_from_spec
  File "", line 1173, in create_module
  File "", line 228, in _call_with_frames_removed
ImportError: DLL load failed while importing _gdal: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 401, in loadPlugin
    __import__(packageName)
  File "F:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "F:\OSGeo4W/apps/qgis/./python/plugins\processing\__init__.py", line 26, in 
    from processing.tools.general import *  # NOQA
  File "F:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "F:\OSGeo4W/apps/qgis/./python/plugins\processing\tools\general.py", line 32, in 
    from processing.core.Processing import Processing
  File "F:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "F:\OSGeo4W/apps/qgis/./python/plugins\processing\core\Processing.py", line 58, in 
    from processing.algs.qgis.QgisAlgorithmProvider import QgisAlgorithmProvider  # NOQA
  File "F:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "F:\OSGeo4W/apps/qgis/./python/plugins\processing\algs\qgis\QgisAlgorithmProvider.py", line 49, in 
    from .HypsometricCurves import HypsometricCurves
  File "F:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "F:\OSGeo4W/apps/qgis/./python/plugins\processing\algs\qgis\HypsometricCurves.py", line 27, in 
    from osgeo import gdal, ogr, osr
  File "F:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "F:\OSGeo4W\apps\gdal-dev\lib\site-packages\osgeo\__init__.py", line 46, in 
    _gdal = swig_import_helper()
  File "F:\OSGeo4W\apps\gdal-dev\lib\site-packages\osgeo\__init__.py", line 42, in swig_import_helper
    raise ImportError(traceback_string + '\n' + msg)
ImportError: Traceback (most recent call last):
  File "F:\OSGeo4W\apps\gdal-dev\lib\site-packages\osgeo\__init__.py", line 30, in swig_import_helper
    return importlib.import_module(mname)
  File "F:\OSGeo4W\apps\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "", line 1030, in _gcd_import
  File "", line 1007, in _find_and_load
  File "", line 986, in _find_and_load_unlocked
  File "", line 666, in _load_unlocked
  File "", line 565, in module_from_spec
  File "", line 1173, in create_module
  File "", line 228, in _call_with_frames_removed
ImportError: DLL load failed while importing _gdal: The specified module could not be found.

On Windows, with Python >= 3.8, DLLs are no longer imported from the PATH.
If gdalXXX.dll is in the PATH, then set the USE_PATH_FOR_GDAL_PYTHON=YES environment variable
to feed the PATH into os.add_dll_directory().

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.28.0-Firenze Firenze, ed3ad0430f3 

Python Path:
F:/OSGeo4W/apps/qgis/./python
C:/Users/geo_beja/AppData/Roaming/QGIS/QGIS3\profiles\empty/python
C:/Users/geo_beja/AppData/Roaming/QGIS/QGIS3\profiles\empty/python/plugins
F:/OSGeo4W/apps/qgis/./python/plugins
F:\OSGeo4W\apps\gdal-dev\lib\site-packages
F:\OSGeo4W
F:\OSGeo4W\bin\python39.zip
F:\OSGeo4W\apps\Python39\DLLs
F:\OSGeo4W\apps\Python39\lib
F:\OSGeo4W\bin
C:\Users\geo_beja\AppData\Roaming\Python\Python39\site-packages
F:\OSGeo4W\apps\Python39
F:\OSGeo4W\apps\Python39\lib\site-packages
C:/Users/geo_beja/AppData/Roaming/QGIS/QGIS3\profiles\empty/python
</details>

### Steps to reproduce the issue

1. Open OSGeo4W shell (QGIS dev and the current release need to be installed)
3. Open QGIS develop: `qgis-dev`. The desktop can be closed afterwards
4. Open QGIS release: `qgis`
5. Check the 

![grafik](https://user-images.githubusercontent.com/1404870/201869661-57efd8f5-06ef-4346-954a-e0dd1a83a071.png)

### Versions

QGIS version | 3.28.0-Firenze | QGIS code revision | ed3ad0430f3
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
Compiled against GDAL/OGR | 3.5.2 | Running against GDAL/OGR | 3.5.3
PROJ version | 9.1.0
EPSG Registry database version | v10.074 (2022-08-01)
GEOS version | 3.10.3-CAPI-1.16.1
SQLite version | 3.39.4
PDAL version | 2.4.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
db_manager | 0.1.20
MetaSearch | 0.3.6
sagaprovider | 2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@jakimowb, this issue is related to the OSGeo4W installation / packaging system. OSGeo4W has a dedicated website for issues tracking at https://trac.osgeo.org/osgeo4w/. It would be great, and probably more effective, if you could file a issue report there.

**Comment by jef-n** [comment]
Not reproducable.  "The system cannot find the path specified" is not normal.  You could start the .exe (qgis-bin / qgis-dev-bin / qgis-ltr-bin)  like the shortcut would - the batch file is only used during install.

**Comment by agiudiceandrea** [comment]
@jef-n I can reproduce the issue (apart from "The system cannot find the path specified").

1) in a new OSGeo4W shell:
- `qgis-dev`
- QGIS 3.29 starts without issues
- `qgis`
- QGIS 3.28 starts with the `"Couldn't` load plugin 'processing'" issue

2) in a new OSGeo4W shell:
- `qgis`
- QGIS 3.28 starts without issues
- `qgis-dev`
- QGIS 3.29 starts without issues

It seems to me the issue is due to the fact that qgis-dev.bat sets the gdal-dev path in the PATH, while qgis.bat doesn't set the gdal path in the PATH.
