### ISSUE TITLE
QGis (3.28.0-2) crashes at start up on Manjaro with an error "QGIS died on signal 4ptrace"

### ISSUE THREAD

**Issue by erydit** [qgis/QGIS#50902]
### What is the bug or the crash?

After update to the version 3.28.0-2 Qgis started to crash on start up with an error:
```
QGIS died on signal 4ptrace: Operation is not allowed.
No thread selected
No stack.
gdb returned 256
```

"> sudo qgis" gives a more detailed report:
```
Warning: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
QGIS died on signal 4[New LWP 3500]
[New LWP 3508]
[New LWP 3572]
[New LWP 3573]
[New LWP 3574]
[New LWP 3575]
[New LWP 3576]
[New LWP 3577]
[New LWP 3578]
[New LWP 3579]
[New LWP 3580]
[New LWP 3581]
[New LWP 3582]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
0x00007fbb380e4097 in wait4 () from /usr/lib/libc.so.6
[Current thread is 1 (Thread 0x7fbb3b29dcc0 (LWP 3499))]
#0  0x00007fbb380e4097 in wait4 () at /usr/lib/libc.so.6
#1  0x0000560af3fd57c8 in  ()
#2  0x00007fbb3804aa00 in <signal handler called> () at /usr/lib/libc.so.6
#3  0x00007fbb119fd301 in arrow::compute::BloomFilterMasks::BloomFilterMasks() () at /usr/lib/libarrow.so.900
#4  0x00007fbb3df36cee in  () at /lib64/ld-linux-x86-64.so.2
#5  0x00007fbb3df36ddc in  () at /lib64/ld-linux-x86-64.so.2
#6  0x00007fbb38161e94 in _dl_catch_exception () at /usr/lib/libc.so.6
#7  0x00007fbb3df3d557 in  () at /lib64/ld-linux-x86-64.so.2
#8  0x00007fbb38161e3e in _dl_catch_exception () at /usr/lib/libc.so.6
#9  0x00007fbb3df3d8ed in  () at /lib64/ld-linux-x86-64.so.2
#10 0x00007fbb380949dc in  () at /usr/lib/libc.so.6
#11 0x00007fbb38161e3e in _dl_catch_exception () at /usr/lib/libc.so.6
#12 0x00007fbb38161ef3 in _dl_catch_error () at /usr/lib/libc.so.6
#13 0x00007fbb380944af in  () at /usr/lib/libc.so.6
#14 0x00007fbb38094a91 in dlopen () at /usr/lib/libc.so.6
#15 0x00007fbb35cfee23 in CPLGetSymbol () at /usr/lib/libgdal.so.31
#16 0x00007fbb365cd2d5 in GDALDriverManager::AutoLoadDrivers() () at /usr/lib/libgdal.so.31
#17 0x00007fbb362a74f7 in GDALAllRegister () at /usr/lib/libgdal.so.31
#18 0x00007fbb391081fb in QgsApplication::applyGdalSkippedDrivers() () at /usr/lib/libqgis_core.so.3.28.0
#19 0x00007fbb39112101 in QgsApplication::registerGdalDriversFromSettings() () at /usr/lib/libqgis_core.so.3.28.0
#20 0x00007fbb3809d887 in  () at /usr/lib/libc.so.6
#21 0x00007fbb39043f45 in  () at /usr/lib/libqgis_core.so.3.28.0
#22 0x00007fbb3904510f in  () at /usr/lib/libqgis_core.so.3.28.0
#23 0x00007fbb3901e732 in QgsProviderRegistry::init() () at /usr/lib/libqgis_core.so.3.28.0
#24 0x00007fbb3901f3c1 in QgsProviderRegistry::QgsProviderRegistry(QString const&) () at /usr/lib/libqgis_core.so.3.28.0
#25 0x00007fbb3901f55a in QgsProviderRegistry::instance(QString const&) () at /usr/lib/libqgis_core.so.3.28.0
#26 0x00007fbb39103cbf in QgsApplication::initQgis() () at /usr/lib/libqgis_core.so.3.28.0
#27 0x00007fbb3d53948b in QgisApp::QgisApp(QSplashScreen*, bool, bool, bool, QString const&, QString const&, QWidget*, QFlags<Qt::WindowType>) () at /usr/lib/libqgis_app.so.3.28.0
#28 0x0000560af3fcfe4c in  ()
#29 0x00007fbb38035290 in  () at /usr/lib/libc.so.6
#30 0x00007fbb3803534a in __libc_start_main () at /usr/lib/libc.so.6
#31 0x0000560af3fd4095 in  ()
[Inferior 1 (process 3499) detached]
gdb returned 0
```

" > qgis -P" does not help.

System:
```
OS: Manjaro 22.0.0 Sikaris
 Kernel: x86_64 Linux 6.0.8-1-MANJARO
 Uptime: 46m
 Packages: 1503
 Shell: bash
 Resolution: 1920x1080
 DE: Xfce4
 WM: Xfwm4
 WM Theme: Matcha-sea
 GTK Theme: Matcha-sea [GTK2]
 Icon Theme: Papirus-Maia
 Font: Noto Sans 10
 Disk: 1,7T / 6,8T (24%)
 CPU: AMD FX-8350 Eight-Core @ 8x 4GHz
 GPU: AMD RS780 (DRM 2.50.0 / 6.0.8-1-MANJARO, LLVM 14.0.6)
 RAM: 3166MiB / 19485MiB
```

### Steps to reproduce the issue

Trying to start qgis normally, ">qgis" in terminal, or using desktop icon.

### Versions

3.28.0-2

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by erydit** [comment]
Just found out. 
Uninstalling "arrow" helps and qgis started to work again.
Re-installation of arrow package (v. 9.0.0-3) leads to QGis crashes again. 
There was no similar issues with previous QGis versions.

**Comment by erydit** [comment]
OK, I fell into the same trap twice. The issue is related to the https://github.com/apache/arrow/issues/12681 .
QGIS depends on GDAL, GDAL depends on arrow, Arch maintainers of the arrow package builds it with the flag "-DARROW_SIMD_LEVEL=AVX2" for the repositories, however my old but proud CPU does not maintain this set of instructions. 
Rebuld of the arrow with "-DARROW_SIMD_LEVEL=SSE4_2" flag resolves the whole issue chain.
