### ISSUE TITLE
Loading TIN interpolator from processing history in another QGIS instance cause Python error

### ISSUE THREAD

**Issue by nicogodet** [qgis/QGIS#50970]
### What is the bug or the crash?

```
RuntimeError: wrapped C/C++ object of type QgsVectorLayer has been deleted 
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis/./python/plugins\processing\gui\wrappers.py", line 204, in setWidgetValue
    self.setValue(value)
  File "C:\OSGeo4W/apps/qgis/./python/plugins\processing\algs\qgis\ui\InterpolationWidgets.py", line 223, in setValue
    self.widget.setValue(value)
  File "C:\OSGeo4W/apps/qgis/./python/plugins\processing\algs\qgis\ui\InterpolationWidgets.py", line 167, in setValue
    field_name = layer.fields().at(field_index).name()
RuntimeError: wrapped C/C++ object of type QgsVectorLayer has been deleted


Version de Python : 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Version de QGIS : 3.28.1-Firenze Firenze, fde3b8fbb8c 
```

### Steps to reproduce the issue

1. Run TIN Interpolator
2. Open another QGIS instance, load TIN interpolator from history

### Versions

3.28.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
From python console:
```python
>>> from processing.tools import dataobjects
>>> QgsProcessingUtils.mapLayerFromString('T:\\path_to_data.gpkg|layername=my_layer', dataobjects.createContext())
Traceback (most recent call last):
  File "C:\OSGeo4W\apps\Python39\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
RuntimeError: wrapped C/C++ object of type QgsVectorLayer has been deleted
```

Not specific to TIN Interpolator

**Comment by nicogodet** [comment]
Python snippet still fails on https://github.com/qgis/QGIS/commit/376402f9aeb
