### ISSUE TITLE
QGIS crashes on `QGIS_PROTECT_QOBJECT_THREAD_ACCESS_NON_FATAL`

### ISSUE THREAD

**Issue by uclaros** [qgis/QGIS#51314]
### What is the bug or the crash?

In the latest master I often get crashes when trying to set a 3d render to a vector layer

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007fc431ed5597 in __GI___wait4 (pid=293496, stat_loc=0x557c6f606b14, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
30      ../sysdeps/unix/sysv/linux/wait4.c: No such file or directory.
[Current thread is 1 (Thread 0x7fc420918b80 (LWP 293417))]
#0  0x00007fc431ed5597 in __GI___wait4 (pid=293496, stat_loc=0x557c6f606b14, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
        sc_ret = -512
        sc_cancel_oldtype = 0
#1  0x0000557c6c2486a6 in qgisCrash(int) (signal=11) at /home/uclaros/dev/cpp/QGIS/src/app/main.cpp:349
        status = 135794
        pidstr = "--pid=293417\000ract method __int__"
        gdbpid = 293496
        exename = "/home/uclaros/dev/cpp/QGIS/build-master-debug/output/bin/qgis\000\000rd\000\000\000rd\000\000\000re\000\000\000\332\a__int__\206\b\000\000\363\002\000\000\000\004\002z\023SupportsInt.__int__N)\br|\000\000\000ry\000\000\000rz\000\000\000r\315\000\000\000r\316\000\000\000r\002\000\000\000\332\003intr\025\002\000\000rd\000\000\000rd\000\000\000rd\000\000\000re\000\000\000r6\000\000\000\201\b\000\000\363\n\000\000\000\b\000\004\002"...
        len = 61
#2  0x00007fc431e3daf0 in <signal handler called> () at /lib/x86_64-linux-gnu/libc.so.6
#3  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=11, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
        tid = <optimized out>
        ret = 0
        pd = <optimized out>
        old_mask = {__val = {140478058044528, 2275, 8996114480133012734, 140478338610032, 255, 49, 892534833, 20, 140478099477536, 11, 140478097637726, 140480336724576, 49, 20, 140478099477536, 140478096487757}}
        ret = <optimized out>
#4  0x00007fc431e8989f in __pthread_kill_internal (signo=11, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#5  0x00007fc431e3da52 in __GI_raise (sig=11) at ../sysdeps/posix/raise.c:26
        ret = <optimized out>
#6  0x00007fc431e3daf0 in <signal handler called> () at /lib/x86_64-linux-gnu/libc.so.6
#7  0x00007fc4360daba4 in QObject::thread() const () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007fc43418736b in QgsVectorLayer::fields() const (this=0x557c6da2ef60) at /home/uclaros/dev/cpp/QGIS/src/core/vector/qgsvectorlayer.cpp:3733
        __PRETTY_FUNCTION__ = "virtual QgsFields QgsVectorLayer::fields() const"
        __FUNCTION__ = "fields"
#9  0x00007fc43888b551 in QgsPropertyOverrideButton::updateFieldLists() (this=0x557c7600c640) at /home/uclaros/dev/cpp/QGIS/src/gui/qgspropertyoverridebutton.cpp:161
        fields = {_vptr.QgsFields = 0x7ffe24485770, d = {d = 0x557c73656ef0}}
        idx = 32708
#10 0x00007fc43888b37e in QgsPropertyOverrideButton::init(int, QgsProperty const&, QgsPropertyDefinition const&, QgsVectorLayer const*, bool) (this=0x557c7600c640, propertyKey=0, property=..., definition=..., layer=0x557c6da2ef60, auxiliaryStorageEnabled=true) at /home/uclaros/dev/cpp/QGIS/src/gui/qgspropertyoverridebutton.cpp:141
        ts = {<QList<QString>> = {<QListSpecialMethods<QString>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = std::atomic<int> = { -1 }}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x557c75f22980}, d = 0x557c75f22980}}, <No data fields>}
#11 0x00007fc43888af9c in QgsPropertyOverrideButton::init(int, QgsProperty const&, QMap<int, QgsPropertyDefinition> const&, QgsVectorLayer const*, bool) (this=0x557c7600c640, propertyKey=0, property=..., definitions=..., layer=0x557c6da2ef60, auxiliaryStorageEnabled=true) at /home/uclaros/dev/cpp/QGIS/src/gui/qgspropertyoverridebutton.cpp:98
#12 0x00007fc43888b4bd in QgsPropertyOverrideButton::init(int, QgsAbstractPropertyCollection const&, QMap<int, QgsPropertyDefinition> const&, QgsVectorLayer const*, bool) (this=0x557c7600c640, propertyKey=0, collection=..., definitions=..., layer=0x557c6da2ef60, auxiliaryStorageEnabled=true) at /home/uclaros/dev/cpp/QGIS/src/gui/qgspropertyoverridebutton.cpp:148
#13 0x00007fc43a088bd1 in QgsPhongMaterialWidget::setSettings(QgsAbstractMaterialSettings const*, QgsVectorLayer*) (this=0x557c74d5d950, settings=0x557c73509bb0, layer=0x557c6da2ef60) at /home/uclaros/dev/cpp/QGIS/src/app/3d/qgsphongmaterialwidget.cpp:108
        phongMaterial = 0x557c73509bb0
#14 0x00007fc43a06f97a in QgsMaterialWidget::updateMaterialWidget() (this=0x557c7218b210) at /home/uclaros/dev/cpp/QGIS/src/app/3d/qgsmaterialwidget.cpp:151
        w = 0x557c74d5d950
        am = 0x557c6e8b2960
        settingsType = {d = 0x7fc4311fcb80 <QgsPhongMaterialSettings::type() const::{lambda()#1}::operator()() const::qstring_literal>}
#15 0x00007fc43a06f631 in QgsMaterialWidget::materialTypeChanged() (this=0x557c7218b210) at /home/uclaros/dev/cpp/QGIS/src/app/3d/qgsmaterialwidget.cpp:121
        newMaterial = std::unique_ptr<QgsAbstractMaterialSettings> = {get() = 0x0}
        am = 0x557c6e8b2960
        currentSettings = std::unique_ptr<QgsAbstractMaterialSettings> = {get() = 0x557c6da45d00}
        existingType = {d = 0x7fc4311ff7c0 <QgsSimpleLineMaterialSettings::type() const::{lambda()#1}::operator()() const::qstring_literal>}
        newType = {d = 0x7fc4311ce880 <Qgs3D::initialize()::{lambda()#6}::operator()() const::qstring_literal>}
#16 0x00007fc43a06f064 in QgsMaterialWidget::setTechnique(QgsMaterialSettingsRenderingTechnique) (this=0x557c7218b210, technique=QgsMaterialSettingsRenderingTechnique::Triangles) at /home/uclaros/dev/cpp/QGIS/src/app/3d/qgsmaterialwidget.cpp:75
        prevType = {d = 0x7fc4311ce9c0 <Qgs3D::initialize()::{lambda()#10}::operator()() const::qstring_literal>}
        materialTypes = {<QList<QString>> = {<QListSpecialMethods<QString>> = {<No data fields>}, {p = {d = 0x557c7565c990}, d = 0x557c7565c990}}, <No data fields>}
        prevIndex = -1
#17 0x00007fc43a06c01c in QgsLine3DSymbolWidget::updateGuiState() (this=0x557c6da9c570) at /home/uclaros/dev/cpp/QGIS/src/app/3d/qgsline3dsymbolwidget.cpp:95
        simple = false
#18 0x00007fc43a06e78c in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (QgsLine3DSymbolWidget::*)()>::call(void (QgsLine3DSymbolWidget::*)(), QgsLine3DSymbolWidget*, void**) (f=(void (QgsLine3DSymbolWidget::*)(class QgsLine3DSymbolWidget * const)) 0x7fc43a06bfa2 <QgsLine3DSymbolWidget::updateGuiState()>, o=0x557c6da9c570, arg=0x7ffe24485e70) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:152
#19 0x00007fc43a06e5ec in QtPrivate::FunctionPointer<void (QgsLine3DSymbolWidget::*)()>::call<QtPrivate::List<>, void>(void (QgsLine3DSymbolWidget::*)(), QgsLine3DSymbolWidget*, void**) (f=(void (QgsLine3DSymbolWidget::*)(class QgsLine3DSymbolWidget * const)) 0x7fc43a06bfa2 <QgsLine3DSymbolWidget::updateGuiState()>, o=0x557c6da9c570, arg=0x7ffe24485e70) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:185
#20 0x00007fc43a06e39b in QtPrivate::QSlotObject<void (QgsLine3DSymbolWidget::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0x557c6da68a10, r=0x557c6da9c570, a=0x7ffe24485e70, ret=0x0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:418
#21 0x00007fc4360e89af in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007fc436e54cd2 in QAbstractButton::toggled(bool) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007fc436e551a1 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007fc436e56785 in QAbstractButton::setChecked(bool) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#25 0x00007fc43a06bcb9 in QgsLine3DSymbolWidget::setSymbol(QgsAbstract3DSymbol const*, QgsVectorLayer*) (this=0x557c6da9c570, symbol=0x557c73128460, layer=0x557c70565950) at /home/uclaros/dev/cpp/QGIS/src/app/3d/qgsline3dsymbolwidget.cpp:66
        lineSymbol = 0x557c73128460
#26 0x00007fc43a09890a in QgsSymbol3DWidget::setSymbol(QgsAbstract3DSymbol const*, QgsVectorLayer*) (this=0x557c70a23a90, symbol=0x557c73128460, vlayer=0x557c70565950) at /home/uclaros/dev/cpp/QGIS/src/app/3d/qgssymbol3dwidget.cpp:74
        w = 0x557c6da9c570
#27 0x00007fc43a09b7df in QgsSingleSymbol3DRendererWidget::setLayer(QgsVectorLayer*) (this=0x557c70b27750, layer=0x557c70565950) at /home/uclaros/dev/cpp/QGIS/src/app/3d/qgsvectorlayer3drendererwidget.cpp:72
        sym = std::unique_ptr<QgsAbstract3DSymbol> = {get() = 0x557c73128460}
        r = 0x0
#28 0x00007fc43a09ccac in QgsVectorLayer3DRendererWidget::onRendererTypeChanged(int) (this=0x557c6db76a60, index=1) at /home/uclaros/dev/cpp/QGIS/src/app/3d/qgsvectorlayer3drendererwidget.cpp:203
#29 0x00007fc43a09decc in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<int>, void, void (QgsVectorLayer3DRendererWidget::*)(int)>::call(void (QgsVectorLayer3DRendererWidget::*)(int), QgsVectorLayer3DRendererWidget*, void**) (f=(void (QgsVectorLayer3DRendererWidget::*)(class QgsVectorLayer3DRendererWidget * const, int)) 0x7fc43a09cc46 <QgsVectorLayer3DRendererWidget::onRendererTypeChanged(int)>, o=0x557c6db76a60, arg=0x7ffe24486240) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:152
#30 0x00007fc43a09ddcb in QtPrivate::FunctionPointer<void (QgsVectorLayer3DRendererWidget::*)(int)>::call<QtPrivate::List<int>, void>(void (QgsVectorLayer3DRendererWidget::*)(int), QgsVectorLayer3DRendererWidget*, void**) (f=(void (QgsVectorLayer3DRendererWidget::*)(class QgsVectorLayer3DRendererWidget * const, int)) 0x7fc43a09cc46 <QgsVectorLayer3DRendererWidget::onRendererTypeChanged(int)>, o=0x557c6db76a60, arg=0x7ffe24486240) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:185
#31 0x00007fc43a09dcf1 in QtPrivate::QSlotObject<void (QgsVectorLayer3DRendererWidget::*)(int), QtPrivate::List<int>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0x557c70b16e90, r=0x557c6db76a60, a=0x7ffe24486240, ret=0x0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:418
#32 0x00007fc4360e89af in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#33 0x00007fc436e66541 in QComboBox::currentIndexChanged(int) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#34 0x00007fc436e67d02 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#35 0x00007fc436e6b58b in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#36 0x00007fc436e6b7f7 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#37 0x00007fc4360e89dc in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#38 0x00007fc436e66732 in QComboBoxPrivateContainer::itemSelected(QModelIndex const&) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#39 0x00007fc436e6707e in QComboBoxPrivateContainer::eventFilter(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#40 0x00007fc4360b139b in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#41 0x00007fc436d62f3e in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#42 0x00007fc436d6b4f2 in QApplication::notify(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#43 0x00007fc4336a03b7 in QgsApplication::notify(QObject*, QEvent*) (this=0x7ffe24487ba0, receiver=0x557c70a32b40, event=0x7ffe24486af0) at /home/uclaros/dev/cpp/QGIS/src/core/qgsapplication.cpp:546
        done = true
        __PRETTY_FUNCTION__ = "virtual bool QgsApplication::notify(QObject*, QEvent*)"
#44 0x00007fc4360b1618 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#45 0x00007fc436d695fe in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#46 0x00007fc436dbdf15 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#47 0x00007fc436dc0e50 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#48 0x00007fc436d62f4e in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#49 0x00007fc4336a03b7 in QgsApplication::notify(QObject*, QEvent*) (this=0x7ffe24487ba0, receiver=0x7fc418008410, event=0x7ffe24486ed0) at /home/uclaros/dev/cpp/QGIS/src/core/qgsapplication.cpp:546
        done = true
        __PRETTY_FUNCTION__ = "virtual bool QgsApplication::notify(QObject*, QEvent*)"
#50 0x00007fc4360b1618 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#51 0x00007fc43653d625 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#52 0x00007fc436511ddc in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#53 0x00007fc41fefbe4a in  () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#54 0x00007fc43131e729 in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#55 0x00007fc43131e9b8 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#56 0x00007fc43131ea4c in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#57 0x00007fc4361091c6 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#58 0x00007fc4360b009b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#59 0x00007fc4360b8206 in QCoreApplication::exec() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#60 0x0000557c6c250a16 in main(int, char**) (argc=1, argv=0x7ffe24489018) at /home/uclaros/dev/cpp/QGIS/src/app/main.cpp:1726
        preApplicationLogMessages = {<QList<QString>> = {<QListSpecialMethods<QString>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = std::atomic<int> = { -1 }}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x557c6cc5e880}, d = 0x557c6cc5e880}}, <No data fields>}
        rescLimit = {rlim_cur = 4096, rlim_max = 1048576}
        __FUNCTION__ = "main"
        mySnapshotFileName = {d = 0x7fc436196b20 <QArrayData::shared_null>}
        configLocalStorageLocation = {d = 0x557c6cc6cc80}
        profileName = {d = 0x557c6cc6aba0}
        mySnapshotWidth = 800
        mySnapshotHeight = 600
        myHideSplash = false
        settingsMigrationForce = false
        mySkipVersionCheck = false
        hideBrowser = false
        myRestoreDefaultWindowState = false
        myRestorePlugins = true
        mySkipBadLayers = false
        myCustomization = true
        dxfOutputFile = {d = 0x7fc436196b20 <QArrayData::shared_null>}
        dxfSymbologyMode = QgsDxfExport::SymbolLayerSymbology
        dxfScale = 50000
        dxfEncoding = {d = 0x557c6c25e1a0 <main::{lambda()#4}::operator()() const::qstring_literal>}
        dxfMapTheme = {d = 0x7fc436196b20 <QArrayData::shared_null>}
        dxfExtent = {mXmin = 0, mYmin = 0, mXmax = 0, mYmax = 0}
        takeScreenShots = false
        screenShotsPath = {d = 0x7fc436196b20 <QArrayData::shared_null>}
        screenShotsCategories = 0
        myInitialExtent = {d = 0x557c6c25e1e0 <main::{lambda()#5}::operator()() const::qstring_literal>}
        translationCode = {d = 0x557c6cc9b580}
        authdbdirectory = {d = 0x7fc436196b20 <QArrayData::shared_null>}
        pythonfile = {d = 0x7fc436196b20 <QArrayData::shared_null>}
        pythonArgs = {<QList<QString>> = {<QListSpecialMethods<QString>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = std::atomic<int> = { -1 }}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x7fc436197630 <QListData::shared_null>}, d = 0x7fc436197630 <QListData::shared_null>}}, <No data fields>}
        customizationfile = {d = 0x557c6d31cb20}
        globalsettingsfile = {d = 0x557c6cc5dd20}
        openClProgramFolder = {d = 0x7fc436196b20 <QArrayData::shared_null>}
        args = {<QList<QString>> = {<QListSpecialMethods<QString>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = std::atomic<int> = { -1 }}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x557c6cc61790}, d = 0x557c6cc61790}}, <No data fields>}
        myUseGuiFlag = true
        rootProfileFolder = {d = 0x557c6cc6cd40}
        manager = {<QObject> = {<No data fields>}, static staticMetaObject = {d = {superdata = {direct = 0x7fc436341120 <QObject::staticMetaObject>}, stringdata = 0x7fc4344646e0 <qt_meta_stringdata_QgsUserProfileManager>, data = 0x7fc434464760 <qt_meta_data_QgsUserProfileManager>, static_metacall = 0x7fc432e6a17a <QgsUserProfileManager::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, mWatchProfiles = false, mWatcher = std::unique_ptr<class QFileSystemWatcher> = {get() = 0x0}, mRootProfilePath = {d = 0x557c6cc6cd40}, mUserProfile = std::unique_ptr<class QgsUserProfile> = {get() = 0x0}, mSettings = std::unique_ptr<class QSettings> = {get() = 0x557c6cc5e860}}
        profile = 0x557c6cc6cf80
        profileFolder = {d = 0x557c6cc6d4d0}
        myApp = {<QApplication> = {<No data fields>}, static staticMetaObject = {d = {superdata = {direct = 0x7fc437276f60 <QApplication::staticMetaObject>}, stringdata = 0x7fc434455680 <qt_meta_stringdata_QgsApplication>, data = 0x7fc4344558a0 <qt_meta_data_QgsApplication>, static_metacall = 0x7fc432e5769c <QgsApplication::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, static settingsLocaleUserLocale = {<QgsSettingsEntryByReference<QString>> = {<QgsSettingsEntryBase> = {_vptr.QgsSettingsEntryBase = 0x7fc435bbbe08 <vtable for QgsSettingsEntryString+16>, mKey = {d = 0x557c6ca85f20}, mDefaultValue = {d = {data = {c = 32 ' ', uc = 32 ' ', s = 27424, sc = 32 ' ', us = 27424, i = 907635488, u = 907635488, l = 140480697953056, ul = 140480697953056, b = 32, d = 6.9406686762405694e-310, f = 2.28611316e-06, real = 6.9406686762405694e-310, ll = 140480697953056, ull = 140480697953056, o = 0x7fc436196b20 <QArrayData::shared_null>, ptr = 0x7fc436196b20 <QArrayData::shared_null>, shared = 0x7fc436196b20 <QArrayData::shared_null>}, type = 10, is_shared = 0, is_null = 0}}, mDescription = {d = 0x7fc436196b20 <QArrayData::shared_null>}, mPluginName = {d = 0x7fc436196b20 <QArrayData::shared_null>}, mOptions = {i = 0}}, <No data fields>}, mMinLength = 0, mMaxLength = -1}, static settingsLocaleOverrideFlag = {<QgsSettingsEntryByValue<bool>> = {<QgsSettingsEntryBase> = {_vptr.QgsSettingsEntryBase = 0x7fc435bbbd60 <vtable for QgsSettingsEntryBool+16>, mKey = {d = 0x557c6ca85f70}, mDefaultValue = {d = {data = {c = 0 '\000', uc = 0 '\000', s = -31488, sc = 0 '\000', us = 34048, i = 608732416, u = 608732416, l = 140729507153152, ul = 140729507153152, b = false, d = 6.9529614840542368e-310, f = 4.34807423e-17, real = 6.9529614840542368e-310, ll = 140729507153152, ull = 140729507153152, o = 0x7ffe24488500, ptr = 0x7ffe24488500, shared = 0x7ffe24488500}, type = 1, is_shared = 0, is_null = 0}}, mDescription = {d = 0x7fc436196b20 <QArrayData::shared_null>}, mPluginName = {d = 0x7fc436196b20 <QArrayData::shared_null>}, mOptions = {i = 0}}, <No data fields>}, <No data fields>}, static settingsLocaleGlobalLocale = {<QgsSettingsEntryByReference<QString>> = {<QgsSettingsEntryBase> = {_vptr.QgsSettingsEntryBase = 0x7fc435bbbe08 <vtable for QgsSettingsEntryString+16>, mKey = {d = 0x557c6ca863e0}, mDefaultValue = {d = {data = {c = 32 ' ', uc = 32 ' ', s = 27424, sc = 32 ' ', us = 27424, i = 907635488, u = 907635488, l = 140480697953056, ul = 140480697953056, b = 32, d = 6.9406686762405694e-310, f = 2.28611316e-06, real = 6.9406686762405694e-310, ll = 140480697953056, ull = 140480697953056, o = 0x7fc436196b20 <QArrayData::shared_null>, ptr = 0x7fc436196b20 <QArrayData::shared_null>, shared = 0x7fc436196b20 <QArrayData::shared_null>}, type = 10, is_shared = 0, is_null = 0}}, mDescription = {d = 0x7fc436196b20 <QArrayData::shared_null>}, mPluginName = {d = 0x7fc436196b20 <QArrayData::shared_null>}, mOptions = {i = 0}}, <No data fields>}, mMinLength = 0, mMaxLength = -1}, static settingsLocaleShowGroupSeparator = {<QgsSettingsEntryByValue<bool>> = {<QgsSettingsEntryBase> = {_vptr.QgsSettingsEntryBase = 0x7fc435bbbd60 <vtable for QgsSettingsEntryBool+16>, mKey = {d = 0x557c6ca86430}, mDefaultValue = {d = {data = {c = 0 '\000', uc = 0 '\000', s = -31488, sc = 0 '\000', us = 34048, i = 608732416, u = 608732416, l = 140729507153152, ul = 140729507153152, b = false, d = 6.9529614840542368e-310, f = 4.34807423e-17, real = 6.9529614840542368e-310, ll = 140729507153152, ull = 140729507153152, o = 0x7ffe24488500, ptr = 0x7ffe24488500, shared = 0x7ffe24488500}, type = 1, is_shared = 0, is_null = 0}}, mDescription = {d = 0x7fc436196b20 <QArrayData::shared_null>}, mPluginName = {d = 0x7fc436196b20 <QArrayData::shared_null>}, mOptions = {i = 0}}, <No data fields>}, <No data fields>}, static settingsSearchPathsForSVG = {<QgsSettingsEntryByReference<QStringList>> = {<QgsSettingsEntryBase> = {_vptr.QgsSettingsEntryBase = 0x7fc435bbbdb8 <vtable for QgsSettingsEntryStringList+16>, mKey = {d = 0x557c6ca86490}, mDefaultValue = {d = {data = {c = 48 '0', uc = 48 '0', s = 30256, sc = 48 '0', us = 30256, i = 907638320, u = 907638320, l = 140480697955888, ul = 140480697955888, b = 48, d = 6.9406686763804888e-310, f = 2.28675708e-06, real = 6.9406686763804888e-310, ll = 140480697955888, ull = 140480697955888, o = 0x7fc436197630 <QListData::shared_null>, ptr = 0x7fc436197630 <QListData::shared_null>, shared = 0x7fc436197630 <QListData::shared_null>}, type = 11, is_shared = 0, is_null = 0}}, mDescription = {d = 0x7fc436196b20 <QArrayData::shared_null>}, mPluginName = {d = 0x7fc436196b20 <QArrayData::shared_null>}, mOptions = {i = 0}}, <No data fields>}, <No data fields>}, mIconCache = {d = 0x557c6ca36470}, mCursorCache = {d = 0x557c6e1d5340}, mQgisTranslator = 0x557c6cc6c200, mQtTranslator = 0x557c6cd98da0, mQtBaseTranslator = 0x557c6cd9cdd0, mDataItemProviderRegistry = 0x557c6d592140, mAuthManager = 0x557c6d3b7040, mApplicationMembers = 0x557c6cd830c0}
        settings = {<QObject> = {<No data fields>}, static staticMetaObject = {d = {superdata = {direct = 0x7fc436341120 <QObject::staticMetaObject>}, stringdata = 0x7fc4344658c0 <qt_meta_stringdata_QgsSettings>, data = 0x7fc434465900 <qt_meta_data_QgsSettings>, static_metacall = 0x7fc432e6bbd8 <QgsSettings::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, mUserSettings = 0x557c6cc99d00, mGlobalSettings = 0x557c6d050650, mUsingGlobalArray = false}
        libPaths = {<QList<QString>> = {<QListSpecialMethods<QString>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = std::atomic<int> = { -1 }}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x557c6d3309e0}, d = 0x557c6d3309e0}}, <No data fields>}
        relLibPath = {d = 0x557c6cdbeb30}
        customizationsettings = 0x557c6d5d8bf0
        systemEnvVars = {d = 0x557c6cf06760}
        useCustomVars = false
        desiredStyle = {d = 0x557c6d768ab0}
        theme = {d = 0x557c6cf066f0}
        activeStyleName = {d = 0x557c6d43d270}
        mySplashPath = {d = 0x7fc434650520 <QgsApplication::splashPath()::{lambda()#1}::operator()() const::qstring_literal>}
        myPixmap = <incomplete type>
        screenDpi = 157.74020756611984
        w = 985
        h = 492
        mypSplash = 0x557c6cd97e10
        qgis = 0x557c6dc03130
        sigwatch = {<QObject> = {<No data fields>}, static staticMetaObject = {d = {superdata = {direct = 0x7fc436341120 <QObject::staticMetaObject>}, stringdata = 0x557c6c29fba0 <qt_meta_stringdata_UnixSignalWatcher>, data = 0x557c6c29fc60 <qt_meta_data_UnixSignalWatcher>, static_metacall = 0x557c6c259c80 <UnixSignalWatcher::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, d_ptr = 0x557c6cd47480}
        retval = 0
[Inferior 1 (process 293417) detached]
gdb returned 0
Aborted
```

### Steps to reproduce the issue

1. open the layer styling panel
2. drag and drop `/tests/testdata/3d/earth_size_sphere_4978.gpkg` to a new project
3. select the _3d view_ tab in the styling panel
4. pick _single symbol_ renderer
5. if it did not crash, click _new project_ and goto 2.

sometimes it crashes first time, some times it just refuses to crash

### Versions

29fd311f -> bad
cfbf5ef5 -> good

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
This is expected -- it's only in debug builds and is designed to flag badly behaved code. Make sure the cmake AGGRESSIVE_SAFE_MODE flag is unset and it won't crash, just output error strings instead.
