### ISSUE TITLE
QGIS - SMARTMAP - problem

### ISSUE THREAD

**Issue by stoprocentreal** [qgis/QGIS#52089]
### What is the bug or the crash?

The interpolation isn't working... When I start interpolation It sends me message below. 

             

### Steps to reproduce the issue

Traceback (most recent call last):
              File "/Users/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Smart_Map/Smart_Map.py", line 3809, in pushButton_Krigagem_clicked
              Output_Layer_File_tiff = self.export_raster_to_qgis(Input_Table, Output_Layer_File_tiff, Output_Layer_Name, z_field)
              File "/Users/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Smart_Map/Smart_Map.py", line 8301, in export_raster_to_qgis
              self.define_raster_color_ramp(rlayer, Output_Layer_Name)
              File "/Users/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Smart_Map/Smart_Map.py", line 8526, in define_raster_color_ramp
              QgsColorRampShader.ColorRampItem(classes[2], QColor(int(stops[6]),int(stops[7]),int(stops[8]),int(stops[9])), '%.6f' % classes[2]),
             ValueError: invalid literal for int() with base 10: 'ccw'
             

### Versions

I tried more versions but right now I'm using 3.28.3, Python 3.9.5, macOS Ventura 13.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by YoannQDQ** [comment]
This is a plugin issue. Report it on https://github.com/gustavowillam/SmartMapPlugin/issues

Seems like Smart Map was not updated since QGIS 3.22, so try to install this version instead. I'm closing this one.

**Comment by annaguidi** [comment]
has this been resolved? I still experience this error, have the newest version of the plugin installed, QGIS version is grenoble 3.38.3 and python version is 3.9.5

**Comment by Grinette** [comment]
Hi everyone,
Has the problem been solved?
I'm using version 3.26.3
