### ISSUE TITLE
Export model as script getting "Python error"

### ISSUE THREAD

**Issue by dat-linux** [qgis/QGIS#52387]
### What is the bug or the crash?

2023-03-26T19:54:23     WARNING    Traceback (most recent call last):
              File "/usr/share/qgis/python/plugins/processing/modeler/ModelerDialog.py", line 398, in exportAsScriptAlgorithm
              dlg.show()
              File "/home/.local/share/QGIS/QGIS3/profiles/default/python/plugins/bettereditor/customclasses.py", line 633, in show
              self.customize()
              File "/home/.local/share/QGIS/QGIS3/profiles/default/python/plugins/bettereditor/customclasses.py", line 639, in customize
              self.editor.customize()
              File "/home/.local/share/QGIS/QGIS3/profiles/default/python/plugins/bettereditor/customclasses.py", line 609, in customize
              define_indicators(self)
              File "/home/.local/share/QGIS/QGIS3/profiles/default/python/plugins/bettereditor/indicatorsutils.py", line 61, in define_indicators
              Editor.MARKER_NUM,
             AttributeError: type object 'Editor' has no attribute 'MARKER_NUM'

### Steps to reproduce the issue

Run "export as script algorithm" from the modeler.

### Versions

3.30 on Linux

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
`python/plugins/bettereditor`
This is related to a plugin, try with a new profile (even if you checked it, I I have doubt).

**Comment by dat-linux** [comment]
New profile is the same problem. I have no doubt. 

Though removing the plugin seems to fix things.
