### ISSUE TITLE
Python error 

### ISSUE THREAD

**Issue by abdul1969** [qgis/QGIS#52533]
### What is the bug or the crash?

whenever I add MAP background I get this message 

2023-04-04T17:25:48     WARNING    Traceback (most recent call last):
              File "C:\Users/abdalmenem.altobeh/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\RasterAttributeTable\RasterAttributeTable.py", line 122, in updateRatActions
              if has_rat(layer):
              File "C:\Users/abdalmenem.altobeh/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\RasterAttributeTable\rat_utils.py", line 523, in has_rat
              if get_rat(raster_layer, band).isValid():
              File "C:\Users/abdalmenem.altobeh/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\RasterAttributeTable\rat_utils.py", line 71, in get_rat
              ds = gdal.OpenEx(raster_layer.source())
              File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\osgeo\gdal.py", line 4720, in OpenEx
              return _gdal.OpenEx(*args, **kwargs)
             RuntimeError: `crs=EPSG:3857&format&type=xyz&url=https://mt1.google.com/vt/lyrs%3Dy%26x%3D%7Bx%7D%26y%3D%7By%7D%26z%3D%7Bz%7D&zmax=20&zmin=0' does not exist in the file system, and is not recognized as a supported dataset name.

### Steps to reproduce the issue

d

### Versions

d

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

t

**Comment by nicogodet** [comment]
Raster Attribute Table is now part of QGIS core since QGIS 3.30.

If you can't upgrade for a good reason, your issue is linked to the python plugin Raster Attribute Table and should not be reported on QGIS repo.
It should be reported here: https://github.com/noaa-ocs-hydrography/qgis-raster-attribute-table-plugin/issues
Looking at some currently opened issue on this repo, it has been reported already.
