### ISSUE TITLE
QGis (3.30.0-2) crashes at start up on Manjaro with an error "QGIS died on signal 11" 

### ISSUE THREAD

**Issue by henres** [qgis/QGIS#52883]
### What is the bug or the crash?

QGIS crash at startup

```shell
QGIS died on signal 11QGIS died on signal 11QGIS died on signal 11QGIS died on signal 11QGIS died on signal 11QGIS died on signal 11QGIS died on signal 11QGIS died on signal 11QGIS died on signal 11QGIS died on signal 11QGIS died on signal 11QGIS died on signal 11QGIS died on signal 11QGIS died on signal 11
This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.archlinux.org>
Enable debuginfod for this session? (y or [n]) [answered N; input not from terminal]
Debuginfod has been disabled.
To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
[New LWP 569116]
[New LWP 569117]
[New LWP 569119]
[New LWP 569120]
[New LWP 569121]
[New LWP 569123]
[New LWP 569124]
[New LWP 569125]
[New LWP 569126]
[New LWP 569127]
[New LWP 569128]
[New LWP 569129]
[New LWP 569130]
[New LWP 569131]
[New LWP 569132]
[New LWP 569133]
[New LWP 569134]
[New LWP 569135]
[New LWP 569136]
[New LWP 569137]
[New LWP 569138]
[New LWP 569139]
[New LWP 569140]
[New LWP 569141]
[New LWP 569142]
[New LWP 569143]
[New LWP 569144]
[New LWP 569145]
[New LWP 569146]
[New LWP 569147]
[New LWP 569148]
[New LWP 569149]
[New LWP 569150]

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.archlinux.org>
Enable debuginfod for this session? (y or [n]) [answered N; input not from terminal]
Debuginfod has been disabled.
To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
warning: process 569114 is already traced by process 569155
ptrace: Operation not permitted.
No thread selected
No stack.

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.archlinux.org>
Enable debuginfod for this session? (y or [n]) [answered N; input not from terminal]
Debuginfod has been disabled.
To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
warning: process 569114 is already traced by process 569155
ptrace: Operation not permitted.
No thread selected
No stack.

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.archlinux.org>
Enable debuginfod for this session? (y or [n]) [answered N; input not from terminal]
Debuginfod has been disabled.
To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
warning: process 569114 is already traced by process 569155
ptrace: Operation not permitted.
No thread selected
No stack.

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.archlinux.org>
Enable debuginfod for this session? (y or [n]) [answered N; input not from terminal]
Debuginfod has been disabled.
To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
warning: process 569114 is already traced by process 569155
ptrace: Operation not permitted.
No thread selected
No stack.

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.archlinux.org>
Enable debuginfod for this session? (y or [n]) [answered N; input not from terminal]
Debuginfod has been disabled.
To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
warning: process 569114 is already traced by process 569155
ptrace: Operation not permitted.
No thread selected
No stack.

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.archlinux.org>
Enable debuginfod for this session? (y or [n]) [answered N; input not from terminal]
Debuginfod has been disabled.
To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
warning: process 569114 is already traced by process 569155
ptrace: Operation not permitted.
No thread selected
No stack.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
0x00007f385bb190dd in syscall () from /usr/lib/libc.so.6
[Current thread is 1 (Thread 0x7f385222edc0 (LWP 569114))]
#0  0x00007f385bb190dd in syscall () at /usr/lib/libc.so.6
#1  0x00007f385e0e056c in QSemaphore::acquire(int) () at /usr/lib/libQt5Core.so.5
#2  0x00007f385e9855ae in  () at /usr/lib/libQt5Gui.so.5
#3  0x00007f385e7941ff in QImage::smoothScaled(int, int) const () at /usr/lib/libQt5Gui.so.5
#4  0x00007f385e797e41 in QImage::transformed(QTransform const&, Qt::TransformationMode) const () at /usr/lib/libQt5Gui.so.5
#5  0x00007f385e7c05b4 in QPixmap::transformed(QTransform const&, Qt::TransformationMode) const () at /usr/lib/libQt5Gui.so.5
#6  0x00007f385e7c076c in QPixmap::scaled(QSize const&, Qt::AspectRatioMode, Qt::TransformationMode) const () at /usr/lib/libQt5Gui.so.5
#7  0x000055e97ee6831f in  ()
#8  0x00007f385ba3c790 in  () at /usr/lib/libc.so.6
#9  0x00007f385ba3c84a in __libc_start_main () at /usr/lib/libc.so.6
#10 0x000055e97ee6c8c5 in  ()
gdb returned 256
gdb returned 256
gdb returned 256
gdb returned 256
[Inferior 1 (process 569114) detached]
```

### Steps to reproduce the issue

* Install official version from manjaro
* launch with default command: `qgis`

### Versions

Manjaro
budgie-desktop 10.7.1
QGIS 3.30.0-'s-Hertogenbosch ''s-Hertogenbosch' (exported)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by henres** [comment]
I tried with the one from flatpak (3.30.1) :
```
╰─$ flatpak run org.qgis.qgis --noplugins                                                                                1 ↵
Gtk-Message: 14:57:37.803: Failed to load module "xapp-gtk3-module"
Gtk-Message: 14:57:37.803: Failed to load module "canberra-gtk-module"
Gtk-Message: 14:57:37.835: Failed to load module "canberra-gtk-module"
Gtk-Message: 14:57:37.835: Failed to load module "canberra-gtk-module"
Warning: Qt: Session management error: None of the authentication protocols specified are supported
QGIS died on signal 11QGIS died on signal 11QGIS died on signal 11QGIS died on signal 11QGIS died on signal 11QGIS died on signal 11QGIS died on signal 11QGIS died on signal 11QGIS died on signal 11QGIS died on signal 11QGIS died on signal 11%
```

**Comment by nicogodet** [comment]
QGIS maintains package for Debian and Ubuntu only.
Could you report this issue to manjaro maintainers  and same for flatpak ?

**Comment by alexbruy** [comment]
As noted in the previous comment, this should be reported to the package maintaners.
