### ISSUE TITLE
Uncaught AttributeError: 'RasterizeByExampleAlgorithm' object has no attribute 'tr'


### ISSUE THREAD

**Issue by UrbanPlan-LDB** [qgis/QGIS#52942]
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis-ltr/./python/plugins\processing\gui\AlgorithmLocatorFilter.py", line 95, in fetchResults
    if a.group():
  File "C:\Users\Lucio De Benedictis\AppData\Roaming\QGIS\QGIS3\profiles\Lucio_02_23\processing\scripts\RasterizeByExample.py", line 26, in group
    return self.tr('Raster Tools')
AttributeError: 'RasterizeByExampleAlgorithm' object has no attribute 'tr'

```
processing 2.12.99, QGIS 3.28.5-Firenze on Windows 10

**Comment by nicogodet** [comment]
Certainly not reproducible with a new profile as requested by issue form.

Your issue is related to one of your script and not to QGIS it self.
