### ISSUE TITLE
can't create table in postgresql

### ISSUE THREAD

**Issue by logan001** [qgis/QGIS#52951]
### What is the bug or the crash?

my system: archlinux,  postresql, postgresql 15.2-1, postgis 3.3.2-2

i've made a database/table according to qgis docs and manage to connect to it from qgis without problems but whenever i try to create a table with geometry i get errors like the one below. 
```
_core.QgsException: SQL error: SELECT AddGeometryColumn('public', 'test', 'geom', 0, 'LINESTRING', 2) returned 0 [ERROR:  function addgeometrycolumn(unknown, unknown, unknown, integer, unknown, integer) does not exist LINE 1: SELECT AddGeometryColumn('public', 'test', 'geom', 0, 'LINES...               ^ HINT:  No function matches the given name and argument types. You might need to add explicit type casts. ] 
Traceback (most recent call last):
  File "/usr/share/qgis/python/plugins/db_manager/dlg_create_table.py", line 307, in createTable
    self.db.createVectorTable(table, flds, geom, schema)
  File "/usr/share/qgis/python/plugins/db_manager/db_plugins/plugin.py", line 608, in createVectorTable
    self.connector.addGeometryColumn((schema, table), geomCol, geomType, geomSrid, geomDim)
  File "/usr/share/qgis/python/plugins/db_manager/db_plugins/postgis/connector.py", line 1164, in addGeometryColumn
    self._execute_and_commit(sql)
  File "/usr/share/qgis/python/plugins/db_manager/db_plugins/connector.py", line 103, in _execute_and_commit
    self._execute(None, sql)
  File "/usr/share/qgis/python/plugins/db_manager/db_plugins/postgis/connector.py", line 1216, in _execute
    return CursorAdapter(self.core_connection, sql, feedback=self.feedback)
  File "/usr/share/qgis/python/plugins/db_manager/db_plugins/postgis/connector.py", line 80, in __init__
    self._execute()
  File "/usr/share/qgis/python/plugins/db_manager/db_plugins/postgis/connector.py", line 107, in _execute
    result = self.connection.execSql(self.sql, feedback=self.feedback)
_core.QgsException: SQL error: SELECT AddGeometryColumn('public', 'test', 'geom', 0, 'LINESTRING', 2) returned 0 [ERROR:  function addgeometrycolumn(unknown, unknown, unknown, integer, unknown, integer) does not exist
LINE 1: SELECT AddGeometryColumn('public', 'test', 'geom', 0, 'LINES...
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
]

```

i can create tables without geometry field.
in about qgis i see `PostgreSQL client version unknown`
do i need some python packages that i'm not aware?

### Steps to reproduce the issue

create a user/database in postgresql,, connect to it in qgis, try to create a table with groemtry

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.30.1-'s-Hertogenbosch | QGIS code branch | Release 3.30
-- | -- | -- | --
Qt version | 5.15.9
Python version | 3.10.10
Compiled against GDAL/OGR | 3.6.3 | Running against GDAL/OGR | 3.6.4
PROJ version | 9.2.0
EPSG Registry database version | v10.082 (2023-02-06)
Compiled against GEOS | 3.11.1-CAPI-1.17.1 | Running against GEOS | 3.11.2-CAPI-1.17.2
SQLite version | 3.41.2
PDAL version | 2.5.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.2.0
QScintilla2 version | 2.13.4
OS version | Arch Linux
  |   |   |  
Active Python plugins
qad | 3.0.6
processing | 2.12.99
MetaSearch | 0.3.6
grassprovider | 2.12.99
db_manager | 0.1.20

</body></html>QGIS version
3.30.1-'s-Hertogenbosch
QGIS code branch
[Release 3.30](https://github.com/qgis/QGIS/tree/release-3_30)
Qt version
5.15.9
Python version
3.10.10
Compiled against GDAL/OGR
3.6.3
Running against GDAL/OGR
3.6.4
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
Compiled against GEOS
3.11.1-CAPI-1.17.1
Running against GEOS
3.11.2-CAPI-1.17.2
SQLite version
3.41.2
PDAL version
2.5.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.2.0
QScintilla2 version
2.13.4
OS version
Arch Linux

Active Python plugins
qad
3.0.6
processing
2.12.99
MetaSearch
0.3.6
grassprovider
2.12.99
db_manager
0.1.20

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by logan001** [comment]
nvm. after more googles i find out the create extensions part that i can't find  in qgis docs.
