### ISSUE TITLE
Python error - faulthandler - in QGIS LTR

### ISSUE THREAD

**Issue by dlejay** [qgis/QGIS#52987]
### What is the bug or the crash?

```
An error occurred during execution of following code:
faulthandler.enable(file=fault_handler_file)


Traceback (most recent call last):
  File "", line 1, in 
PermissionError: [Errno 1] Operation not permitted


Python version:
3.10.11 (main, Apr  8 2023, 02:11:11) [Clang 14.0.0 (clang-1400.0.29.202)]

QGIS version:
3.28.6-Firenze 'Firenze', exported

```

### Steps to reproduce the issue

Start QGIS and get greeted with a “Python error” popup.

Notice : this does only happens ~ half of the time when starting QGIS.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.28.6-Firenze | QGIS code branch | Release 3.28
-- | -- | -- | --
Qt version | 5.15.8
Python version | 3.10.11
GDAL/OGR version | 3.6.4
PROJ version | 9.2.0
EPSG Registry database version | v10.082 (2023-02-06)
GEOS version | 3.11.2-CAPI-1.17.2
SQLite version | 3.41.2
PDAL version | 2.5.2
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.3
OS version | macOS 13.3
  |   |   |  
Active Python plugins
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

</body></html>QGIS version
3.28.6-Firenze
QGIS code branch
[Release 3.28](https://github.com/qgis/QGIS/tree/release-3_28)
Qt version
5.15.8
Python version
3.10.11
GDAL/OGR version
3.6.4
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.2
PDAL version
2.5.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.3
OS version
macOS 13.3

Active Python plugins
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by BryanWall** [comment]
The issue is still happening for me on v3.28.6, just compiled from source today

**Comment by Firefishy** [comment]
I get this too. macOS. Installed via conda. I wonder if it is some macOS permissions affecting the startup.

**Comment by Firefishy** [comment]
I can confirm `I tried with a new QGIS profile` and I still get the same error.

**Comment by simenojensen** [comment]
I also have this issue

**Comment by Paree24** [comment]
Getting the same error

**Comment by justinbb** [comment]
The problem is that the Python error handler is being initialized too early (in the constructor of the QGIS app object).
Yes, this has always worked in the past, but it is not okay on Apple Silicon Macs, for unknown reasons – though trying to do everything in the app object constructor is not always possible.
Not dependent on packaging environment (MacPorts, Conda, etc.), error happens in all Apple Silicon builds.

After dismissing the frightening error dialog, one can use QGIS with no apparent problems. However, the Python error handler is NOT present and a Python error will crash the whole thing.
Note that if the error handler is removed and reinstalled (using the Python console), it will work correctly. Thus I conclude that the only problem is the _timing_ of the error handler installation; if it is done later, it is fine.

**Comment by andrensc** [comment]
Have the same issue on an M1 with QGIS 3@justinbb Can I induce a Python error to know if my installation is compromised? Besides how do you remove and reinstall the error handler?

**Comment by bhjolly** [comment]
@justinbb any chance of a quick tip for how to remove/install the faulthandler using the python console? Google/documentation are not helpful and I'm getting hard crashes using the 'Reshape features' tool on a vector layer that are just killing me (I assume fixing the faulthandler might help with that)

**Comment by justinbb** [comment]
@andrensc @bhjolly I think this is sufficient:
– show the Python console (menu Plugins > Python Console)
– at the prompt, type the following lines (taken from `QGIS/src/python/qgspythonutilsimpl.cpp`)
```
import faulthandler
faulthandler.disable()
qgis.utils.__qgis_fault_handler_file=open(qgis.utils.__qgis_fault_handler_file_path, 'wt')
faulthandler.enable(file=qgis.utils.__qgis_fault_handler_file)
```
The purpose of the Python fault handler is to provide debugging information in case a fatal error occurs in Python code. It may or may not be relevant to the problem you're having.

**Comment by bhjolly** [comment]
Thanks @justinbb, I actually got the same error running that code in my console:
```
>>> import faulthandler
>>> faulthandler.disable()
True
>>> qgis.utils.__qgis_fault_handler_file=open(qgis.utils.__qgis_fault_handler_file_path, 'wt')
>>> faulthandler.enable(file=qgis.utils.__qgis_fault_handler_file)
Traceback (most recent call last):
  File "/Users/jollyb/micromamba/envs/qgis/lib/python3.12/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
PermissionError: [Errno 1] Operation not permitted
```
If I re-run that .enable line in the same session it doesn't throw it the second time. However on a restart I still get the popup with the faulthandler 'Operation not permitted' error. This is for QGIS 3.38 installed from conda-forge.

As a side note, even once that code was run my issue with the Reshape tool still caused a hard crash so not sure what's going on there (might try and log a new GH issue)

**Comment by fhfonsecaa** [comment]
I have the same issue:

```
An error occurred during execution of following code:
faulthandler.enable(file=qgis.utils.__qgis_fault_handler_file)


Traceback (most recent call last):
  File "", line 1, in 
PermissionError: [Errno 1] Operation not permitted


Python version:
3.12.6 | packaged by conda-forge | (main, Sep 11 2024, 04:57:14) [Clang 17.0.6 ]

QGIS version:
3.38.2-Grenoble 'Grenoble', exported
```

I installed from `conda` and I have the following system:

<img width="392" alt="image" src="https://github.com/user-attachments/assets/197271f2-85cf-4450-a1f0-1a0376eee355">

**Comment by mgelain** [comment]
Same error here, installed via macports:
faulthandler.enable(file=qgis.utils.__qgis_fault_handler_file)


Traceback (most recent call last):
  File "", line 1, in 
PermissionError: [Errno 1] Operation not permitted


Python Version:
3.12.7 (main, Oct  5 2024, 01:39:55) [Clang 16.0.0 (clang-1600.0.26.3)]

Versione di QGIS:
3.34.11-Prizren 'Prizren', exported
Python Path:
['/Applications/MacPorts/QGIS3-LTR.app/Contents/MacOS/../Resources/python', '/Users/hhh/Library/Application Support/QGIS/QGIS3/profiles/default/python', '/Users/hhh/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins', '/Applications/MacPorts/QGIS3-LTR.app/Contents/MacOS/../Resources/python/plugins', '/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python312.zip', '/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12', '/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/lib-dynload', '/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages']

**Comment by varioushemrog** [comment]
Having the same problem.  On a MacBook Pro 2021 M1. 

**An error occurred during execution of following code:
faulthandler.enable(file=qgis.utils.__qgis_fault_handler_file)**


Traceback (most recent call last):
  File "", line 1, in 
PermissionError: [Errno 1] Operation not permitted


Python version:
3.12.9 | packaged by conda-forge | (main, Feb 14 2025, 07:58:30) [Clang 18.1.8 ]

QGIS version:
3.40.3-Bratislava 'Bratislava', exported

Python path:
['/Users/HelenaMaria/documents/permaculture/TopographicMapsTools/MiniConda3/[/Users/HelenaMaria/Documents/PERMACULTURE/TopographicMapsTools/MiniConda3]/envs/QGIS/share/qgis/python', '/Users/HelenaMaria/Library/Application Support/QGIS/QGIS3/profiles/default/python', '/Users/HelenaMaria/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins', '/Users/HelenaMaria/documents/permaculture/TopographicMapsTools/MiniConda3/[/Users/HelenaMaria/Documents/PERMACULTURE/TopographicMapsTools/MiniConda3]/envs/QGIS/share/qgis/python/plugins', '/Users/HelenaMaria/documents/permaculture/TopographicMapsTools/MiniConda3/[/Users/HelenaMaria/Documents/PERMACULTURE/TopographicMapsTools/MiniConda3]/envs/QGIS/share/qgis/python/plugins', '/Users/HelenaMaria/documents/permaculture/TopographicMapsTools/MiniConda3/[/Users/HelenaMaria/Documents/PERMACULTURE/TopographicMapsTools/MiniConda3]/envs/QGIS/share/qgis/python', '/Users/HelenaMaria', '/Users/HelenaMaria/documents/permaculture/TopographicMapsTools/MiniConda3/[/Users/HelenaMaria/Documents/PERMACULTURE/TopographicMapsTools/MiniConda3]/envs/QGIS/lib/python312.zip', '/Users/HelenaMaria/documents/permaculture/TopographicMapsTools/MiniConda3/[/Users/HelenaMaria/Documents/PERMACULTURE/TopographicMapsTools/MiniConda3]/envs/QGIS/lib/python3.12', '/Users/HelenaMaria/documents/permaculture/TopographicMapsTools/MiniConda3/[/Users/HelenaMaria/Documents/PERMACULTURE/TopographicMapsTools/MiniConda3]/envs/QGIS/lib/python3.12/lib-dynload', '/Users/HelenaMaria/documents/permaculture/TopographicMapsTools/MiniConda3/[/Users/HelenaMaria/Documents/PERMACULTURE/TopographicMapsTools/MiniConda3]/envs/QGIS/lib/python3.12/site-packages']

Is there any other place where we can find support for Macs?

**Comment by m-kuhn** [comment]
> Note that if the error handler is removed and reinstalled (using the Python console), it will work correctly. Thus I conclude that the only problem is the _timing_ of the error handler installation; if it is done later, it is fine.

Unfortunately deferring this doesn't make a difference, I postponed the faulthandler init to 10 seconds after start and it will trigger the same (permissions) problem.
What I can confirm is that it only raises a pemission exception once (disabling it in the app init, it will raise the first time it's executed on the python terminal).

**Comment by nyalldawson** [comment]
@m-kuhn I think we should just disable the faulthandler completely on Mac. There must be some underlying issue with the module on Mac, but I can't find any other references to this.

**Comment by justinbb** [comment]
As @nyalldawson says, it should be disabled, until the underlying problem can (someday?) be fixed. Maybe the faulthandler would be helpful for plugin developers, but for ordinary users the false alarm and annoyance of the alert far outweighs any theoretical benefits.

@m-kuhn Aha, it seems I was led astray by the old report-the-error-the-first-time-only [trick](https://en.wikipedia.org/wiki/Get_Smart). Thank you for checking the (now disproven) deferral hypothesis.

**Comment by Patpatchung** [comment]
The issue is still happening for me on v.3.40.6-Bratislava, macOS 15.4.1, MacBook Pro M3.
However, when I run it in clamshell mode, the issue doesn't appear.
In my opinion, this has to do with whether or not Touch ID is used.
