### ISSUE TITLE
Errore python: Si è verificato un errore durante l'esecuzione del codice Python: Vedi il log dei messaggi (Errore Python) per maggiori dettagli.

### ISSUE THREAD

**Issue by giogeromino** [qgis/QGIS#53158]
### What is the bug or the crash?

Hi, what could i do?

2023-05-19T10:30:11     WARNING    Traceback (most recent call last):
              File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python/plugins\processing\script\ScriptAlgorithmProvider.py", line 128, in loadAlgorithms
              alg = ScriptUtils.loadAlgorithm(moduleName, filePath)
              File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python/plugins\processing\script\ScriptUtils.py", line 67, in loadAlgorithm
              spec.loader.exec_module(module)
              File "", line 851, in exec_module
              File "", line 988, in get_code
              File "", line 918, in source_to_code
              File "", line 228, in _call_with_frames_removed
              File "C:\Users\Utente\AppData\Roaming\QGIS\QGIS3\profiles\default\processing\scripts\saga01.py", line 1
              Usage: saga_cmd ta_preprocessor 4 -ELEV [-FILLED ] [-FDIR ] [-WSHED ] [-MINSLOPE ]
              ^
             SyntaxError: invalid syntax

### Steps to reproduce the issue

opening qgis

### Versions

same problem on 3.30.2 and 3.28.6 on win11

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@giogeromino, as indicated in the warning message, it seems you have installed a bugged Python script (saga01.py) in C:\Users\Utente\AppData\Roaming\QGIS\QGIS3\profiles\default\processing\scripts\
Remove or fix it in order to avoid the warning message.

**Comment by giogeromino** [comment]
Credo possiamo parlare in italiano. Non ho fatto alcuna installazione aggiuntiva, dunque dovrebbe essere qualcosa che proviene dalla installazione del programma principale, come poso fare?

**Comment by giogeromino** [comment]
Aggiungo un particolare, non so se possa essere utile. Le stesse installazioni (3.30 e 3.28) in un pc vecchio con win 10 non producono lo stesso errore

**Comment by agiudiceandrea** [comment]
The Python script is not in the QGIS installation folder and it is not installed by the QGIS installer, but it is in the folder for user custom Python scripts of the QGIS user profile that you are using. So you need to either remove such Python script from the folder of the QGIS user profile you are using as already indicated, or create and use a new QGIS user profile.
