### ISSUE TITLE
Impossibile caricare il plugin 'wps' a causa di un errore chiamando il metodo classFactory() 

### ISSUE THREAD

**Issue by 33PG33** [qgis/QGIS#53226]
### What is the issue about the documentation?

ValueError: unknown API 'QVariant' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.6/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/patrick.gianoni/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\wps\__init__.py", line 50, in classFactory
    from .qgswps import QgsWps
  File "C:\PROGRA~1/QGIS32~1.6/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/patrick.gianoni/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\wps\qgswps.py", line 23, in 
    from .QgsWpsDockWidget import QgsWpsDockWidget
  File "C:\PROGRA~1/QGIS32~1.6/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/patrick.gianoni/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\wps\QgsWpsDockWidget.py", line 26, in 
    from .qgswpsgui import QgsWpsGui
  File "C:\PROGRA~1/QGIS32~1.6/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/patrick.gianoni/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\wps\qgswpsgui.py", line 26, in 
    from .wpslib.wpsserver import WpsServer
  File "C:\PROGRA~1/QGIS32~1.6/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/patrick.gianoni/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\wps\wpslib\wpsserver.py", line 29, in 
    from ..apicompat.sipv2.compat import pystring
  File "C:\PROGRA~1/QGIS32~1.6/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/patrick.gianoni/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\wps\apicompat\__init__.py", line 2, in 
    from . import apicompat
  File "C:\PROGRA~1/QGIS32~1.6/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/patrick.gianoni/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\wps\apicompat\apicompat.py", line 34, in 
    if sipv1():
  File "C:\Users/patrick.gianoni/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\wps\apicompat\apicompat.py", line 30, in sipv1
    return sip.getapi("QVariant") == 1
ValueError: unknown API 'QVariant'

Versione Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Versione di QGIS: 3.28.6-Firenze Firenze, 868c9fa03b 

Percorso Python:
C:\Users/patrick.gianoni/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\networks
C:/PROGRA~1/QGIS32~1.6/apps/qgis-ltr/./python
C:/Users/patrick.gianoni/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/patrick.gianoni/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.6/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS32~1.6\apps\grass\grass82\etc\python
C:\Users\Public\Desktop\QGIS 3.28.6
C:\Program Files\QGIS 3.28.6\bin\python39.zip
C:\PROGRA~1\QGIS32~1.6\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.6\apps\Python39\lib
C:\Program Files\QGIS 3.28.6\bin
C:\PROGRA~1\QGIS32~1.6\apps\Python39
C:\PROGRA~1\QGIS32~1.6\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.6\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.6\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.6\apps\Python39\lib\site-packages\Pythonwin
C:/Users/patrick.gianoni/AppData/Roaming/QGIS/QGIS3\profiles\default/python

**Comment by agiudiceandrea** [comment]
@33PG33 the issue is due to the "WPS Client" plugin that you have installed in your QGIS user profile. Please report the issue to the plugin repository. To workaround the issue, uninstall the plugin.
