### ISSUE TITLE
Uncaught AttributeError: 'RasterizeByExampleAlgorithm' object has no attribute 'tr'


### ISSUE THREAD

**Issue by UrbanPlan-LDB** [qgis/QGIS#53279]
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis/./python/plugins\processing\gui\AlgorithmLocatorFilter.py", line 95, in fetchResults
    if a.group():
  File "C:\Users\Lucio De Benedictis\AppData\Roaming\QGIS\QGIS3\profiles\Lucio_02_23\processing\scripts\RasterizeByExample.py", line 26, in group
    return self.tr('Raster Tools')
AttributeError: 'RasterizeByExampleAlgorithm' object has no attribute 'tr'

```
processing 2.12.99, QGIS 3.30.2-'s-Hertogenbosch on Windows 10

**Comment by DelazJ** [comment]
@UrbanPlan-LDB As already explained at https://github.com/qgis/QGIS/issues/52942#issuecomment-1528825690, this is not a QGIS issue but an error related to your RasterizeByExample.py script. So please, report back to the author if it is not you.

**Comment by UrbanPlan-LDB** [comment]
OK, sorry. thanks for the suggestion. good work and have a nice day
