### ISSUE TITLE
Gdal Polygonize not working

### ISSUE THREAD

**Issue by jorgealonsog28** [qgis/QGIS#53364]
### What is the bug or the crash?

GDAL command output:
Creating output C:/Users/Land Life Company/AppData/Local/Temp/processing_suExSo/19b0621a98f744da8d53f8ba7a06ffc4/OUTPUT.xtf of format Interlis 2.
Traceback (most recent call last): 
File "C:\PROGRA~1\QGIS32~1.7\apps\Python39\lib\site-packages\osgeo_utils\auxiliary\gdal_argparse.py", line 175, in main 
self.doit(**kwargs) 
File "C:\PROGRA~1\QGIS32~1.7\apps\Python39\lib\site-packages\osgeo_utils\gdal_polygonize.py", line 314, in doit 
return gdal_polygonize(**kwargs) 
File "C:\PROGRA~1\QGIS32~1.7\apps\Python39\lib\site-packages\osgeo_utils\gdal_polygonize.py", line 132, in gdal_polygonize 
dst_layer = dst_ds.CreateLayer( 
AttributeError: 'NoneType' object has no attribute 'CreateLayer'
Process returned error code 1
Execution completed in 0.45 seconds
Results:
{'OUTPUT': 'C:/Users/Land Life '
'Company/AppData/Local/Temp/processing_suExSo/19b0621a98f744da8d53f8ba7a06ffc4/OUTPUT.xtf'}

### Steps to reproduce the issue

1. Open the polygonize tool
2. Select the .tif I want to convert
3. Execute the tool

### Versions

3.28.7 

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
The error message clearly states that GDAL can't create an output in XTF format. Please select another format for your output.
