### ISSUE TITLE
Crash when switching from symbology rule in styling panel to geom-less scratch layer

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#53876]
### What is the bug or the crash?

QGIS crashes if I have a rule symbology view/tab open in the styling panel and switch to a geometryless scratch layer.

### Steps to reproduce the issue

1. Open the attached project [crash.qgz.zip](https://github.com/qgis/QGIS/files/12093792/crash.qgz.zip)
3. Select the "world" layer
4. In the styling panel double click on the rule of the style so that the symbology of the rule is open in the styling panel
5. Click on the "scratch layer, no geom" layer in the layer list
6. QGIS crashes

My `gdb` backtrace:
```
$ gdb qgis.bin 
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from qgis.bin...
Reading symbols from /usr/lib/debug/.build-id/4d/83aecf1a95ed8ee05830ea6a6c92ef7a23238d.debug...
(gdb) run
Starting program: /usr/bin/qgis.bin 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe0a84640 (LWP 44686)]
[New Thread 0x7fffdb368640 (LWP 44687)]
[New Thread 0x7fffdaacc640 (LWP 44689)]
[New Thread 0x7fffda2cb640 (LWP 44690)]
[New Thread 0x7fffd8dbc640 (LWP 44691)]
[New Thread 0x7fffc35ff640 (LWP 44692)]
[New Thread 0x7fffc2dfe640 (LWP 44693)]
[New Thread 0x7fffc25fd640 (LWP 44694)]
[New Thread 0x7fffc09b9640 (LWP 44695)]
[New Thread 0x7fffb3fff640 (LWP 44696)]
[New Thread 0x7fffb37fe640 (LWP 44697)]
[New Thread 0x7fffb2ffd640 (LWP 44698)]
[New Thread 0x7fffb27fc640 (LWP 44699)]
[New Thread 0x7fffb1928640 (LWP 45781)]
[New Thread 0x7fffb0f86640 (LWP 45806)]
[New Thread 0x7fff8ffff640 (LWP 45807)]
[New Thread 0x7fff8f7fe640 (LWP 45808)]
[Detaching after fork from child process 45809]
[New Thread 0x7fff8effd640 (LWP 45811)]
[Detaching after vfork from child process 45813]
[New Thread 0x7fff3bfc9640 (LWP 45816)]
[New Thread 0x7fff3a5ff640 (LWP 45817)]
[New Thread 0x7fff399ff640 (LWP 45818)]
[New Thread 0x7fff38dff640 (LWP 45821)]
[New Thread 0x7fff2bfff640 (LWP 45822)]
[New Thread 0x7fff2b7fe640 (LWP 45823)]
Warning 4: Failed to open /usr/share/qgis/resources/data/world_map.gpkg: Keine Berechtigung.

bt
Thread 1 "qgis.bin" received signal SIGSEGV, Segmentation fault.
QgsLayerStylingWidget::apply (this=0x555557b18e90) at ./src/app/qgslayerstylingwidget.cpp:347
347	./src/app/qgslayerstylingwidget.cpp: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  QgsLayerStylingWidget::apply() (this=0x555557b18e90) at ./src/app/qgslayerstylingwidget.cpp:347
#1  0x00007ffff48f1793 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#2  0x00007ffff48f57fe in QTimer::timeout(QTimer::QPrivateSignal) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#3  0x00007ffff48e733f in QObject::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007ffff556c713 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#5  0x00007ffff2fa2ca3 in QgsApplication::notify(QObject*, QEvent*) (this=0x7fffffffd5b0, receiver=0x555557b2ab10, event=0x7fffffffcf80) at ./src/core/qgsapplication.cpp:580
#6  0x00007ffff48b9e3a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007ffff49123eb in QTimerInfoList::activateTimers() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007ffff4912cec in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007fffea720d3b in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x00007fffea776258 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007fffea71e3e3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#12 0x00007ffff49130b8 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007ffff48b875b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007ffff48c0cf4 in QCoreApplication::exec() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x0000555555562002 in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at ./src/app/main.cpp:1817
(gdb)
```

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS-Version | 3.32.0-Lima | QGIS-Codeversion | 311a8cb8a6
-- | -- | -- | --
Qt-Version | 5.15.3
Python-Version | 3.10.6
GDAL-Version | 3.4.1
PROJ-Version | 8.2.1
EPSG-Registraturdatenbankversion | v10.041 (2021-12-03)
GEOS-Version | 3.10.2-CAPI-1.16.0
SQLite-Version | 3.37.2
PDAL-Version | 2.3.0
PostgreSQL-Client-Version | 14.8 (Ubuntu 14.8-0ubuntu0.22.04.1)
SpatiaLite-Version | 5.0.1
QWT-Version | 6.1.4
QScintilla2-Version | 2.11.6
BS-Version | Ubuntu 22.04.2 LTS
  |   |   |  
Aktive Python-Erweiterungen
processing | 2.12.99
grassprovider | 2.12.99
MetaSearch | 0.3.6
db_manager | 0.1.20

</body></html>QGIS-Version
3.32.0-Lima
QGIS-Codeversion
[311a8cb8a6](https://github.com/qgis/QGIS/commit/311a8cb8a6)
Qt-Version
5.15.3
Python-Version
3.10.6
GDAL-Version
3.4.1
PROJ-Version
8.2.1
EPSG-Registraturdatenbankversion
v10.041 (2021-12-03)
GEOS-Version
3.10.2-CAPI-1.16.0
SQLite-Version
3.37.2
PDAL-Version
2.3.0
PostgreSQL-Client-Version
14.8 (Ubuntu 14.8-0ubuntu0.22.04.1)
SpatiaLite-Version
5.0.1
QWT-Version
6.1.4
QScintilla2-Version
2.11.6
BS-Version
Ubuntu 22.04.2 LTS

Aktive Python-Erweiterungen
processing
2.12.99
grassprovider
2.12.99
MetaSearch
0.3.6
db_manager
0.1.20

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Screen to be on before switching to the scratch layer:
![grafik](https://github.com/qgis/QGIS/assets/7661092/e8339078-6977-489c-a9f1-f19763778c03)

**Comment by kannes** [comment]
Thanks @elpaso!
