### ISSUE TITLE
Applying filters QgsMapLayerComboBox in the Qt Designer causes plugin to crash

### ISSUE THREAD

**Issue by H-W-LANGE** [qgis/QGIS#54890]
### What is the bug or the crash?

I am in the process of developing a plugin for QGIS and ran into issues when I tried to apply filters to the QgsMapLayerComboBox widget. As soon as I tried to remove some of the options in the filter section, QGIS was unable to open the plugin and gave the following error:

`Couldn't load plugin 'view_drone' due to an error when calling its classFactory() method 

PyQt5.uic.exceptions.NoSuchClassError: Unknown C++ class: QgsMapLayerProxyModel 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS33~1.3/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/hewa/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\view_drone\__init__.py", line 35, in classFactory
    from .view_drone import ViewDrone
  File "C:\PROGRA~1/QGIS33~1.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/hewa/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\view_drone\view_drone.py", line 31, in 
    from .view_drone_dialog import ViewDroneDialog
  File "C:\PROGRA~1/QGIS33~1.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/hewa/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\view_drone\view_drone_dialog.py", line 31, in 
    FORM_CLASS, _ = uic.loadUiType(os.path.join(
  File "C:\PROGRA~1/QGIS33~1.3/apps/qgis/./python\qgis\PyQt\uic\__init__.py", line 36, in __loadUiType
    return __PyQtLoadUiType(*args, **kwargs)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\__init__.py", line 200, in loadUiType
    winfo = compiler.UICompiler().compileUi(uifile, code_string, from_imports,
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\Compiler\compiler.py", line 111, in compileUi
    w = self.parse(input_stream, resource_suffix)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 1037, in parse
    actor(elem)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 828, in createUserInterface
    self.traverseWidgetTree(elem)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 503, in createLayout
    self.traverseWidgetTree(elem)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 546, in handleItem
    self.traverseWidgetTree(elem)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 264, in createWidget
    self.stack.push(self.setupObject(widget_class, parent, elem))
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 230, in setupObject
    self.wprops.setProperties(obj, branch)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\properties.py", line 415, in setProperties
    prop_value = self.convert(prop, widget)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\properties.py", line 378, in convert
    return func(prop[0], **args)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\properties.py", line 120, in _set
    expr = [self._pyEnumMember(v) for v in prop.text.split('|')]
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\properties.py", line 120, in 
    expr = [self._pyEnumMember(v) for v in prop.text.split('|')]
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\properties.py", line 115, in _pyEnumMember
    raise NoSuchClassError(prefix)
PyQt5.uic.exceptions.NoSuchClassError: Unknown C++ class: QgsMapLayerProxyModel

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.32.3-Lima Lima, 67d46100b5 

Python Path:
C:\Users/hewa/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\AddressToolsDK
C:/PROGRA~1/QGIS33~1.3/apps/qgis/./python
C:/Users/hewa/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/hewa/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS33~1.3/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS33~1.3\apps\grass\grass83\etc\python
C:\Users\hewa\Documents
C:\Program Files\QGIS 3.32.3\bin\python39.zip
C:\PROGRA~1\QGIS33~1.3\apps\Python39\DLLs
C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib
C:\Program Files\QGIS 3.32.3\bin
C:\Users\hewa\AppData\Roaming\Python\Python39\site-packages
C:\PROGRA~1\QGIS33~1.3\apps\Python39
C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\Pythonwin
C:/Users/hewa/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\hewa\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools
C:\Users\hewa\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools
C:\Users\hewa\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\HCMGIS/forms`

### Steps to reproduce the issue

- Create a plugin using the plugin builder
- Open the UI file in the Qt Designer
- Add a QgsMapLayerComboBox
- Apply a filter (eg. unchecking a box in the filter section)
- Save UI file
- Launch QGIS/try to open plugin

### Versions

I've tried using both 3.28.10-Firenze and 3.32.3-Lima and they both have the same issue

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by alexbruy** [comment]
Duplicates #38472.

Please search bugtracker before creating new ticket.
