### ISSUE TITLE
QGIS LTR via Osgeo4W fails to run several plugins including processing

### ISSUE THREAD

**Issue by antoniolocandro** [qgis/QGIS#55093]
### What is the bug or the crash?

2023-10-30T10:05:36     CRITICAL    Traceback (most recent call last):
              File "C:\OSGeo4W\apps\gdal-dev\lib\site-packages\osgeo\__init__.py", line 30, in swig_import_helper
              return importlib.import_module(mname)
              File "C:\OSGeo4W\apps\Python39\lib\importlib\__init__.py", line 127, in import_module
              return _bootstrap._gcd_import(name[level:], package, level)
              File "", line 1030, in _gcd_import
              File "", line 1007, in _find_and_load
              File "", line 986, in _find_and_load_unlocked
              File "", line 666, in _load_unlocked
              File "", line 565, in module_from_spec
              File "", line 1173, in create_module
              File "", line 228, in _call_with_frames_removed
             ImportError: DLL load failed while importing _gdal: The specified module could not be found.
             

### Steps to reproduce the issue

Update via Osgeo4W, open QGIS-ltr

### Versions

QGIS version
3.28.12-Firenze
QGIS code revision
dcc633b2de
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.2
PROJ version
9.3.0
EPSG Registry database version
v10.094 (2023-08-08)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
MemoryLayerSaver
5.0.1
quick_map_services
0.19.33
db_manager
0.1.20

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Couldn't load plugin 'processing' 

ModuleNotFoundError: No module named '_gdal' 
Traceback (most recent call last):
  File "C:\OSGeo4W\apps\gdal-dev\lib\site-packages\osgeo\__init__.py", line 30, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\OSGeo4W\apps\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "", line 1030, in _gcd_import
  File "", line 1007, in _find_and_load
  File "", line 986, in _find_and_load_unlocked
  File "", line 666, in _load_unlocked
  File "", line 565, in module_from_spec
  File "", line 1173, in create_module
  File "", line 228, in _call_with_frames_removed
ImportError: DLL load failed while importing _gdal: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 401, in loadPlugin
    __import__(packageName)
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGeo4W/apps/qgis-ltr/./python/plugins\processing\__init__.py", line 26, in 
    from processing.tools.general import *  # NOQA
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGeo4W/apps/qgis-ltr/./python/plugins\processing\tools\general.py", line 32, in 
    from processing.core.Processing import Processing
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGeo4W/apps/qgis-ltr/./python/plugins\processing\core\Processing.py", line 58, in 
    from processing.algs.qgis.QgisAlgorithmProvider import QgisAlgorithmProvider  # NOQA
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGeo4W/apps/qgis-ltr/./python/plugins\processing\algs\qgis\QgisAlgorithmProvider.py", line 49, in 
    from .HypsometricCurves import HypsometricCurves
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGeo4W/apps/qgis-ltr/./python/plugins\processing\algs\qgis\HypsometricCurves.py", line 27, in 
    from osgeo import gdal, ogr, osr
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGeo4W\apps\gdal-dev\lib\site-packages\osgeo\__init__.py", line 35, in 
    _gdal = swig_import_helper()
  File "C:\OSGeo4W\apps\gdal-dev\lib\site-packages\osgeo\__init__.py", line 32, in swig_import_helper
    return importlib.import_module('_gdal')
  File "C:\OSGeo4W\apps\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_gdal'

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.28.12-Firenze Firenze, dcc633b2de 

Python Path:
C:/OSGeo4W/apps/qgis-ltr/./python
C:/Users/anton/AppData/Roaming/QGIS/QGIS3\profiles\delete/python
C:/Users/anton/AppData/Roaming/QGIS/QGIS3\profiles\delete/python/plugins
C:/OSGeo4W/apps/qgis-ltr/./python/plugins
C:\OSGeo4W\apps\grass\grass83\etc\python
C:\OSGeo4W\apps\gdal-dev\lib\site-packages
C:\OSGeo4W
C:\OSGeo4W\bin\python39.zip
C:\OSGeo4W\apps\Python39\DLLs
C:\OSGeo4W\apps\Python39\lib
C:\OSGeo4W\bin
C:\OSGeo4W\apps\Python39
C:\OSGeo4W\apps\Python39\lib\site-packages
C:\OSGeo4W\apps\Python39\lib\site-packages\win32
C:\OSGeo4W\apps\Python39\lib\site-packages\win32\lib
C:\OSGeo4W\apps\Python39\lib\site-packages\Pythonwin
C:/Users/anton/AppData/Roaming/QGIS/QGIS3\profiles\delete/python

**Comment by agiudiceandrea** [comment]
@antoniolocandro, since it seems the issue is not in the QGIS codebase, but it seems an OSGeo4W installer/packaging issue, I think it would be useful to report the issue on https://trac.osgeo.org/osgeo4w/

**Comment by antoniolocandro** [comment]
I will try to do it but user setup in osgeo4w is a bit difficult to register to post the comment

**Comment by antoniolocandro** [comment]
Ok, I was uninstalling and reinstall and it worked. SAGA issues but I don't really use that one so I will close
