### ISSUE TITLE
LTR: fails to build with SIP 6.8.0

### ISSUE THREAD

**Issue by buzo-ffm** [qgis/QGIS#55481]
### What is the bug or the crash?

LTR 3.28.13 fails to build on Arch Linux with SIP 6.8, see attached build output.

### Steps to reproduce the issue

Try to build LTR 3.28.13 with SIP 6.8.

### Versions

QGIS LTR 3.28.13, SIP 6.8

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by MehdiChinoune** [comment]
I have encountered the same issue with 3.34.1

**Comment by jef-n** [comment]
Is this actually a qgis issue?  The error looks like a bug within sip.  Are there other packages that use that version of sip in arch?

**Comment by MehdiChinoune** [comment]
Well this issue is due a typo is sip code https://www.riverbankcomputing.com/pipermail/pyqt/2023-November/045607.html

**Comment by gdt** [comment]
I have been in touch with sip upstream, reporting problems and testing.   There are commits to sip's 6.8-maint branch since 6.8.1, and I just tested with `changeset:   2984:fc6f81078cc4`.    I confirmed that rolling sip back to 6.7.12 results in qgis building fine.   I realize that we are not necessarily finding a qgis bug, but obviously we should be in a state where the latest qgis release builds with the latest sip release, and right now I'm not sure what needs fixing.

qgis now gets much further along, and fails with
```
[ 83%] Building CXX object python/CMakeFiles/python_module_qgis__core.dir/core/build/_core/sip_corepart0.cpp.o
In file included from /tmp/work/geography/qgis/work/qgis-3.28.13/build/python/core/build/_core/sipAPI_core.h:10,
                 from /tmp/work/geography/qgis/work/qgis-3.28.13/build/python/core/build/_core/sip_corepart0.cpp:7:
/tmp/work/geography/qgis/work/qgis-3.28.13/build/python/core/build/sip.h:84: warning: "SIP_VERSION" redefined
   84 | #define SIP_VERSION                 0x60800
      | 
<command-line>: note: this is the location of the previous definition
conversions.sip: In function 'bool null_from_qvariant_converter(const QVariant*, PyObject**)':
conversions.sip:2132: warning: comparison between 'enum QVariant::Type' and 'enum QMetaType::Type' [-Wenum-compare]
conversions.sip:2132: warning: comparison between types 'QVariant::Type' and 'QMetaType::Type' [-Wsign-compare]
conversions.sip:2133: warning: comparison between 'enum QVariant::Type' and 'enum QMetaType::Type' [-Wenum-compare]
conversions.sip:2133: warning: comparison between types 'QVariant::Type' and 'QMetaType::Type' [-Wsign-compare]
conversions.sip:2134: warning: comparison between 'enum QVariant::Type' and 'enum QMetaType::Type' [-Wenum-compare]
conversions.sip:2134: warning: comparison between types 'QVariant::Type' and 'QMetaType::Type' [-Wsign-compare]
/tmp/work/geography/qgis/work/qgis-3.28.13/build/python/core/build/_core/sip_corepart0.cpp: At global scope:
/tmp/work/geography/qgis/work/qgis-3.28.13/build/python/core/build/_core/sip_corepart0.cpp:28321: error: 'sip_gilstate_tsipGILState' has not been declared
28321 | void sipVEH__core_processing_exception_handler(sipSimpleWrapper *, sip_gilstate_tsipGILState)
      | 
In file included from /tmp/work/geography/qgis/work/qgis-3.28.13/build/python/core/build/_core/sipAPI_core.h:10,
                 from /tmp/work/geography/qgis/work/qgis-3.28.13/build/python/core/build/_core/sip_corepart0.cpp:7:
/tmp/work/geography/qgis/work/qgis-3.28.13/build/python/core/core.sip: In function 'void sipVEH__core_processing_exception_handler(sipSimpleWrapper*, int)':
/tmp/work/geography/qgis/work/qgis-3.28.13/build/python/core/core.sip:149: error: 'sipGILState' was not declared in this scope; did you mean 'sipGetState'?
  149 |     SIP_RELEASE_GIL( sipGILState );
      | 
/tmp/work/geography/qgis/work/qgis-3.28.13/build/python/core/build/sip.h:178:48: note: in definition of macro 'SIP_RELEASE_GIL'
  178 | #define SIP_RELEASE_GIL(gs) PyGILState_Release(gs);
      |                                                ^~
auto_generated/symbology/qgsstyle.sip: In function 'const sipTypeDef* sipSubClass_QgsStyleEntityInterface(void**)':
auto_generated/symbology/qgsstyle.sip:1253: warning: enumeration value 'LegendPatchShapeEntity' not handled in switch [-Wswitch]
auto_generated/symbology/qgsstyle.sip:1253: warning: enumeration value 'Symbol3DEntity' not handled in switch [-Wswitch]
/tmp/work/geography/qgis/work/qgis-3.28.13/build/python/core/build/_core/sip_corepart0.cpp: In function 'bool sipExceptionHandler__core(std::__exception_ptr::exception_ptr)':
/tmp/work/geography/qgis/work/qgis-3.28.13/build/python/core/build/_core/sip_corepart0.cpp:38168: warning: exception of type 'QgsProviderConnectionException' will be caught
38168 |             catch (QgsProviderConnectionException &sipExceptionRef)
      | 
/tmp/work/geography/qgis/work/qgis-3.28.13/build/python/core/build/_core/sip_corepart0.cpp:38158: warning:    by earlier handler for 'QgsException'
38158 |             catch (QgsException &sipExceptionRef)
      | 
gmake[2]: *** [python/CMakeFiles/python_module_qgis__core.dir/build.make:879: python/CMakeFiles/python_module_qgis__core.dir/core/build/_core/sip_corepart0.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:11600: python/CMakeFiles/python_module_qgis__core.dir/all] Error 2
gmake: *** [Makefile:166: all] Error 2
*** Error code 2
```

**Comment by gdt** [comment]
I have been working with upstream and just built/installed sip from the tip of the 6.8-maint branch, and with that built qgis 3.23.13.  I had a successful build and the resulting installation worked to open a project with geopackage vector data and a TMS baselayer.   Also, the file that threw the error above now diffs equal, except for `#line` lines and the comment about the sip version.   I am anticipating a sip 6.8.1 soon and then this issue can be closed, as I now believe that this was never a qgis bug.

@buzo-ffm Can you edit the title to stay "6.8.0" rather than "6.8", or perhaps after someone confirms 6.8.1 say "fails to build with 6.8.0 (6.8.1 is ok)" as a hint to people searching?

**Comment by kikislater** [comment]
For archlinux users, I have reported the sip error here : 
https://gitlab.archlinux.org/archlinux/packaging/packages/sip/-/issues/1

Editing `/usr/lib/python3.11/site-packages/sipbuild/generator/outputs/code.py` replacing `SocstringSignature` by `DocstringSignature` is a workaround before patch / correction applied in archlinux
I didn't test in LTR but got the problem in 3.34.1 even with 6.8.0. I revert back to 6.7.12

**Comment by gdt** [comment]
That's one bug, but there are more; I count 9 fixes in upstream hg.   Fixing SocStringSignature lets the build get a lot further, but it failed on something else.   For now, reverting to 6.7.12 seems like the right approach.

**Comment by MehdiChinoune** [comment]
qgis 3.34.1 still failing with sip 6.8.1

**Comment by dvdkon** [comment]
> qgis 3.34.1 still failing with sip 6.8.1

Could you please post the error?

**Comment by kikislater** [comment]
6.8.0 fails with qtwebkit enable, without qtwebkit it builds fine. 
I didn't test with 6.8.1, looking forward to results with it

**Comment by gdt** [comment]
I just built with 6.8.1, NetBSD 10 amd64.    No surprise as I had just built with the same bits pre-tag debugging with upstream.

**Comment by MehdiChinoune** [comment]
sip 6.8.1
```
[6593/9718] Generating core/build/_core/sip_corepart0.cpp, core/build/_core/sip_corepart1.cpp, core/build/_core/sip_corepart2.cpp, core/build/_core/sip_corepart3.cpp, core/build/_core/sip_corepart4.cpp, core/build/_core/sip_corepart5.cpp, core/build/_core/sip_corepart6.cpp, core/build/_core/sip_corepart7.cpp, core/build/_core/sip_corepart8.cpp, core/build/_core/sip_corepart9.cpp, core/build/_core/sip_corepart10.cpp, core/build/_core/sip_corepart11.cpp, core/build/_core/sip_corepart12.cpp, core/build/_core/sip_corepart13.cpp, core/build/_core/sip_corepart14.cpp, core/build/_core/sip_corepart15.cpp, core/build/_core/sip_corepart16.cpp, core/build/_core/sip_corepart17.cpp, core/build/_core/sip_corepart18.cpp, core/build/_core/sip_corepart19.cpp, core/build/_core/sip_corepart20.cpp, core/build/_core/sip_corepart21.cpp
  FAILED: python/core/build/_core/sip_corepart0.cpp python/core/build/_core/sip_corepart1.cpp python/core/build/_core/sip_corepart2.cpp python/core/build/_core/sip_corepart3.cpp python/core/build/_core/sip_corepart4.cpp python/core/build/_core/sip_corepart5.cpp python/core/build/_core/sip_corepart6.cpp python/core/build/_core/sip_corepart7.cpp python/core/build/_core/sip_corepart8.cpp python/core/build/_core/sip_corepart9.cpp python/core/build/_core/sip_corepart10.cpp python/core/build/_core/sip_corepart11.cpp python/core/build/_core/sip_corepart12.cpp python/core/build/_core/sip_corepart13.cpp python/core/build/_core/sip_corepart14.cpp python/core/build/_core/sip_corepart15.cpp python/core/build/_core/sip_corepart16.cpp python/core/build/_core/sip_corepart17.cpp python/core/build/_core/sip_corepart18.cpp python/core/build/_core/sip_corepart19.cpp python/core/build/_core/sip_corepart20.cpp python/core/build/_core/sip_corepart21.cpp C:/_/B/src/build-UCRT64/python/core/build/_core/sip_corepart0.cpp C:/_/B/src/build-UCRT64/python/core/build/_core/sip_corepart1.cpp C:/_/B/src/build-UCRT64/python/core/build/_core/sip_corepart2.cpp C:/_/B/src/build-UCRT64/python/core/build/_core/sip_corepart3.cpp C:/_/B/src/build-UCRT64/python/core/build/_core/sip_corepart4.cpp C:/_/B/src/build-UCRT64/python/core/build/_core/sip_corepart5.cpp C:/_/B/src/build-UCRT64/python/core/build/_core/sip_corepart6.cpp C:/_/B/src/build-UCRT64/python/core/build/_core/sip_corepart7.cpp C:/_/B/src/build-UCRT64/python/core/build/_core/sip_corepart8.cpp C:/_/B/src/build-UCRT64/python/core/build/_core/sip_corepart9.cpp C:/_/B/src/build-UCRT64/python/core/build/_core/sip_corepart10.cpp C:/_/B/src/build-UCRT64/python/core/build/_core/sip_corepart11.cpp C:/_/B/src/build-UCRT64/python/core/build/_core/sip_corepart12.cpp C:/_/B/src/build-UCRT64/python/core/build/_core/sip_corepart13.cpp C:/_/B/src/build-UCRT64/python/core/build/_core/sip_corepart14.cpp C:/_/B/src/build-UCRT64/python/core/build/_core/sip_corepart15.cpp C:/_/B/src/build-UCRT64/python/core/build/_core/sip_corepart16.cpp C:/_/B/src/build-UCRT64/python/core/build/_core/sip_corepart17.cpp C:/_/B/src/build-UCRT64/python/core/build/_core/sip_corepart18.cpp C:/_/B/src/build-UCRT64/python/core/build/_core/sip_corepart19.cpp C:/_/B/src/build-UCRT64/python/core/build/_core/sip_corepart20.cpp C:/_/B/src/build-UCRT64/python/core/build/_core/sip_corepart21.cpp 
  C:\Windows\system32\cmd.exe /C "cd /D C:\_\B\src\build-UCRT64\python\core && D:\M\msys64\ucrt64\bin\cmake.exe -E echo && D:\M\msys64\ucrt64\bin\sip-build.exe --no-protected-is-public --pep484-pyi --no-make --concatenate=22 --qmake=D:/M/msys64/ucrt64/bin/qmake.exe --include-dir=C:/_/B/src/build-UCRT64/python --include-dir=D:/M/msys64/ucrt64/lib/python3.11/site-packages/PyQt5/bindings --api-dir C:/_/B/src/build-UCRT64/python && D:\M\msys64\ucrt64\bin\cmake.exe -E touch C:/_/B/src/build-UCRT64/python/core/build/_core/sip_corepart0.cpp C:/_/B/src/build-UCRT64/python/core/build/_core/sip_corepart1.cpp C:/_/B/src/build-UCRT64/python/core/build/_core/sip_corepart2.cpp C:/_/B/src/build-UCRT64/python/core/build/_core/sip_corepart3.cpp C:/_/B/src/build-UCRT64/python/core/build/_core/sip_corepart4.cpp C:/_/B/src/build-UCRT64/python/core/build/_core/sip_corepart5.cpp C:/_/B/src/build-UCRT64/python/core/build/_core/sip_corepart6.cpp C:/_/B/src/build-UCRT64/python/core/build/_core/sip_corepart7.cpp C:/_/B/src/build-UCRT64/python/core/build/_core/sip_corepart8.cpp C:/_/B/src/build-UCRT64/python/core/build/_core/sip_corepart9.cpp C:/_/B/src/build-UCRT64/python/core/build/_core/sip_corepart10.cpp C:/_/B/src/build-UCRT64/python/core/build/_core/sip_corepart11.cpp C:/_/B/src/build-UCRT64/python/core/build/_core/sip_corepart12.cpp C:/_/B/src/build-UCRT64/python/core/build/_core/sip_corepart13.cpp C:/_/B/src/build-UCRT64/python/core/build/_core/sip_corepart14.cpp C:/_/B/src/build-UCRT64/python/core/build/_core/sip_corepart15.cpp C:/_/B/src/build-UCRT64/python/core/build/_core/sip_corepart16.cpp C:/_/B/src/build-UCRT64/python/core/build/_core/sip_corepart17.cpp C:/_/B/src/build-UCRT64/python/core/build/_core/sip_corepart18.cpp C:/_/B/src/build-UCRT64/python/core/build/_core/sip_corepart19.cpp C:/_/B/src/build-UCRT64/python/core/build/_core/sip_corepart20.cpp C:/_/B/src/build-UCRT64/python/core/build/_core/sip_corepart21.cpp"
  
  pyproject.toml: line 7: using '[tool.sip.metadata]' to specify the project metadata is deprecated and will be removed in SIP v7.0.0, use '[project]' instead
  Querying qmake about your Qt installation...
  These bindings will be built: core.
  Generating the core bindings...
  Generating the _core .api file...
  Generating the _core .pyi file...
  sip-build: An internal error occurred...
  Traceback (most recent call last):
    File "<frozen runpy>", line 198, in _run_module_as_main
    File "<frozen runpy>", line 88, in _run_code
    File "D:/M/msys64/ucrt64/bin/sip-build.exe/__main__.py", line 7, in <module>
    File "D:/M/msys64/ucrt64/lib/python3.11/site-packages/sipbuild/tools/build.py", line 37, in main
      handle_exception(e)
    File "D:/M/msys64/ucrt64/lib/python3.11/site-packages/sipbuild/exceptions.py", line 83, in handle_exception
      raise e
    File "D:/M/msys64/ucrt64/lib/python3.11/site-packages/sipbuild/tools/build.py", line 34, in main
      project.build()
    File "D:/M/msys64/ucrt64/lib/python3.11/site-packages/sipbuild/project.py", line 245, in build
      self.builder.build()
    File "D:/M/msys64/ucrt64/lib/python3.11/site-packages/sipbuild/builder.py", line 46, in build
      self._generate_bindings()
    File "D:/M/msys64/ucrt64/lib/python3.11/site-packages/sipbuild/builder.py", line 273, in _generate_bindings
      buildable = bindings.generate()
                  ^^^^^^^^^^^^^^^^^^^
    File "D:/M/msys64/ucrt64/lib/python3.11/site-packages/sipbuild/bindings.py", line 220, in generate
      output_code(spec, self, project, buildable)
    File "D:/M/msys64/ucrt64/lib/python3.11/site-packages/sipbuild/generator/outputs/code.py", line 60, in output_code
      _module_code(spec, bindings, project, py_debug, buildable)
    File "D:/M/msys64/ucrt64/lib/python3.11/site-packages/sipbuild/generator/outputs/code.py", line 1269, in _module_code
      _iface_file_cpp(spec, bindings, project, buildable, py_debug,
    File "D:/M/msys64/ucrt64/lib/python3.11/site-packages/sipbuild/generator/outputs/code.py", line 2132, in _iface_file_cpp
      _class_cpp(sf, spec, bindings, klass, py_debug)
    File "D:/M/msys64/ucrt64/lib/python3.11/site-packages/sipbuild/generator/outputs/code.py", line 2368, in _class_cpp
      _class_functions(sf, spec, bindings, klass, py_debug)
    File "D:/M/msys64/ucrt64/lib/python3.11/site-packages/sipbuild/generator/outputs/code.py", line 3396, in _class_functions
      _member_function(sf, spec, bindings, klass, visible_member.member,
    File "D:/M/msys64/ucrt64/lib/python3.11/site-packages/sipbuild/generator/outputs/code.py", line 6455, in _member_function
      has_auto_docstring = _member_docstring(sf, spec, bindings, member,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "D:/M/msys64/ucrt64/lib/python3.11/site-packages/sipbuild/generator/outputs/code.py", line 8340, in _member_docstring
      sf.write(_docstring_text(overload.docstring))
    File "D:/M/msys64/ucrt64/lib/python3.11/site-packages/sipbuild/generator/outputs/code.py", line 9067, in write
      self._f.write(s)
    File "D:/M/msys64/ucrt64/lib/python3.11/encodings/cp1252.py", line 19, in encode
      return codecs.charmap_encode(input,self.errors,encoding_table)[0]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  UnicodeEncodeError: 'charmap' codec can't encode character '\u2076' in position 89: character maps to <undefined>
```

**Comment by gdt** [comment]
@MehdiChinoune Did you confirm that with *only* changing sip to 6.7.12 or some such version, it builds?   I'm not suggesting it didn't -- 6.8 rewrites the generation code in python, and therefore unicode encoding issues are not that surprising :-(

**Comment by MehdiChinoune** [comment]
Latest successful build was qgis-3.34.0+sip-6.7.12
I don't think qgis 3.34.1 has changed something related to python bindings.
https://github.com/qgis/QGIS/compare/final-3_34_0...final-3_34_1

**Comment by gdt** [comment]
There is now a commit on 6.8-maint beyond 6.8.1 which probably fixes your issue.  See sip upstream repo:
```
changeset:   2991:8a93542bb346
branch:      6.8-maint
tag:         tip
user:        Phil Thompson <phil@riverbankcomputing.com>
date:        Tue Dec 12 22:32:31 2023 +0000
summary:     All generated files are UTF-8 encoded rather than using the platform default.
```

**Comment by MehdiChinoune** [comment]
> There is now a commit on 6.8-maint beyond 6.8.1 which probably fixes your issue. See sip upstream repo:
> 
> ```
> changeset:   2991:8a93542bb346
> branch:      6.8-maint
> tag:         tip
> user:        Phil Thompson <phil@riverbankcomputing.com>
> date:        Tue Dec 12 22:32:31 2023 +0000
> summary:     All generated files are UTF-8 encoded rather than using the platform default.
> ```

It works.
Thanks

**Comment by MehdiChinoune** [comment]
Shouldn't this issue be closed, after sip got fixed?
