### ISSUE TITLE
IDW Python error

### ISSUE THREAD

**Issue by stebond** [qgis/QGIS#55869]
### What is the bug or the crash?

I get Python error using QGIS ->IDW:
2024-01-17T09:34:54     WARNING    Traceback (most recent call last):
              File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python/plugins\processing\algs\qgis\ui\InterpolationWidgets.py", line 305, in pixelSizeChanged
              rows = max(round(self.extent.height() / cell_size) + 1, 1)
             OverflowError: cannot convert float infinity to integer
             
2024-01-17T09:34:54     WARNING    Traceback (most recent call last):
              File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python/plugins\processing\ProcessingPlugin.py", line 428, in executeAlgorithm
              dlg = AlgorithmDialog(alg, in_place, iface.mainWindow())
              File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python/plugins\processing\gui\AlgorithmDialog.py", line 69, in __init__
              self.setMainWidget(self.getParametersPanel(alg, self))
              File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python/plugins\processing\gui\AlgorithmDialog.py", line 93, in getParametersPanel
              panel = ParametersPanel(parent, alg, self.in_place, self.active_layer)
              File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python/plugins\processing\gui\ParametersPanel.py", line 69, in __init__
              self.initWidgets()
              File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python/plugins\processing\gui\ParametersPanel.py", line 197, in initWidgets
              wrapper.postInitialize(list(self.wrappers.values()))
              File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python/plugins\processing\algs\qgis\ui\InterpolationWidgets.py", line 383, in postInitialize
              self.setLayers(wrapper.parameterValue())
              File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python/plugins\processing\algs\qgis\ui\InterpolationWidgets.py", line 393, in setLayers
              self.widget.setLayers(layersData)
              File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python/plugins\processing\algs\qgis\ui\InterpolationWidgets.py", line 285, in setLayers
              self.pixelSizeChanged()
              File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python/plugins\processing\algs\qgis\ui\InterpolationWidgets.py", line 305, in pixelSizeChanged
              rows = max(round(self.extent.height() / cell_size) + 1, 1)
             OverflowError: cannot convert float infinity to integer
             

### Steps to reproduce the issue

Open QGIS
Load  a simple CSV Data
goto to Processing->tools
search for IDW
click on QGIS-IDW
Ther python error will appear
Probably the cellsize=0 is the problemSearch

### Versions

Versione di QGIS
3.34.0-Prizren
Revisione codice QGIS
ffbdd67881
Versione Qt
5.15.3
Versione Python
3.9.5
Versione GDAL/OGR
3.7.2
Versione PROJ
9.3.0
Versione database del Registro EPSG
v10.094 (2023-08-08)
Versione GEOS
3.12.0-CAPI-1.18.0
Versione SQLite
3.41.1
Versione PDAL
2.5.5
Versione client PostgreSQL
15.2
Versione SpatiaLite
5.1.0
Versione QWT
6.1.6
Versione QScintilla2
2.13.4
Versione SO
Windows 10 Version 2009

Plugins Python attivi
DEMto3D
3.6
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
This was fixed in 3.34.1
