### ISSUE TITLE
issue in start up after install, No module named 'pyrsgis'

### ISSUE THREAD

**Issue by emoralescas** [qgis/QGIS#56354]
### What is the bug or the crash?

after fresh install on Windows10 professionel the version 3.34.3-Prizren I always received the below message, and obviously no tool is working.

how to solve it?

2024-02-14T21:18:35     CRITICAL    Traceback (most recent call last):
              File "C:\PROGRA~1/QGIS33~1.3/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              File "C:\Users/maguina/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\rastertool\__init__.py", line 35, in classFactory
              from .RasterTool import RasterTool
              File "C:\PROGRA~1/QGIS33~1.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\Users/maguina/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\rastertool\RasterTool.py", line 54, in 
              from pyrsgis.convert import rastertocsv
              File "C:\PROGRA~1/QGIS33~1.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
             ModuleNotFoundError: No module named 'pyrsgis'

### Steps to reproduce the issue

install
open

### Versions

3.34.3-Prizren

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by emoralescas** [comment]
after forcing the instal of pyrsgis through pip, now I get the following meesage:
             ImportError: cannot import name 'rastertocsv' from 'pyrsgis.convert' (C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\pyrsgis\convert\__init__.py)

but all modules and elements seem to be available in the system

**Comment by nyalldawson** [comment]
This is a bug in the third party raster tools plugin, not QGIS.
