### ISSUE TITLE
QGIS running my files and pop up the issues, But cannot locate the files of errors

### ISSUE THREAD

**Issue by JackieLong1005** [qgis/QGIS#56879]
### Feature description

2024-03-15T19:33:56     WARNING    Traceback (most recent call last):
              File "C:\Users/JackieLong/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\XYZHubConnector\plugin.py", line 806, in reload_tile
              kw = self.make_tile_params(rect, level)
              File "C:\Users/JackieLong/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\XYZHubConnector\plugin.py", line 730, in make_tile_params
              kw["tile_ids"] = tile_utils.bboxToListColRow(*rect, level, schema=schema)
              File "C:\Users/JackieLong/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\XYZHubConnector\xyz_qgis\layer\tile_utils.py", line 218, in bboxToListColRow
              r1, r2, c1, c2 = bboxToLevelRowCol(x_min, y_min, x_max, y_max, level, schema)
              File "C:\Users/JackieLong/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\XYZHubConnector\xyz_qgis\layer\tile_utils.py", line 195, in bboxToLevelRowCol
              r1, c1 = coord_to_row_col([x_min, y_min], level, schema)
              File "C:\Users/JackieLong/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\XYZHubConnector\xyz_qgis\layer\tile_utils.py", line 94, in coord_to_row_col
              r, c = coord_to_percent(coord, level, schema)
              File "C:\Users/JackieLong/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\XYZHubConnector\xyz_qgis\layer\tile_utils.py", line 89, in coord_to_percent
              row_percent, col_percent = coord_to_percent_bing_reversed(coord, level)
              File "C:\Users/JackieLong/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\XYZHubConnector\xyz_qgis\layer\tile_utils.py", line 32, in coord_to_percent_bing_reversed
              sinLatitude = math.sin((latitude * math.pi) / 180)
             ValueError: math domain error

**Comment by agiudiceandrea** [comment]
@JackieLong1005 the issue is due to an external third-party plugin. Please create and use a new [QGIS user profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles).
