### ISSUE TITLE
Python error when loading a mesh layer on QGIS 3.36.2

### ISSUE THREAD

**Issue by Amalvir** [qgis/QGIS#57234]
### What is the bug or the crash?

Hi everyone,
When I load a mesh layer into QGIS, the following Python error appears. In the both cases, the layers load fine despite the error.

The same issue is raised when I load a project with mesh layers.

This issue doesn't appear in 3.36.1.
**This issue doesn't appear with a new profile**

Am I alone with this issue ?

```
Traceback (most recent call last):
  File "C:\OSGeo4W\apps\Python312\Lib\site-packages\decorator.py", line 231, in fun
    args, kw = fix(args, kw, sig)
               ^^^^^^^^^^^^^^^^^^
  File "C:\OSGeo4W\apps\Python312\Lib\site-packages\decorator.py", line 203, in fix
    ba = sig.bind(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OSGeo4W\apps\Python312\Lib\inspect.py", line 3242, in bind
    return self._bind(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OSGeo4W\apps\Python312\Lib\inspect.py", line 3163, in _bind
    raise TypeError('too many positional arguments') from None
TypeError: too many positional arguments
```

### Steps to reproduce the issue

Just load a mesh layer in a project in QGIS 3.36.2.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

Version de QGIS | 3.36.2-Maidenhead | Révision du code | 6d250527
-- | -- | -- | --
Version de Qt | 5.15.13
Version de Python | 3.12.3
Version de GDAL/OGR | 3.8.5
Version de Proj | 9.4.0
Version de la base de données du registre EPSG | v11.004 (2024-02-24)
Version de GEOS | 3.12.1-CAPI-1.18.1
Version de SQLite | 3.45.1
Version de PDAL | 2.6.3
Version du client PostgreSQL | 16.2
Version de SpatiaLite | 5.1.0
Version de QWT | 6.2.0
Version de QScintilla2 | 2.14.1
Version de l'OS | Windows 10 Version 2009
  |   |   |  
Extensions Python actives
AnotherDXF2Shape | 1.3.1
autoSaver | 2.9
contour | 2.0.13
crayfish | 3.6.0
extract_dalles | 0.1
french_locator_filter | 1.1.0
go2streetview | 8.7
meshflow | 0.1.1
processing_saga_nextgen | 1.0.0
profiletool | 4.2.6
qfieldsync | v4.9.1
qgis_resource_sharing | 1.0.0
Serval | 3.32.0
valuetool | 3.0.19
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Thank you for your answers.

**Comment by nicogodet** [comment]
You are not alone ;)

> This issue doesn't appear in 3.36.1.
> This issue doesn't appear with a new profile

So this is likely related to a plugin.

**Comment by Amalvir** [comment]
I've just found the plugin that's causing the problem.
In my case it is Meshflow (https://github.com/vcloarec/meshflow), I will write a ticket on the project.

So it is not a bug ? Should I close the ticket ?

**Comment by nicogodet** [comment]
Yup, it should be closed.
