### ISSUE TITLE
Erro Classificação Supervisionada SCP 

### ISSUE THREAD

**Issue by Juliana9** [qgis/QGIS#57680]
### What is the bug or the crash?

Estou tentando fazer uma classificação supervisionada no Qgis versão mais estável, e todas as vezes que tento abrir o gráfico das amostras espectrais dá um erro enquanto executava o código Python 

### Steps to reproduce the issue

2024-06-05T16:18:48     WARNING    Traceback (most recent call last):
              File "C:\Users/julia/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SemiAutomaticClassificationPlugin\interface\scp_dock.py", line 2639, in add_signature_to_spectral_plot
              cfg.spectral_signature_plotter.signature_list_plot_table()
              File "C:\Users/julia/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SemiAutomaticClassificationPlugin\spectral_signature\spectral_signature_plot.py", line 278, in signature_list_plot_table
              self.signature_plot()
              File "C:\Users/julia/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SemiAutomaticClassificationPlugin\spectral_signature\spectral_signature_plot.py", line 306, in signature_plot
              self.ax.lines.pop(i)
              ^^^^^^^^^^^^^^^^^
             AttributeError: 'ArtistList' object has no attribute 'pop'

### Versions

A versão é a mais estável 3.34.7

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@Juliana9, thanks for reporting. You need to report the issue to the plugin developers at https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/issues if not already reported there.
