### ISSUE TITLE
PyQgsSelectiveMasking testcase fails: FileNotFoundError: [Errno 2] No such file or directory: 'qpdf'

### ISSUE THREAD

**Issue by strk** [qgis/QGIS#57733]
### What is the bug or the crash?

testcase fails, I guess due to missing dependency.

Solution proposed: don't run the test if the dependency is not met, printing a WARNING instead

### Steps to reproduce the issue

ctest -R PyQgsSelectiveMasking --output-on-failure

### Versions

Current master branch

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Traceback (most recent call last):
  File "/usr/local/src/qgis/qgis/src/master/tests/src/python/test_selective_masking.py", line 1317, in test_vector_random_generator_fill
    self.check_layout_export("layout_export_random_generator_fill", 0, [layer], extent=extent)
  File "/usr/local/src/qgis/qgis/src/master/tests/src/python/test_selective_masking.py", line 223, in check_layout_export
    subprocess.run(["qpdf", "--qdf", "--object-streams=disable", result_filename, result_txt])
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'qpdf'

**Comment by strk** [comment]
[CI](https://github.com/qgis/QGIS/actions/runs/9593653933/job/26455771785?pr=57802#step:13:2284) is also showing errors in that test:
```
======================================================================
FAIL: test_markerline_masked (__main__.TestSelectiveMaskingGeometryBackend)
Test a layout export where a QgsMarkerLineSymbolLayer is masked
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/QGIS/tests/src/python/test_selective_masking.py", line 1376, in test_markerline_masked
    self.check_layout_export("layout_export_markerline_masked", 0, [self.polys_layer, self.lines_layer])
  File "/root/QGIS/tests/src/python/test_selective_masking.py", line 251, in check_layout_export
    self.assertTrue(res)
AssertionError: False is not true
```
