### ISSUE TITLE
The native:meshexporttimeseries algorithm breaks when run in a standalone script

### ISSUE THREAD

**Issue by kylefelipe** [qgis/QGIS#57986]
### What is the bug or the crash?

Traceback (most recent call last):
  File "/home/kylefelipe/terraq_repo/tarefa_qgis_netcdf/script_luiz.py", line 119, in <module>
    processing.run("native:meshexporttimeseries", configs)
  File "/usr/share/qgis/python/plugins/processing/tools/general.py", line 109, in run
    return Processing.runAlgorithm(algOrName, parameters, onFinish, feedback, context)
  File "/usr/share/qgis/python/plugins/processing/core/Processing.py", line 215, in runAlgorithm
    raise QgsProcessingException(msg)
_core.QgsProcessingException: There were errors executing the algorithm.

### Steps to reproduce the issue

Download this script.py from gist [click here](https://gist.github.com/kylefelipe/f02e9b3140964a57325443d4751f8e29)
Download the example files in the same folder as the script [Google Drive](https://drive.google.com/drive/folders/1wmXTKsacpMmLdIgq5Y4rVgUs0sGrjUzt?usp=drive_link)
Run the script from the terminal, or OSGEO Shell.
Linux example:
```shell
python3 script.py
```

### Versions

QGIS version | 3.34.8-Prizren | QGIS code revision | 91642333b10
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.12
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | 14.12 (Ubuntu 14.12-0ubuntu0.22.04.1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.4 LTS
  |   |   |  
Active Python plugins
quick_map_services | 0.19.34
MetaSearch | 0.3.6
processing | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20

QGIS version
3.34.8-Prizren
QGIS code revision
[91642333b10](https://github.com/qgis/QGIS/commit/91642333b10)
Qt version
5.15.3
Python version
3.10.12
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
14.12 (Ubuntu 14.12-0ubuntu0.22.04.1)
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Ubuntu 22.04.4 LTS

Active Python plugins
quick_map_services
0.19.34
MetaSearch
0.3.6
processing
2.12.99
grassprovider
2.12.99
db_manager
0.1.20

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Runing meshexporttimeseries from GUI works like a charm.
STEPS:

Add the .nc file as Mesh layer to project
Set mesh projection to ESPG:4326
Add the gpkg as vector layer to project
Go to Toolbox> Double click on Export time series values from points of a mesh dataset
Input mesh layere > Choose mesh layer above
Data set groups > Click on `...` then `Select in available dataset groups` then `select all` > `ok`
Ending time > choose the last one (press end on keyboard)
Points for data export > Choose pont layer
Digits count for coordinates  > 8
Digits count for dataset value > 8
exported data csv file > choose path and file name
click `run`...

**Comment by agiudiceandrea** [comment]
@kylefelipe, thanks for reporting. Does the output of the commands
```
from qgis.core import QgsProviderRegistry
print(QgsProviderRegistry.instance().providerList())
```
added just before the `mesh_layer = QgsMeshLayer(mesh_path, "mesh", "mdal")` contain the `mdal` provider name?
Does the output of print(mesh_layer) added just after `mesh_layer = QgsMeshLayer(mesh_path, "mesh", "mdal")` states that is a valid layer?

**Comment by kylefelipe** [comment]
Hi @agiudiceandrea, thx for helping me!

> print(QgsProviderRegistry.instance().providerList())
> added just before the `mesh_layer = QgsMeshLayer(mesh_path, "mesh", "mdal")` contain the `mdal` provider name?

R: No, just show these names 
```['arcgisvectortileservice', 'cesiumtiles', 'copc', 'ept', 'gdal', 'mbtilesvectortiles', 'memory', 'mesh_memory', 'ogr', 'tiledscene', 'vectortile', 'vpc', 'vtpkvectortiles', 'xyzvectortiles']```

> Does the output of `print(mesh_layer)` added just after `mesh_layer = QgsMeshLayer(mesh_path, "mesh", "mdal")` states that it is a valid layer?

R) No, it shows that is an invalid layer

> you need to put the `QgsApplication.processingRegistry().addProvider(QgsNativeAlgorithms())` after the `Processing.initialize()` line, not before. Anyway, `QgsApplication.processingRegistry().addProvider(QgsNativeAlgorithms())` is not needed.

R) Thx.

I am updating the gist with new code...
And its still issuing  ```(...) There where errors executing the algorithm```

**Comment by agiudiceandrea** [comment]
> I am updating the gist with new code...

Does the new code make `QgsProviderRegistry.instance().providerList()` contain the mdal provider name and mesh_layer be a valid mesh layer? What is the full error message?

**Comment by kylefelipe** [comment]
@agiudiceandrea 

> > I am updating the gist with new code...
> 
> Does the new code make `QgsProviderRegistry.instance().providerList()` contain the mdal provider name and mesh_layer be a valid mesh layer? What is the full error message?

No...

Full error:
```['arcgisvectortileservice', 'cesiumtiles', 'copc', 'ept', 'gdal', 'mbtilesvectortiles', 'memory', 'mesh_memory', 'ogr', 'tiledscene', 'vectortile', 'vpc', 'vtpkvectortiles', 'xyzvectortiles']
False
<QgsMeshLayer: 'mesh' (Invalid)>
Traceback (most recent call last):
  File "/home/kylefelipe/terraq_repo/tarefa_qgis_netcdf/using_pyqgis.py", line 72, in <module>
    processing.run("native:meshexporttimeseries", configs)
  File "/usr/share/qgis/python/plugins/processing/tools/general.py", line 109, in run
    return Processing.runAlgorithm(algOrName, parameters, onFinish, feedback, context)
  File "/usr/share/qgis/python/plugins/processing/core/Processing.py", line 215, in runAlgorithm
    raise QgsProcessingException(msg)
_core.QgsProcessingException: There were errors executing the algorithm.```

**Comment by abreufilho** [comment]
Any updates on that? Im running into the same issue.
