### ISSUE TITLE
QGIS 3.38.1-Grenoble Install issue

### ISSUE THREAD

**Issue by Oisin-JK** [qgis/QGIS#58319]
### What is the bug or the crash?

I've just installed QGIS using the OSGeo4W installer. Running the LTR version (3.3.34.9-Prizren) causes no issues. Running the current version (3.38.1-Grenoble) causes several Python errors, as quoted below. The relevant gdal_TileDB.dll is present at the stated location.

Error logs are reproduced below. How do I resolve this?

2024-08-05T15:25:32 CRITICAL Traceback (most recent call last): File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 426, in startPlugin plugins[packageName] = package.classFactory(iface) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\OSGeo4W/apps/qgis/./python/plugins\grassprovider_init.py", line 24, in classFactory from grassprovider.grass_plugin import GrassProviderPlugin File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 923, in _import mod = _builtin_import(name, globals, locals, fromlist, level) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\OSGeo4W/apps/qgis/./python/plugins\grassprovider\grass_plugin.py", line 26, in from grassprovider.grass_provider import GrassProvider File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 923, in _import mod = _builtin_import(name, globals, locals, fromlist, level) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\OSGeo4W/apps/qgis/./python/plugins\grassprovider\grass_provider.py", line 32, in from processing.core.ProcessingConfig import (ProcessingConfig, Setting) File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 923, in _import mod = builtin_import(name, globals, locals, fromlist, level) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\OSGeo4W/apps/qgis/./python/plugins\processing_init.py", line 24, in from processing.tools.general import * # NOQA ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 923, in _import mod = _builtin_import(name, globals, locals, fromlist, level) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\OSGeo4W/apps/qgis/./python/plugins\processing\tools\general.py", line 31, in from processing.core.Processing import Processing File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 923, in _import mod = _builtin_import(name, globals, locals, fromlist, level) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\OSGeo4W/apps/qgis/./python/plugins\processing\core\Processing.py", line 55, in from processing.algs.qgis.QgisAlgorithmProvider import QgisAlgorithmProvider # NOQA ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 923, in _import mod = _builtin_import(name, globals, locals, fromlist, level) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\OSGeo4W/apps/qgis/./python/plugins\processing\algs\qgis\QgisAlgorithmProvider.py", line 45, in from .HypsometricCurves import HypsometricCurves File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 923, in _import mod = _builtin_import(name, globals, locals, fromlist, level) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\OSGeo4W/apps/qgis/./python/plugins\processing\algs\qgis\HypsometricCurves.py", line 27, in gdal.UseExceptions() File "C:\OSGeo4W\apps\Python312\Lib\site-packages\osgeo\gdal.py", line 246, in UseExceptions from . import gdal_array File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 923, in _import mod = _builtin_import(name, globals, locals, fromlist, level) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\OSGeo4W\apps\Python312\Lib\site-packages\osgeo\gdal_array.py", line 286, in gdal.AllRegister() File "C:\OSGeo4W\apps\Python312\Lib\site-packages\osgeo\gdal.py", line 8575, in AllRegister return _gdal.AllRegister(*args) ^^^^^^^^^^^^^^^^^^^^^^^^ RuntimeError: Can't load requested DLL: C:\OSGeo4W\apps\gdal\lib\gdalplugins\gdal_TileDB.dll 126: The specified module could not be found.

         May be caused by: Can't load requested DLL: C:\OSGeo4W\apps\gdal\lib\gdalplugins\gdal_TileDB.dll
         126: The specified module could not be found. 
         
          2024-08-05T15:25:39     CRITICAL    Traceback (most recent call last):
          File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 404, in loadPlugin
          __import__(packageName)
          File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 923, in _import
          mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "C:\OSGeo4W/apps/qgis/./python/plugins\processing\__init__.py", line
24, in from processing.tools.general import * # NOQA ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 923, in _import mod = _builtin_import(name, globals, locals, fromlist, level) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\OSGeo4W/apps/qgis/./python/plugins\processing\tools\general.py", line 31, in from processing.core.Processing import Processing File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 923, in _import mod = _builtin_import(name, globals, locals, fromlist, level) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\OSGeo4W/apps/qgis/./python/plugins\processing\core\Processing.py", line 55, in from processing.algs.qgis.QgisAlgorithmProvider import QgisAlgorithmProvider # NOQA ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 923, in _import mod = _builtin_import(name, globals, locals, fromlist, level) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\OSGeo4W/apps/qgis/./python/plugins\processing\algs\qgis\QgisAlgorithmProvider.py", line 45, in from .HypsometricCurves import HypsometricCurves File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 923, in _import mod = _builtin_import(name, globals, locals, fromlist, level) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\OSGeo4W/apps/qgis/./python/plugins\processing\algs\qgis\HypsometricCurves.py", line 27, in gdal.UseExceptions() File "C:\OSGeo4W\apps\Python312\Lib\site-packages\osgeo\gdal.py", line 246, in UseExceptions from . import gdal_array File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 923, in _import mod = _builtin_import(name, globals, locals, fromlist, level) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\OSGeo4W\apps\Python312\Lib\site-packages\osgeo\gdal_array.py", line 286, in gdal.AllRegister() File "C:\OSGeo4W\apps\Python312\Lib\site-packages\osgeo\gdal.py", line 8575, in AllRegister return _gdal.AllRegister(*args) ^^^^^^^^^^^^^^^^^^^^^^^^ RuntimeError: Can't load requested DLL: C:\OSGeo4W\apps\gdal\lib\gdalplugins\gdal_TileDB.dll 126: The specified module could not be found.

         May be caused by: Can't load requested DLL: C:\OSGeo4W\apps\gdal\lib\gdalplugins\gdal_TileDB.dll
         126: The specified module could not be found.

### Steps to reproduce the issue

Install using OSGeo4W installer
Run 3.38.1-Grenoble

### Versions

3.38.1-Grenoble

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by jef-n** [comment]
gdal-tiledb was discontinued in OSGeo4W with GDAL 3.9.0.  Uninstall it.   But the installer should also an update that will remove the file.

**Comment by Oisin-JK** [comment]
Can you re-open this issue. I have uninstalled tiledb - see screenshot here:
![image](https://github.com/user-attachments/assets/1952d43f-cf57-48e8-a520-3ff3f57c6182)

I still get errors opening 3.38.1, as per attached files. I am using the latest OSGeo4W installer.
[error1.txt](https://github.com/user-attachments/files/16508933/error1.txt)
[error2.txt](https://github.com/user-attachments/files/16508937/error2.txt)
[error3.txt](https://github.com/user-attachments/files/16508938/error3.txt)
[error4.txt](https://github.com/user-attachments/files/16508939/error4.txt)
[error5.txt](https://github.com/user-attachments/files/16508940/error5.txt)

**Comment by agiudiceandrea** [comment]
@Oisin-JK, is there a `gdal_TileDB.dll` file in the `C:\OSGeo4W\apps\gdal\lib\gdalplugins\` folder?

**Comment by Oisin-JK** [comment]
Yes.

**Comment by jef-n** [comment]
gdal-tiledb is obsolete and only appears in the installer's list if you uncheck "hide obsolete package"

**Comment by Oisin-JK** [comment]
I have not unchecked  "hide obsolete package". 
It is present. 
I get the erros detailed above.

**Comment by agiudiceandrea** [comment]
@gdal-tiledb, since you need to uninstall the gdal-tiledb package, then you need to unchecked the "hide obsolete package" option in order to see it listed and thus be able to uninstall it.

**Comment by jef-n** [comment]
> I have not unchecked "hide obsolete package".  It is present.

And that's why you don't see gdal-tiledb even if it was installed.  So the picture doesn't tell us whetherit is installed or not.
