### ISSUE TITLE
QgsProcessingException (native:extractbyexpression): INPUT: no value specified for parameter

### ISSUE THREAD

**Issue by see7e** [qgis/QGIS#58944]
## Issue

Running `native:extractbyexpression` twice reises QgsProcessingException for the INPUT:

```python
first_section_cables = processing.run("native:extractbyexpression", {
    'INPUT':d_cable,
    'EXPRESSION':"(overlay_intersects('Pole Closure') OR overlay_intersects('FacadeClosure')) AND overlay_intersects('Riser')",
    'OUTPUT':'TEMPORARY_OUTPUT'
})["OUTPUT"]
first_section_cables.dataProvider().createSpatialIndex()

# Step 2: Extract cables connecting Riser to TB
second_section_cables = processing.run("native:extractbyexpression", {
    'LAYER': d_cable,
    'EXPRESSION': "overlay_intersects('Riser') AND overlay_intersects('TerminationBox')",
    'OUTPUT': "TEMPORARY_OUTPUT"
})["OUTPUT"]
second_section_cables.dataProvider().createSpatialIndex()
```
## Output

```bash
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS33~1.7\apps\Python312\Lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "<string>", line 38, in <module>
  File "C:\PROGRA~1/QGIS33~1.7/apps/qgis-ltr/./python/plugins\processing\tools\general.py", line 109, in run
    return Processing.runAlgorithm(algOrName, parameters, onFinish, feedback, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1/QGIS33~1.7/apps/qgis-ltr/./python/plugins\processing\core\Processing.py", line 170, in runAlgorithm
    raise QgsProcessingException(msg)
_core.QgsProcessingException: Unable to execute algorithm
Could not load source layer for INPUT: no value specified for parameter
```

## Files

[prj.zip](https://github.com/user-attachments/files/17231951/prj.zip)

### Steps to reproduce the issue

```python
# Import necessary libraries
from qgis.core import QgsProject, QgsGeometry
import processing
import pandas as pd

# Initialize QGIS project instance
PRJ = QgsProject.instance()
# pole = PRJ.mapLayersByName('Pole Closure')[0]
# facade = PRJ.mapLayersByName('FacadeClosure')[0]

# # Merge pole and facade layers into a single layer (AB)
# ab = processing.run("native:mergevectorlayers", {
#     'LAYERS': [pole, facade],
#     'OUTPUT': 'TEMPORARY_OUTPUT'
# })['OUTPUT']
# ab.dataProvider().createSpatialIndex()
ab = PRJ.mapLayersByName('AB')[0]

# Load relevant layers
# tb = PRJ.mapLayersByName('TerminationBox')[0]
tb = PRJ.mapLayersByName('TB')[0]
# d_cable = PRJ.mapLayersByName('Distribution Cables')[0]
d_cable = PRJ.mapLayersByName('CABLES')[0]

if not ab and not tb and not d_cable:
    print('One or more layers not found')
    exit()

# Step 1: Extract cables connecting AB to Riser
first_section_cables = processing.run("native:extractbyexpression", {
    'INPUT':d_cable,
    'EXPRESSION':"(overlay_intersects('Pole Closure') OR overlay_intersects('FacadeClosure')) AND overlay_intersects('Riser')",
    'OUTPUT':'TEMPORARY_OUTPUT'
})["OUTPUT"]
first_section_cables.dataProvider().createSpatialIndex()

# Step 2: Extract cables connecting Riser to TB
second_section_cables = processing.run("native:extractbyexpression", {
    'LAYER': d_cable,
    'EXPRESSION': "overlay_intersects('Riser') AND overlay_intersects('TerminationBox')",
    'OUTPUT': "TEMPORARY_OUTPUT"
})["OUTPUT"]
second_section_cables.dataProvider().createSpatialIndex()
```

### Versions

QGIS version
3.34.7-Prizren
QGIS code revision
6f7d735c
Qt version
5.15.13
Python version
3.12.3
GDAL/OGR version
3.9.0
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Windows 11 Version 2009

Active Python plugins
joinmultiplelines
Version 0.4.1
latlontools
3.6.19
loadthemall
3.4
pluginbuilder3
3.2.1
plugin_reloader
0.9.3
QuickOSM
2.2.3
quick_map_services
0.19.33
refFunctions
1.6
StreetView
3.2
unifiberprocesssuit
2.0.3
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by see7e** [comment]
The issue was to replace the 'LAYER': d_cable, with 'INPUT'
