### ISSUE TITLE
db manager show errors while open pg node.

### ISSUE THREAD

**Issue by sendreams** [qgis/QGIS#59791]
### What is the bug or the crash?

<img width="526" alt="1733743793633" src="https://github.com/user-attachments/assets/8f85f953-2557-4763-9cb5-ddfd26a274e0">

```
An error has occurred while executing Python code: 

TypeError: 'NoneType' object is not subscriptable 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS33~1.13/apps/qgis-ltr/./python/plugins\db_manager\db_model.py", line 452, in rowCount
    self._refreshIndex(parent, True)
  File "C:\PROGRA~1/QGIS33~1.13/apps/qgis-ltr/./python/plugins\db_manager\db_model.py", line 501, in _refreshIndex
    if item.populate():
       ^^^^^^^^^^^^^^^
  File "C:\PROGRA~1/QGIS33~1.13/apps/qgis-ltr/./python/plugins\db_manager\db_model.py", line 178, in populate
    if not connection.connect():
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1/QGIS33~1.13/apps/qgis-ltr/./python/plugins\db_manager\db_plugins\postgis\plugin.py", line 99, in connect
    return self.connectToUri(uri)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1/QGIS33~1.13/apps/qgis-ltr/./python/plugins\db_manager\db_plugins\plugin.py", line 138, in connectToUri
    self.db = self.databasesFactory(self, uri)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1/QGIS33~1.13/apps/qgis-ltr/./python/plugins\db_manager\db_plugins\postgis\plugin.py", line 63, in databasesFactory
    return PGDatabase(connection, uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1/QGIS33~1.13/apps/qgis-ltr/./python/plugins\db_manager\db_plugins\postgis\plugin.py", line 107, in __init__
    Database.__init__(self, connection, uri)
  File "C:\PROGRA~1/QGIS33~1.13/apps/qgis-ltr/./python/plugins\db_manager\db_plugins\plugin.py", line 263, in __init__
    self.connector = self.connectorsFactory(uri)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1/QGIS33~1.13/apps/qgis-ltr/./python/plugins\db_manager\db_plugins\postgis\plugin.py", line 110, in connectorsFactory
    return PostGisDBConnector(uri, self.connection())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1/QGIS33~1.13/apps/qgis-ltr/./python/plugins\db_manager\db_plugins\postgis\connector.py", line 259, in __init__
    self._checkGeometryColumnsTable()
  File "C:\PROGRA~1/QGIS33~1.13/apps/qgis-ltr/./python/plugins\db_manager\db_plugins\postgis\connector.py", line 321, in _checkGeometryColumnsTable
    self.has_geometry_columns_access = priv[0]
                                       ~~~~^^^
TypeError: 'NoneType' object is not subscriptable


Python version: 3.12.7 (main, Oct 25 2024, 11:18:09) [MSC v.1938 64 bit (AMD64)] 
QGIS version: 3.34.13-Prizren Prizren, 222b5995 

Python Path:
C:/PROGRA~1/QGIS33~1.13/apps/qgis-ltr/./python
C:/Users/Administrator/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Administrator/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS33~1.13/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS33~1.13\apps\grass\grass84\etc\python
C:\Users\Administrator\Documents
C:\Program Files\QGIS 3.34.13\bin\python312.zip
C:\PROGRA~1\QGIS33~1.13\apps\Python312\DLLs
C:\PROGRA~1\QGIS33~1.13\apps\Python312\Lib
C:\Program Files\QGIS 3.34.13\bin
C:\PROGRA~1\QGIS33~1.13\apps\Python312
C:\PROGRA~1\QGIS33~1.13\apps\Python312\Lib\site-packages
C:\PROGRA~1\QGIS33~1.13\apps\Python312\Lib\site-packages\win32
C:\PROGRA~1\QGIS33~1.13\apps\Python312\Lib\site-packages\win32\lib
C:\PROGRA~1\QGIS33~1.13\apps\Python312\Lib\site-packages\Pythonwin
C:/Users/Administrator/AppData/Roaming/QGIS/QGIS3\profiles\default/python
```

### Steps to reproduce the issue

1.  open postgresql with navicat or other tool
2.  create a database 
3.  rename the default 'public' schema to any other name, for example change to 'test'
4.  use qgis connect to pg
5.  open db manager 
6.  expand the pg node
7.  show errors 

### Versions

version: 3.14.13-1 

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
As per https://github.com/qgis/QGIS-Enhancement-Proposals/blob/master/qep-426-demote_dbmanager.md, the db manager plugin is no longer maintained by the QGIS project. Closing as a wont-fix.
